openapi: 3.0.0
servers:
  - url: https://app.drchrono.com
info:
  description: |+
    This document is intended as a detailed reference for the precise behavior of
    the drchrono API. If this is your first time using the API, start with our <a href="/api-docs-old/tutorial">tutorial</a>. If you are upgrading from a previous version, take a look at the changelog section.

    # Authorization

    ## Initial authorization

    There are three main steps in the OAuth 2.0 authentication workflow:

    1. Redirect the provider to the authorization page.
    2. The provider authorizes your application and is redirected back to
       your web application.
    3. Your application exchanges the `authorization_code` that came with
       the redirect for an `access_token` and `refresh_token`.

    ### Step 1: Redirect to drchrono

    The first step is redirecting your user to drchrono, typically with a button
    labeled "Connect to drchrono" or "Login with drchrono".  This is just a link that
    takes your user to the following URL:

        https://drchrono.com/o/authorize/?redirect_uri=REDIRECT_URI_ENCODED&response_type=code&client_id=CLIENT_ID_ENCODED&scope=SCOPES_ENCODED

    - `REDIRECT_URI_ENCODED` is the URL-encoded version of the redirect URI (as registered for your application and used in later steps).
    - `CLIENT_ID_ENCODED` is the URL-encoded version of your application's client ID.
    - `SCOPES_ENCODED` is a URL-encoded version of a space-separated list of scopes, which can be found in each endpoint or omitted to default to all scopes.

    The `scope` parameter consists of an optional, space-separated list of scopes your application is requesting.
    If omitted, all scopes will be requested.

    Scopes are of the form `BASE_SCOPE:[read|write]` where `BASE_SCOPE` is any of `user`, `calendar`, `patients`, `patients:summary`, `billing`, `clinical` and `labs`.
    You should request only the scopes you need.
    For instance, an application which sends "Happy Birthday!" emails to a doctor's patients on their birthdays would use the scope parameter `"patients:summary:read"`,
    while one that allows patients to schedule appointments online would need at least
    `"patients:summary:read patients:summary:write calendar:read calendar:write clinical:read clinical:write"`.

    ### Step 2: Provider authorization

    After logging in (if necessary), the provider will be presented with a screen
    with your application's name and the list of permissions you requested (via the
    `scope` parameter).

    When they click the "Authorize" button, they will be redirected to your redirect
    URI with a `code` query parameter appended, which contains an authorization code to be
    used in step 3.  If they click the "Cancel" button, they will be redirected to
    your redirect URI with `error=access_denied` instead.

    Note: This authorization code expires extremely quickly, so you must perform
    step 3 immediately, ideally before rendering the resulting page for the end
    user.

    ### Step 3: Token exchange

    The `code` obtained from step 2 is usable exactly once to obtain an access token
    and refresh token.  Here is an example token exchange in Python:

        import datetime, pytz, requests

        if 'error' in get_params:
            raise ValueError('Error authorizing application: %s' % get_params[error])

        response = requests.post('https://drchrono.com/o/token/', data={
            'code': get_params['code'],
            'grant_type': 'authorization_code',
            'redirect_uri': 'http://mytestapp.com/redirect_uri',
            'client_id': 'abcdefg12345',
            'client_secret': 'abcdefg12345'
        })
        response.raise_for_status()
        data = response.json()

        # Save these in your database associated with the user
        access_token = data['access_token']
        refresh_token = data['refresh_token']
        expires_timestamp = datetime.datetime.now(pytz.utc) + datetime.timedelta(seconds=data['expires_in'])

    You now have all you need to make API requests authenticated as that provider.
    When using this access token, you'll only be able to access the data that the
    user has access to and that you have been granted permissions for.

    ## Refreshing an access token

    Access tokens only last 48 hours (given in seconds in the `'expires_in'` key in
    the token exchange step above), so they occasionally need to be refreshed.  It
    would be inconvenient to ask the user to re-authorize every time, so instead you
    can use the refresh token like the original authorization to obtain a new access
    token.  Replace the `code` parameter with `refresh_token`, change the value
    `grant_type` from `authorization_code` to `refresh_token`, and omit the
    `redirect_uri` parameter.

    Example in Python:

        ...
        response = requests.post('https://drchrono.com/o/token/', data={
            'refresh_token': get_refresh_token(),
            'grant_type': 'refresh_token',
            'client_id': 'abcdefg12345',
            'client_secret': 'abcdefg12345'
        })
        ...

    # Webhooks

    In order to use drchrono API webhooks, you first need to have an API application on file
    (even if it is in Test Model).
    Each API webhook is associated with one API application, go to
    <a href="/api-management/" target="_blank">here</a> to set up both API applications and webhooks!

    Once you registered an API application, you will see webhook section in each saved API applications.
    Create a webhook and register some events there and save all the changes, then you are good to go!

    ## Webhooks setup

    All fields under webhooks section are required.

    **Callback URL**
    Callback URl is used to receive all hooks when subscribed events are triggered. This should be an URL under your control.

    **Secret token**
    Secret token is used to verify webhooks, this is very important, please set something with high entropy. Also we will
    talk more about this later.

    **Events**

    Events is used to register events you want to receiver notification when they happen. Currently we support following events.

    Event name | Event description
    ---------- | -----------------
    `APPOINTMENT_CREATE` | We will deliver a hook any time an appointment is created
    `APPOINTMENT_MODIFY` | We will deliver a hook any time an appointment is modified
    `PATIENT_CREATE` | We will deliver a hook any time a patient is created
    `PATIENT_MODIFY` | We will deliver a hook any time a patient is modified
    `PATIENT_PROBLEM_CREATE` | We will deliver a hook any time a patient problem is created
    `PATIENT_PROBLEM_MODIFY` | We will deliver a hook any time a patient problem is modified
    `PATIENT_ALLERGY_CREATE` | We will deliver a hook any time a patient allergy is created
    `PATIENT_ALLERGY_MODIFY` | We will deliver a hook any time a patient allergy is modified
    `PATIENT_MEDICATION_CREATE` | We will deliver a hook any time a patient medication is created
    `PATIENT_MEDICATION_MODIFY` | We will deliver a hook any time a patient medication is modified
    `CLINICAL_NOTE_LOCK` | We will deliver a hook any time a clinical note is locked
    `CLINICAL_NOTE_UNLOCK` | We will deliver a hook any time a clinical note is unlocked
    `TASK_CREATE` | We will deliver a hook any time a task is created
    `TASK_MODIFY` | We will deliver a hook any time a task is modified and any time creation, modification and deletion of task notes, associated task item
    `TASK_DELETE` | We will deliver a hook any time a task is deleted


    ## Webhooks verification

    In order to make sure the callback URL in webhook is under your control, we added a verification
    step before we send any hooks out to you.

    Verification can be done by clicking "Verify webhook" button in webhooks setup page. After you click
    the button, we will send a `GET` request to the callback URL, along with a parameter called `msg`.

    Please use your webhook's secret token as hash key and SHA-256 as digest constructor, hash the `msg` value with
    <a href="https://tools.ietf.org/html/rfc2104.html">HMAC algorithm</a>.
    And we expect a `200` JSON response, in JSON response body, there should be a key called `secret_token` existing, and its value should be
    equal to the <strong>hashed</strong> `msg`. Otherwise, verification will fail.

    Here is an example webhook verification in Python:

        import hashlib, hmac

        def webhook_verify(request):
            secret_token = hmac.new(WEBHOOK_SECRET_TOKEN, request.GET['msg'], hashlib.sha256).hexdigest()
            return json_response({
                'secret_token': secret_token
            })

    <div class="alert alert-warning">
    <b>Note:</b> Verification will be needed when webhook is first created and anytime callback URl is changed.
    </div>


    ## Webhooks header and body

    **Header**

    Key | Value
    --- | -----
    `X-drchrono-event` | Event that triggered this hook, could be any one event above or `PING`
    `X-drchrono-signature` | Secret token associated with this webhook
    `X-drchrono-delivery` | ID of this delivery

    **Body**

    Key | Value
    --- | -----
    `receiver` | This will be an JSON representation of the webhook
    `object` | This will be an JSON representation of the object related to the triggered event, this would share same serializer as drchrono API

    ## Webhooks ping and deliveries

    Webhooks ping and deliveries will be sent as `POST` requests.

    **PING**:

    You can always ping your webhook to check things, by clicking the "Ping webhook" button in webhook setup page. And a hook with header `X-drchrono-event: PING` would be sent to the callback URL.

    **Deliveries**:

    You can check recent deliveries by clicking the "deliveries" link in webhook setup page. And you can resend a hook by clicking "redeliver" button after select a specific delivery.

    ## Webhooks delivery mechanism

    We will delivery a hook the moment a subscribed event is triggered. We will not record any response header or body you send back after you receive the hook.
    However we only consider the response status code. We will consider any `2xx` responses as successfully delivered.
    Any other responses, like `302` would be considered failing.
    And we will try to redeliver unsuccessfully delivered hooks 3 times, first redeliver happens at 1 hour after the initial event,
    second receliver happens 3 hours after the initial event, and the third redeliver happens 7 hours after the initial event.
    After these redeliveries, if the delivery is still unsuccessful, you have to redeliver it by hand.


    ## Webhooks security

    You may want to secure your webhooks to only consider requests send out from drchrono. And this is where <code>secret_token</code> is needed in
    request header.
    Try to set the <code>secret_token</code> to something with high entropy, a good example could be taking the output of
    <code>ruby -rsecurerandom -e 'puts SecureRandom.hex(20)'</code>.
    After this, you might want to verify all request headers you received on your server with this token.


    # iframe integration

    Some API apps provide additional functionality for interacting with patient data
    not offered by drchrono, and can benefit by being incorporated into drchrono's
    patient information page via iframe.  We have created a simple API to make this
    possible.

    To make an existing API application accessible via an iframe on the patient
    page, you need to update either "Patient iframe" or "Clinical note iframe" section in API management page,
    to make the iframe to appear on (either the patient page or the clinical note page),
    with the URL that the iframe will use for each page, and the height it should
    have. The application will be reviewed before it is approved to ensure that it
    is functional and secure.

    ## Register a Doctor

    iframe applications will appear as choices on the left-hand menu of the patient
    page for doctors registered with your application.  To register a doctor with
    your application, make a `POST` request to the `/api/iframe_integration`
    endpoint using the access token for the corresponding doctor. This endpoint does not
    expect any payload.

    To disable your iframe application for a doctor, make a `DELETE` request to the
    same endpoint.

    ## Populating the iframe

    There are two places where the iframe can be displayed, either within the
    patient detail page or the clinical note page, shown below respectively:

    <img src="{% asset 'public/images/iframe_patient_page.png' %}" alt="Iframe on the patient page"/>

    <img src="{% asset 'public/images/iframe_clinical_note.png' %}" alt="Iframe on the clinical note page"/>

    When requesting approval for your iframe app, you must specify a URL for one or
    both of these pages which will serve as the base URL for your IFrame
    contents. When a doctor views your iframe, the source URL will have various
    query parameters appended to it, for example for the patient page the `src`
    parameter of the IFrame will be:

    ```
    <iframe_url>?doctor_id=<doctor_id>&patient_id=<patient_id>&practice_id=<practice_id>&iat=<iat>&jwt=<jwt>
    ```

    The `jwt` parameter is crucial if your application transfers any sort of PHI and
    does not implement its own login system.  It encapsulates the other parameters
    in a [JSON web token (JWT)](http://jwt.io) and signs them using SHA-256 HMAC
    with your `client_secret` as the key.  This verifies that the iframe is being
    loaded within one of drchrono's pages by an authorized user.  In production, you
    should validate the JWT using an approved library (which are listed on the
    [official site](http://jwt.io)), and only use the parameters extracted from the
    JWT.  Using Python and Django, this might look like:

        import jwt

        CLIENT_SECRET = <client_secret>
        MAX_TIME_DRIFT_SECONDS = 60

        def validate_parameters(request):
            token = request.GET['jwt']

            return jwt.decode(token, CLIENT_SECRET, algorithms=['HS256'], leeway=MAX_TIME_DRIFT_SECONDS)

    Modern browsers' same-origin policy means that data cannot be passed between
    your application and drchrono's page through the iframe.  Therefore, interaction
    must happen through the API, using information provided in JWT.

    # Versions and deprecation

    ## Stability Policy

    Changes to this API version will be limited to adding endpoints, or adding fields to existing
    endpoints, or adding optional query parameters. Any new fields which are not read-only will be optional.

    ## Deprecation Policy

    The drchrono API is versioned. Versions can be in the following states:

    * **Active:** This is our latest and greatest version of the API. It is actively supported by
    our API team and is improved upon with new features, bug fixes and optimizations that do
    not break backwards compatibility.

    * **Deprecated:** A deprecated API version is considered second best--having been
    surpassed by our active API version. An API version remains in this state for one year,
    after which time it falls to the not supported state. A deprecated API version is passively supported;
    while it won't be removed until becoming unsupported, it may not receive new features but will likely
    be subject to security updates and performance improvements.

    * **Unsupported:** An API version in the not supported state may be deactivated at any
    time. An application using an unsupported API version should migrate to an active API version.

    ## Version Map
    | Version Name | Previous Name | Start Date | Deprecation Date |
    |--------------|---------------|------------|------------------|
    | v2           | v2015_08      | 08/2015    | TBA              |
    | v3           | v2016_06      | 06/2016    |                  |
    | v4           | N/A           | 09/2018    |                  |

    If you are looking for documentation for an older version

    - [V4(Hunt Valley)](/api-docs-old/v4/documentation) (old V4 documentation)
    - [V3(Sunnyvale)](/api-docs-old/v3/documentation)
    - [V2(Mountain View)](/api-docs-old/v2/documentation)

    # Changelog

    Here's changelog for different versions

    - [V4 Changelog](/api-docs-old/v4/changelog)
    - [V3 changelog](/api-docs-old/v3/changelog)

  title: ""
  version: v4 (Hunt Valley)
  x-apisguru-categories:
    - customer_relation
  x-logo:
    altText: DrChrono Logo
    url: https://api.apis.guru/v2/cache/logo/https_www.drchrono.com_site_media_images_drchrono-dark.53a9fc1649a7.png
  x-origin:
    - format: openapi
      url: https://drchrono.com/openapi-schema
      version: "3.0"
  x-providerName: drchrono.com
tags:
  - description: Create and manage administrative resources
    name: Administrative
  - description: Create and manage clinical resources
    name: Clinical
  - description: Create and manage billing resources
    name: Billing
  - description: Create and manage practice management resources
    name: PracticeManagement
paths:
  /api/allergies:
    get:
      description: Retrieve or search patient allergies
      operationId: allergies_list
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: Create patient allergy
      operationId: allergies_create
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/allergies/{id}":
    get:
      description: Retrieve an existing patient allergy
      operationId: allergies_read
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      description: Update an existing patient allergy
      operationId: allergies_partial_update
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      description: Update an existing patient allergy
      operationId: allergies_update
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/amendments:
    get:
      description: Retrieve or search patient amendments. You can only interact with amendments created by your API application
      operationId: amendments_list
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: Create patient amendments to a patient's clinical records
      operationId: amendments_create
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/amendments/{id}":
    delete:
      description: Delete an existing patient amendment, you can only interact with amendments created by your API application
      operationId: amendments_delete
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    get:
      description: Retrieve an existing patient amendment, you can only interact with amendments created by your API application
      operationId: amendments_read
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      description: Update an existing patient amendment, you can only interact with amendments created by your API application
      operationId: amendments_partial_update
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      description: Update an existing patient amendment, you can only interact with amendments created by your API application
      operationId: amendments_update
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/appointment_profiles:
    get:
      description: Retrieve or search appointment profiles for a doctor's calendar
      operationId: appointment_profiles_list
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
        - settings
      x-practice-access: '"share_appointment_profiles" need to be set for data access among practice'
    post:
      description: Create appointment profiles for a doctor's calendar
      operationId: appointment_profiles_create
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
        - settings
      x-practice-access: '"share_appointment_profiles" need to be set for data access among practice'
  "/api/appointment_profiles/{id}":
    delete:
      description: Delete an existing appointment profile
      operationId: appointment_profiles_delete
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
        - settings
      x-practice-access: '"share_appointment_profiles" need to be set for data access among practice'
    get:
      description: Retrieve an existing appointment profile
      operationId: appointment_profiles_read
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
        - settings
      x-practice-access: '"share_appointment_profiles" need to be set for data access among practice'
    patch:
      description: Update an existing appointment profile
      operationId: appointment_profiles_partial_update
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
        - settings
      x-practice-access: '"share_appointment_profiles" need to be set for data access among practice'
    put:
      description: Update an existing appointment profile
      operationId: appointment_profiles_update
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
        - settings
      x-practice-access: '"share_appointment_profiles" need to be set for data access among practice'
  /api/appointment_templates:
    get:
      description: Retrieve or search appointment templates for a doctor's calendar
      operationId: appointment_templates_list
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
        - settings
      x-practice-access: '"share_appointment_profiles" need to be set for data access among practice'
    post:
      description: Create appointment templates for a doctor's calendar
      operationId: appointment_templates_create
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
        - settings
      x-practice-access: '"share_appointment_profiles" need to be set for data access among practice'
  "/api/appointment_templates/{id}":
    delete:
      description: Delete an existing appointment template
      operationId: appointment_templates_delete
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
        - settings
      x-practice-access: '"share_appointment_profiles" need to be set for data access among practice'
    get:
      description: Retrieve an existing appointment template
      operationId: appointment_templates_read
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
        - settings
      x-practice-access: '"share_appointment_profiles" need to be set for data access among practice'
    patch:
      description: Update an existing appointment template
      operationId: appointment_templates_partial_update
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
        - settings
      x-practice-access: '"share_appointment_profiles" need to be set for data access among practice'
    put:
      description: Update an existing appointment template
      operationId: appointment_templates_update
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
        - settings
      x-practice-access: '"share_appointment_profiles" need to be set for data access among practice'
  /api/appointments:
    get:
      description: "Retrieve or search appointment or breaks.

        <b>Note:</b> Either `since`, `date` or `date_range` parameter must be specified.

        \            "
      operationId: appointments_list
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: Create a new appointment or break on doctor's calendar
      operationId: appointments_create
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/appointments/{id}":
    delete:
      description: Delete an existing appointment or break
      operationId: appointments_delete
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    get:
      description: Retrieve an existing appointment or break
      operationId: appointments_read
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      description: Update an existing appointment or break
      operationId: appointments_partial_update
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      description: Update an existing appointment or break
      operationId: appointments_update
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/billing_profiles:
    get:
      description: Retrieve or search billing profiles
      operationId: billing_profiles_list
      security:
        - drchrono_oauth2:
            - billing:read
            - billing:write
      tags:
        - Billing
      x-permissions:
        - billing
        - show-billing-tab
      x-practice-access: '"share_billing_profiles" need to be set for data access among practice'
  "/api/billing_profiles/{id}":
    get:
      description: Retrieve an existing billing profiles
      operationId: billing_profiles_read
      security:
        - drchrono_oauth2:
            - billing:read
            - billing:write
      tags:
        - Billing
      x-permissions:
        - billing
        - show-billing-tab
      x-practice-access: '"share_billing_profiles" need to be set for data access among practice'
  /api/care_plans:
    get:
      description: Retrieve or search care plans
      operationId: care_plans_list
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/care_plans/{id}":
    get:
      description: Retrieve an existing care plan
      operationId: care_plans_read
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/care_team_members:
    get:
      operationId: care_team_members_list
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/care_team_members/{id}":
    get:
      operationId: care_team_members_read
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/claim_billing_notes:
    get:
      description: Retrieve or search billing notes
      operationId: claim_billing_notes_list
      security:
        - drchrono_oauth2:
            - billing:read
            - billing:write
      tags:
        - Clinical
      x-permissions:
        - billing
        - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: Create a new billing note
      operationId: claim_billing_notes_create
      security:
        - drchrono_oauth2:
            - billing:read
            - billing:write
      tags:
        - Clinical
      x-permissions:
        - billing
        - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/claim_billing_notes/{id}":
    get:
      description: Retrieve an existing billing note
      operationId: claim_billing_notes_read
      security:
        - drchrono_oauth2:
            - billing:read
            - billing:write
      tags:
        - Clinical
      x-permissions:
        - billing
        - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/clinical_note_field_types:
    get:
      description: Retrieve or search clinical note field types
      operationId: clinical_note_field_types_list
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_clinical_templates" need to be set for data access among practice'
  "/api/clinical_note_field_types/{id}":
    get:
      description: Retrieve an existing clinial note field type
      operationId: clinical_note_field_types_read
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_clinical_templates" need to be set for data access among practice'
  /api/clinical_note_field_values:
    get:
      description: Retrieve or search clinical note field values
      operationId: clinical_note_field_values_list
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: Create clinical note field value
      operationId: clinical_note_field_values_create
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/clinical_note_field_values/{id}":
    get:
      description: Retrieve an existing clinical note field value
      operationId: clinical_note_field_values_read
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      description: Update an existing clinical note field value
      operationId: clinical_note_field_values_partial_update
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      description: Update an existing clinical note field value
      operationId: clinical_note_field_values_update
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/clinical_note_templates:
    get:
      description: Retrieve or search clinical note templates
      operationId: clinical_note_templates_list
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_clinical_templates" need to be set for data access among practice'
  "/api/clinical_note_templates/{id}":
    get:
      description: Retrieve an existing clinical note tempalte
      operationId: clinical_note_templates_read
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_clinical_templates" need to be set for data access among practice'
  /api/clinical_notes:
    get:
      operationId: clinical_notes_list
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/clinical_notes/{id}":
    get:
      operationId: clinical_notes_read
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/comm_logs:
    get:
      description: Retrieve or search communicatioin (phone call) logs
      operationId: comm_logs_list
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
      tags:
        - Billing
      x-permissions:
        - scheduling
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: Create communication (phone call) logs
      operationId: comm_logs_create
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
      tags:
        - Billing
      x-permissions:
        - scheduling
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/comm_logs/{id}":
    get:
      description: Retrieve an existing communication (phone call) logs
      operationId: comm_logs_read
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
      tags:
        - Billing
      x-permissions:
        - scheduling
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      description: Update an existing communication (phone call) logs
      operationId: comm_logs_partial_update
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
      tags:
        - Billing
      x-permissions:
        - scheduling
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      description: Update an existing communication (phone call) logs
      operationId: comm_logs_update
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
      tags:
        - Billing
      x-permissions:
        - scheduling
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/consent_forms:
    get:
      description: Retrieve or search patient consent forms
      operationId: consent_forms_list
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_consent_forms" need to be set for data access among practice'
    post:
      description: Create a patient consent form
      operationId: consent_forms_create
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_consent_forms" need to be set for data access among practice'
  "/api/consent_forms/{id}":
    get:
      description: Retrieve an existing patient consent form
      operationId: consent_forms_read
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_consent_forms" need to be set for data access among practice'
    patch:
      description: Update an existing patient consent form
      operationId: consent_forms_partial_update
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_consent_forms" need to be set for data access among practice'
    put:
      description: Update an existing patient consent form
      operationId: consent_forms_update
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_consent_forms" need to be set for data access among practice'
  "/api/consent_forms/{id}/apply_to_appointment":
    post:
      description: Assign (apply) a consent form to appointment
      operationId: consent_forms_apply_to_appointment
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_consent_forms" need to be set for data access among practice'
  "/api/consent_forms/{id}/unapply_from_appointment":
    post:
      description: Unassign (unapply) a consent form from appointment
      operationId: consent_forms_unapply_from_appointment
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_consent_forms" need to be set for data access among practice'
  /api/custom_appointment_fields:
    get:
      description: Retrieve or search custom appointment fields
      operationId: custom_appointment_fields_list
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
        - settings
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: Create custom appointment fields
      operationId: custom_appointment_fields_create
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
        - settings
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/custom_appointment_fields/{id}":
    get:
      description: Retrieve an existing custom appointment field
      operationId: custom_appointment_fields_read
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
        - settings
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      description: Update an existing custom appointment field
      operationId: custom_appointment_fields_partial_update
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
        - settings
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      description: Update an existing custom appointment field
      operationId: custom_appointment_fields_update
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
        - settings
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/custom_demographics:
    get:
      description: Retrieve or search custom demographics fields
      operationId: custom_demographics_list
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
        - settings
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: Create custom demographics fields
      operationId: custom_demographics_create
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
        - settings
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/custom_demographics/{id}":
    get:
      description: Retrieve an existing custom demographics field
      operationId: custom_demographics_read
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
        - settings
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      description: Update an existing custom demographics field
      operationId: custom_demographics_partial_update
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
        - settings
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      description: Update an existing custom demographics field
      operationId: custom_demographics_update
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
        - settings
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/custom_insurance_plan_names:
    get:
      description: Retrieve or search custom insurance plan names
      operationId: custom_insurance_plan_names_list
      security:
        - drchrono_oauth2:
            - settings:read
            - settings:write
      tags:
        - Billing
      x-permissions:
        - settings
      x-practice-access: Data access among practice is available
  "/api/custom_insurance_plan_names/{id}":
    get:
      description: Retrieve an existing custom insurance plan name
      operationId: custom_insurance_plan_names_read
      security:
        - drchrono_oauth2:
            - settings:read
            - settings:write
      tags:
        - Billing
      x-permissions:
        - settings
      x-practice-access: Data access among practice is available
  /api/custom_vitals:
    get:
      description: Retrieve or search custom vital types
      operationId: custom_vitals_list
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
        - settings
      x-practice-access: '"share_clinical_templates" need to be set for data access among practice'
  "/api/custom_vitals/{id}":
    get:
      description: Retrieve an existing custom vital type
      operationId: custom_vitals_read
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
        - settings
      x-practice-access: '"share_clinical_templates" need to be set for data access among practice'
  /api/doctors:
    get:
      description: Retrieve or search doctors within practice group
      operationId: doctors_list
      security:
        - drchrono_oauth2:
            - user:read
            - user:write
      tags:
        - Administrative
      x-permissions: []
      x-practice-access: Data access among practice is available
  "/api/doctors/{id}":
    get:
      description: Retrieve an existing dcotor
      operationId: doctors_read
      security:
        - drchrono_oauth2:
            - user:read
            - user:write
      tags:
        - Administrative
      x-permissions: []
      x-practice-access: Data access among practice is available
  /api/documents:
    get:
      description: Retrieve or search documents
      operationId: documents_list
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: Create documents
      operationId: documents_create
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/documents/{id}":
    delete:
      description: Delete an existing appointment template
      operationId: documents_delete
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
    get:
      description: Retrieve an existing appointment template
      operationId: documents_read
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      description: Update an existing appointment template
      operationId: documents_partial_update
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      description: Update an existing appointment template
      operationId: documents_update
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/eligibility_checks:
    get:
      description: Retrieve or search past eligibility checks for patient
      operationId: eligibility_checks_list
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
            - patients:read
            - patients:write
      tags:
        - Billing
      x-permissions:
        - scheduling
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/eligibility_checks/{id}":
    get:
      description: Retrieve an existing past eligibility check
      operationId: eligibility_checks_read
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
            - patients:read
            - patients:write
      tags:
        - Billing
      x-permissions:
        - scheduling
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/eobs:
    get:
      description: Retrieve or search EOB objects
      operationId: eobs_list
      security:
        - drchrono_oauth2:
            - billing:read
            - billing:write
      tags:
        - Clinical
      x-permissions:
        - billing
        - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: Create EOB object
      operationId: eobs_create
      security:
        - drchrono_oauth2:
            - billing:read
            - billing:write
      tags:
        - Clinical
      x-permissions:
        - billing
        - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/eobs/{id}":
    get:
      description: Retrieve an existing EOB object
      operationId: eobs_read
      security:
        - drchrono_oauth2:
            - billing:read
            - billing:write
      tags:
        - Clinical
      x-permissions:
        - billing
        - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/fee_schedules:
    get:
      operationId: fee_schedules_list
      security:
        - drchrono_oauth2:
            - billing:read
            - billing:write
      tags:
        - Clinical
      x-permissions:
        - billing
        - show-billing-tab
      x-practice-access: '"share_fee_schedules" need to be set for data access among practice'
  "/api/fee_schedules/{id}":
    get:
      operationId: fee_schedules_read
      security:
        - drchrono_oauth2:
            - billing:read
            - billing:write
      tags:
        - Clinical
      x-permissions:
        - billing
        - show-billing-tab
      x-practice-access: '"share_fee_schedules" need to be set for data access among practice'
  /api/implantable_devices:
    get:
      description: Retrieve or search implantable devices
      operationId: implantable_devices_list
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/implantable_devices/{id}":
    get:
      description: Retrieve an existing implantable device
      operationId: implantable_devices_read
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/insurances:
    get:
      operationId: insurances_list
      security:
        - drchrono_oauth2:
            - user:read
            - user:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: Data access among practice is available
  "/api/insurances/{id}":
    get:
      operationId: insurances_read
      security:
        - drchrono_oauth2:
            - user:read
            - user:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: Data access among practice is available
  /api/inventory_categories:
    get:
      description: Retrieve or search inventory categories
      operationId: inventory_categories_list
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - PracticeManagement
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_inventory" need to be set for data access among practice'
  "/api/inventory_categories/{id}":
    get:
      description: Retrieve an existing inventory category
      operationId: inventory_categories_read
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - PracticeManagement
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_inventory" need to be set for data access among practice'
  /api/inventory_vaccines:
    get:
      description: Retrieve or search vaccine inventories
      operationId: inventory_vaccines_list
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - PracticeManagement
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_inventory" need to be set for data access among practice'
    post:
      description: Create vaccine inventory
      operationId: inventory_vaccines_create
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - PracticeManagement
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_inventory" need to be set for data access among practice'
  "/api/inventory_vaccines/{id}":
    get:
      description: Retrieve an existing vaccine inventory
      operationId: inventory_vaccines_read
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - PracticeManagement
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_inventory" need to be set for data access among practice'
  /api/lab_documents:
    get:
      description: Retrieve or search lab order documents
      operationId: lab_documents_list
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: |
        Create lab order documents. An example lab workflow is as following:

        - When you get orders, submit them via `/api/lab_orders`, such that doctors can see them in drchrono.

        - When results come in, submit the result document PDF via `/api/lab_documents` and submit the results data via `/api/lab_results`

        - Update `/api/lab_orders` status
      operationId: lab_documents_create
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/lab_documents/{id}":
    delete:
      description: Delete an existing lab order document
      operationId: lab_documents_delete
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
    get:
      description: Retrieve an existing lab order document
      operationId: lab_documents_read
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      description: Update an existing lab order document
      operationId: lab_documents_partial_update
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      description: Update an existing lab order document
      operationId: lab_documents_update
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/lab_orders:
    get:
      description: Retrieve or search lab orders
      operationId: lab_orders_list
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: |
        Create lab orders. An example lab workflow is as following:

        - When you get orders, submit them via `/api/lab_orders`, such that doctors can see them in drchrono.

        - When results come in, submit the result document PDF via `/api/lab_documents` and submit the results data via `/api/lab_results`

        - Update `/api/lab_orders` status
      operationId: lab_orders_create
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/lab_orders/{id}":
    delete:
      description: Delete an existing lab order
      operationId: lab_orders_delete
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
    get:
      description: Retrieve an existing lab order
      operationId: lab_orders_read
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      description: Update an existing lab order
      operationId: lab_orders_partial_update
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      description: Update an existing lab order
      operationId: lab_orders_update
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/lab_orders_summary:
    get:
      operationId: lab_orders_summary_list
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/lab_orders_summary/{id}":
    get:
      operationId: lab_orders_summary_read
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/lab_results:
    get:
      description: Retrieve or search lab results
      operationId: lab_results_list
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: |
        Create lab results. An example lab workflow is as following:

        - When you get orders, submit them via `/api/lab_orders`, such that doctors can see them in drchrono.

        - When results come in, submit the result document PDF via `/api/lab_documents` and submit the results data via `/api/lab_results`

        - Update `/api/lab_orders` status
      operationId: lab_results_create
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/lab_results/{id}":
    delete:
      description: Delete an existing lab result
      operationId: lab_results_delete
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
    get:
      description: Retrieve an existing lab result
      operationId: lab_results_read
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      description: Update an existing lab result
      operationId: lab_results_partial_update
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      description: Update an existing lab result
      operationId: lab_results_update
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/lab_tests:
    get:
      description: Retrieve or search lab tests
      operationId: lab_tests_list
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: |
        Create lab tests. An example lab workflow is as following:

        - When you get orders, submit them via `/api/lab_orders`, such that doctors can see them in drchrono.

        - When results come in, submit the result document PDF via `/api/lab_documents` and submit the results data via `/api/lab_results`

        - Update `/api/lab_orders` status
      operationId: lab_tests_create
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/lab_tests/{id}":
    delete:
      description: Delete an existing lab test
      operationId: lab_tests_delete
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
    get:
      description: Retrieve an existing lab test
      operationId: lab_tests_read
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      description: Update an existing lab test
      operationId: lab_tests_partial_update
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      description: Update an existing lab test
      operationId: lab_tests_update
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/line_items:
    get:
      description: Retrieve or search billing line items
      operationId: line_items_list
      security:
        - drchrono_oauth2:
            - billing:read
            - billing:write
      tags:
        - Billing
      x-permissions:
        - billing
        - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: Create billing line item for appointments
      operationId: line_items_create
      security:
        - drchrono_oauth2:
            - billing:read
            - billing:write
      tags:
        - Billing
      x-permissions:
        - billing
        - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/line_items/{id}":
    delete:
      operationId: line_items_delete
      security:
        - drchrono_oauth2:
            - billing:read
            - billing:write
      tags:
        - Billing
      x-permissions:
        - billing
        - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
    get:
      description: Retrieve an existing billing line item
      operationId: line_items_read
      security:
        - drchrono_oauth2:
            - billing:read
            - billing:write
      tags:
        - Billing
      x-permissions:
        - billing
        - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      operationId: line_items_partial_update
      security:
        - drchrono_oauth2:
            - billing:read
            - billing:write
      tags:
        - Billing
      x-permissions:
        - billing
        - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      operationId: line_items_update
      security:
        - drchrono_oauth2:
            - billing:read
            - billing:write
      tags:
        - Billing
      x-permissions:
        - billing
        - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/medications:
    get:
      description: Retrieve or search patient medications
      operationId: medications_list
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: Create patient medications
      operationId: medications_create
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/medications/{id}":
    get:
      description: Retrieve an existing patient medications
      operationId: medications_read
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      description: Update an existing patient medications
      operationId: medications_partial_update
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      description: Update an existing patient medications
      operationId: medications_update
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/medications/{id}/append_to_pharmacy_note":
    patch:
      description: Append a message to the "pharmacy_note" section of the prescription, in a new paragraph
      operationId: medications_append_to_pharmacy_note
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/messages:
    get:
      description: Retrieve or search messages in doctor's message center
      operationId: messages_list
      security:
        - drchrono_oauth2:
            - messages:read
            - messages:write
      tags:
        - PracticeManagement
      x-permissions:
        - message-center
      x-practice-access: '"share_faxes" need to be set for data access among practice'
    post:
      description: Create messages in doctor's message center
      operationId: messages_create
      security:
        - drchrono_oauth2:
            - messages:read
            - messages:write
      tags:
        - PracticeManagement
      x-permissions:
        - message-center
      x-practice-access: '"share_faxes" need to be set for data access among practice'
  "/api/messages/{id}":
    delete:
      description: Delete an existing message in doctor's message center
      operationId: messages_delete
      security:
        - drchrono_oauth2:
            - messages:read
            - messages:write
      tags:
        - PracticeManagement
      x-permissions:
        - message-center
      x-practice-access: '"share_faxes" need to be set for data access among practice'
    get:
      description: Retrieve an existing message in doctor's message center
      operationId: messages_read
      security:
        - drchrono_oauth2:
            - messages:read
            - messages:write
      tags:
        - PracticeManagement
      x-permissions:
        - message-center
      x-practice-access: '"share_faxes" need to be set for data access among practice'
    patch:
      description: Update an existing message in doctor's message center
      operationId: messages_partial_update
      security:
        - drchrono_oauth2:
            - messages:read
            - messages:write
      tags:
        - PracticeManagement
      x-permissions:
        - message-center
      x-practice-access: '"share_faxes" need to be set for data access among practice'
    put:
      description: Update an existing message in doctor's message center
      operationId: messages_update
      security:
        - drchrono_oauth2:
            - messages:read
            - messages:write
      tags:
        - PracticeManagement
      x-permissions:
        - message-center
      x-practice-access: '"share_faxes" need to be set for data access among practice'
  /api/offices:
    get:
      description: Retrieve or search offices
      operationId: offices_list
      security:
        - drchrono_oauth2:
            - user:read
            - user:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
  "/api/offices/{id}":
    get:
      description: Retrieve an existing office
      operationId: offices_read
      security:
        - drchrono_oauth2:
            - user:read
            - user:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
    patch:
      description: Update an existing office
      operationId: offices_partial_update
      security:
        - drchrono_oauth2:
            - user:read
            - user:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
    put:
      description: Update an existing office
      operationId: offices_update
      security:
        - drchrono_oauth2:
            - user:read
            - user:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
  "/api/offices/{id}/add_exam_room":
    post:
      description: Add an exam room to the office
      operationId: offices_add_exam_room
      security:
        - drchrono_oauth2:
            - user:read
            - user:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
  /api/patient_communications:
    get:
      description: Retrieve or search patient communications for CQM
      operationId: patient_communications_list
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: Create patient communication for CQM
      operationId: patient_communications_create
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/patient_communications/{id}":
    get:
      description: Retrieve an existing patient communication for CQM
      operationId: patient_communications_read
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      description: Update an existing patient communication for CQM
      operationId: patient_communications_partial_update
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      description: Update an existing patient communication for CQM
      operationId: patient_communications_update
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/patient_flag_types:
    get:
      description: Retrieve or search patient flag types
      operationId: patient_flag_types_list
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
        - settings
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: Create patient flag types
      operationId: patient_flag_types_create
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
        - settings
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/patient_flag_types/{id}":
    get:
      description: Retrieve an existing patient flag type
      operationId: patient_flag_types_read
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
        - settings
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      description: Update an existing patient flag type
      operationId: patient_flag_types_partial_update
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
        - settings
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      description: Update an existing patient flag type
      operationId: patient_flag_types_update
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
            - settings:read
            - settings:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
        - settings
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/patient_interventions:
    get:
      description: Retrieve or search patient interventions for CQM
      operationId: patient_interventions_list
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: Create patient intervention for CQM
      operationId: patient_interventions_create
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/patient_interventions/{id}":
    get:
      description: Retrieve an existing patient intervention for CQM
      operationId: patient_interventions_read
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      description: Update an existing patient intervention for CQM
      operationId: patient_interventions_partial_update
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      description: Update an existing patient intervention for CQM
      operationId: patient_interventions_update
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/patient_lab_results:
    get:
      operationId: patient_lab_results_list
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      operationId: patient_lab_results_create
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/patient_lab_results/{id}":
    delete:
      operationId: patient_lab_results_delete
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
    get:
      operationId: patient_lab_results_read
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      operationId: patient_lab_results_partial_update
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      operationId: patient_lab_results_update
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/patient_messages:
    get:
      operationId: patient_messages_list
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
            - messages:read
            - messages:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
        - message-center
      x-practice-access: '"share_faxes" need to be set for data access among practice'
    post:
      operationId: patient_messages_create
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
            - messages:read
            - messages:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
        - message-center
      x-practice-access: '"share_faxes" need to be set for data access among practice'
  "/api/patient_messages/{id}":
    get:
      operationId: patient_messages_read
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
            - messages:read
            - messages:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
        - message-center
      x-practice-access: '"share_faxes" need to be set for data access among practice'
    patch:
      operationId: patient_messages_partial_update
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
            - messages:read
            - messages:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
        - message-center
      x-practice-access: '"share_faxes" need to be set for data access among practice'
    put:
      operationId: patient_messages_update
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
            - messages:read
            - messages:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
        - message-center
      x-practice-access: '"share_faxes" need to be set for data access among practice'
  /api/patient_payment_log:
    get:
      description: Retrieve or search patient payment logs
      operationId: patient_payment_log_list
      security:
        - drchrono_oauth2:
            - billing:read
            - billing:write
      tags:
        - Billing
      x-permissions:
        - billing
        - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/patient_payment_log/{id}":
    get:
      description: Retrieve an existing patient payment log
      operationId: patient_payment_log_read
      security:
        - drchrono_oauth2:
            - billing:read
            - billing:write
      tags:
        - Billing
      x-permissions:
        - billing
        - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/patient_payments:
    get:
      description: Retrieve or search patient payments
      operationId: patient_payments_list
      security:
        - drchrono_oauth2:
            - billing:patient-payment:read
            - billing:patient-payment:write
      tags:
        - Billing
      x-permissions:
        - access-patient-payments
        - billing
        - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: Create patient payment
      operationId: patient_payments_create
      security:
        - drchrono_oauth2:
            - billing:patient-payment:read
            - billing:patient-payment:write
      tags:
        - Billing
      x-permissions:
        - access-patient-payments
        - billing
        - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/patient_payments/{id}":
    get:
      description: Retrieve an existing patient payment
      operationId: patient_payments_read
      security:
        - drchrono_oauth2:
            - billing:patient-payment:read
            - billing:patient-payment:write
      tags:
        - Billing
      x-permissions:
        - access-patient-payments
        - billing
        - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/patient_physical_exams:
    get:
      description: Retrieve or search patient physical exams for CQM
      operationId: patient_physical_exams_list
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: Create patient physical exam for CQM
      operationId: patient_physical_exams_create
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/patient_physical_exams/{id}":
    get:
      description: Retrieve an existing patient physical exam for CQM
      operationId: patient_physical_exams_read
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      description: Update an existing patient physical exam for CQM
      operationId: patient_physical_exams_partial_update
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      description: Update an existing patient physical exam for CQM
      operationId: patient_physical_exams_update
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/patient_risk_assessments:
    get:
      operationId: patient_risk_assessments_list
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      operationId: patient_risk_assessments_create
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/patient_risk_assessments/{id}":
    get:
      operationId: patient_risk_assessments_read
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      operationId: patient_risk_assessments_partial_update
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      operationId: patient_risk_assessments_update
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/patient_vaccine_records:
    get:
      description: Retrieve or search patient vaccine records
      operationId: patient_vaccine_records_list
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_inventory", "share_patients" need to be set for data access among practice'
    post:
      description: Create patient vaccine records
      operationId: patient_vaccine_records_create
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_inventory", "share_patients" need to be set for data access among practice'
  "/api/patient_vaccine_records/{id}":
    get:
      description: Retrieve an existing patient vaccine records
      operationId: patient_vaccine_records_read
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_inventory", "share_patients" need to be set for data access among practice'
    patch:
      description: Update an existing patient vaccine records
      operationId: patient_vaccine_records_partial_update
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_inventory", "share_patients" need to be set for data access among practice'
    put:
      description: Update an existing patient vaccine records
      operationId: patient_vaccine_records_update
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_inventory", "share_patients" need to be set for data access among practice'
  /api/patients:
    get:
      description: Retrieve or search patients
      operationId: patients_list
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: Create patient
      operationId: patients_create
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/patients/{id}":
    delete:
      description: Delete an existing patient
      operationId: patients_delete
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
    get:
      description: Retrieve an existing patient
      operationId: patients_read
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      description: Update an existing patient
      operationId: patients_partial_update
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      description: Update an existing patient
      operationId: patients_update
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/patients/{id}/ccda":
    get:
      description: Retrieve patient CCDA
      operationId: patients_ccda
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/patients/{id}/onpatient_access":
    delete:
      description: Revoke sent onpatient invites
      operationId: patients_onpatient_access_delete
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
    get:
      description: Retrieve or search existing onpatient access invites
      operationId: patients_onpatient_access_read
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: Send new onpatient invite to patient
      operationId: patients_onpatient_access_create
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/patients/{id}/qrda1":
    get:
      description: Retrieve patient QRDA1
      operationId: patients_qrda1
      security:
        - drchrono_oauth2:
            - patients:read
            - patients:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/patients_summary:
    get:
      operationId: patients_summary_list
      security:
        - drchrono_oauth2:
            - patients:summary:read
            - patients:summary:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      operationId: patients_summary_create
      security:
        - drchrono_oauth2:
            - patients:summary:read
            - patients:summary:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/patients_summary/{id}":
    delete:
      operationId: patients_summary_delete
      security:
        - drchrono_oauth2:
            - patients:summary:read
            - patients:summary:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
    get:
      operationId: patients_summary_read
      security:
        - drchrono_oauth2:
            - patients:summary:read
            - patients:summary:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      operationId: patients_summary_partial_update
      security:
        - drchrono_oauth2:
            - patients:summary:read
            - patients:summary:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      operationId: patients_summary_update
      security:
        - drchrono_oauth2:
            - patients:summary:read
            - patients:summary:write
      tags:
        - Clinical
      x-permissions:
        - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/prescription_messages:
    get:
      description: Retrieve or search prescription messages
      operationId: prescription_messages_list
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/prescription_messages/{id}":
    get:
      description: Retrieve an existing prescription message
      operationId: prescription_messages_read
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/problems:
    get:
      description: Retrieve or search patient problems
      operationId: problems_list
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    post:
      description: Create patient problems
      operationId: problems_create
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/problems/{id}":
    get:
      description: Retrieve an existing patient problems
      operationId: problems_read
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    patch:
      description: Update an existing patient problems
      operationId: problems_partial_update
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
    put:
      description: Update an existing patient problems
      operationId: problems_update
      security:
        - drchrono_oauth2:
            - clinical:read
            - clinical:write
      tags:
        - Clinical
      x-permissions:
        - clinical-notes
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/procedures:
    get:
      operationId: procedures_list
      security:
        - drchrono_oauth2:
            - billing:read
            - billing:write
      tags:
        - Billing
      x-permissions:
        - billing
        - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/procedures/{id}":
    get:
      operationId: procedures_read
      security:
        - drchrono_oauth2:
            - billing:read
            - billing:write
      tags:
        - Billing
      x-permissions:
        - billing
        - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/reminder_profiles:
    get:
      description: Retrieve or search reminder profiles
      operationId: reminder_profiles_list
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
      x-practice-access: '"share_reminder_profile" need to be set for data access among practice'
    post:
      description: Create reminder profile
      operationId: reminder_profiles_create
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
      x-practice-access: '"share_reminder_profile" need to be set for data access among practice'
  "/api/reminder_profiles/{id}":
    delete:
      description: Delete an existing reminder profile
      operationId: reminder_profiles_delete
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
      x-practice-access: '"share_reminder_profile" need to be set for data access among practice'
    get:
      description: Retrieve an existing reminder profile
      operationId: reminder_profiles_read
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
      x-practice-access: '"share_reminder_profile" need to be set for data access among practice'
    patch:
      description: Update an existing reminder profile
      operationId: reminder_profiles_partial_update
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
      x-practice-access: '"share_reminder_profile" need to be set for data access among practice'
    put:
      description: Update an existing reminder profile
      operationId: reminder_profiles_update
      security:
        - drchrono_oauth2:
            - calendar:read
            - calendar:write
      tags:
        - Clinical
      x-permissions:
        - scheduling
      x-practice-access: '"share_reminder_profile" need to be set for data access among practice'
  /api/sublabs:
    get:
      description: Retrieve or search sub vendors
      operationId: sublabs_list
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: Data access among practice is available
    post:
      description: |
        Create sub-vendors

        - When you get orders, submit them via `/api/lab_orders`, such that doctors can see them in drchrono.

        - When results come in, submit the result document PDF via `/api/lab_documents` and submit the results data via `/api/lab_results`

        - Update `/api/lab_orders` status
      operationId: sublabs_create
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: Data access among practice is available
  "/api/sublabs/{id}":
    delete:
      description: Delete an existing sub vendor
      operationId: sublabs_delete
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: Data access among practice is available
    get:
      description: Retrieve an existing sub vendor
      operationId: sublabs_read
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: Data access among practice is available
    patch:
      description: Update an existing sub vendor
      operationId: sublabs_partial_update
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: Data access among practice is available
    put:
      description: Update an existing sub vendor
      operationId: sublabs_update
      security:
        - drchrono_oauth2:
            - labs:read
            - labs:write
      tags:
        - Clinical
      x-permissions: []
      x-practice-access: Data access among practice is available
  /api/task_categories:
    get:
      description: Retrieve or search task categories
      operationId: task_categories_list
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
    post:
      description: Create a task category
      operationId: task_categories_create
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
  "/api/task_categories/{id}":
    get:
      description: Retrieve an existing task category
      operationId: task_categories_read
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
    patch:
      description: Update an existing task category
      operationId: task_categories_partial_update
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
    put:
      description: Update an existing task category
      operationId: task_categories_update
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
  /api/task_notes:
    get:
      description: Retrieve or search task notes
      operationId: task_notes_list
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
    post:
      description: Create a task note
      operationId: task_notes_create
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
  "/api/task_notes/{id}":
    get:
      description: Retrieve an existing task note
      operationId: task_notes_read
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
    patch:
      description: Update an existing task note
      operationId: task_notes_partial_update
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
    put:
      description: Update an existing task note
      operationId: task_notes_update
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
  /api/task_statuses:
    get:
      description: Retrieve or search task statuses
      operationId: task_statuses_list
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
    post:
      description: Create a task status
      operationId: task_statuses_create
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
  "/api/task_statuses/{id}":
    get:
      description: Retrieve an existing task status
      operationId: task_statuses_read
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
    patch:
      description: Update an existing task status
      operationId: task_statuses_partial_update
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
    put:
      description: Update an existing task status
      operationId: task_statuses_update
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
  /api/task_templates:
    get:
      description: Retrieve or search task templates
      operationId: task_templates_list
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
    post:
      description: Create a task template
      operationId: task_templates_create
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
  "/api/task_templates/{id}":
    get:
      description: Retrieve an existing task template
      operationId: task_templates_read
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
    patch:
      description: Update an existing task template
      operationId: task_templates_partial_update
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
    put:
      description: Update an existing task template
      operationId: task_templates_update
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
  /api/tasks:
    get:
      description: Retrieve or search tasks
      operationId: tasks_list
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
    post:
      description: Create a task
      operationId: tasks_create
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
  "/api/tasks/{id}":
    get:
      description: Retrieve an existing task
      operationId: tasks_read
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
    patch:
      description: Update an existing task
      operationId: tasks_partial_update
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
    put:
      description: Update an existing task
      operationId: tasks_update
      security:
        - drchrono_oauth2:
            - tasks:read
            - tasks:write
      tags:
        - PracticeManagement
      x-permissions: []
      x-practice-access: Data access among practice is available
  /api/transactions:
    get:
      description: Retrieve or search insurance transactions associated with billing line items
      operationId: transactions_list
      security:
        - drchrono_oauth2:
            - billing:read
            - billing:write
      tags:
        - Billing
      x-permissions:
        - billing
        - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
  "/api/transactions/{id}":
    get:
      description: Retrieve an existing insurance transaction
      operationId: transactions_read
      security:
        - drchrono_oauth2:
            - billing:read
            - billing:write
      tags:
        - Billing
      x-permissions:
        - billing
        - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
  /api/user_groups:
    get:
      description: Retrieve or search user groups
      operationId: user_groups_list
      security:
        - drchrono_oauth2: []
      tags:
        - Administrative
      x-permissions: []
      x-practice-access: Data access among practice is available
  "/api/user_groups/{id}":
    get:
      description: Retrieve an existing user group
      operationId: user_groups_read
      security:
        - drchrono_oauth2: []
      tags:
        - Administrative
      x-permissions: []
      x-practice-access: Data access among practice is available
  /api/users:
    get:
      description: Retrieve or search users, `/api/users/current` can be used to identify logged in user, it will redirect to `/api/users/{current_user_id}`
      operationId: users_list
      security:
        - drchrono_oauth2: []
      tags:
        - Administrative
      x-permissions: []
      x-practice-access: Data access among practice is available
  "/api/users/{id}":
    get:
      description: Retrieve an existing user, `/api/users/current` can be used to identify logged in user, it will redirect to `/api/users/{current_user_id}`
      operationId: users_read
      security:
        - drchrono_oauth2: []
      tags:
        - Administrative
      x-permissions: []
      x-practice-access: Data access among practice is available
components:
  securitySchemes:
    drchrono_oauth2:
      description: ""
      flows:
        authorizationCode:
          authorizationUrl: https://drchrono.com/o/authorize/
          scopes:
            billing:patient-payment:read: View patient payment information
            billing:patient-payment:write: Modify patient payment information
            billing:read: View billing information.
            billing:write: Modify billing information.
            calendar:read: View your appointments.
            calendar:write: Schedule appointments and modify the data associated with them.
            clinical:read: View clinical information, such as vitals, clinical notes, medications and diagnoses.
            clinical:write: Create and modify clinical information, such as vitals, clinical notes, medications and diagnoses.
            labs:read: View patient lab orders and results.
            labs:write: Create and modify patient lab orders and results.
            messages:read: View messages in your message center.
            messages:write: Create and modify messages in your message center.
            patients:read: View detailed patient information.
            patients:summary:read: View summary information about your patients. This includes patients' name, chart_id, age, and gender.
            patients:summary:write: Create new patients and set their name, chart_id, age, and gender.
            patients:write: Create patients and modify detailed patient information.
            settings:read: View resources that requires Settings permission, such as custom fields.
            settings:write: Create resources that requires Settings permission, such as custom fields.
            tasks:read: View tasks in your tasks center
            tasks:write: Create and modify tasks in your tasks center
            user:read: View your basic information.
            user:write: Edit select account information, such as creating new exam rooms.
          tokenUrl: https://drchrono.com/o/token/
      type: oauth2
