openapi: 3.0.0
servers:
  - url: https://www.googleapis.com/replicapool/v1beta1/projects
info:
  contact:
    name: Google
    url: https://google.com
  description: The Replica Pool API allows users to declaratively provision and manage groups of Google Compute Engine instances based on a common template.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Replica Pool
  version: v1beta1
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
    - backend
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png
  x-origin:
    - converter:
        url: https://github.com/lucybot/api-spec-converter
        version: 2.7.31
      format: google
      url: https://www.googleapis.com/discovery/v1/apis/replicapool/v1beta1/rest
      version: v1
  x-providerName: googleapis.com
  x-serviceName: replicapool
tags:
  - name: pools
  - name: replicas
paths:
  "/{projectName}/zones/{zone}/pools":
    get:
      description: List all replica pools.
      operationId: replicapool.pools.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform.read-only
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform.read-only
        - Oauth2:
            - https://www.googleapis.com/auth/ndev.cloudman
          Oauth2c:
            - https://www.googleapis.com/auth/ndev.cloudman
        - Oauth2:
            - https://www.googleapis.com/auth/ndev.cloudman.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/ndev.cloudman.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/replicapool
          Oauth2c:
            - https://www.googleapis.com/auth/replicapool
        - Oauth2:
            - https://www.googleapis.com/auth/replicapool.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/replicapool.readonly
      tags:
        - pools
    post:
      description: Inserts a new replica pool.
      operationId: replicapool.pools.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
        - Oauth2:
            - https://www.googleapis.com/auth/ndev.cloudman
          Oauth2c:
            - https://www.googleapis.com/auth/ndev.cloudman
        - Oauth2:
            - https://www.googleapis.com/auth/replicapool
          Oauth2c:
            - https://www.googleapis.com/auth/replicapool
      tags:
        - pools
  "/{projectName}/zones/{zone}/pools/{poolName}":
    get:
      description: Gets information about a single replica pool.
      operationId: replicapool.pools.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform.read-only
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform.read-only
        - Oauth2:
            - https://www.googleapis.com/auth/ndev.cloudman
          Oauth2c:
            - https://www.googleapis.com/auth/ndev.cloudman
        - Oauth2:
            - https://www.googleapis.com/auth/ndev.cloudman.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/ndev.cloudman.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/replicapool
          Oauth2c:
            - https://www.googleapis.com/auth/replicapool
        - Oauth2:
            - https://www.googleapis.com/auth/replicapool.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/replicapool.readonly
      tags:
        - pools
    post:
      description: Deletes a replica pool.
      operationId: replicapool.pools.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
        - Oauth2:
            - https://www.googleapis.com/auth/ndev.cloudman
          Oauth2c:
            - https://www.googleapis.com/auth/ndev.cloudman
        - Oauth2:
            - https://www.googleapis.com/auth/replicapool
          Oauth2c:
            - https://www.googleapis.com/auth/replicapool
      tags:
        - pools
  "/{projectName}/zones/{zone}/pools/{poolName}/replicas":
    get:
      description: Lists all replicas in a pool.
      operationId: replicapool.replicas.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform.read-only
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform.read-only
        - Oauth2:
            - https://www.googleapis.com/auth/ndev.cloudman
          Oauth2c:
            - https://www.googleapis.com/auth/ndev.cloudman
        - Oauth2:
            - https://www.googleapis.com/auth/ndev.cloudman.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/ndev.cloudman.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/replicapool
          Oauth2c:
            - https://www.googleapis.com/auth/replicapool
        - Oauth2:
            - https://www.googleapis.com/auth/replicapool.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/replicapool.readonly
      tags:
        - replicas
  "/{projectName}/zones/{zone}/pools/{poolName}/replicas/{replicaName}":
    get:
      description: Gets information about a specific replica.
      operationId: replicapool.replicas.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform.read-only
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform.read-only
        - Oauth2:
            - https://www.googleapis.com/auth/ndev.cloudman
          Oauth2c:
            - https://www.googleapis.com/auth/ndev.cloudman
        - Oauth2:
            - https://www.googleapis.com/auth/ndev.cloudman.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/ndev.cloudman.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/replicapool
          Oauth2c:
            - https://www.googleapis.com/auth/replicapool
        - Oauth2:
            - https://www.googleapis.com/auth/replicapool.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/replicapool.readonly
      tags:
        - replicas
    post:
      description: Deletes a replica from the pool.
      operationId: replicapool.replicas.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
        - Oauth2:
            - https://www.googleapis.com/auth/ndev.cloudman
          Oauth2c:
            - https://www.googleapis.com/auth/ndev.cloudman
        - Oauth2:
            - https://www.googleapis.com/auth/replicapool
          Oauth2c:
            - https://www.googleapis.com/auth/replicapool
      tags:
        - replicas
  "/{projectName}/zones/{zone}/pools/{poolName}/replicas/{replicaName}/restart":
    post:
      description: Restarts a replica in a pool.
      operationId: replicapool.replicas.restart
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
        - Oauth2:
            - https://www.googleapis.com/auth/ndev.cloudman
          Oauth2c:
            - https://www.googleapis.com/auth/ndev.cloudman
        - Oauth2:
            - https://www.googleapis.com/auth/replicapool
          Oauth2c:
            - https://www.googleapis.com/auth/replicapool
      tags:
        - replicas
  "/{projectName}/zones/{zone}/pools/{poolName}/resize":
    post:
      description: Resize a pool. This is an asynchronous operation, and multiple overlapping resize requests can be made. Replica Pools will use the information from the last resize request.
      operationId: replicapool.pools.resize
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
        - Oauth2:
            - https://www.googleapis.com/auth/ndev.cloudman
          Oauth2c:
            - https://www.googleapis.com/auth/ndev.cloudman
        - Oauth2:
            - https://www.googleapis.com/auth/replicapool
          Oauth2c:
            - https://www.googleapis.com/auth/replicapool
      tags:
        - pools
  "/{projectName}/zones/{zone}/pools/{poolName}/updateTemplate":
    post:
      description: Update the template used by the pool.
      operationId: replicapool.pools.updatetemplate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
        - Oauth2:
            - https://www.googleapis.com/auth/ndev.cloudman
          Oauth2c:
            - https://www.googleapis.com/auth/ndev.cloudman
        - Oauth2:
            - https://www.googleapis.com/auth/replicapool
          Oauth2c:
            - https://www.googleapis.com/auth/replicapool
      tags:
        - pools
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/cloud-platform: View and manage your data across Google Cloud Platform services
            https://www.googleapis.com/auth/cloud-platform.read-only: View your data across Google Cloud Platform services
            https://www.googleapis.com/auth/ndev.cloudman: View and manage your Google Cloud Platform management resources and deployment status information
            https://www.googleapis.com/auth/ndev.cloudman.readonly: View your Google Cloud Platform management resources and deployment status information
            https://www.googleapis.com/auth/replicapool: View and manage replica pools
            https://www.googleapis.com/auth/replicapool.readonly: View replica pools
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 accessCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/cloud-platform: View and manage your data across Google Cloud Platform services
            https://www.googleapis.com/auth/cloud-platform.read-only: View your data across Google Cloud Platform services
            https://www.googleapis.com/auth/ndev.cloudman: View and manage your Google Cloud Platform management resources and deployment status information
            https://www.googleapis.com/auth/ndev.cloudman.readonly: View your Google Cloud Platform management resources and deployment status information
            https://www.googleapis.com/auth/replicapool: View and manage replica pools
            https://www.googleapis.com/auth/replicapool.readonly: View replica pools
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
