swagger: "2.0"
schemes:
  - https
host: esi.evetech.net
basePath: /latest
info:
  description: An OpenAPI for EVE Online
  title: EVE Swagger Interface
  version: 0.8.6
  x-apisguru-categories:
    - media
  x-logo:
    backgroundColor: "#FFFFFF"
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_Evetech_profile_image.jpeg
  x-origin:
    - format: swagger
      url: https://esi.tech.ccp.is/latest/swagger.json
      version: "2.0"
  x-providerName: evetech.net
securityDefinitions:
  evesso:
    authorizationUrl: https://login.eveonline.com/v2/oauth/authorize
    flow: implicit
    scopes:
      esi-alliances.read_contacts.v1: EVE SSO scope esi-alliances.read_contacts.v1
      esi-assets.read_assets.v1: EVE SSO scope esi-assets.read_assets.v1
      esi-assets.read_corporation_assets.v1: EVE SSO scope esi-assets.read_corporation_assets.v1
      esi-bookmarks.read_character_bookmarks.v1: EVE SSO scope esi-bookmarks.read_character_bookmarks.v1
      esi-bookmarks.read_corporation_bookmarks.v1: EVE SSO scope esi-bookmarks.read_corporation_bookmarks.v1
      esi-calendar.read_calendar_events.v1: EVE SSO scope esi-calendar.read_calendar_events.v1
      esi-calendar.respond_calendar_events.v1: EVE SSO scope esi-calendar.respond_calendar_events.v1
      esi-characters.read_agents_research.v1: EVE SSO scope esi-characters.read_agents_research.v1
      esi-characters.read_blueprints.v1: EVE SSO scope esi-characters.read_blueprints.v1
      esi-characters.read_contacts.v1: EVE SSO scope esi-characters.read_contacts.v1
      esi-characters.read_corporation_roles.v1: EVE SSO scope esi-characters.read_corporation_roles.v1
      esi-characters.read_fatigue.v1: EVE SSO scope esi-characters.read_fatigue.v1
      esi-characters.read_fw_stats.v1: EVE SSO scope esi-characters.read_fw_stats.v1
      esi-characters.read_loyalty.v1: EVE SSO scope esi-characters.read_loyalty.v1
      esi-characters.read_medals.v1: EVE SSO scope esi-characters.read_medals.v1
      esi-characters.read_notifications.v1: EVE SSO scope esi-characters.read_notifications.v1
      esi-characters.read_opportunities.v1: EVE SSO scope esi-characters.read_opportunities.v1
      esi-characters.read_standings.v1: EVE SSO scope esi-characters.read_standings.v1
      esi-characters.read_titles.v1: EVE SSO scope esi-characters.read_titles.v1
      esi-characters.write_contacts.v1: EVE SSO scope esi-characters.write_contacts.v1
      esi-characterstats.read.v1: EVE SSO scope esi-characterstats.read.v1
      esi-clones.read_clones.v1: EVE SSO scope esi-clones.read_clones.v1
      esi-clones.read_implants.v1: EVE SSO scope esi-clones.read_implants.v1
      esi-contracts.read_character_contracts.v1: EVE SSO scope esi-contracts.read_character_contracts.v1
      esi-contracts.read_corporation_contracts.v1: EVE SSO scope esi-contracts.read_corporation_contracts.v1
      esi-corporations.read_blueprints.v1: EVE SSO scope esi-corporations.read_blueprints.v1
      esi-corporations.read_contacts.v1: EVE SSO scope esi-corporations.read_contacts.v1
      esi-corporations.read_container_logs.v1: EVE SSO scope esi-corporations.read_container_logs.v1
      esi-corporations.read_corporation_membership.v1: EVE SSO scope esi-corporations.read_corporation_membership.v1
      esi-corporations.read_divisions.v1: EVE SSO scope esi-corporations.read_divisions.v1
      esi-corporations.read_facilities.v1: EVE SSO scope esi-corporations.read_facilities.v1
      esi-corporations.read_fw_stats.v1: EVE SSO scope esi-corporations.read_fw_stats.v1
      esi-corporations.read_medals.v1: EVE SSO scope esi-corporations.read_medals.v1
      esi-corporations.read_standings.v1: EVE SSO scope esi-corporations.read_standings.v1
      esi-corporations.read_starbases.v1: EVE SSO scope esi-corporations.read_starbases.v1
      esi-corporations.read_structures.v1: EVE SSO scope esi-corporations.read_structures.v1
      esi-corporations.read_titles.v1: EVE SSO scope esi-corporations.read_titles.v1
      esi-corporations.track_members.v1: EVE SSO scope esi-corporations.track_members.v1
      esi-fittings.read_fittings.v1: EVE SSO scope esi-fittings.read_fittings.v1
      esi-fittings.write_fittings.v1: EVE SSO scope esi-fittings.write_fittings.v1
      esi-fleets.read_fleet.v1: EVE SSO scope esi-fleets.read_fleet.v1
      esi-fleets.write_fleet.v1: EVE SSO scope esi-fleets.write_fleet.v1
      esi-industry.read_character_jobs.v1: EVE SSO scope esi-industry.read_character_jobs.v1
      esi-industry.read_character_mining.v1: EVE SSO scope esi-industry.read_character_mining.v1
      esi-industry.read_corporation_jobs.v1: EVE SSO scope esi-industry.read_corporation_jobs.v1
      esi-industry.read_corporation_mining.v1: EVE SSO scope esi-industry.read_corporation_mining.v1
      esi-killmails.read_corporation_killmails.v1: EVE SSO scope esi-killmails.read_corporation_killmails.v1
      esi-killmails.read_killmails.v1: EVE SSO scope esi-killmails.read_killmails.v1
      esi-location.read_location.v1: EVE SSO scope esi-location.read_location.v1
      esi-location.read_online.v1: EVE SSO scope esi-location.read_online.v1
      esi-location.read_ship_type.v1: EVE SSO scope esi-location.read_ship_type.v1
      esi-mail.organize_mail.v1: EVE SSO scope esi-mail.organize_mail.v1
      esi-mail.read_mail.v1: EVE SSO scope esi-mail.read_mail.v1
      esi-mail.send_mail.v1: EVE SSO scope esi-mail.send_mail.v1
      esi-markets.read_character_orders.v1: EVE SSO scope esi-markets.read_character_orders.v1
      esi-markets.read_corporation_orders.v1: EVE SSO scope esi-markets.read_corporation_orders.v1
      esi-markets.structure_markets.v1: EVE SSO scope esi-markets.structure_markets.v1
      esi-planets.manage_planets.v1: EVE SSO scope esi-planets.manage_planets.v1
      esi-planets.read_customs_offices.v1: EVE SSO scope esi-planets.read_customs_offices.v1
      esi-search.search_structures.v1: EVE SSO scope esi-search.search_structures.v1
      esi-skills.read_skillqueue.v1: EVE SSO scope esi-skills.read_skillqueue.v1
      esi-skills.read_skills.v1: EVE SSO scope esi-skills.read_skills.v1
      esi-ui.open_window.v1: EVE SSO scope esi-ui.open_window.v1
      esi-ui.write_waypoint.v1: EVE SSO scope esi-ui.write_waypoint.v1
      esi-universe.read_structures.v1: EVE SSO scope esi-universe.read_structures.v1
      esi-wallet.read_character_wallet.v1: EVE SSO scope esi-wallet.read_character_wallet.v1
      esi-wallet.read_corporation_wallets.v1: EVE SSO scope esi-wallet.read_corporation_wallets.v1
    type: oauth2
paths:
  /alliances/:
    get:
      description: |-
        List all active player alliances

        ---
        Alternate route: `/dev/alliances/`

        Alternate route: `/legacy/alliances/`

        Alternate route: `/v1/alliances/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_alliances
      summary: List all alliances
      tags:
        - Alliance
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/alliances/{alliance_id}/":
    get:
      description: |-
        Public information about an alliance

        ---
        Alternate route: `/dev/alliances/{alliance_id}/`

        Alternate route: `/v3/alliances/{alliance_id}/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_alliances_alliance_id
      summary: Get alliance information
      tags:
        - Alliance
      x-alternate-versions:
        - dev
        - v3
      x-cached-seconds: 3600
  "/alliances/{alliance_id}/contacts/":
    get:
      description: |-
        Return contacts of an alliance

        ---
        Alternate route: `/dev/alliances/{alliance_id}/contacts/`

        Alternate route: `/v2/alliances/{alliance_id}/contacts/`

        ---
        This route is cached for up to 300 seconds
      operationId: get_alliances_alliance_id_contacts
      security:
        - evesso:
            - esi-alliances.read_contacts.v1
      summary: Get alliance contacts
      tags:
        - Contacts
      x-alternate-versions:
        - dev
        - v2
      x-cached-seconds: 300
  "/alliances/{alliance_id}/contacts/labels/":
    get:
      description: |-
        Return custom labels for an alliance's contacts

        ---
        Alternate route: `/dev/alliances/{alliance_id}/contacts/labels/`

        Alternate route: `/legacy/alliances/{alliance_id}/contacts/labels/`

        Alternate route: `/v1/alliances/{alliance_id}/contacts/labels/`

        ---
        This route is cached for up to 300 seconds
      operationId: get_alliances_alliance_id_contacts_labels
      security:
        - evesso:
            - esi-alliances.read_contacts.v1
      summary: Get alliance contact labels
      tags:
        - Contacts
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 300
  "/alliances/{alliance_id}/corporations/":
    get:
      description: |-
        List all current member corporations of an alliance

        ---
        Alternate route: `/dev/alliances/{alliance_id}/corporations/`

        Alternate route: `/legacy/alliances/{alliance_id}/corporations/`

        Alternate route: `/v1/alliances/{alliance_id}/corporations/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_alliances_alliance_id_corporations
      summary: List alliance's corporations
      tags:
        - Alliance
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/alliances/{alliance_id}/icons/":
    get:
      description: |-
        Get the icon urls for a alliance

        ---
        Alternate route: `/dev/alliances/{alliance_id}/icons/`

        Alternate route: `/legacy/alliances/{alliance_id}/icons/`

        Alternate route: `/v1/alliances/{alliance_id}/icons/`

        ---
        This route expires daily at 11:05
      operationId: get_alliances_alliance_id_icons
      summary: Get alliance icon
      tags:
        - Alliance
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /characters/affiliation/:
    post:
      description: |-
        Bulk lookup of character IDs to corporation, alliance and faction

        ---
        Alternate route: `/dev/characters/affiliation/`

        Alternate route: `/legacy/characters/affiliation/`

        Alternate route: `/v1/characters/affiliation/`

        ---
        This route is cached for up to 3600 seconds
      operationId: post_characters_affiliation
      summary: Character affiliation
      tags:
        - Character
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/characters/{character_id}/":
    get:
      description: |-
        Public information about a character

        ---
        Alternate route: `/dev/characters/{character_id}/`

        Alternate route: `/v4/characters/{character_id}/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_characters_character_id
      summary: Get character's public information
      tags:
        - Character
      x-alternate-versions:
        - dev
        - v4
      x-cached-seconds: 3600
  "/characters/{character_id}/agents_research/":
    get:
      description: |-
        Return a list of agents research information for a character. The formula for finding the current research points with an agent is: currentPoints = remainderPoints + pointsPerDay * days(currentTime - researchStartDate)

        ---
        Alternate route: `/dev/characters/{character_id}/agents_research/`

        Alternate route: `/legacy/characters/{character_id}/agents_research/`

        Alternate route: `/v1/characters/{character_id}/agents_research/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_characters_character_id_agents_research
      security:
        - evesso:
            - esi-characters.read_agents_research.v1
      summary: Get agents research
      tags:
        - Character
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/characters/{character_id}/assets/":
    get:
      description: |-
        Return a list of the characters assets

        ---
        Alternate route: `/dev/characters/{character_id}/assets/`

        Alternate route: `/v3/characters/{character_id}/assets/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_characters_character_id_assets
      security:
        - evesso:
            - esi-assets.read_assets.v1
      summary: Get character assets
      tags:
        - Assets
      x-alternate-versions:
        - dev
        - v3
      x-cached-seconds: 3600
  "/characters/{character_id}/assets/locations/":
    post:
      description: |
        Return locations for a set of item ids, which you can get from character assets endpoint. Coordinates for items in hangars or stations are set to (0,0,0)

        ---
        Alternate route: `/dev/characters/{character_id}/assets/locations/`

        Alternate route: `/v2/characters/{character_id}/assets/locations/`
      operationId: post_characters_character_id_assets_locations
      security:
        - evesso:
            - esi-assets.read_assets.v1
      summary: Get character asset locations
      tags:
        - Assets
      x-alternate-versions:
        - dev
        - v2
  "/characters/{character_id}/assets/names/":
    post:
      description: |
        Return names for a set of item ids, which you can get from character assets endpoint. Typically used for items that can customize names, like containers or ships.

        ---
        Alternate route: `/dev/characters/{character_id}/assets/names/`

        Alternate route: `/legacy/characters/{character_id}/assets/names/`

        Alternate route: `/v1/characters/{character_id}/assets/names/`
      operationId: post_characters_character_id_assets_names
      security:
        - evesso:
            - esi-assets.read_assets.v1
      summary: Get character asset names
      tags:
        - Assets
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/characters/{character_id}/attributes/":
    get:
      description: |-
        Return attributes of a character

        ---
        Alternate route: `/dev/characters/{character_id}/attributes/`

        Alternate route: `/legacy/characters/{character_id}/attributes/`

        Alternate route: `/v1/characters/{character_id}/attributes/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_characters_character_id_attributes
      security:
        - evesso:
            - esi-skills.read_skills.v1
      summary: Get character attributes
      tags:
        - Skills
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/characters/{character_id}/blueprints/":
    get:
      description: |-
        Return a list of blueprints the character owns

        ---
        Alternate route: `/dev/characters/{character_id}/blueprints/`

        Alternate route: `/v2/characters/{character_id}/blueprints/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_characters_character_id_blueprints
      security:
        - evesso:
            - esi-characters.read_blueprints.v1
      summary: Get blueprints
      tags:
        - Character
      x-alternate-versions:
        - dev
        - v2
      x-cached-seconds: 3600
  "/characters/{character_id}/bookmarks/":
    get:
      description: |-
        A list of your character's personal bookmarks

        ---
        Alternate route: `/dev/characters/{character_id}/bookmarks/`

        Alternate route: `/v2/characters/{character_id}/bookmarks/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_characters_character_id_bookmarks
      security:
        - evesso:
            - esi-bookmarks.read_character_bookmarks.v1
      summary: List bookmarks
      tags:
        - Bookmarks
      x-alternate-versions:
        - dev
        - v2
      x-cached-seconds: 3600
  "/characters/{character_id}/bookmarks/folders/":
    get:
      description: |-
        A list of your character's personal bookmark folders

        ---
        Alternate route: `/dev/characters/{character_id}/bookmarks/folders/`

        Alternate route: `/v2/characters/{character_id}/bookmarks/folders/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_characters_character_id_bookmarks_folders
      security:
        - evesso:
            - esi-bookmarks.read_character_bookmarks.v1
      summary: List bookmark folders
      tags:
        - Bookmarks
      x-alternate-versions:
        - dev
        - v2
      x-cached-seconds: 3600
  "/characters/{character_id}/calendar/":
    get:
      description: |-
        Get 50 event summaries from the calendar. If no from_event ID is given, the resource will return the next 50 chronological event summaries from now. If a from_event ID is specified, it will return the next 50 chronological event summaries from after that event

        ---
        Alternate route: `/dev/characters/{character_id}/calendar/`

        Alternate route: `/legacy/characters/{character_id}/calendar/`

        Alternate route: `/v1/characters/{character_id}/calendar/`

        ---
        This route is cached for up to 5 seconds
      operationId: get_characters_character_id_calendar
      security:
        - evesso:
            - esi-calendar.read_calendar_events.v1
      summary: List calendar event summaries
      tags:
        - Calendar
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 5
  "/characters/{character_id}/calendar/{event_id}/":
    get:
      description: |-
        Get all the information for a specific event

        ---
        Alternate route: `/dev/characters/{character_id}/calendar/{event_id}/`

        Alternate route: `/v3/characters/{character_id}/calendar/{event_id}/`

        ---
        This route is cached for up to 5 seconds
      operationId: get_characters_character_id_calendar_event_id
      security:
        - evesso:
            - esi-calendar.read_calendar_events.v1
      summary: Get an event
      tags:
        - Calendar
      x-alternate-versions:
        - dev
        - v3
      x-cached-seconds: 5
    put:
      description: |
        Set your response status to an event

        ---
        Alternate route: `/dev/characters/{character_id}/calendar/{event_id}/`

        Alternate route: `/v3/characters/{character_id}/calendar/{event_id}/`
      operationId: put_characters_character_id_calendar_event_id
      security:
        - evesso:
            - esi-calendar.respond_calendar_events.v1
      summary: Respond to an event
      tags:
        - Calendar
      x-alternate-versions:
        - dev
        - v3
  "/characters/{character_id}/calendar/{event_id}/attendees/":
    get:
      description: |-
        Get all invited attendees for a given event

        ---
        Alternate route: `/dev/characters/{character_id}/calendar/{event_id}/attendees/`

        Alternate route: `/legacy/characters/{character_id}/calendar/{event_id}/attendees/`

        Alternate route: `/v1/characters/{character_id}/calendar/{event_id}/attendees/`

        ---
        This route is cached for up to 600 seconds
      operationId: get_characters_character_id_calendar_event_id_attendees
      security:
        - evesso:
            - esi-calendar.read_calendar_events.v1
      summary: Get attendees
      tags:
        - Calendar
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 600
  "/characters/{character_id}/clones/":
    get:
      description: |-
        A list of the character's clones

        ---
        Alternate route: `/dev/characters/{character_id}/clones/`

        Alternate route: `/v3/characters/{character_id}/clones/`

        ---
        This route is cached for up to 120 seconds
      operationId: get_characters_character_id_clones
      security:
        - evesso:
            - esi-clones.read_clones.v1
      summary: Get clones
      tags:
        - Clones
      x-alternate-versions:
        - dev
        - v3
      x-cached-seconds: 120
  "/characters/{character_id}/contacts/":
    delete:
      description: |
        Bulk delete contacts

        ---
        Alternate route: `/dev/characters/{character_id}/contacts/`

        Alternate route: `/v2/characters/{character_id}/contacts/`
      operationId: delete_characters_character_id_contacts
      security:
        - evesso:
            - esi-characters.write_contacts.v1
      summary: Delete contacts
      tags:
        - Contacts
      x-alternate-versions:
        - dev
        - v2
    get:
      description: |-
        Return contacts of a character

        ---
        Alternate route: `/dev/characters/{character_id}/contacts/`

        Alternate route: `/v2/characters/{character_id}/contacts/`

        ---
        This route is cached for up to 300 seconds
      operationId: get_characters_character_id_contacts
      security:
        - evesso:
            - esi-characters.read_contacts.v1
      summary: Get contacts
      tags:
        - Contacts
      x-alternate-versions:
        - dev
        - v2
      x-cached-seconds: 300
    post:
      description: |
        Bulk add contacts with same settings

        ---
        Alternate route: `/dev/characters/{character_id}/contacts/`

        Alternate route: `/v2/characters/{character_id}/contacts/`
      operationId: post_characters_character_id_contacts
      security:
        - evesso:
            - esi-characters.write_contacts.v1
      summary: Add contacts
      tags:
        - Contacts
      x-alternate-versions:
        - dev
        - v2
    put:
      description: |
        Bulk edit contacts with same settings

        ---
        Alternate route: `/dev/characters/{character_id}/contacts/`

        Alternate route: `/v2/characters/{character_id}/contacts/`
      operationId: put_characters_character_id_contacts
      security:
        - evesso:
            - esi-characters.write_contacts.v1
      summary: Edit contacts
      tags:
        - Contacts
      x-alternate-versions:
        - dev
        - v2
  "/characters/{character_id}/contacts/labels/":
    get:
      description: |-
        Return custom labels for a character's contacts

        ---
        Alternate route: `/dev/characters/{character_id}/contacts/labels/`

        Alternate route: `/legacy/characters/{character_id}/contacts/labels/`

        Alternate route: `/v1/characters/{character_id}/contacts/labels/`

        ---
        This route is cached for up to 300 seconds
      operationId: get_characters_character_id_contacts_labels
      security:
        - evesso:
            - esi-characters.read_contacts.v1
      summary: Get contact labels
      tags:
        - Contacts
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 300
  "/characters/{character_id}/contracts/":
    get:
      description: |-
        Returns contracts available to a character, only if the character is issuer, acceptor or assignee. Only returns contracts no older than 30 days, or if the status is "in_progress".

        ---
        Alternate route: `/dev/characters/{character_id}/contracts/`

        Alternate route: `/legacy/characters/{character_id}/contracts/`

        Alternate route: `/v1/characters/{character_id}/contracts/`

        ---
        This route is cached for up to 300 seconds
      operationId: get_characters_character_id_contracts
      security:
        - evesso:
            - esi-contracts.read_character_contracts.v1
      summary: Get contracts
      tags:
        - Contracts
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 300
  "/characters/{character_id}/contracts/{contract_id}/bids/":
    get:
      description: |-
        Lists bids on a particular auction contract

        ---
        Alternate route: `/dev/characters/{character_id}/contracts/{contract_id}/bids/`

        Alternate route: `/legacy/characters/{character_id}/contracts/{contract_id}/bids/`

        Alternate route: `/v1/characters/{character_id}/contracts/{contract_id}/bids/`

        ---
        This route is cached for up to 300 seconds
      operationId: get_characters_character_id_contracts_contract_id_bids
      security:
        - evesso:
            - esi-contracts.read_character_contracts.v1
      summary: Get contract bids
      tags:
        - Contracts
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 300
  "/characters/{character_id}/contracts/{contract_id}/items/":
    get:
      description: |-
        Lists items of a particular contract

        ---
        Alternate route: `/dev/characters/{character_id}/contracts/{contract_id}/items/`

        Alternate route: `/legacy/characters/{character_id}/contracts/{contract_id}/items/`

        Alternate route: `/v1/characters/{character_id}/contracts/{contract_id}/items/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_characters_character_id_contracts_contract_id_items
      security:
        - evesso:
            - esi-contracts.read_character_contracts.v1
      summary: Get contract items
      tags:
        - Contracts
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/characters/{character_id}/corporationhistory/":
    get:
      description: |-
        Get a list of all the corporations a character has been a member of

        ---
        Alternate route: `/dev/characters/{character_id}/corporationhistory/`

        Alternate route: `/legacy/characters/{character_id}/corporationhistory/`

        Alternate route: `/v1/characters/{character_id}/corporationhistory/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_characters_character_id_corporationhistory
      summary: Get corporation history
      tags:
        - Character
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/characters/{character_id}/cspa/":
    post:
      description: |
        Takes a source character ID in the url and a set of target character ID's in the body, returns a CSPA charge cost

        ---
        Alternate route: `/dev/characters/{character_id}/cspa/`

        Alternate route: `/v4/characters/{character_id}/cspa/`
      operationId: post_characters_character_id_cspa
      security:
        - evesso:
            - esi-characters.read_contacts.v1
      summary: Calculate a CSPA charge cost
      tags:
        - Character
      x-alternate-versions:
        - dev
        - v4
  "/characters/{character_id}/fatigue/":
    get:
      description: |-
        Return a character's jump activation and fatigue information

        ---
        Alternate route: `/dev/characters/{character_id}/fatigue/`

        Alternate route: `/legacy/characters/{character_id}/fatigue/`

        Alternate route: `/v1/characters/{character_id}/fatigue/`

        ---
        This route is cached for up to 300 seconds
      operationId: get_characters_character_id_fatigue
      security:
        - evesso:
            - esi-characters.read_fatigue.v1
      summary: Get jump fatigue
      tags:
        - Character
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 300
  "/characters/{character_id}/fittings/":
    get:
      description: |-
        Return fittings of a character

        ---
        Alternate route: `/dev/characters/{character_id}/fittings/`

        Alternate route: `/legacy/characters/{character_id}/fittings/`

        Alternate route: `/v1/characters/{character_id}/fittings/`

        ---
        This route is cached for up to 300 seconds
      operationId: get_characters_character_id_fittings
      security:
        - evesso:
            - esi-fittings.read_fittings.v1
      summary: Get fittings
      tags:
        - Fittings
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 300
    post:
      description: |
        Save a new fitting for a character

        ---
        Alternate route: `/dev/characters/{character_id}/fittings/`

        Alternate route: `/legacy/characters/{character_id}/fittings/`

        Alternate route: `/v1/characters/{character_id}/fittings/`
      operationId: post_characters_character_id_fittings
      security:
        - evesso:
            - esi-fittings.write_fittings.v1
      summary: Create fitting
      tags:
        - Fittings
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/characters/{character_id}/fittings/{fitting_id}/":
    delete:
      description: |
        Delete a fitting from a character

        ---
        Alternate route: `/dev/characters/{character_id}/fittings/{fitting_id}/`

        Alternate route: `/legacy/characters/{character_id}/fittings/{fitting_id}/`

        Alternate route: `/v1/characters/{character_id}/fittings/{fitting_id}/`
      operationId: delete_characters_character_id_fittings_fitting_id
      security:
        - evesso:
            - esi-fittings.write_fittings.v1
      summary: Delete fitting
      tags:
        - Fittings
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/characters/{character_id}/fleet/":
    get:
      description: |-
        Return the fleet ID the character is in, if any.

        ---
        Alternate route: `/dev/characters/{character_id}/fleet/`

        Alternate route: `/legacy/characters/{character_id}/fleet/`

        Alternate route: `/v1/characters/{character_id}/fleet/`

        ---
        This route is cached for up to 60 seconds
      operationId: get_characters_character_id_fleet
      security:
        - evesso:
            - esi-fleets.read_fleet.v1
      summary: Get character fleet info
      tags:
        - Fleets
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 60
  "/characters/{character_id}/fw/stats/":
    get:
      description: |-
        Statistical overview of a character involved in faction warfare

        ---
        Alternate route: `/dev/characters/{character_id}/fw/stats/`

        Alternate route: `/legacy/characters/{character_id}/fw/stats/`

        Alternate route: `/v1/characters/{character_id}/fw/stats/`

        ---
        This route expires daily at 11:05
      operationId: get_characters_character_id_fw_stats
      security:
        - evesso:
            - esi-characters.read_fw_stats.v1
      summary: Overview of a character involved in faction warfare
      tags:
        - Faction Warfare
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/characters/{character_id}/implants/":
    get:
      description: |-
        Return implants on the active clone of a character

        ---
        Alternate route: `/dev/characters/{character_id}/implants/`

        Alternate route: `/legacy/characters/{character_id}/implants/`

        Alternate route: `/v1/characters/{character_id}/implants/`

        ---
        This route is cached for up to 300 seconds
      operationId: get_characters_character_id_implants
      security:
        - evesso:
            - esi-clones.read_implants.v1
      summary: Get active implants
      tags:
        - Clones
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 300
  "/characters/{character_id}/industry/jobs/":
    get:
      description: |-
        List industry jobs placed by a character

        ---
        Alternate route: `/dev/characters/{character_id}/industry/jobs/`

        Alternate route: `/legacy/characters/{character_id}/industry/jobs/`

        Alternate route: `/v1/characters/{character_id}/industry/jobs/`

        ---
        This route is cached for up to 300 seconds
      operationId: get_characters_character_id_industry_jobs
      security:
        - evesso:
            - esi-industry.read_character_jobs.v1
      summary: List character industry jobs
      tags:
        - Industry
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 300
  "/characters/{character_id}/killmails/recent/":
    get:
      description: |-
        Return a list of a character's kills and losses going back 90 days

        ---
        Alternate route: `/dev/characters/{character_id}/killmails/recent/`

        Alternate route: `/legacy/characters/{character_id}/killmails/recent/`

        Alternate route: `/v1/characters/{character_id}/killmails/recent/`

        ---
        This route is cached for up to 300 seconds
      operationId: get_characters_character_id_killmails_recent
      security:
        - evesso:
            - esi-killmails.read_killmails.v1
      summary: Get a character's recent kills and losses
      tags:
        - Killmails
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 300
  "/characters/{character_id}/location/":
    get:
      description: |-
        Information about the characters current location. Returns the current solar system id, and also the current station or structure ID if applicable

        ---
        Alternate route: `/dev/characters/{character_id}/location/`

        Alternate route: `/legacy/characters/{character_id}/location/`

        Alternate route: `/v1/characters/{character_id}/location/`

        ---
        This route is cached for up to 5 seconds
      operationId: get_characters_character_id_location
      security:
        - evesso:
            - esi-location.read_location.v1
      summary: Get character location
      tags:
        - Location
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 5
  "/characters/{character_id}/loyalty/points/":
    get:
      description: |-
        Return a list of loyalty points for all corporations the character has worked for

        ---
        Alternate route: `/dev/characters/{character_id}/loyalty/points/`

        Alternate route: `/legacy/characters/{character_id}/loyalty/points/`

        Alternate route: `/v1/characters/{character_id}/loyalty/points/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_characters_character_id_loyalty_points
      security:
        - evesso:
            - esi-characters.read_loyalty.v1
      summary: Get loyalty points
      tags:
        - Loyalty
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/characters/{character_id}/mail/":
    get:
      description: |-
        Return the 50 most recent mail headers belonging to the character that match the query criteria. Queries can be filtered by label, and last_mail_id can be used to paginate backwards

        ---
        Alternate route: `/dev/characters/{character_id}/mail/`

        Alternate route: `/legacy/characters/{character_id}/mail/`

        Alternate route: `/v1/characters/{character_id}/mail/`

        ---
        This route is cached for up to 30 seconds
      operationId: get_characters_character_id_mail
      security:
        - evesso:
            - esi-mail.read_mail.v1
      summary: Return mail headers
      tags:
        - Mail
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 30
    post:
      description: |
        Create and send a new mail

        ---
        Alternate route: `/dev/characters/{character_id}/mail/`

        Alternate route: `/legacy/characters/{character_id}/mail/`

        Alternate route: `/v1/characters/{character_id}/mail/`
      operationId: post_characters_character_id_mail
      security:
        - evesso:
            - esi-mail.send_mail.v1
      summary: Send a new mail
      tags:
        - Mail
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/characters/{character_id}/mail/labels/":
    get:
      description: |-
        Return a list of the users mail labels, unread counts for each label and a total unread count.

        ---
        Alternate route: `/dev/characters/{character_id}/mail/labels/`

        Alternate route: `/v3/characters/{character_id}/mail/labels/`

        ---
        This route is cached for up to 30 seconds
      operationId: get_characters_character_id_mail_labels
      security:
        - evesso:
            - esi-mail.read_mail.v1
      summary: Get mail labels and unread counts
      tags:
        - Mail
      x-alternate-versions:
        - dev
        - v3
      x-cached-seconds: 30
    post:
      description: |
        Create a mail label

        ---
        Alternate route: `/dev/characters/{character_id}/mail/labels/`

        Alternate route: `/legacy/characters/{character_id}/mail/labels/`

        Alternate route: `/v2/characters/{character_id}/mail/labels/`
      operationId: post_characters_character_id_mail_labels
      security:
        - evesso:
            - esi-mail.organize_mail.v1
      summary: Create a mail label
      tags:
        - Mail
      x-alternate-versions:
        - dev
        - legacy
        - v2
  "/characters/{character_id}/mail/labels/{label_id}/":
    delete:
      description: |
        Delete a mail label

        ---
        Alternate route: `/dev/characters/{character_id}/mail/labels/{label_id}/`

        Alternate route: `/legacy/characters/{character_id}/mail/labels/{label_id}/`

        Alternate route: `/v1/characters/{character_id}/mail/labels/{label_id}/`
      operationId: delete_characters_character_id_mail_labels_label_id
      security:
        - evesso:
            - esi-mail.organize_mail.v1
      summary: Delete a mail label
      tags:
        - Mail
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/characters/{character_id}/mail/lists/":
    get:
      description: |-
        Return all mailing lists that the character is subscribed to

        ---
        Alternate route: `/dev/characters/{character_id}/mail/lists/`

        Alternate route: `/legacy/characters/{character_id}/mail/lists/`

        Alternate route: `/v1/characters/{character_id}/mail/lists/`

        ---
        This route is cached for up to 120 seconds
      operationId: get_characters_character_id_mail_lists
      security:
        - evesso:
            - esi-mail.read_mail.v1
      summary: Return mailing list subscriptions
      tags:
        - Mail
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 120
  "/characters/{character_id}/mail/{mail_id}/":
    delete:
      description: |
        Delete a mail

        ---
        Alternate route: `/dev/characters/{character_id}/mail/{mail_id}/`

        Alternate route: `/legacy/characters/{character_id}/mail/{mail_id}/`

        Alternate route: `/v1/characters/{character_id}/mail/{mail_id}/`
      operationId: delete_characters_character_id_mail_mail_id
      security:
        - evesso:
            - esi-mail.organize_mail.v1
      summary: Delete a mail
      tags:
        - Mail
      x-alternate-versions:
        - dev
        - legacy
        - v1
    get:
      description: |-
        Return the contents of an EVE mail

        ---
        Alternate route: `/dev/characters/{character_id}/mail/{mail_id}/`

        Alternate route: `/legacy/characters/{character_id}/mail/{mail_id}/`

        Alternate route: `/v1/characters/{character_id}/mail/{mail_id}/`

        ---
        This route is cached for up to 30 seconds
      operationId: get_characters_character_id_mail_mail_id
      security:
        - evesso:
            - esi-mail.read_mail.v1
      summary: Return a mail
      tags:
        - Mail
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 30
    put:
      description: |
        Update metadata about a mail

        ---
        Alternate route: `/dev/characters/{character_id}/mail/{mail_id}/`

        Alternate route: `/legacy/characters/{character_id}/mail/{mail_id}/`

        Alternate route: `/v1/characters/{character_id}/mail/{mail_id}/`
      operationId: put_characters_character_id_mail_mail_id
      security:
        - evesso:
            - esi-mail.organize_mail.v1
      summary: Update metadata about a mail
      tags:
        - Mail
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/characters/{character_id}/medals/":
    get:
      description: |-
        Return a list of medals the character has

        ---
        Alternate route: `/dev/characters/{character_id}/medals/`

        Alternate route: `/legacy/characters/{character_id}/medals/`

        Alternate route: `/v1/characters/{character_id}/medals/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_characters_character_id_medals
      security:
        - evesso:
            - esi-characters.read_medals.v1
      summary: Get medals
      tags:
        - Character
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/characters/{character_id}/mining/":
    get:
      description: |-
        Paginated record of all mining done by a character for the past 30 days


        ---
        Alternate route: `/dev/characters/{character_id}/mining/`

        Alternate route: `/legacy/characters/{character_id}/mining/`

        Alternate route: `/v1/characters/{character_id}/mining/`

        ---
        This route is cached for up to 600 seconds
      operationId: get_characters_character_id_mining
      security:
        - evesso:
            - esi-industry.read_character_mining.v1
      summary: Character mining ledger
      tags:
        - Industry
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 600
  "/characters/{character_id}/notifications/":
    get:
      description: |-
        Return character notifications

        ---
        Alternate route: `/dev/characters/{character_id}/notifications/`

        Alternate route: `/v4/characters/{character_id}/notifications/`

        ---
        This route is cached for up to 600 seconds
      operationId: get_characters_character_id_notifications
      security:
        - evesso:
            - esi-characters.read_notifications.v1
      summary: Get character notifications
      tags:
        - Character
      x-alternate-versions:
        - dev
        - v4
      x-cached-seconds: 600
  "/characters/{character_id}/notifications/contacts/":
    get:
      description: |-
        Return notifications about having been added to someone's contact list

        ---
        Alternate route: `/dev/characters/{character_id}/notifications/contacts/`

        Alternate route: `/legacy/characters/{character_id}/notifications/contacts/`

        Alternate route: `/v1/characters/{character_id}/notifications/contacts/`

        ---
        This route is cached for up to 600 seconds
      operationId: get_characters_character_id_notifications_contacts
      security:
        - evesso:
            - esi-characters.read_notifications.v1
      summary: Get new contact notifications
      tags:
        - Character
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 600
  "/characters/{character_id}/online/":
    get:
      description: |-
        Checks if the character is currently online

        ---
        Alternate route: `/dev/characters/{character_id}/online/`

        Alternate route: `/v2/characters/{character_id}/online/`

        ---
        This route is cached for up to 60 seconds
      operationId: get_characters_character_id_online
      security:
        - evesso:
            - esi-location.read_online.v1
      summary: Get character online
      tags:
        - Location
      x-alternate-versions:
        - dev
        - v2
      x-cached-seconds: 60
  "/characters/{character_id}/opportunities/":
    get:
      description: |-
        Return a list of tasks finished by a character

        ---
        Alternate route: `/dev/characters/{character_id}/opportunities/`

        Alternate route: `/legacy/characters/{character_id}/opportunities/`

        Alternate route: `/v1/characters/{character_id}/opportunities/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_characters_character_id_opportunities
      security:
        - evesso:
            - esi-characters.read_opportunities.v1
      summary: Get a character's completed tasks
      tags:
        - Opportunities
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/characters/{character_id}/orders/":
    get:
      description: |-
        List open market orders placed by a character

        ---
        Alternate route: `/dev/characters/{character_id}/orders/`

        Alternate route: `/v2/characters/{character_id}/orders/`

        ---
        This route is cached for up to 1200 seconds
      operationId: get_characters_character_id_orders
      security:
        - evesso:
            - esi-markets.read_character_orders.v1
      summary: List open orders from a character
      tags:
        - Market
      x-alternate-versions:
        - dev
        - v2
      x-cached-seconds: 1200
  "/characters/{character_id}/orders/history/":
    get:
      description: |-
        List cancelled and expired market orders placed by a character up to 90 days in the past.

        ---
        Alternate route: `/dev/characters/{character_id}/orders/history/`

        Alternate route: `/legacy/characters/{character_id}/orders/history/`

        Alternate route: `/v1/characters/{character_id}/orders/history/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_characters_character_id_orders_history
      security:
        - evesso:
            - esi-markets.read_character_orders.v1
      summary: List historical orders by a character
      tags:
        - Market
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/characters/{character_id}/planets/":
    get:
      description: |-
        Returns a list of all planetary colonies owned by a character.

        ---
        Alternate route: `/dev/characters/{character_id}/planets/`

        Alternate route: `/legacy/characters/{character_id}/planets/`

        Alternate route: `/v1/characters/{character_id}/planets/`

        ---
        This route is cached for up to 600 seconds
      operationId: get_characters_character_id_planets
      security:
        - evesso:
            - esi-planets.manage_planets.v1
      summary: Get colonies
      tags:
        - Planetary Interaction
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 600
  "/characters/{character_id}/planets/{planet_id}/":
    get:
      description: |-
        Returns full details on the layout of a single planetary colony, including links, pins and routes. Note: Planetary information is only recalculated when the colony is viewed through the client. Information will not update until this criteria is met.

        ---
        Alternate route: `/dev/characters/{character_id}/planets/{planet_id}/`

        Alternate route: `/v3/characters/{character_id}/planets/{planet_id}/`

        ---
        This route is cached for up to 600 seconds
      operationId: get_characters_character_id_planets_planet_id
      security:
        - evesso:
            - esi-planets.manage_planets.v1
      summary: Get colony layout
      tags:
        - Planetary Interaction
      x-alternate-versions:
        - dev
        - v3
      x-cached-seconds: 600
  "/characters/{character_id}/portrait/":
    get:
      description: |-
        Get portrait urls for a character

        ---
        Alternate route: `/dev/characters/{character_id}/portrait/`

        Alternate route: `/v2/characters/{character_id}/portrait/`

        ---
        This route expires daily at 11:05
      operationId: get_characters_character_id_portrait
      summary: Get character portraits
      tags:
        - Character
      x-alternate-versions:
        - dev
        - v2
  "/characters/{character_id}/roles/":
    get:
      description: |-
        Returns a character's corporation roles

        ---
        Alternate route: `/dev/characters/{character_id}/roles/`

        Alternate route: `/v2/characters/{character_id}/roles/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_characters_character_id_roles
      security:
        - evesso:
            - esi-characters.read_corporation_roles.v1
      summary: Get character corporation roles
      tags:
        - Character
      x-alternate-versions:
        - dev
        - v2
      x-cached-seconds: 3600
  "/characters/{character_id}/search/":
    get:
      description: |-
        Search for entities that match a given sub-string.

        ---
        Alternate route: `/dev/characters/{character_id}/search/`

        Alternate route: `/v3/characters/{character_id}/search/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_characters_character_id_search
      security:
        - evesso:
            - esi-search.search_structures.v1
      summary: Search on a string
      tags:
        - Search
      x-alternate-versions:
        - dev
        - v3
      x-cached-seconds: 3600
  "/characters/{character_id}/ship/":
    get:
      description: |-
        Get the current ship type, name and id

        ---
        Alternate route: `/dev/characters/{character_id}/ship/`

        Alternate route: `/legacy/characters/{character_id}/ship/`

        Alternate route: `/v1/characters/{character_id}/ship/`

        ---
        This route is cached for up to 5 seconds
      operationId: get_characters_character_id_ship
      security:
        - evesso:
            - esi-location.read_ship_type.v1
      summary: Get current ship
      tags:
        - Location
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 5
  "/characters/{character_id}/skillqueue/":
    get:
      description: |-
        List the configured skill queue for the given character

        ---
        Alternate route: `/dev/characters/{character_id}/skillqueue/`

        Alternate route: `/legacy/characters/{character_id}/skillqueue/`

        Alternate route: `/v2/characters/{character_id}/skillqueue/`

        ---
        This route is cached for up to 120 seconds
      operationId: get_characters_character_id_skillqueue
      security:
        - evesso:
            - esi-skills.read_skillqueue.v1
      summary: Get character's skill queue
      tags:
        - Skills
      x-alternate-versions:
        - dev
        - legacy
        - v2
      x-cached-seconds: 120
  "/characters/{character_id}/skills/":
    get:
      description: |-
        List all trained skills for the given character

        ---
        Alternate route: `/dev/characters/{character_id}/skills/`

        Alternate route: `/v4/characters/{character_id}/skills/`

        ---
        This route is cached for up to 120 seconds
      operationId: get_characters_character_id_skills
      security:
        - evesso:
            - esi-skills.read_skills.v1
      summary: Get character skills
      tags:
        - Skills
      x-alternate-versions:
        - dev
        - v4
      x-cached-seconds: 120
  "/characters/{character_id}/standings/":
    get:
      description: |-
        Return character standings from agents, NPC corporations, and factions

        ---
        Alternate route: `/dev/characters/{character_id}/standings/`

        Alternate route: `/legacy/characters/{character_id}/standings/`

        Alternate route: `/v1/characters/{character_id}/standings/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_characters_character_id_standings
      security:
        - evesso:
            - esi-characters.read_standings.v1
      summary: Get standings
      tags:
        - Character
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/characters/{character_id}/stats/":
    get:
      description: |-
        Returns aggregate yearly stats for a character

        ---
        Alternate route: `/dev/characters/{character_id}/stats/`

        Alternate route: `/v2/characters/{character_id}/stats/`

        ---
        This route is cached for up to 86400 seconds
      operationId: get_characters_character_id_stats
      security:
        - evesso:
            - esi-characterstats.read.v1
      summary: Yearly aggregate stats
      tags:
        - Character
      x-alternate-versions:
        - dev
        - v2
      x-cached-seconds: 86400
  "/characters/{character_id}/titles/":
    get:
      description: |-
        Returns a character's titles

        ---
        Alternate route: `/dev/characters/{character_id}/titles/`

        Alternate route: `/legacy/characters/{character_id}/titles/`

        Alternate route: `/v1/characters/{character_id}/titles/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_characters_character_id_titles
      security:
        - evesso:
            - esi-characters.read_titles.v1
      summary: Get character corporation titles
      tags:
        - Character
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/characters/{character_id}/wallet/":
    get:
      description: |-
        Returns a character's wallet balance

        ---
        Alternate route: `/dev/characters/{character_id}/wallet/`

        Alternate route: `/legacy/characters/{character_id}/wallet/`

        Alternate route: `/v1/characters/{character_id}/wallet/`

        ---
        This route is cached for up to 120 seconds
      operationId: get_characters_character_id_wallet
      security:
        - evesso:
            - esi-wallet.read_character_wallet.v1
      summary: Get a character's wallet balance
      tags:
        - Wallet
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 120
  "/characters/{character_id}/wallet/journal/":
    get:
      description: |-
        Retrieve the given character's wallet journal going 30 days back

        ---
        Alternate route: `/legacy/characters/{character_id}/wallet/journal/`

        Alternate route: `/v4/characters/{character_id}/wallet/journal/`

        ---
        This route is cached for up to 3600 seconds

        ---
        Warning: This route has an upgrade available

        ---
        [Diff of the upcoming changes](https://esi.evetech.net/diff/latest/dev/#GET-/characters/{character_id}/wallet/journal/)
      operationId: get_characters_character_id_wallet_journal
      security:
        - evesso:
            - esi-wallet.read_character_wallet.v1
      summary: Get character wallet journal
      tags:
        - Wallet
      x-alternate-versions:
        - legacy
        - v4
      x-cached-seconds: 3600
  "/characters/{character_id}/wallet/transactions/":
    get:
      description: |-
        Get wallet transactions of a character

        ---
        Alternate route: `/dev/characters/{character_id}/wallet/transactions/`

        Alternate route: `/legacy/characters/{character_id}/wallet/transactions/`

        Alternate route: `/v1/characters/{character_id}/wallet/transactions/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_characters_character_id_wallet_transactions
      security:
        - evesso:
            - esi-wallet.read_character_wallet.v1
      summary: Get wallet transactions
      tags:
        - Wallet
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/contracts/public/bids/{contract_id}/":
    get:
      description: |-
        Lists bids on a public auction contract

        ---
        Alternate route: `/dev/contracts/public/bids/{contract_id}/`

        Alternate route: `/legacy/contracts/public/bids/{contract_id}/`

        Alternate route: `/v1/contracts/public/bids/{contract_id}/`

        ---
        This route is cached for up to 300 seconds
      operationId: get_contracts_public_bids_contract_id
      summary: Get public contract bids
      tags:
        - Contracts
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 300
  "/contracts/public/items/{contract_id}/":
    get:
      description: |-
        Lists items of a public contract

        ---
        Alternate route: `/dev/contracts/public/items/{contract_id}/`

        Alternate route: `/legacy/contracts/public/items/{contract_id}/`

        Alternate route: `/v1/contracts/public/items/{contract_id}/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_contracts_public_items_contract_id
      summary: Get public contract items
      tags:
        - Contracts
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/contracts/public/{region_id}/":
    get:
      description: |-
        Returns a paginated list of all public contracts in the given region

        ---
        Alternate route: `/dev/contracts/public/{region_id}/`

        Alternate route: `/legacy/contracts/public/{region_id}/`

        Alternate route: `/v1/contracts/public/{region_id}/`

        ---
        This route is cached for up to 1800 seconds
      operationId: get_contracts_public_region_id
      summary: Get public contracts
      tags:
        - Contracts
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 1800
  "/corporation/{corporation_id}/mining/extractions/":
    get:
      description: |
        Extraction timers for all moon chunks being extracted by refineries belonging to a corporation.


        ---
        Alternate route: `/dev/corporation/{corporation_id}/mining/extractions/`

        Alternate route: `/legacy/corporation/{corporation_id}/mining/extractions/`

        Alternate route: `/v1/corporation/{corporation_id}/mining/extractions/`

        ---
        This route is cached for up to 1800 seconds

        ---
        Requires one of the following EVE corporation role(s): Station_Manager
      operationId: get_corporation_corporation_id_mining_extractions
      security:
        - evesso:
            - esi-industry.read_corporation_mining.v1
      summary: Moon extraction timers
      tags:
        - Industry
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 1800
      x-required-roles:
        - Station_Manager
  "/corporation/{corporation_id}/mining/observers/":
    get:
      description: |
        Paginated list of all entities capable of observing and recording mining for a corporation


        ---
        Alternate route: `/dev/corporation/{corporation_id}/mining/observers/`

        Alternate route: `/legacy/corporation/{corporation_id}/mining/observers/`

        Alternate route: `/v1/corporation/{corporation_id}/mining/observers/`

        ---
        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Accountant
      operationId: get_corporation_corporation_id_mining_observers
      security:
        - evesso:
            - esi-industry.read_corporation_mining.v1
      summary: Corporation mining observers
      tags:
        - Industry
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
      x-required-roles:
        - Accountant
  "/corporation/{corporation_id}/mining/observers/{observer_id}/":
    get:
      description: |
        Paginated record of all mining seen by an observer


        ---
        Alternate route: `/dev/corporation/{corporation_id}/mining/observers/{observer_id}/`

        Alternate route: `/legacy/corporation/{corporation_id}/mining/observers/{observer_id}/`

        Alternate route: `/v1/corporation/{corporation_id}/mining/observers/{observer_id}/`

        ---
        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Accountant
      operationId: get_corporation_corporation_id_mining_observers_observer_id
      security:
        - evesso:
            - esi-industry.read_corporation_mining.v1
      summary: Observed corporation mining
      tags:
        - Industry
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
      x-required-roles:
        - Accountant
  /corporations/npccorps/:
    get:
      description: |-
        Get a list of npc corporations

        ---
        Alternate route: `/dev/corporations/npccorps/`

        Alternate route: `/legacy/corporations/npccorps/`

        Alternate route: `/v1/corporations/npccorps/`

        ---
        This route expires daily at 11:05
      operationId: get_corporations_npccorps
      summary: Get npc corporations
      tags:
        - Corporation
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/corporations/{corporation_id}/":
    get:
      description: |-
        Public information about a corporation

        ---
        Alternate route: `/dev/corporations/{corporation_id}/`

        Alternate route: `/v4/corporations/{corporation_id}/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_corporations_corporation_id
      summary: Get corporation information
      tags:
        - Corporation
      x-alternate-versions:
        - dev
        - v4
      x-cached-seconds: 3600
  "/corporations/{corporation_id}/alliancehistory/":
    get:
      description: |-
        Get a list of all the alliances a corporation has been a member of

        ---
        Alternate route: `/dev/corporations/{corporation_id}/alliancehistory/`

        Alternate route: `/v2/corporations/{corporation_id}/alliancehistory/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_corporations_corporation_id_alliancehistory
      summary: Get alliance history
      tags:
        - Corporation
      x-alternate-versions:
        - dev
        - v2
      x-cached-seconds: 3600
  "/corporations/{corporation_id}/assets/":
    get:
      description: |
        Return a list of the corporation assets

        ---
        Alternate route: `/dev/corporations/{corporation_id}/assets/`

        Alternate route: `/v3/corporations/{corporation_id}/assets/`

        ---
        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director
      operationId: get_corporations_corporation_id_assets
      security:
        - evesso:
            - esi-assets.read_corporation_assets.v1
      summary: Get corporation assets
      tags:
        - Assets
      x-alternate-versions:
        - dev
        - v3
      x-cached-seconds: 3600
      x-required-roles:
        - Director
  "/corporations/{corporation_id}/assets/locations/":
    post:
      description: |
        Return locations for a set of item ids, which you can get from corporation assets endpoint. Coordinates for items in hangars or stations are set to (0,0,0)

        ---
        Alternate route: `/dev/corporations/{corporation_id}/assets/locations/`

        Alternate route: `/v2/corporations/{corporation_id}/assets/locations/`


        ---
        Requires one of the following EVE corporation role(s): Director
      operationId: post_corporations_corporation_id_assets_locations
      security:
        - evesso:
            - esi-assets.read_corporation_assets.v1
      summary: Get corporation asset locations
      tags:
        - Assets
      x-alternate-versions:
        - dev
        - v2
      x-required-roles:
        - Director
  "/corporations/{corporation_id}/assets/names/":
    post:
      description: |
        Return names for a set of item ids, which you can get from corporation assets endpoint. Only valid for items that can customize names, like containers or ships

        ---
        Alternate route: `/dev/corporations/{corporation_id}/assets/names/`

        Alternate route: `/legacy/corporations/{corporation_id}/assets/names/`

        Alternate route: `/v1/corporations/{corporation_id}/assets/names/`


        ---
        Requires one of the following EVE corporation role(s): Director
      operationId: post_corporations_corporation_id_assets_names
      security:
        - evesso:
            - esi-assets.read_corporation_assets.v1
      summary: Get corporation asset names
      tags:
        - Assets
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-required-roles:
        - Director
  "/corporations/{corporation_id}/blueprints/":
    get:
      description: |
        Returns a list of blueprints the corporation owns

        ---
        Alternate route: `/dev/corporations/{corporation_id}/blueprints/`

        Alternate route: `/v2/corporations/{corporation_id}/blueprints/`

        ---
        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director
      operationId: get_corporations_corporation_id_blueprints
      security:
        - evesso:
            - esi-corporations.read_blueprints.v1
      summary: Get corporation blueprints
      tags:
        - Corporation
      x-alternate-versions:
        - dev
        - v2
      x-cached-seconds: 3600
      x-required-roles:
        - Director
  "/corporations/{corporation_id}/bookmarks/":
    get:
      description: |-
        A list of your corporation's bookmarks

        ---
        Alternate route: `/dev/corporations/{corporation_id}/bookmarks/`

        Alternate route: `/legacy/corporations/{corporation_id}/bookmarks/`

        Alternate route: `/v1/corporations/{corporation_id}/bookmarks/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_corporations_corporation_id_bookmarks
      security:
        - evesso:
            - esi-bookmarks.read_corporation_bookmarks.v1
      summary: List corporation bookmarks
      tags:
        - Bookmarks
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/corporations/{corporation_id}/bookmarks/folders/":
    get:
      description: |-
        A list of your corporation's bookmark folders

        ---
        Alternate route: `/dev/corporations/{corporation_id}/bookmarks/folders/`

        Alternate route: `/legacy/corporations/{corporation_id}/bookmarks/folders/`

        Alternate route: `/v1/corporations/{corporation_id}/bookmarks/folders/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_corporations_corporation_id_bookmarks_folders
      security:
        - evesso:
            - esi-bookmarks.read_corporation_bookmarks.v1
      summary: List corporation bookmark folders
      tags:
        - Bookmarks
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/corporations/{corporation_id}/contacts/":
    get:
      description: |-
        Return contacts of a corporation

        ---
        Alternate route: `/dev/corporations/{corporation_id}/contacts/`

        Alternate route: `/v2/corporations/{corporation_id}/contacts/`

        ---
        This route is cached for up to 300 seconds
      operationId: get_corporations_corporation_id_contacts
      security:
        - evesso:
            - esi-corporations.read_contacts.v1
      summary: Get corporation contacts
      tags:
        - Contacts
      x-alternate-versions:
        - dev
        - v2
      x-cached-seconds: 300
      x-required-roles: []
  "/corporations/{corporation_id}/contacts/labels/":
    get:
      description: |-
        Return custom labels for a corporation's contacts

        ---
        Alternate route: `/dev/corporations/{corporation_id}/contacts/labels/`

        Alternate route: `/legacy/corporations/{corporation_id}/contacts/labels/`

        Alternate route: `/v1/corporations/{corporation_id}/contacts/labels/`

        ---
        This route is cached for up to 300 seconds
      operationId: get_corporations_corporation_id_contacts_labels
      security:
        - evesso:
            - esi-corporations.read_contacts.v1
      summary: Get corporation contact labels
      tags:
        - Contacts
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 300
      x-required-roles: []
  "/corporations/{corporation_id}/containers/logs/":
    get:
      description: |
        Returns logs recorded in the past seven days from all audit log secure containers (ALSC) owned by a given corporation

        ---
        Alternate route: `/dev/corporations/{corporation_id}/containers/logs/`

        Alternate route: `/v2/corporations/{corporation_id}/containers/logs/`

        ---
        This route is cached for up to 600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director
      operationId: get_corporations_corporation_id_containers_logs
      security:
        - evesso:
            - esi-corporations.read_container_logs.v1
      summary: Get all corporation ALSC logs
      tags:
        - Corporation
      x-alternate-versions:
        - dev
        - v2
      x-cached-seconds: 600
      x-required-roles:
        - Director
  "/corporations/{corporation_id}/contracts/":
    get:
      description: |-
        Returns contracts available to a corporation, only if the corporation is issuer, acceptor or assignee. Only returns contracts no older than 30 days, or if the status is "in_progress".

        ---
        Alternate route: `/dev/corporations/{corporation_id}/contracts/`

        Alternate route: `/legacy/corporations/{corporation_id}/contracts/`

        Alternate route: `/v1/corporations/{corporation_id}/contracts/`

        ---
        This route is cached for up to 300 seconds
      operationId: get_corporations_corporation_id_contracts
      security:
        - evesso:
            - esi-contracts.read_corporation_contracts.v1
      summary: Get corporation contracts
      tags:
        - Contracts
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 300
      x-required-roles: []
  "/corporations/{corporation_id}/contracts/{contract_id}/bids/":
    get:
      description: |-
        Lists bids on a particular auction contract

        ---
        Alternate route: `/dev/corporations/{corporation_id}/contracts/{contract_id}/bids/`

        Alternate route: `/legacy/corporations/{corporation_id}/contracts/{contract_id}/bids/`

        Alternate route: `/v1/corporations/{corporation_id}/contracts/{contract_id}/bids/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_corporations_corporation_id_contracts_contract_id_bids
      security:
        - evesso:
            - esi-contracts.read_corporation_contracts.v1
      summary: Get corporation contract bids
      tags:
        - Contracts
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
      x-required-roles: []
  "/corporations/{corporation_id}/contracts/{contract_id}/items/":
    get:
      description: |-
        Lists items of a particular contract

        ---
        Alternate route: `/dev/corporations/{corporation_id}/contracts/{contract_id}/items/`

        Alternate route: `/legacy/corporations/{corporation_id}/contracts/{contract_id}/items/`

        Alternate route: `/v1/corporations/{corporation_id}/contracts/{contract_id}/items/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_corporations_corporation_id_contracts_contract_id_items
      security:
        - evesso:
            - esi-contracts.read_corporation_contracts.v1
      summary: Get corporation contract items
      tags:
        - Contracts
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
      x-required-roles: []
  "/corporations/{corporation_id}/customs_offices/":
    get:
      description: |
        List customs offices owned by a corporation

        ---
        Alternate route: `/dev/corporations/{corporation_id}/customs_offices/`

        Alternate route: `/legacy/corporations/{corporation_id}/customs_offices/`

        Alternate route: `/v1/corporations/{corporation_id}/customs_offices/`

        ---
        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director
      operationId: get_corporations_corporation_id_customs_offices
      security:
        - evesso:
            - esi-planets.read_customs_offices.v1
      summary: List corporation customs offices
      tags:
        - Planetary Interaction
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
      x-required-roles:
        - Director
  "/corporations/{corporation_id}/divisions/":
    get:
      description: |
        Return corporation hangar and wallet division names, only show if a division is not using the default name

        ---
        Alternate route: `/dev/corporations/{corporation_id}/divisions/`

        Alternate route: `/legacy/corporations/{corporation_id}/divisions/`

        Alternate route: `/v1/corporations/{corporation_id}/divisions/`

        ---
        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director
      operationId: get_corporations_corporation_id_divisions
      security:
        - evesso:
            - esi-corporations.read_divisions.v1
      summary: Get corporation divisions
      tags:
        - Corporation
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
      x-required-roles:
        - Director
  "/corporations/{corporation_id}/facilities/":
    get:
      description: |
        Return a corporation's facilities

        ---
        Alternate route: `/dev/corporations/{corporation_id}/facilities/`

        Alternate route: `/legacy/corporations/{corporation_id}/facilities/`

        Alternate route: `/v1/corporations/{corporation_id}/facilities/`

        ---
        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Factory_Manager
      operationId: get_corporations_corporation_id_facilities
      security:
        - evesso:
            - esi-corporations.read_facilities.v1
      summary: Get corporation facilities
      tags:
        - Corporation
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
      x-required-roles:
        - Factory_Manager
  "/corporations/{corporation_id}/fw/stats/":
    get:
      description: |-
        Statistics about a corporation involved in faction warfare

        ---
        Alternate route: `/dev/corporations/{corporation_id}/fw/stats/`

        Alternate route: `/legacy/corporations/{corporation_id}/fw/stats/`

        Alternate route: `/v1/corporations/{corporation_id}/fw/stats/`

        ---
        This route expires daily at 11:05
      operationId: get_corporations_corporation_id_fw_stats
      security:
        - evesso:
            - esi-corporations.read_fw_stats.v1
      summary: Overview of a corporation involved in faction warfare
      tags:
        - Faction Warfare
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-required-roles: []
  "/corporations/{corporation_id}/icons/":
    get:
      description: |-
        Get the icon urls for a corporation

        ---
        Alternate route: `/dev/corporations/{corporation_id}/icons/`

        Alternate route: `/legacy/corporations/{corporation_id}/icons/`

        Alternate route: `/v1/corporations/{corporation_id}/icons/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_corporations_corporation_id_icons
      summary: Get corporation icon
      tags:
        - Corporation
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/corporations/{corporation_id}/industry/jobs/":
    get:
      description: |
        List industry jobs run by a corporation

        ---
        Alternate route: `/dev/corporations/{corporation_id}/industry/jobs/`

        Alternate route: `/legacy/corporations/{corporation_id}/industry/jobs/`

        Alternate route: `/v1/corporations/{corporation_id}/industry/jobs/`

        ---
        This route is cached for up to 300 seconds

        ---
        Requires one of the following EVE corporation role(s): Factory_Manager
      operationId: get_corporations_corporation_id_industry_jobs
      security:
        - evesso:
            - esi-industry.read_corporation_jobs.v1
      summary: List corporation industry jobs
      tags:
        - Industry
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 300
      x-required-roles:
        - Factory_Manager
  "/corporations/{corporation_id}/killmails/recent/":
    get:
      description: |
        Get a list of a corporation's kills and losses going back 90 days

        ---
        Alternate route: `/dev/corporations/{corporation_id}/killmails/recent/`

        Alternate route: `/legacy/corporations/{corporation_id}/killmails/recent/`

        Alternate route: `/v1/corporations/{corporation_id}/killmails/recent/`

        ---
        This route is cached for up to 300 seconds

        ---
        Requires one of the following EVE corporation role(s): Director
      operationId: get_corporations_corporation_id_killmails_recent
      security:
        - evesso:
            - esi-killmails.read_corporation_killmails.v1
      summary: Get a corporation's recent kills and losses
      tags:
        - Killmails
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 300
      x-required-roles:
        - Director
  "/corporations/{corporation_id}/medals/":
    get:
      description: |-
        Returns a corporation's medals

        ---
        Alternate route: `/dev/corporations/{corporation_id}/medals/`

        Alternate route: `/legacy/corporations/{corporation_id}/medals/`

        Alternate route: `/v1/corporations/{corporation_id}/medals/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_corporations_corporation_id_medals
      security:
        - evesso:
            - esi-corporations.read_medals.v1
      summary: Get corporation medals
      tags:
        - Corporation
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
      x-required-roles: []
  "/corporations/{corporation_id}/medals/issued/":
    get:
      description: |
        Returns medals issued by a corporation

        ---
        Alternate route: `/dev/corporations/{corporation_id}/medals/issued/`

        Alternate route: `/legacy/corporations/{corporation_id}/medals/issued/`

        Alternate route: `/v1/corporations/{corporation_id}/medals/issued/`

        ---
        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director
      operationId: get_corporations_corporation_id_medals_issued
      security:
        - evesso:
            - esi-corporations.read_medals.v1
      summary: Get corporation issued medals
      tags:
        - Corporation
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
      x-required-roles:
        - Director
  "/corporations/{corporation_id}/members/":
    get:
      description: |-
        Return the current member list of a corporation, the token's character need to be a member of the corporation.

        ---
        Alternate route: `/dev/corporations/{corporation_id}/members/`

        Alternate route: `/v3/corporations/{corporation_id}/members/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_corporations_corporation_id_members
      security:
        - evesso:
            - esi-corporations.read_corporation_membership.v1
      summary: Get corporation members
      tags:
        - Corporation
      x-alternate-versions:
        - dev
        - v3
      x-cached-seconds: 3600
  "/corporations/{corporation_id}/members/limit/":
    get:
      description: |
        Return a corporation's member limit, not including CEO himself

        ---
        Alternate route: `/dev/corporations/{corporation_id}/members/limit/`

        Alternate route: `/legacy/corporations/{corporation_id}/members/limit/`

        Alternate route: `/v1/corporations/{corporation_id}/members/limit/`

        ---
        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director
      operationId: get_corporations_corporation_id_members_limit
      security:
        - evesso:
            - esi-corporations.track_members.v1
      summary: Get corporation member limit
      tags:
        - Corporation
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
      x-required-roles:
        - Director
  "/corporations/{corporation_id}/members/titles/":
    get:
      description: |
        Returns a corporation's members' titles

        ---
        Alternate route: `/dev/corporations/{corporation_id}/members/titles/`

        Alternate route: `/legacy/corporations/{corporation_id}/members/titles/`

        Alternate route: `/v1/corporations/{corporation_id}/members/titles/`

        ---
        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director
      operationId: get_corporations_corporation_id_members_titles
      security:
        - evesso:
            - esi-corporations.read_titles.v1
      summary: Get corporation's members' titles
      tags:
        - Corporation
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
      x-required-roles:
        - Director
  "/corporations/{corporation_id}/membertracking/":
    get:
      description: |
        Returns additional information about a corporation's members which helps tracking their activities

        ---
        Alternate route: `/dev/corporations/{corporation_id}/membertracking/`

        Alternate route: `/legacy/corporations/{corporation_id}/membertracking/`

        Alternate route: `/v1/corporations/{corporation_id}/membertracking/`

        ---
        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director
      operationId: get_corporations_corporation_id_membertracking
      security:
        - evesso:
            - esi-corporations.track_members.v1
      summary: Track corporation members
      tags:
        - Corporation
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
      x-required-roles:
        - Director
  "/corporations/{corporation_id}/orders/":
    get:
      description: |
        List open market orders placed on behalf of a corporation

        ---
        Alternate route: `/dev/corporations/{corporation_id}/orders/`

        Alternate route: `/v3/corporations/{corporation_id}/orders/`

        ---
        This route is cached for up to 1200 seconds

        ---
        Requires one of the following EVE corporation role(s): Accountant, Trader
      operationId: get_corporations_corporation_id_orders
      security:
        - evesso:
            - esi-markets.read_corporation_orders.v1
      summary: List open orders from a corporation
      tags:
        - Market
      x-alternate-versions:
        - dev
        - v3
      x-cached-seconds: 1200
      x-required-roles:
        - Accountant
        - Trader
  "/corporations/{corporation_id}/orders/history/":
    get:
      description: |
        List cancelled and expired market orders placed on behalf of a corporation up to 90 days in the past.

        ---
        Alternate route: `/dev/corporations/{corporation_id}/orders/history/`

        Alternate route: `/v2/corporations/{corporation_id}/orders/history/`

        ---
        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Accountant, Trader
      operationId: get_corporations_corporation_id_orders_history
      security:
        - evesso:
            - esi-markets.read_corporation_orders.v1
      summary: List historical orders from a corporation
      tags:
        - Market
      x-alternate-versions:
        - dev
        - v2
      x-cached-seconds: 3600
      x-required-roles:
        - Accountant
        - Trader
  "/corporations/{corporation_id}/roles/":
    get:
      description: |-
        Return the roles of all members if the character has the personnel manager role or any grantable role.

        ---
        Alternate route: `/dev/corporations/{corporation_id}/roles/`

        Alternate route: `/legacy/corporations/{corporation_id}/roles/`

        Alternate route: `/v1/corporations/{corporation_id}/roles/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_corporations_corporation_id_roles
      security:
        - evesso:
            - esi-corporations.read_corporation_membership.v1
      summary: Get corporation member roles
      tags:
        - Corporation
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/corporations/{corporation_id}/roles/history/":
    get:
      description: |
        Return how roles have changed for a coporation's members, up to a month

        ---
        Alternate route: `/dev/corporations/{corporation_id}/roles/history/`

        Alternate route: `/legacy/corporations/{corporation_id}/roles/history/`

        Alternate route: `/v1/corporations/{corporation_id}/roles/history/`

        ---
        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director
      operationId: get_corporations_corporation_id_roles_history
      security:
        - evesso:
            - esi-corporations.read_corporation_membership.v1
      summary: Get corporation member roles history
      tags:
        - Corporation
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
      x-required-roles:
        - Director
  "/corporations/{corporation_id}/shareholders/":
    get:
      description: |
        Return the current shareholders of a corporation.

        ---
        Alternate route: `/dev/corporations/{corporation_id}/shareholders/`

        Alternate route: `/legacy/corporations/{corporation_id}/shareholders/`

        Alternate route: `/v1/corporations/{corporation_id}/shareholders/`

        ---
        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director
      operationId: get_corporations_corporation_id_shareholders
      security:
        - evesso:
            - esi-wallet.read_corporation_wallets.v1
      summary: Get corporation shareholders
      tags:
        - Corporation
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
      x-required-roles:
        - Director
  "/corporations/{corporation_id}/standings/":
    get:
      description: |-
        Return corporation standings from agents, NPC corporations, and factions

        ---
        Alternate route: `/dev/corporations/{corporation_id}/standings/`

        Alternate route: `/legacy/corporations/{corporation_id}/standings/`

        Alternate route: `/v1/corporations/{corporation_id}/standings/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_corporations_corporation_id_standings
      security:
        - evesso:
            - esi-corporations.read_standings.v1
      summary: Get corporation standings
      tags:
        - Corporation
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
      x-required-roles: []
  "/corporations/{corporation_id}/starbases/":
    get:
      description: |
        Returns list of corporation starbases (POSes)

        ---
        Alternate route: `/dev/corporations/{corporation_id}/starbases/`

        Alternate route: `/legacy/corporations/{corporation_id}/starbases/`

        Alternate route: `/v1/corporations/{corporation_id}/starbases/`

        ---
        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director
      operationId: get_corporations_corporation_id_starbases
      security:
        - evesso:
            - esi-corporations.read_starbases.v1
      summary: Get corporation starbases (POSes)
      tags:
        - Corporation
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
      x-required-roles:
        - Director
  "/corporations/{corporation_id}/starbases/{starbase_id}/":
    get:
      description: |
        Returns various settings and fuels of a starbase (POS)

        ---
        Alternate route: `/dev/corporations/{corporation_id}/starbases/{starbase_id}/`

        Alternate route: `/legacy/corporations/{corporation_id}/starbases/{starbase_id}/`

        Alternate route: `/v1/corporations/{corporation_id}/starbases/{starbase_id}/`

        ---
        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director
      operationId: get_corporations_corporation_id_starbases_starbase_id
      security:
        - evesso:
            - esi-corporations.read_starbases.v1
      summary: Get starbase (POS) detail
      tags:
        - Corporation
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
      x-required-roles:
        - Director
  "/corporations/{corporation_id}/structures/":
    get:
      description: |-
        Get a list of corporation structures. This route's version includes the changes to structures detailed in this blog: https://www.eveonline.com/article/upwell-2.0-structures-changes-coming-on-february-13th Note: this route will not return any flex structures owned by a corporation, use the v3 route to have those included in the response. A list of FLEX structures can be found here: https://support.eveonline.com/hc/en-us/articles/213021829-Upwell-Structures

        ---
        Alternate route: `/v2/corporations/{corporation_id}/structures/`

        ---
        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Station_Manager


        ---
        Warning: This route has an upgrade available

        ---
        [Diff of the upcoming changes](https://esi.evetech.net/diff/latest/dev/#GET-/corporations/{corporation_id}/structures/)
      operationId: get_corporations_corporation_id_structures
      security:
        - evesso:
            - esi-corporations.read_structures.v1
      summary: Get corporation structures
      tags:
        - Corporation
      x-alternate-versions:
        - v2
      x-cached-seconds: 3600
      x-required-roles:
        - Station_Manager
  "/corporations/{corporation_id}/titles/":
    get:
      description: |
        Returns a corporation's titles

        ---
        Alternate route: `/dev/corporations/{corporation_id}/titles/`

        Alternate route: `/legacy/corporations/{corporation_id}/titles/`

        Alternate route: `/v1/corporations/{corporation_id}/titles/`

        ---
        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director
      operationId: get_corporations_corporation_id_titles
      security:
        - evesso:
            - esi-corporations.read_titles.v1
      summary: Get corporation titles
      tags:
        - Corporation
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
      x-required-roles:
        - Director
  "/corporations/{corporation_id}/wallets/":
    get:
      description: |
        Get a corporation's wallets

        ---
        Alternate route: `/dev/corporations/{corporation_id}/wallets/`

        Alternate route: `/legacy/corporations/{corporation_id}/wallets/`

        Alternate route: `/v1/corporations/{corporation_id}/wallets/`

        ---
        This route is cached for up to 300 seconds

        ---
        Requires one of the following EVE corporation role(s): Accountant, Junior_Accountant
      operationId: get_corporations_corporation_id_wallets
      security:
        - evesso:
            - esi-wallet.read_corporation_wallets.v1
      summary: Returns a corporation's wallet balance
      tags:
        - Wallet
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 300
      x-required-roles:
        - Accountant
        - Junior_Accountant
  "/corporations/{corporation_id}/wallets/{division}/journal/":
    get:
      description: |-
        Retrieve the given corporation's wallet journal for the given division going 30 days back. Note: any journal records having to do with the new navigation structures from the release of Onslaught will not show up in this version. To see those, use the v4 version of this route.

        ---
        Alternate route: `/legacy/corporations/{corporation_id}/wallets/{division}/journal/`

        Alternate route: `/v3/corporations/{corporation_id}/wallets/{division}/journal/`

        ---
        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Accountant, Junior_Accountant


        ---
        Warning: This route has an upgrade available

        ---
        [Diff of the upcoming changes](https://esi.evetech.net/diff/latest/dev/#GET-/corporations/{corporation_id}/wallets/{division}/journal/)
      operationId: get_corporations_corporation_id_wallets_division_journal
      security:
        - evesso:
            - esi-wallet.read_corporation_wallets.v1
      summary: Get corporation wallet journal
      tags:
        - Wallet
      x-alternate-versions:
        - legacy
        - v3
      x-cached-seconds: 3600
      x-required-roles:
        - Accountant
        - Junior_Accountant
  "/corporations/{corporation_id}/wallets/{division}/transactions/":
    get:
      description: |
        Get wallet transactions of a corporation

        ---
        Alternate route: `/dev/corporations/{corporation_id}/wallets/{division}/transactions/`

        Alternate route: `/legacy/corporations/{corporation_id}/wallets/{division}/transactions/`

        Alternate route: `/v1/corporations/{corporation_id}/wallets/{division}/transactions/`

        ---
        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Accountant, Junior_Accountant
      operationId: get_corporations_corporation_id_wallets_division_transactions
      security:
        - evesso:
            - esi-wallet.read_corporation_wallets.v1
      summary: Get corporation wallet transactions
      tags:
        - Wallet
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
      x-required-roles:
        - Accountant
        - Junior_Accountant
  /dogma/attributes/:
    get:
      description: |-
        Get a list of dogma attribute ids

        ---
        Alternate route: `/dev/dogma/attributes/`

        Alternate route: `/legacy/dogma/attributes/`

        Alternate route: `/v1/dogma/attributes/`

        ---
        This route expires daily at 11:05
      operationId: get_dogma_attributes
      summary: Get attributes
      tags:
        - Dogma
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/dogma/attributes/{attribute_id}/":
    get:
      description: |-
        Get information on a dogma attribute

        ---
        Alternate route: `/dev/dogma/attributes/{attribute_id}/`

        Alternate route: `/legacy/dogma/attributes/{attribute_id}/`

        Alternate route: `/v1/dogma/attributes/{attribute_id}/`

        ---
        This route expires daily at 11:05
      operationId: get_dogma_attributes_attribute_id
      summary: Get attribute information
      tags:
        - Dogma
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/dogma/dynamic/items/{type_id}/{item_id}/":
    get:
      description: |-
        Returns info about a dynamic item resulting from mutation with a mutaplasmid.

        ---
        Alternate route: `/dev/dogma/dynamic/items/{type_id}/{item_id}/`

        Alternate route: `/legacy/dogma/dynamic/items/{type_id}/{item_id}/`

        Alternate route: `/v1/dogma/dynamic/items/{type_id}/{item_id}/`

        ---
        This route expires daily at 11:05
      operationId: get_dogma_dynamic_items_type_id_item_id
      summary: Get dynamic item information
      tags:
        - Dogma
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /dogma/effects/:
    get:
      description: |-
        Get a list of dogma effect ids

        ---
        Alternate route: `/dev/dogma/effects/`

        Alternate route: `/legacy/dogma/effects/`

        Alternate route: `/v1/dogma/effects/`

        ---
        This route expires daily at 11:05
      operationId: get_dogma_effects
      summary: Get effects
      tags:
        - Dogma
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/dogma/effects/{effect_id}/":
    get:
      description: |-
        Get information on a dogma effect

        ---
        Alternate route: `/dev/dogma/effects/{effect_id}/`

        Alternate route: `/v2/dogma/effects/{effect_id}/`

        ---
        This route expires daily at 11:05
      operationId: get_dogma_effects_effect_id
      summary: Get effect information
      tags:
        - Dogma
      x-alternate-versions:
        - dev
        - v2
  "/fleets/{fleet_id}/":
    get:
      description: |-
        Return details about a fleet

        ---
        Alternate route: `/dev/fleets/{fleet_id}/`

        Alternate route: `/legacy/fleets/{fleet_id}/`

        Alternate route: `/v1/fleets/{fleet_id}/`

        ---
        This route is cached for up to 5 seconds
      operationId: get_fleets_fleet_id
      security:
        - evesso:
            - esi-fleets.read_fleet.v1
      summary: Get fleet information
      tags:
        - Fleets
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 5
    put:
      description: |
        Update settings about a fleet

        ---
        Alternate route: `/dev/fleets/{fleet_id}/`

        Alternate route: `/legacy/fleets/{fleet_id}/`

        Alternate route: `/v1/fleets/{fleet_id}/`
      operationId: put_fleets_fleet_id
      security:
        - evesso:
            - esi-fleets.write_fleet.v1
      summary: Update fleet
      tags:
        - Fleets
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/fleets/{fleet_id}/members/":
    get:
      description: |-
        Return information about fleet members

        ---
        Alternate route: `/dev/fleets/{fleet_id}/members/`

        Alternate route: `/legacy/fleets/{fleet_id}/members/`

        Alternate route: `/v1/fleets/{fleet_id}/members/`

        ---
        This route is cached for up to 5 seconds
      operationId: get_fleets_fleet_id_members
      security:
        - evesso:
            - esi-fleets.read_fleet.v1
      summary: Get fleet members
      tags:
        - Fleets
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 5
    post:
      description: |
        Invite a character into the fleet. If a character has a CSPA charge set it is not possible to invite them to the fleet using ESI

        ---
        Alternate route: `/dev/fleets/{fleet_id}/members/`

        Alternate route: `/legacy/fleets/{fleet_id}/members/`

        Alternate route: `/v1/fleets/{fleet_id}/members/`
      operationId: post_fleets_fleet_id_members
      security:
        - evesso:
            - esi-fleets.write_fleet.v1
      summary: Create fleet invitation
      tags:
        - Fleets
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/fleets/{fleet_id}/members/{member_id}/":
    delete:
      description: |
        Kick a fleet member

        ---
        Alternate route: `/dev/fleets/{fleet_id}/members/{member_id}/`

        Alternate route: `/legacy/fleets/{fleet_id}/members/{member_id}/`

        Alternate route: `/v1/fleets/{fleet_id}/members/{member_id}/`
      operationId: delete_fleets_fleet_id_members_member_id
      security:
        - evesso:
            - esi-fleets.write_fleet.v1
      summary: Kick fleet member
      tags:
        - Fleets
      x-alternate-versions:
        - dev
        - legacy
        - v1
    put:
      description: |
        Move a fleet member around

        ---
        Alternate route: `/dev/fleets/{fleet_id}/members/{member_id}/`

        Alternate route: `/legacy/fleets/{fleet_id}/members/{member_id}/`

        Alternate route: `/v1/fleets/{fleet_id}/members/{member_id}/`
      operationId: put_fleets_fleet_id_members_member_id
      security:
        - evesso:
            - esi-fleets.write_fleet.v1
      summary: Move fleet member
      tags:
        - Fleets
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/fleets/{fleet_id}/squads/{squad_id}/":
    delete:
      description: |
        Delete a fleet squad, only empty squads can be deleted

        ---
        Alternate route: `/dev/fleets/{fleet_id}/squads/{squad_id}/`

        Alternate route: `/legacy/fleets/{fleet_id}/squads/{squad_id}/`

        Alternate route: `/v1/fleets/{fleet_id}/squads/{squad_id}/`
      operationId: delete_fleets_fleet_id_squads_squad_id
      security:
        - evesso:
            - esi-fleets.write_fleet.v1
      summary: Delete fleet squad
      tags:
        - Fleets
      x-alternate-versions:
        - dev
        - legacy
        - v1
    put:
      description: |
        Rename a fleet squad

        ---
        Alternate route: `/dev/fleets/{fleet_id}/squads/{squad_id}/`

        Alternate route: `/legacy/fleets/{fleet_id}/squads/{squad_id}/`

        Alternate route: `/v1/fleets/{fleet_id}/squads/{squad_id}/`
      operationId: put_fleets_fleet_id_squads_squad_id
      security:
        - evesso:
            - esi-fleets.write_fleet.v1
      summary: Rename fleet squad
      tags:
        - Fleets
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/fleets/{fleet_id}/wings/":
    get:
      description: |-
        Return information about wings in a fleet

        ---
        Alternate route: `/dev/fleets/{fleet_id}/wings/`

        Alternate route: `/legacy/fleets/{fleet_id}/wings/`

        Alternate route: `/v1/fleets/{fleet_id}/wings/`

        ---
        This route is cached for up to 5 seconds
      operationId: get_fleets_fleet_id_wings
      security:
        - evesso:
            - esi-fleets.read_fleet.v1
      summary: Get fleet wings
      tags:
        - Fleets
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 5
    post:
      description: |
        Create a new wing in a fleet

        ---
        Alternate route: `/dev/fleets/{fleet_id}/wings/`

        Alternate route: `/legacy/fleets/{fleet_id}/wings/`

        Alternate route: `/v1/fleets/{fleet_id}/wings/`
      operationId: post_fleets_fleet_id_wings
      security:
        - evesso:
            - esi-fleets.write_fleet.v1
      summary: Create fleet wing
      tags:
        - Fleets
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/fleets/{fleet_id}/wings/{wing_id}/":
    delete:
      description: |
        Delete a fleet wing, only empty wings can be deleted. The wing may contain squads, but the squads must be empty

        ---
        Alternate route: `/dev/fleets/{fleet_id}/wings/{wing_id}/`

        Alternate route: `/legacy/fleets/{fleet_id}/wings/{wing_id}/`

        Alternate route: `/v1/fleets/{fleet_id}/wings/{wing_id}/`
      operationId: delete_fleets_fleet_id_wings_wing_id
      security:
        - evesso:
            - esi-fleets.write_fleet.v1
      summary: Delete fleet wing
      tags:
        - Fleets
      x-alternate-versions:
        - dev
        - legacy
        - v1
    put:
      description: |
        Rename a fleet wing

        ---
        Alternate route: `/dev/fleets/{fleet_id}/wings/{wing_id}/`

        Alternate route: `/legacy/fleets/{fleet_id}/wings/{wing_id}/`

        Alternate route: `/v1/fleets/{fleet_id}/wings/{wing_id}/`
      operationId: put_fleets_fleet_id_wings_wing_id
      security:
        - evesso:
            - esi-fleets.write_fleet.v1
      summary: Rename fleet wing
      tags:
        - Fleets
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/fleets/{fleet_id}/wings/{wing_id}/squads/":
    post:
      description: |
        Create a new squad in a fleet

        ---
        Alternate route: `/dev/fleets/{fleet_id}/wings/{wing_id}/squads/`

        Alternate route: `/legacy/fleets/{fleet_id}/wings/{wing_id}/squads/`

        Alternate route: `/v1/fleets/{fleet_id}/wings/{wing_id}/squads/`
      operationId: post_fleets_fleet_id_wings_wing_id_squads
      security:
        - evesso:
            - esi-fleets.write_fleet.v1
      summary: Create fleet squad
      tags:
        - Fleets
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /fw/leaderboards/:
    get:
      description: |-
        Top 4 leaderboard of factions for kills and victory points separated by total, last week and yesterday

        ---
        Alternate route: `/dev/fw/leaderboards/`

        Alternate route: `/legacy/fw/leaderboards/`

        Alternate route: `/v1/fw/leaderboards/`

        ---
        This route expires daily at 11:05
      operationId: get_fw_leaderboards
      summary: List of the top factions in faction warfare
      tags:
        - Faction Warfare
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /fw/leaderboards/characters/:
    get:
      description: |-
        Top 100 leaderboard of pilots for kills and victory points separated by total, last week and yesterday

        ---
        Alternate route: `/dev/fw/leaderboards/characters/`

        Alternate route: `/legacy/fw/leaderboards/characters/`

        Alternate route: `/v1/fw/leaderboards/characters/`

        ---
        This route expires daily at 11:05
      operationId: get_fw_leaderboards_characters
      summary: List of the top pilots in faction warfare
      tags:
        - Faction Warfare
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /fw/leaderboards/corporations/:
    get:
      description: |-
        Top 10 leaderboard of corporations for kills and victory points separated by total, last week and yesterday

        ---
        Alternate route: `/dev/fw/leaderboards/corporations/`

        Alternate route: `/legacy/fw/leaderboards/corporations/`

        Alternate route: `/v1/fw/leaderboards/corporations/`

        ---
        This route expires daily at 11:05
      operationId: get_fw_leaderboards_corporations
      summary: List of the top corporations in faction warfare
      tags:
        - Faction Warfare
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /fw/stats/:
    get:
      description: |-
        Statistical overviews of factions involved in faction warfare

        ---
        Alternate route: `/dev/fw/stats/`

        Alternate route: `/legacy/fw/stats/`

        Alternate route: `/v1/fw/stats/`

        ---
        This route expires daily at 11:05
      operationId: get_fw_stats
      summary: An overview of statistics about factions involved in faction warfare
      tags:
        - Faction Warfare
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /fw/systems/:
    get:
      description: |-
        An overview of the current ownership of faction warfare solar systems

        ---
        Alternate route: `/dev/fw/systems/`

        Alternate route: `/v2/fw/systems/`

        ---
        This route is cached for up to 1800 seconds
      operationId: get_fw_systems
      summary: Ownership of faction warfare systems
      tags:
        - Faction Warfare
      x-alternate-versions:
        - dev
        - v2
      x-cached-seconds: 1800
  /fw/wars/:
    get:
      description: |-
        Data about which NPC factions are at war

        ---
        Alternate route: `/dev/fw/wars/`

        Alternate route: `/legacy/fw/wars/`

        Alternate route: `/v1/fw/wars/`

        ---
        This route expires daily at 11:05
      operationId: get_fw_wars
      summary: Data about which NPC factions are at war
      tags:
        - Faction Warfare
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /incursions/:
    get:
      description: |-
        Return a list of current incursions

        ---
        Alternate route: `/dev/incursions/`

        Alternate route: `/legacy/incursions/`

        Alternate route: `/v1/incursions/`

        ---
        This route is cached for up to 300 seconds
      operationId: get_incursions
      summary: List incursions
      tags:
        - Incursions
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 300
  /industry/facilities/:
    get:
      description: |-
        Return a list of industry facilities

        ---
        Alternate route: `/dev/industry/facilities/`

        Alternate route: `/legacy/industry/facilities/`

        Alternate route: `/v1/industry/facilities/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_industry_facilities
      summary: List industry facilities
      tags:
        - Industry
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  /industry/systems/:
    get:
      description: |-
        Return cost indices for solar systems

        ---
        Alternate route: `/dev/industry/systems/`

        Alternate route: `/legacy/industry/systems/`

        Alternate route: `/v1/industry/systems/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_industry_systems
      summary: List solar system cost indices
      tags:
        - Industry
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  /insurance/prices/:
    get:
      description: |-
        Return available insurance levels for all ship types

        ---
        Alternate route: `/dev/insurance/prices/`

        Alternate route: `/legacy/insurance/prices/`

        Alternate route: `/v1/insurance/prices/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_insurance_prices
      summary: List insurance levels
      tags:
        - Insurance
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/killmails/{killmail_id}/{killmail_hash}/":
    get:
      description: |-
        Return a single killmail from its ID and hash

        ---
        Alternate route: `/dev/killmails/{killmail_id}/{killmail_hash}/`

        Alternate route: `/legacy/killmails/{killmail_id}/{killmail_hash}/`

        Alternate route: `/v1/killmails/{killmail_id}/{killmail_hash}/`

        ---
        This route is cached for up to 1209600 seconds
      operationId: get_killmails_killmail_id_killmail_hash
      summary: Get a single killmail
      tags:
        - Killmails
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 1209600
  "/loyalty/stores/{corporation_id}/offers/":
    get:
      description: |-
        Return a list of offers from a specific corporation's loyalty store

        ---
        Alternate route: `/dev/loyalty/stores/{corporation_id}/offers/`

        Alternate route: `/legacy/loyalty/stores/{corporation_id}/offers/`

        Alternate route: `/v1/loyalty/stores/{corporation_id}/offers/`

        ---
        This route expires daily at 11:05
      operationId: get_loyalty_stores_corporation_id_offers
      summary: List loyalty store offers
      tags:
        - Loyalty
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /markets/groups/:
    get:
      description: |-
        Get a list of item groups

        ---
        Alternate route: `/dev/markets/groups/`

        Alternate route: `/legacy/markets/groups/`

        Alternate route: `/v1/markets/groups/`

        ---
        This route expires daily at 11:05
      operationId: get_markets_groups
      summary: Get item groups
      tags:
        - Market
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/markets/groups/{market_group_id}/":
    get:
      description: |-
        Get information on an item group

        ---
        Alternate route: `/dev/markets/groups/{market_group_id}/`

        Alternate route: `/legacy/markets/groups/{market_group_id}/`

        Alternate route: `/v1/markets/groups/{market_group_id}/`

        ---
        This route expires daily at 11:05
      operationId: get_markets_groups_market_group_id
      summary: Get item group information
      tags:
        - Market
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /markets/prices/:
    get:
      description: |-
        Return a list of prices

        ---
        Alternate route: `/dev/markets/prices/`

        Alternate route: `/legacy/markets/prices/`

        Alternate route: `/v1/markets/prices/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_markets_prices
      summary: List market prices
      tags:
        - Market
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/markets/structures/{structure_id}/":
    get:
      description: |-
        Return all orders in a structure

        ---
        Alternate route: `/dev/markets/structures/{structure_id}/`

        Alternate route: `/legacy/markets/structures/{structure_id}/`

        Alternate route: `/v1/markets/structures/{structure_id}/`

        ---
        This route is cached for up to 300 seconds
      operationId: get_markets_structures_structure_id
      security:
        - evesso:
            - esi-markets.structure_markets.v1
      summary: List orders in a structure
      tags:
        - Market
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 300
  "/markets/{region_id}/history/":
    get:
      description: |-
        Return a list of historical market statistics for the specified type in a region

        ---
        Alternate route: `/dev/markets/{region_id}/history/`

        Alternate route: `/legacy/markets/{region_id}/history/`

        Alternate route: `/v1/markets/{region_id}/history/`

        ---
        This route expires daily at 11:05
      operationId: get_markets_region_id_history
      summary: List historical market statistics in a region
      tags:
        - Market
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/markets/{region_id}/orders/":
    get:
      description: |-
        Return a list of orders in a region

        ---
        Alternate route: `/dev/markets/{region_id}/orders/`

        Alternate route: `/legacy/markets/{region_id}/orders/`

        Alternate route: `/v1/markets/{region_id}/orders/`

        ---
        This route is cached for up to 300 seconds
      operationId: get_markets_region_id_orders
      summary: List orders in a region
      tags:
        - Market
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 300
  "/markets/{region_id}/types/":
    get:
      description: |-
        Return a list of type IDs that have active orders in the region, for efficient market indexing.

        ---
        Alternate route: `/dev/markets/{region_id}/types/`

        Alternate route: `/legacy/markets/{region_id}/types/`

        Alternate route: `/v1/markets/{region_id}/types/`

        ---
        This route is cached for up to 600 seconds
      operationId: get_markets_region_id_types
      summary: List type IDs relevant to a market
      tags:
        - Market
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 600
  /opportunities/groups/:
    get:
      description: |-
        Return a list of opportunities groups

        ---
        Alternate route: `/dev/opportunities/groups/`

        Alternate route: `/legacy/opportunities/groups/`

        Alternate route: `/v1/opportunities/groups/`

        ---
        This route expires daily at 11:05
      operationId: get_opportunities_groups
      summary: Get opportunities groups
      tags:
        - Opportunities
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/opportunities/groups/{group_id}/":
    get:
      description: |-
        Return information of an opportunities group

        ---
        Alternate route: `/dev/opportunities/groups/{group_id}/`

        Alternate route: `/legacy/opportunities/groups/{group_id}/`

        Alternate route: `/v1/opportunities/groups/{group_id}/`

        ---
        This route expires daily at 11:05
      operationId: get_opportunities_groups_group_id
      summary: Get opportunities group
      tags:
        - Opportunities
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /opportunities/tasks/:
    get:
      description: |-
        Return a list of opportunities tasks

        ---
        Alternate route: `/dev/opportunities/tasks/`

        Alternate route: `/legacy/opportunities/tasks/`

        Alternate route: `/v1/opportunities/tasks/`

        ---
        This route expires daily at 11:05
      operationId: get_opportunities_tasks
      summary: Get opportunities tasks
      tags:
        - Opportunities
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/opportunities/tasks/{task_id}/":
    get:
      description: |-
        Return information of an opportunities task

        ---
        Alternate route: `/dev/opportunities/tasks/{task_id}/`

        Alternate route: `/legacy/opportunities/tasks/{task_id}/`

        Alternate route: `/v1/opportunities/tasks/{task_id}/`

        ---
        This route expires daily at 11:05
      operationId: get_opportunities_tasks_task_id
      summary: Get opportunities task
      tags:
        - Opportunities
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/route/{origin}/{destination}/":
    get:
      description: |-
        Get the systems between origin and destination

        ---
        Alternate route: `/dev/route/{origin}/{destination}/`

        Alternate route: `/legacy/route/{origin}/{destination}/`

        Alternate route: `/v1/route/{origin}/{destination}/`

        ---
        This route is cached for up to 86400 seconds
      operationId: get_route_origin_destination
      summary: Get route
      tags:
        - Routes
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 86400
  /search/:
    get:
      description: |-
        Search for entities that match a given sub-string.

        ---
        Alternate route: `/dev/search/`

        Alternate route: `/v2/search/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_search
      summary: Search on a string
      tags:
        - Search
      x-alternate-versions:
        - dev
        - v2
      x-cached-seconds: 3600
  /sovereignty/campaigns/:
    get:
      description: |-
        Shows sovereignty data for campaigns.

        ---
        Alternate route: `/dev/sovereignty/campaigns/`

        Alternate route: `/legacy/sovereignty/campaigns/`

        Alternate route: `/v1/sovereignty/campaigns/`

        ---
        This route is cached for up to 5 seconds
      operationId: get_sovereignty_campaigns
      summary: List sovereignty campaigns
      tags:
        - Sovereignty
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 5
  /sovereignty/map/:
    get:
      description: |-
        Shows sovereignty information for solar systems

        ---
        Alternate route: `/dev/sovereignty/map/`

        Alternate route: `/legacy/sovereignty/map/`

        Alternate route: `/v1/sovereignty/map/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_sovereignty_map
      summary: List sovereignty of systems
      tags:
        - Sovereignty
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  /sovereignty/structures/:
    get:
      description: |-
        Shows sovereignty data for structures.

        ---
        Alternate route: `/dev/sovereignty/structures/`

        Alternate route: `/legacy/sovereignty/structures/`

        Alternate route: `/v1/sovereignty/structures/`

        ---
        This route is cached for up to 120 seconds
      operationId: get_sovereignty_structures
      summary: List sovereignty structures
      tags:
        - Sovereignty
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 120
  /status/:
    get:
      description: |-
        EVE Server status

        ---
        Alternate route: `/dev/status/`

        Alternate route: `/legacy/status/`

        Alternate route: `/v1/status/`

        ---
        This route is cached for up to 30 seconds
      operationId: get_status
      summary: Retrieve the uptime and player counts
      tags:
        - Status
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 30
  /ui/autopilot/waypoint/:
    post:
      description: |
        Set a solar system as autopilot waypoint

        ---
        Alternate route: `/dev/ui/autopilot/waypoint/`

        Alternate route: `/v2/ui/autopilot/waypoint/`
      operationId: post_ui_autopilot_waypoint
      security:
        - evesso:
            - esi-ui.write_waypoint.v1
      summary: Set Autopilot Waypoint
      tags:
        - User Interface
      x-alternate-versions:
        - dev
        - v2
  /ui/openwindow/contract/:
    post:
      description: |
        Open the contract window inside the client

        ---
        Alternate route: `/dev/ui/openwindow/contract/`

        Alternate route: `/legacy/ui/openwindow/contract/`

        Alternate route: `/v1/ui/openwindow/contract/`
      operationId: post_ui_openwindow_contract
      security:
        - evesso:
            - esi-ui.open_window.v1
      summary: Open Contract Window
      tags:
        - User Interface
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /ui/openwindow/information/:
    post:
      description: |
        Open the information window for a character, corporation or alliance inside the client

        ---
        Alternate route: `/dev/ui/openwindow/information/`

        Alternate route: `/legacy/ui/openwindow/information/`

        Alternate route: `/v1/ui/openwindow/information/`
      operationId: post_ui_openwindow_information
      security:
        - evesso:
            - esi-ui.open_window.v1
      summary: Open Information Window
      tags:
        - User Interface
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /ui/openwindow/marketdetails/:
    post:
      description: |
        Open the market details window for a specific typeID inside the client

        ---
        Alternate route: `/dev/ui/openwindow/marketdetails/`

        Alternate route: `/legacy/ui/openwindow/marketdetails/`

        Alternate route: `/v1/ui/openwindow/marketdetails/`
      operationId: post_ui_openwindow_marketdetails
      security:
        - evesso:
            - esi-ui.open_window.v1
      summary: Open Market Details
      tags:
        - User Interface
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /ui/openwindow/newmail/:
    post:
      description: |
        Open the New Mail window, according to settings from the request if applicable

        ---
        Alternate route: `/dev/ui/openwindow/newmail/`

        Alternate route: `/legacy/ui/openwindow/newmail/`

        Alternate route: `/v1/ui/openwindow/newmail/`
      operationId: post_ui_openwindow_newmail
      security:
        - evesso:
            - esi-ui.open_window.v1
      summary: Open New Mail Window
      tags:
        - User Interface
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /universe/ancestries/:
    get:
      description: |-
        Get all character ancestries

        ---
        Alternate route: `/dev/universe/ancestries/`

        Alternate route: `/legacy/universe/ancestries/`

        Alternate route: `/v1/universe/ancestries/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_ancestries
      summary: Get ancestries
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/universe/asteroid_belts/{asteroid_belt_id}/":
    get:
      description: |-
        Get information on an asteroid belt

        ---
        Alternate route: `/dev/universe/asteroid_belts/{asteroid_belt_id}/`

        Alternate route: `/legacy/universe/asteroid_belts/{asteroid_belt_id}/`

        Alternate route: `/v1/universe/asteroid_belts/{asteroid_belt_id}/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_asteroid_belts_asteroid_belt_id
      summary: Get asteroid belt information
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /universe/bloodlines/:
    get:
      description: |-
        Get a list of bloodlines

        ---
        Alternate route: `/dev/universe/bloodlines/`

        Alternate route: `/legacy/universe/bloodlines/`

        Alternate route: `/v1/universe/bloodlines/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_bloodlines
      summary: Get bloodlines
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /universe/categories/:
    get:
      description: |-
        Get a list of item categories

        ---
        Alternate route: `/dev/universe/categories/`

        Alternate route: `/legacy/universe/categories/`

        Alternate route: `/v1/universe/categories/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_categories
      summary: Get item categories
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/universe/categories/{category_id}/":
    get:
      description: |-
        Get information of an item category

        ---
        Alternate route: `/dev/universe/categories/{category_id}/`

        Alternate route: `/legacy/universe/categories/{category_id}/`

        Alternate route: `/v1/universe/categories/{category_id}/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_categories_category_id
      summary: Get item category information
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /universe/constellations/:
    get:
      description: |-
        Get a list of constellations

        ---
        Alternate route: `/dev/universe/constellations/`

        Alternate route: `/legacy/universe/constellations/`

        Alternate route: `/v1/universe/constellations/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_constellations
      summary: Get constellations
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/universe/constellations/{constellation_id}/":
    get:
      description: |-
        Get information on a constellation

        ---
        Alternate route: `/dev/universe/constellations/{constellation_id}/`

        Alternate route: `/legacy/universe/constellations/{constellation_id}/`

        Alternate route: `/v1/universe/constellations/{constellation_id}/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_constellations_constellation_id
      summary: Get constellation information
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /universe/factions/:
    get:
      description: |-
        Get a list of factions

        ---
        Alternate route: `/dev/universe/factions/`

        Alternate route: `/v2/universe/factions/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_factions
      summary: Get factions
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - v2
  /universe/graphics/:
    get:
      description: |-
        Get a list of graphics

        ---
        Alternate route: `/dev/universe/graphics/`

        Alternate route: `/legacy/universe/graphics/`

        Alternate route: `/v1/universe/graphics/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_graphics
      summary: Get graphics
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/universe/graphics/{graphic_id}/":
    get:
      description: |-
        Get information on a graphic

        ---
        Alternate route: `/dev/universe/graphics/{graphic_id}/`

        Alternate route: `/legacy/universe/graphics/{graphic_id}/`

        Alternate route: `/v1/universe/graphics/{graphic_id}/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_graphics_graphic_id
      summary: Get graphic information
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /universe/groups/:
    get:
      description: |-
        Get a list of item groups

        ---
        Alternate route: `/dev/universe/groups/`

        Alternate route: `/legacy/universe/groups/`

        Alternate route: `/v1/universe/groups/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_groups
      summary: Get item groups
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/universe/groups/{group_id}/":
    get:
      description: |-
        Get information on an item group

        ---
        Alternate route: `/dev/universe/groups/{group_id}/`

        Alternate route: `/legacy/universe/groups/{group_id}/`

        Alternate route: `/v1/universe/groups/{group_id}/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_groups_group_id
      summary: Get item group information
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /universe/ids/:
    post:
      description: |
        Resolve a set of names to IDs in the following categories: agents, alliances, characters, constellations, corporations factions, inventory_types, regions, stations, and systems. Only exact matches will be returned. All names searched for are cached for 12 hours

        ---
        Alternate route: `/dev/universe/ids/`

        Alternate route: `/legacy/universe/ids/`

        Alternate route: `/v1/universe/ids/`
      operationId: post_universe_ids
      summary: Bulk names to IDs
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/universe/moons/{moon_id}/":
    get:
      description: |-
        Get information on a moon

        ---
        Alternate route: `/dev/universe/moons/{moon_id}/`

        Alternate route: `/legacy/universe/moons/{moon_id}/`

        Alternate route: `/v1/universe/moons/{moon_id}/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_moons_moon_id
      summary: Get moon information
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /universe/names/:
    post:
      description: |
        Resolve a set of IDs to names and categories. Supported ID's for resolving are: Characters, Corporations, Alliances, Stations, Solar Systems, Constellations, Regions, Types

        ---
        Alternate route: `/dev/universe/names/`

        Alternate route: `/v2/universe/names/`
      operationId: post_universe_names
      summary: Get names and categories for a set of ID's
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - v2
  "/universe/planets/{planet_id}/":
    get:
      description: |-
        Get information on a planet

        ---
        Alternate route: `/dev/universe/planets/{planet_id}/`

        Alternate route: `/legacy/universe/planets/{planet_id}/`

        Alternate route: `/v1/universe/planets/{planet_id}/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_planets_planet_id
      summary: Get planet information
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /universe/races/:
    get:
      description: |-
        Get a list of character races

        ---
        Alternate route: `/dev/universe/races/`

        Alternate route: `/legacy/universe/races/`

        Alternate route: `/v1/universe/races/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_races
      summary: Get character races
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
  /universe/regions/:
    get:
      description: |-
        Get a list of regions

        ---
        Alternate route: `/dev/universe/regions/`

        Alternate route: `/legacy/universe/regions/`

        Alternate route: `/v1/universe/regions/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_regions
      summary: Get regions
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/universe/regions/{region_id}/":
    get:
      description: |-
        Get information on a region

        ---
        Alternate route: `/dev/universe/regions/{region_id}/`

        Alternate route: `/legacy/universe/regions/{region_id}/`

        Alternate route: `/v1/universe/regions/{region_id}/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_regions_region_id
      summary: Get region information
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/universe/schematics/{schematic_id}/":
    get:
      description: |-
        Get information on a planetary factory schematic

        ---
        Alternate route: `/dev/universe/schematics/{schematic_id}/`

        Alternate route: `/legacy/universe/schematics/{schematic_id}/`

        Alternate route: `/v1/universe/schematics/{schematic_id}/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_universe_schematics_schematic_id
      summary: Get schematic information
      tags:
        - Planetary Interaction
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/universe/stargates/{stargate_id}/":
    get:
      description: |-
        Get information on a stargate

        ---
        Alternate route: `/dev/universe/stargates/{stargate_id}/`

        Alternate route: `/legacy/universe/stargates/{stargate_id}/`

        Alternate route: `/v1/universe/stargates/{stargate_id}/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_stargates_stargate_id
      summary: Get stargate information
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/universe/stars/{star_id}/":
    get:
      description: |-
        Get information on a star

        ---
        Alternate route: `/dev/universe/stars/{star_id}/`

        Alternate route: `/legacy/universe/stars/{star_id}/`

        Alternate route: `/v1/universe/stars/{star_id}/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_stars_star_id
      summary: Get star information
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/universe/stations/{station_id}/":
    get:
      description: |-
        Get information on a station

        ---
        Alternate route: `/dev/universe/stations/{station_id}/`

        Alternate route: `/v2/universe/stations/{station_id}/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_stations_station_id
      summary: Get station information
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - v2
  /universe/structures/:
    get:
      description: |-
        List all public structures

        ---
        Alternate route: `/dev/universe/structures/`

        Alternate route: `/legacy/universe/structures/`

        Alternate route: `/v1/universe/structures/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_universe_structures
      summary: List all public structures
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/universe/structures/{structure_id}/":
    get:
      description: |-
        Returns information on requested structure if you are on the ACL. Otherwise, returns "Forbidden" for all inputs.

        ---
        Alternate route: `/dev/universe/structures/{structure_id}/`

        Alternate route: `/v2/universe/structures/{structure_id}/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_universe_structures_structure_id
      security:
        - evesso:
            - esi-universe.read_structures.v1
      summary: Get structure information
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - v2
      x-cached-seconds: 3600
  /universe/system_jumps/:
    get:
      description: |-
        Get the number of jumps in solar systems within the last hour ending at the timestamp of the Last-Modified header, excluding wormhole space. Only systems with jumps will be listed

        ---
        Alternate route: `/dev/universe/system_jumps/`

        Alternate route: `/legacy/universe/system_jumps/`

        Alternate route: `/v1/universe/system_jumps/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_universe_system_jumps
      summary: Get system jumps
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  /universe/system_kills/:
    get:
      description: |-
        Get the number of ship, pod and NPC kills per solar system within the last hour ending at the timestamp of the Last-Modified header, excluding wormhole space. Only systems with kills will be listed

        ---
        Alternate route: `/dev/universe/system_kills/`

        Alternate route: `/v2/universe/system_kills/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_universe_system_kills
      summary: Get system kills
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - v2
      x-cached-seconds: 3600
  /universe/systems/:
    get:
      description: |-
        Get a list of solar systems

        ---
        Alternate route: `/dev/universe/systems/`

        Alternate route: `/legacy/universe/systems/`

        Alternate route: `/v1/universe/systems/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_systems
      summary: Get solar systems
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/universe/systems/{system_id}/":
    get:
      description: |-
        Get information on a solar system.

        ---
        Alternate route: `/dev/universe/systems/{system_id}/`

        Alternate route: `/v4/universe/systems/{system_id}/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_systems_system_id
      summary: Get solar system information
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - v4
  /universe/types/:
    get:
      description: |-
        Get a list of type ids

        ---
        Alternate route: `/dev/universe/types/`

        Alternate route: `/legacy/universe/types/`

        Alternate route: `/v1/universe/types/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_types
      summary: Get types
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - legacy
        - v1
  "/universe/types/{type_id}/":
    get:
      description: |-
        Get information on a type

        ---
        Alternate route: `/dev/universe/types/{type_id}/`

        Alternate route: `/v3/universe/types/{type_id}/`

        ---
        This route expires daily at 11:05
      operationId: get_universe_types_type_id
      summary: Get type information
      tags:
        - Universe
      x-alternate-versions:
        - dev
        - v3
  /wars/:
    get:
      description: |-
        Return a list of wars

        ---
        Alternate route: `/dev/wars/`

        Alternate route: `/legacy/wars/`

        Alternate route: `/v1/wars/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_wars
      summary: List wars
      tags:
        - Wars
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/wars/{war_id}/":
    get:
      description: |-
        Return details about a war

        ---
        Alternate route: `/dev/wars/{war_id}/`

        Alternate route: `/legacy/wars/{war_id}/`

        Alternate route: `/v1/wars/{war_id}/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_wars_war_id
      summary: Get war information
      tags:
        - Wars
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600
  "/wars/{war_id}/killmails/":
    get:
      description: |-
        Return a list of kills related to a war

        ---
        Alternate route: `/dev/wars/{war_id}/killmails/`

        Alternate route: `/legacy/wars/{war_id}/killmails/`

        Alternate route: `/v1/wars/{war_id}/killmails/`

        ---
        This route is cached for up to 3600 seconds
      operationId: get_wars_war_id_killmails
      summary: List kills for a war
      tags:
        - Wars
      x-alternate-versions:
        - dev
        - legacy
        - v1
      x-cached-seconds: 3600