openapi: 3.0.0
servers:
  - description: The Xero Accounting API exposes accounting and related functions of the main Xero application and can be used for a variety of purposes such as creating transactions like invoices and credit notes, right through to extracting accounting data via our reports endpoint.
    url: https://api.xero.com/api.xro/2.0
x-hasEquivalentPaths: true
info:
  contact:
    email: api@xero.com
    name: Xero Platform Team
    url: https://developer.xero.com
    x-twitter: XeroAPI
  termsOfService: https://developer.xero.com/xero-developer-platform-terms-conditions/
  title: Xero Accounting API
  version: 2.9.4
  x-apisguru-categories:
    - financial
  x-origin:
    - format: openapi
      url: https://raw.githubusercontent.com/XeroAPI/Xero-OpenAPI/master/xero_accounting.yaml
      version: "3.0"
  x-providerName: xero.com
  x-serviceName: xero_accounting
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_apis.guru_assets_images_no-logo.svg
paths:
  /Accounts:
    get:
      operationId: getAccounts
      security:
        - OAuth2:
            - accounting.settings
      summary: Retrieves the full chart of accounts
      tags:
        - Accounting
    put:
      operationId: createAccount
      security:
        - OAuth2:
            - accounting.settings
      summary: Creates a new chart of accounts
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ code: "123456", name: "Foobar", type: AccountType.EXPENSE, description: "Hello World" }'
      x-ruby-requestBody: 'account = { code: "123456", name: "Foobar", type: XeroRuby::Accounting::AccountType::EXPENSE, description: "Hello World" }'
  "/Accounts/{AccountID}":
    delete:
      operationId: deleteAccount
      security:
        - OAuth2:
            - accounting.settings
      summary: Deletes a chart of accounts
      tags:
        - Accounting
      x-hasAccountingValidationError: true
    get:
      operationId: getAccount
      security:
        - OAuth2:
            - accounting.settings
      summary: Retrieves a single chart of accounts by using a unique account Id
      tags:
        - Accounting
    post:
      operationId: updateAccount
      security:
        - OAuth2:
            - accounting.settings
      summary: Updates a chart of accounts
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ accounts: [{ code: "123456", name: "BarFoo", accountID: "00000000-0000-0000-0000-000000000000", type: AccountType.EXPENSE, description: "GoodBye World", taxType: TaxType.INPUT }]}'
      x-ruby-requestBody: '{ accounts: [{ code: "123456", name: "BarFoo", account_id: "00000000-0000-0000-0000-000000000000", type: XeroRuby::Accounting::Account::EXPENSE, description: "GoodBye World", tax_type: XeroRuby::Accounting::TaxType::NONE }]}'
  "/Accounts/{AccountID}/Attachments":
    get:
      operationId: getAccountAttachments
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves attachments for a specific accounts by using a unique account Id
      tags:
        - Accounting
  "/Accounts/{AccountID}/Attachments/{AttachmentID}":
    get:
      operationId: getAccountAttachmentById
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves a specific attachment from a specific account using a unique attachment Id
      tags:
        - Accounting
  "/Accounts/{AccountID}/Attachments/{FileName}":
    get:
      operationId: getAccountAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves an attachment for a specific account by filename
      tags:
        - Accounting
    post:
      operationId: updateAccountAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments
      summary: Updates attachment on a specific account by filename
      tags:
        - Accounting
      x-hasAccountingValidationError: true
    put:
      operationId: createAccountAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments
      summary: Creates an attachment on a specific account
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  /BankTransactions:
    get:
      operationId: getBankTransactions
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves any spent or received money transactions
      tags:
        - Accounting
    post:
      operationId: updateOrCreateBankTransactions
      security:
        - OAuth2:
            - accounting.transactions
      summary: Updates or creates one or more spent or received money transaction
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ bankTransactions: [{ type: BankTransaction.TypeEnum.SPEND, contact: { contactId: "00000000-0000-0000-0000-000000000000" }, lineItems: [{ description: "Foobar", quantity: 1.0, unitAmount: 20.0, accountCode: "000" }], bankAccount: { code: "000" }}]}'
      x-ruby-requestBody: 'bank_transactions = { bank_transactions: [{ type: XeroRuby::Accounting::BankTransaction::SPEND, contact: { contact_id: "00000000-0000-0000-0000-000000000000" }, line_items: [{ description: "Foobar", quantity: 1.0, unit_amount: 20.0, account_code: "000" }], bank_account: { code: "000" }}]}'
    put:
      operationId: createBankTransactions
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates one or more spent or received money transaction
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ bankTransactions: [{ type: BankTransaction.TypeEnum.SPEND, contact: { contactID: "00000000-0000-0000-0000-000000000000" }, lineItems: [{ description: "Foobar", quantity: 1.0, unitAmount: 20.0, accountCode: "000" } ], bankAccount: { code: "000" }}]}'
      x-ruby-requestBody: 'bank_transactions = { bank_transactions: [{ type: XeroRuby::Accounting::BankTransaction::SPEND, contact: { contact_id: "00000000-0000-0000-0000-000000000000" }, line_items: [{ description: "Foobar", quantity: 1.0, unit_amount: 20.0, account_code: "000" } ], bank_account: { code: "000" }}]}'
  "/BankTransactions/{BankTransactionID}":
    get:
      operationId: getBankTransaction
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves a single spent or received money transaction by using a unique bank transaction Id
      tags:
        - Accounting
    post:
      operationId: updateBankTransaction
      security:
        - OAuth2:
            - accounting.transactions
      summary: Updates a single spent or received money transaction
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ bankTransactions: [{ type: BankTransaction.TypeEnum.SPEND, date: "2019-02-25", reference: "You just updated", status: BankTransaction.StatusEnum.AUTHORISED, bankTransactionID: "00000000-0000-0000-0000-000000000000", lineItems: [], contact: {}, bankAccount: { accountID: "00000000-0000-0000-0000-000000000000" }}]}'
      x-ruby-requestBody: '{ bank_transactions: [{ type: XeroRuby::Accounting::BankTransaction::SPEND, date: "2019-02-25", reference: "You just updated", status: XeroRuby::Accounting::BankTransaction::AUTHORISED, bank_transaction_id: "00000000-0000-0000-0000-000000000000", line_items: [], contact: {}, bank_account: { account_id: "00000000-0000-0000-0000-000000000000" }}]}'
  "/BankTransactions/{BankTransactionID}/Attachments":
    get:
      operationId: getBankTransactionAttachments
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves any attachments from a specific bank transactions
      tags:
        - Accounting
  "/BankTransactions/{BankTransactionID}/Attachments/{AttachmentID}":
    get:
      operationId: getBankTransactionAttachmentById
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves specific attachments from a specific BankTransaction using a unique attachment Id
      tags:
        - Accounting
  "/BankTransactions/{BankTransactionID}/Attachments/{FileName}":
    get:
      operationId: getBankTransactionAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves a specific attachment from a specific bank transaction by filename
      tags:
        - Accounting
    post:
      operationId: updateBankTransactionAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments
      summary: Updates a specific attachment from a specific bank transaction by filename
      tags:
        - Accounting
      x-hasAccountingValidationError: true
    put:
      operationId: createBankTransactionAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments
      summary: Creates an attachment for a specific bank transaction by filename
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  "/BankTransactions/{BankTransactionID}/History":
    get:
      operationId: getBankTransactionsHistory
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves history from a specific bank transaction using a unique bank transaction Id
      tags:
        - Accounting
    put:
      operationId: createBankTransactionHistoryRecord
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates a history record for a specific bank transactions
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  /BankTransfers:
    get:
      operationId: getBankTransfers
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves all bank transfers
      tags:
        - Accounting
    put:
      operationId: createBankTransfer
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates a bank transfer
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ bankTransfers: [{ fromBankAccount: { code: "000", accountID: "00000000-0000-0000-0000-000000000000" }, toBankAccount: { code: "001", accountID: "00000000-0000-0000-0000-000000000000" }, amount: "50.00" }]}'
      x-ruby-requestBody: 'bank_transfers = { bank_transfers: [{ from_bank_account: { code: "000", account_id: "00000000-0000-0000-0000-000000000000" }, to_bank_account: { code: "001", account_id: "00000000-0000-0000-0000-000000000000" }, amount: "50.00" }]}'
  "/BankTransfers/{BankTransferID}":
    get:
      operationId: getBankTransfer
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves specific bank transfers by using a unique bank transfer Id
      tags:
        - Accounting
  "/BankTransfers/{BankTransferID}/Attachments":
    get:
      operationId: getBankTransferAttachments
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves attachments from a specific bank transfer
      tags:
        - Accounting
  "/BankTransfers/{BankTransferID}/Attachments/{AttachmentID}":
    get:
      operationId: getBankTransferAttachmentById
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves a specific attachment from a specific bank transfer using a unique attachment ID
      tags:
        - Accounting
  "/BankTransfers/{BankTransferID}/Attachments/{FileName}":
    get:
      operationId: getBankTransferAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves a specific attachment on a specific bank transfer by file name
      tags:
        - Accounting
    post:
      operationId: updateBankTransferAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      x-hasAccountingValidationError: true
    put:
      operationId: createBankTransferAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  "/BankTransfers/{BankTransferID}/History":
    get:
      operationId: getBankTransferHistory
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves history from a specific bank transfer using a unique bank transfer Id
      tags:
        - Accounting
    put:
      operationId: createBankTransferHistoryRecord
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates a history record for a specific bank transfer
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  /BatchPayments:
    description: Batch payments allow you to bundle multiple bills or invoices into one payment transaction. This means a single payment in Xero can be reconciled with a single transaction on the bank statement making for a much simpler bank reconciliation experience.
    get:
      operationId: getBatchPayments
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves either one or many batch payments for invoices
      tags:
        - Accounting
    put:
      operationId: createBatchPayment
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates one or many batch payments for invoices
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ batchPayments: [{ account: { accountId: "00000000-0000-0000-0000-000000000000" }, reference: "ref", date: "2018-08-01", payments: [{  account: { code: "001" }, date: "2019-12-31", amount: 500, invoice: { invoiceId: "00000000-0000-0000-0000-000000000000", lineItems: [], contact: {}, type: Invoice.TypeEnum.ACCPAY }}]}]}'
      x-ruby-requestBody: 'batch_payments = { batch_payments: [{ account: { account_id: "00000000-0000-0000-0000-000000000000" }, reference: "ref", date: "2018-08-01", payments: [{  account: { code: "001" }, date: "2019-12-31", amount: 500, invoice: { invoice_id: "00000000-0000-0000-0000-000000000000", line_items: [], contact: {}, type: XeroRuby::Accounting::Invoice::ACCPAY }}]}]}'
  "/BatchPayments/{BatchPaymentID}/History":
    get:
      operationId: getBatchPaymentHistory
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves history from a specific batch payment
      tags:
        - Accounting
    put:
      operationId: createBatchPaymentHistoryRecord
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates a history record for a specific batch payment
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  /BrandingThemes:
    get:
      operationId: getBrandingThemes
      security:
        - OAuth2:
            - accounting.settings.read
      summary: Retrieves all the branding themes
      tags:
        - Accounting
  "/BrandingThemes/{BrandingThemeID}":
    get:
      operationId: getBrandingTheme
      security:
        - OAuth2:
            - accounting.settings.read
      summary: Retrieves a specific branding theme using a unique branding theme Id
      tags:
        - Accounting
  "/BrandingThemes/{BrandingThemeID}/PaymentServices":
    get:
      operationId: getBrandingThemePaymentServices
      security:
        - OAuth2:
            - paymentservices
      summary: Retrieves the payment services for a specific branding theme
      tags:
        - Accounting
    post:
      operationId: createBrandingThemePaymentServices
      security:
        - OAuth2:
            - paymentservices
      summary: Creates a new custom payment service for a specific branding theme
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ paymentServiceID: "00000000-0000-0000-0000-000000000000", paymentServiceName: "ACME Payments", paymentServiceUrl: "https://www.payupnow.com/", payNowText: "Pay Now" }'
      x-ruby-requestBody: 'payment_service = { payment_service_id: "00000000-0000-0000-0000-000000000000", payment_service_name: "ACME Payments", payment_service_url: "https://www.payupnow.com/", pay_now_text: "Pay Now" }'
  /ContactGroups:
    get:
      operationId: getContactGroups
      security:
        - OAuth2:
            - accounting.contacts.read
      summary: Retrieves the contact Id and name of all the contacts in a contact group
      tags:
        - Accounting
    put:
      operationId: createContactGroup
      security:
        - OAuth2:
            - accounting.contacts
      summary: Creates a contact group
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ contactGroups: [{ name: "VIPs" }]}'
      x-ruby-requestBody: 'contact_groups = { contact_groups: [{ name: "VIPs" }]}'
  "/ContactGroups/{ContactGroupID}":
    get:
      operationId: getContactGroup
      security:
        - OAuth2:
            - accounting.contacts.read
      summary: Retrieves a specific contact group by using a unique contact group Id
      tags:
        - Accounting
    post:
      operationId: updateContactGroup
      security:
        - OAuth2:
            - accounting.contacts
      summary: Updates a specific contact group
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ contactGroups: [{ name: "Vendor" }]}'
      x-ruby-requestBody: 'contact_groups = { contact_groups: [{ name: "Vendor" }]}'
  "/ContactGroups/{ContactGroupID}/Contacts":
    delete:
      operationId: deleteContactGroupContacts
      security:
        - OAuth2:
            - accounting.contacts
      summary: Deletes all contacts from a specific contact group
      tags:
        - Accounting
    put:
      operationId: createContactGroupContacts
      security:
        - OAuth2:
            - accounting.contacts
      summary: Creates contacts to a specific contact group
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ contacts: [{ contactID: "a3675fc4-f8dd-4f03-ba5b-f1870566bcd7" }, { contactID: "4e1753b9-018a-4775-b6aa-1bc7871cfee3" }]}'
      x-ruby-requestBody: 'contacts = { contacts: [{ contact_id: "a3675fc4-f8dd-4f03-ba5b-f1870566bcd7" }, { contact_id: "4e1753b9-018a-4775-b6aa-1bc7871cfee3" }]}'
  "/ContactGroups/{ContactGroupID}/Contacts/{ContactID}":
    delete:
      operationId: deleteContactGroupContact
      security:
        - OAuth2:
            - accounting.contacts
      summary: Deletes a specific contact from a contact group using a unique contact Id
      tags:
        - Accounting
  /Contacts:
    get:
      operationId: getContacts
      security:
        - OAuth2:
            - accounting.contacts.read
      summary: Retrieves all contacts in a Xero organisation
      tags:
        - Accounting
    post:
      operationId: updateOrCreateContacts
      security:
        - OAuth2:
            - accounting.contacts
      summary: Updates or creates one or more contacts in a Xero organisation
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ contacts: [{ name: "Bruce Banner", emailAddress: "hulk@avengers.com", phones: [{ phoneType: Phone.PhoneTypeEnum.MOBILE, phoneNumber: "555-1212", phoneAreaCode: "415" }], paymentTerms: { bills: { day: 15, type: PaymentTermType.OFCURRENTMONTH }, sales: { day: 10, type: PaymentTermType.DAYSAFTERBILLMONTH }}}]}'
      x-ruby-requestBody: '{ contacts: [{ name: "Bruce Banner", email_address: "hulk@avengers.com", phones: [{ phone_type: XeroRuby::Accounting::Phone::MOBILE, phone_number: "555-1212", phone_area_code: "415" }], payment_terms: { bills: { day: 15, type: XeroRuby::Accounting::PaymentTermType::OFCURRENTMONTH }, sales: { day: 10, type: XeroRuby::Accounting::PaymentTermType::OFCURRENTMONTHDAYSAFTERBILLMONTH }}}]}'
    put:
      operationId: createContacts
      security:
        - OAuth2:
            - accounting.contacts
      summary: Creates multiple contacts (bulk) in a Xero organisation
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ contacts: [{ name: "Bruce Banner", emailAddress: "hulk@avengers.com", phones: [{ phoneType: Phone.PhoneTypeEnum.MOBILE, phoneNumber: "555-1212", phoneAreaCode: "415" }], paymentTerms: { bills: { day: 15, type: PaymentTermType.OFCURRENTMONTH }, sales: { day: 10, type: PaymentTermType.DAYSAFTERBILLMONTH }}}]}'
      x-ruby-requestBody: 'contacts = { contacts: [{ name: "Bruce Banner", email_address: "hulk@avengers.com", phones: [{ phone_type: XeroRuby::Accounting::Phone::MOBILE, phone_number: "555-1212", phone_area_code: "415" }], payment_terms: { bills: { day: 15, type: XeroRuby::Accounting::PaymentTermType::OFCURRENTMONTH }, sales: { day: 10, type: XeroRuby::Accounting::PaymentTermType::DAYSAFTERBILLMONTH }}}]}'
  "/Contacts/{ContactID}":
    get:
      operationId: getContact
      security:
        - OAuth2:
            - accounting.contacts.read
      summary: Retrieves a specific contacts in a Xero organisation using a unique contact Id
      tags:
        - Accounting
    post:
      operationId: updateContact
      security:
        - OAuth2:
            - accounting.contacts
      summary: Updates a specific contact in a Xero organisation
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ contacts: [{ contactID: "00000000-0000-0000-0000-000000000000", name: "Thanos" }]}'
      x-ruby-requestBody: 'contacts = { contacts: [{ contact_id: "00000000-0000-0000-0000-000000000000", name: "Thanos" }]}'
  "/Contacts/{ContactID}/Attachments":
    get:
      operationId: getContactAttachments
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves attachments for a specific contact in a Xero organisation
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  "/Contacts/{ContactID}/Attachments/{AttachmentID}":
    get:
      operationId: getContactAttachmentById
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves a specific attachment from a specific contact using a unique attachment Id
      tags:
        - Accounting
  "/Contacts/{ContactID}/Attachments/{FileName}":
    get:
      operationId: getContactAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves a specific attachment from a specific contact by file name
      tags:
        - Accounting
    post:
      operationId: updateContactAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      x-hasAccountingValidationError: true
    put:
      operationId: createContactAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  "/Contacts/{ContactID}/CISSettings":
    get:
      operationId: getContactCISSettings
      security:
        - OAuth2:
            - accounting.contacts.read
      summary: Retrieves CIS settings for a specific contact in a Xero organisation
      tags:
        - Accounting
  "/Contacts/{ContactID}/History":
    get:
      operationId: getContactHistory
      security:
        - OAuth2:
            - accounting.contacts.read
      summary: Retrieves history records for a specific contact
      tags:
        - Accounting
    put:
      operationId: createContactHistory
      security:
        - OAuth2:
            - accounting.contacts
      summary: Creates a new history record for a specific contact
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  "/Contacts/{ContactNumber}":
    get:
      operationId: getContactByContactNumber
      security:
        - OAuth2:
            - accounting.contacts.read
      summary: Retrieves a specific contact by contact number in a Xero organisation
      tags:
        - Accounting
  /CreditNotes:
    get:
      operationId: getCreditNotes
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves any credit notes
      tags:
        - Accounting
    post:
      operationId: updateOrCreateCreditNotes
      security:
        - OAuth2:
            - accounting.transactions
      summary: Updates or creates one or more credit notes
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ creditNotes: [{ type: CreditNote.TypeEnum.ACCPAYCREDIT, contact: { contactID: "00000000-0000-0000-0000-000000000000" }, date: "2019-01-05", lineItems: [{ description: "Foobar", quantity: 2.0, unitAmount: 20.0, accountCode: "400" }]}]}'
      x-ruby-requestBody: 'credit_notes = { credit_notes: [{ type: XeroRuby::Accounting::CreditNote::ACCPAYCREDIT, contact: { contact_id: "00000000-0000-0000-0000-000000000000" }, date: "2019-01-05", line_items: [{ description: "Foobar", quantity: 2.0, unit_amount: 20.0, account_code: "400" }]}]}'
    put:
      operationId: createCreditNotes
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates a new credit note
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ creditNotes: [{ type: CreditNote.TypeEnum.ACCPAYCREDIT, contact: { contactID: "430fa14a-f945-44d3-9f97-5df5e28441b8" }, date: "2019-01-05", lineItems: [{ description: "Foobar", quantity: 2.0, unitAmount: 20.0, accountCode: "400" }]}]}'
      x-ruby-requestBody: 'credit_notes = { credit_notes: [{ type: XeroRuby::Accounting::CreditNote::ACCPAYCREDIT, contact: { contact_id: "430fa14a-f945-44d3-9f97-5df5e28441b8" }, date: "2019-01-05", line_items: [{ description: "Foobar", quantity: 2.0, unit_amount: 20.0, account_code: "400" }]}]}'
  "/CreditNotes/{CreditNoteID}":
    get:
      operationId: getCreditNote
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves a specific credit note using a unique credit note Id
      tags:
        - Accounting
    post:
      operationId: updateCreditNote
      security:
        - OAuth2:
            - accounting.transactions
      summary: Updates a specific credit note
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ creditNotes: [{ type: CreditNote.TypeEnum.ACCPAYCREDIT, contact: { contactID: "00000000-0000-0000-0000-000000000000" }, date: "2019-01-05", status: CreditNote.StatusEnum.AUTHORISED, reference: "Mind stone", lineItems: [{ description: "Infinity Stones", quantity: 1.0, unitAmount: 100.0, accountCode: "400" } ]}]}'
      x-ruby-requestBody: 'credit_notes = { credit_notes: [{ type: XeroRuby::Accounting::CreditNote::ACCPAYCREDIT, contact: { contact_id: "00000000-0000-0000-0000-000000000000" }, date: "2019-01-05", status: XeroRuby::Accounting::CreditNote::AUTHORISED, reference: "Mind stone", line_items: [{ description: "Infinity Stones", quantity: 1.0, unit_amount: 100.0, account_code: "400" } ]}]}'
  "/CreditNotes/{CreditNoteID}/Allocations":
    put:
      operationId: createCreditNoteAllocation
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates allocation for a specific credit note
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ allocations: [{ amount: 1.0, date: "2019-03-05", invoice: { invoiceID: "c45720a1-ade3-4a38-a064-d15489be6841", lineItems: [], type: Invoice.TypeEnum.ACCPAY, contact: {} }}]}'
      x-ruby-requestBody: 'allocations = { allocations: [{ amount: 1.0, date: "2019-03-05", invoice: { invoice_id: "c45720a1-ade3-4a38-a064-d15489be6841", line_items: [], type: XeroRuby::Accounting::Invoice::ACCPAY, contact: {} }}]}'
  "/CreditNotes/{CreditNoteID}/Attachments":
    get:
      operationId: getCreditNoteAttachments
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves attachments for a specific credit notes
      tags:
        - Accounting
  "/CreditNotes/{CreditNoteID}/Attachments/{AttachmentID}":
    get:
      operationId: getCreditNoteAttachmentById
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves a specific attachment from a specific credit note using a unique attachment Id
      tags:
        - Accounting
  "/CreditNotes/{CreditNoteID}/Attachments/{FileName}":
    get:
      operationId: getCreditNoteAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves a specific attachment on a specific credit note by file name
      tags:
        - Accounting
    post:
      operationId: updateCreditNoteAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments
      summary: Updates attachments on a specific credit note by file name
      tags:
        - Accounting
      x-hasAccountingValidationError: true
    put:
      operationId: createCreditNoteAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments
      summary: Creates an attachment for a specific credit note
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  "/CreditNotes/{CreditNoteID}/History":
    get:
      operationId: getCreditNoteHistory
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves history records of a specific credit note
      tags:
        - Accounting
    put:
      operationId: createCreditNoteHistory
      security:
        - OAuth2:
            - accounting.transactions
      summary: Retrieves history records of a specific credit note
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  "/CreditNotes/{CreditNoteID}/pdf":
    get:
      operationId: getCreditNoteAsPdf
      security:
        - OAuth2:
            - accounting.transactions
      summary: Retrieves credit notes as PDF files
      tags:
        - Accounting
      x-path: /CreditNotes/{CreditNoteID}
  /Currencies:
    get:
      operationId: getCurrencies
      security:
        - OAuth2:
            - accounting.settings.read
      summary: Retrieves currencies for your Xero organisation
      tags:
        - Accounting
    put:
      operationId: createCurrency
      security:
        - OAuth2:
            - accounting.settings
      summary: Create a new currency for a Xero organisation
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ code: CurrencyCode.USD, description: "United States Dollar" }'
      x-ruby-requestBody: 'currency = { code: XeroRuby::Accounting::CurrencyCode::USD, description: "United States Dollar" }'
  /Employees:
    get:
      operationId: getEmployees
      security:
        - OAuth2:
            - accounting.settings.read
      summary: Retrieves employees used in Xero payrun
      tags:
        - Accounting
    post:
      operationId: updateOrCreateEmployees
      security:
        - OAuth2:
            - accounting.settings
      summary: Creates a single new employees used in Xero payrun
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ employees: [{ firstName: "Nick", lastName: "Fury", externalLink: { url: "http://twitter.com/#!/search/Nick+Fury" }}]}'
      x-ruby-requestBody: 'employees = { employees: [{ first_name: "Nick", last_name: "Fury", external_link: { url: "http://twitter.com/#!/search/Nick+Fury" }}]}'
    put:
      operationId: createEmployees
      security:
        - OAuth2:
            - accounting.settings
      summary: Creates new employees used in Xero payrun
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ employees: [{ firstName: "Nick", lastName: "Fury", externalLink: { url: "http://twitter.com/#!/search/Nick+Fury" }}]}'
      x-ruby-requestBody: 'employees = { employees: [{ first_name: "Nick", last_name: "Fury", externallink: { url: "http://twitter.com/#!/search/Nick+Fury" }}]}'
  "/Employees/{EmployeeID}":
    get:
      operationId: getEmployee
      security:
        - OAuth2:
            - accounting.settings.read
      summary: Retrieves a specific employee used in Xero payrun using a unique employee Id
      tags:
        - Accounting
  /ExpenseClaims:
    get:
      operationId: getExpenseClaims
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves expense claims
      tags:
        - Accounting
    put:
      operationId: createExpenseClaims
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates expense claims
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ expenseClaims: [{ status: ExpenseClaim.StatusEnum.SUBMITTED, user: { userID: "d1164823-0ac1-41ad-987b-b4e30fe0b273" }, receipts: [{ receiptID: "dc1c7f6d-0a4c-402f-acac-551d62ce5816", lineItems: [], contact: {}, user: {}, date: "2018-01-01" }]}]}'
      x-ruby-requestBody: 'expense_claims = { expense_claims: [{ status: XeroRuby::Accounting::ExpenseClaim::SUBMITTED, user: { user_id: "d1164823-0ac1-41ad-987b-b4e30fe0b273" }, receipts: [{ receipt_id: "dc1c7f6d-0a4c-402f-acac-551d62ce5816", line_items: [], contact: {}, user: {}, date: "2018-01-01" }]}]}'
  "/ExpenseClaims/{ExpenseClaimID}":
    get:
      operationId: getExpenseClaim
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves a specific expense claim using a unique expense claim Id
      tags:
        - Accounting
    post:
      operationId: updateExpenseClaim
      security:
        - OAuth2:
            - accounting.transactions
      summary: Updates a specific expense claims
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ expenseClaims: [{ status: ExpenseClaim.StatusEnum.AUTHORISED, user: { userID: "00000000-0000-0000-0000-000000000000" }, receipts: [{ receiptID: "00000000-0000-0000-0000-000000000000", lineItems: [], contact: {}, date: "2020-01-01", user: {} }]}]}'
      x-ruby-requestBody: 'expense_claims = { expense_claims: [{ status: XeroRuby::Accounting::ExpenseClaim::AUTHORISED, user: { user_id: "00000000-0000-0000-0000-000000000000" }, receipts: [{ receipt_id: "00000000-0000-0000-0000-000000000000", line_items: [], contact: {}, date: "2020-01-01", user: {} }]}]}'
  "/ExpenseClaims/{ExpenseClaimID}/History":
    get:
      operationId: getExpenseClaimHistory
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves history records of a specific expense claim
      tags:
        - Accounting
    put:
      operationId: createExpenseClaimHistory
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates a history record for a specific expense claim
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  /InvoiceReminders/Settings:
    get:
      operationId: getInvoiceReminders
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves invoice reminder settings
      tags:
        - Accounting
  /Invoices:
    get:
      operationId: getInvoices
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves sales invoices or purchase bills
      tags:
        - Accounting
    post:
      operationId: updateOrCreateInvoices
      security:
        - OAuth2:
            - accounting.transactions
      summary: Updates or creates one or more sales invoices or purchase bills
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ invoices: [{ type: Invoice.TypeEnum.ACCREC, contact: { contactID:"00000000-0000-0000-0000-000000000000" }, lineItems:[ { description:"Acme Tires", quantity:2.0, unitAmount:20.0, accountCode:"200", taxType:"NONE", lineAmount:40.0 } ], date: "2019-03-11", dueDate:"2018-12-10", reference:"Website Design", status: Invoice.StatusEnum.AUTHORISED } ] }'
      x-ruby-requestBody: 'invoices = { invoices: [{ type: XeroRuby::Accounting::Invoice::ACCREC, contact: { contact_id: "00000000-0000-0000-0000-000000000000" }, line_items: [{ description: "Acme Tires", quantity: 2.0, unit_amount: 20.0, account_code: "000", tax_type: XeroRuby::Accounting::TaxType::NONE, line_amount: 40.0 }], date: "2019-03-11", due_date: "2018-12-10", reference: "Website Design", status: XeroRuby::Accounting::Invoice::DRAFT }]}'
    put:
      operationId: createInvoices
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates one or more sales invoices or purchase bills
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ invoices: [{ type: Invoice.TypeEnum.ACCREC, contact: { contactID: "00000000-0000-0000-0000-000000000000" }, lineItems: [{ description: "Acme Tires", quantity: 2.0, unitAmount: 20.0, accountCode: "000", taxType: TaxType.NONE, lineAmount: 40.0 }], date: "2019-03-11", dueDate: "2018-12-10", reference: "Website Design", status: Invoice.StatusEnum.DRAFT }]}'
      x-ruby-requestBody: 'invoices = { invoices: [{ type: XeroRuby::Accounting::Invoice::ACCREC, contact: { contact_id: "00000000-0000-0000-0000-000000000000" }, line_items: [{ description: "Acme Tires", quantity: 2.0, unit_amount: 20.0, account_code: "000", tax_type: XeroRuby::Accounting::TaxType::NONE, line_amount: 40.0 }], date: "2019-03-11", due_date: "2018-12-10", reference: "Website Design", status: XeroRuby::Accounting::Invoice::DRAFT }]}'
  "/Invoices/{InvoiceID}":
    get:
      operationId: getInvoice
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves a specific sales invoice or purchase bill using a unique invoice Id
      tags:
        - Accounting
    post:
      operationId: updateInvoice
      security:
        - OAuth2:
            - accounting.transactions
      summary: Updates a specific sales invoices or purchase bills
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ invoices: [{ reference: "I am Iron Man", invoiceID: "00000000-0000-0000-0000-000000000000", lineItems: [], contact: {}, type: Invoice.TypeEnum.ACCPAY }]}'
      x-ruby-requestBody: 'invoices = { invoices: [{ reference: "I am Iron Man", invoice_id: "00000000-0000-0000-0000-000000000000", line_items: [], contact: {}, type: XeroRuby::Accounting::Invoice::ACCPAY }]}'
  "/Invoices/{InvoiceID}/Attachments":
    get:
      operationId: getInvoiceAttachments
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves attachments for a specific invoice or purchase bill
      tags:
        - Accounting
  "/Invoices/{InvoiceID}/Attachments/{AttachmentID}":
    get:
      operationId: getInvoiceAttachmentById
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves a specific attachment from a specific invoices or purchase bills by using a unique attachment Id
      tags:
        - Accounting
  "/Invoices/{InvoiceID}/Attachments/{FileName}":
    get:
      operationId: getInvoiceAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves an attachment from a specific invoice or purchase bill by filename
      tags:
        - Accounting
    post:
      operationId: updateInvoiceAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments
      summary: Updates an attachment from a specific invoices or purchase bill by filename
      tags:
        - Accounting
      x-hasAccountingValidationError: true
    put:
      operationId: createInvoiceAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments
      summary: Creates an attachment for a specific invoice or purchase bill by filename
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  "/Invoices/{InvoiceID}/Email":
    post:
      operationId: emailInvoice
      security:
        - OAuth2:
            - accounting.transactions
      summary: Sends a copy of a specific invoice to related contact via email
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  "/Invoices/{InvoiceID}/History":
    get:
      operationId: getInvoiceHistory
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves history records for a specific invoice
      tags:
        - Accounting
    put:
      operationId: createInvoiceHistory
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates a history record for a specific invoice
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  "/Invoices/{InvoiceID}/OnlineInvoice":
    get:
      operationId: getOnlineInvoice
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves a URL to an online invoice
      tags:
        - Accounting
  "/Invoices/{InvoiceID}/pdf":
    get:
      operationId: getInvoiceAsPdf
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves invoices or purchase bills as PDF files
      tags:
        - Accounting
      x-path: /Invoices/{InvoiceID}
  /Items:
    get:
      operationId: getItems
      security:
        - OAuth2:
            - accounting.settings.read
      summary: Retrieves items
      tags:
        - Accounting
    post:
      operationId: updateOrCreateItems
      security:
        - OAuth2:
            - accounting.settings
      summary: Updates or creates one or more items
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ items: [{ code: "ItemCode123", name: "ItemName XYZ", description: "Item Description ABC" }]}'
      x-ruby-requestBody: 'items = { items: [{ code: "ItemCode123", name: "ItemName XYZ", description: "Item Description ABC" }]}'
    put:
      operationId: createItems
      security:
        - OAuth2:
            - accounting.settings
      summary: Creates one or more items
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ items: [{ code: "abcXYZ123", name: "HelloWorld11", description: "Foobar", inventoryAssetAccountCode: "140", purchaseDetails: { cOGSAccountCode: "500" }}]}'
      x-ruby-requestBody: 'items = { items: [{ code: "abcXYZ123", name: "HelloWorld11", description: "Foobar", inventory_asset_account_code: "140", purchase_details: { cogs_account_code: "500" }}]}'
  "/Items/{ItemID}":
    delete:
      operationId: deleteItem
      security:
        - OAuth2:
            - accounting.settings
      summary: Deletes a specific item
      tags:
        - Accounting
    get:
      operationId: getItem
      security:
        - OAuth2:
            - accounting.settings.read
      summary: Retrieves a specific item using a unique item Id
      tags:
        - Accounting
    post:
      operationId: updateItem
      security:
        - OAuth2:
            - accounting.settings
      summary: Updates a specific item
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ items: [{ code: "ItemCode123", description: "Description 123" }]}'
      x-ruby-requestBody: 'items = { items: [{ code: "ItemCode123", description: "Description 123" }]}'
  "/Items/{ItemID}/History":
    get:
      operationId: getItemHistory
      security:
        - OAuth2:
            - accounting.settings.read
      summary: Retrieves history for a specific item
      tags:
        - Accounting
    put:
      operationId: createItemHistory
      security:
        - OAuth2:
            - accounting.settings
      summary: Creates a history record for a specific item
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  /Journals:
    get:
      operationId: getJournals
      security:
        - OAuth2:
            - accounting.journals.read
      summary: Retrieves journals
      tags:
        - Accounting
  "/Journals/{JournalID}":
    get:
      operationId: getJournal
      security:
        - OAuth2:
            - accounting.journals.read
      summary: Retrieves a specific journal using a unique journal Id.
      tags:
        - Accounting
  /LinkedTransactions:
    get:
      operationId: getLinkedTransactions
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves linked transactions (billable expenses)
      tags:
        - Accounting
    put:
      operationId: createLinkedTransaction
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates linked transactions (billable expenses)
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ sourceTransactionID: "00000000-0000-0000-0000-000000000000", sourceLineItemID: "00000000-0000-0000-0000-000000000000" }'
      x-ruby-requestBody: 'linked_transaction = { source_transaction_id: "00000000-0000-0000-0000-000000000000", source_line_item_id: "00000000-0000-0000-0000-000000000000" }'
  "/LinkedTransactions/{LinkedTransactionID}":
    delete:
      operationId: deleteLinkedTransaction
      security:
        - OAuth2:
            - accounting.transactions
      summary: Deletes a specific linked transactions (billable expenses)
      tags:
        - Accounting
    get:
      operationId: getLinkedTransaction
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves a specific linked transaction (billable expenses) using a unique linked transaction Id
      tags:
        - Accounting
    post:
      operationId: updateLinkedTransaction
      security:
        - OAuth2:
            - accounting.transactions
      summary: Updates a specific linked transactions (billable expenses)
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ linkedTransactions: [{ sourceLineItemID: "00000000-0000-0000-0000-000000000000", contactID: "00000000-0000-0000-0000-000000000000" }]}'
      x-ruby-requestBody: 'linked_transactions = { linked_transactions: [{ source_line_item_id: "00000000-0000-0000-0000-000000000000", contact_id: "00000000-0000-0000-0000-000000000000" }]}'
  /ManualJournals:
    get:
      operationId: getManualJournals
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves manual journals
      tags:
        - Accounting
    post:
      operationId: updateOrCreateManualJournals
      security:
        - OAuth2:
            - accounting.transactions
      summary: Updates or creates a single manual journal
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ manualJournals: [{ narration: "Foo bar", journalLines: [{ lineAmount: 100.0, accountCode: "400", description: "Hello there" },{ lineAmount: -100.0, accountCode: "400", description: "Goodbye", tracking: [{ name: "Simpsons", option: "Bart" }]}], date: "2019-03-14" }]}'
      x-ruby-requestBody: 'manual_journals = { manual_journals: [{ narration: "Foo bar", date: "2019-03-14", journal_lines: [{ line_amount: 100.0, account_code: "400", description: "Hello there" },{ line_amount: -100.0, account_code: "400", description: "Goodbye", tracking: [{ name: "Simpsons", option: "Bart" }]}] }]}'
    put:
      operationId: createManualJournals
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates one or more manual journals
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ manualJournals: [{ narration: "Foo bar", date: "2019-03-14", journalLines: [{ lineAmount: 100.0, accountCode: "400", description: "Hello there" }, { lineAmount: -100.0, accountCode: "400", description: "Goodbye", tracking: [{ name: "Simpson", option: "Bart" }] }]}]}'
      x-ruby-requestBody: 'manual_journals = { manual_journals: [{ narration: "Foo bar", date: "2019-03-14", journal_lines: [{ line_amount: 100.0, account_code: "400", description: "Hello there" }, { line_amount: -100.0, account_code: "400", description: "Goodbye", tracking: [{ name: "Simpson", option: "Bart" }] }]}]}'
  "/ManualJournals/{ManualJournalID}":
    get:
      operationId: getManualJournal
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves a specific manual journal
      tags:
        - Accounting
    post:
      operationId: updateManualJournal
      security:
        - OAuth2:
            - accounting.transactions
      summary: Updates a specific manual journal
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ manualJournals: [{ narration: "Hello Xero", manualJournalId: "00000000-0000-0000-0000-000000000000", journalLines: [] }]}'
      x-ruby-requestBody: 'manual_journals = { manual_journals: [{ narration: "Hello Xero", manual_journal_id: "00000000-0000-0000-0000-000000000000", journal_lines: [] }]}'
  "/ManualJournals/{ManualJournalID}/Attachments":
    get:
      operationId: getManualJournalAttachments
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves attachment for a specific manual journal
      tags:
        - Accounting
  "/ManualJournals/{ManualJournalID}/Attachments/{AttachmentID}":
    get:
      operationId: getManualJournalAttachmentById
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Allows you to retrieve a specific attachment from a specific manual journal using a unique attachment Id
      tags:
        - Accounting
  "/ManualJournals/{ManualJournalID}/Attachments/{FileName}":
    get:
      operationId: getManualJournalAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves a specific attachment from a specific manual journal by file name
      tags:
        - Accounting
    post:
      operationId: updateManualJournalAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments
      summary: Updates a specific attachment from a specific manual journal by file name
      tags:
        - Accounting
      x-hasAccountingValidationError: true
    put:
      operationId: createManualJournalAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments
      summary: Creates a specific attachment for a specific manual journal by file name
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  "/ManualJournals/{ManualJournalID}/History":
    get:
      operationId: getManualJournalsHistory
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves history for a specific manual journal
      tags:
        - Accounting
    put:
      operationId: createManualJournalHistoryRecord
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates a history record for a specific manual journal
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  /Organisation:
    get:
      operationId: getOrganisations
      security:
        - OAuth2:
            - accounting.settings.read
      summary: Retrieves Xero organisation details
      tags:
        - Accounting
  /Organisation/Actions:
    get:
      operationId: getOrganisationActions
      security:
        - OAuth2:
            - accounting.settings.read
      summary: Retrieves a list of the key actions your app has permission to perform in the connected Xero organisation.
      tags:
        - Accounting
  "/Organisation/{OrganisationID}/CISSettings":
    get:
      operationId: getOrganisationCISSettings
      security:
        - OAuth2:
            - accounting.settings.read
      summary: Retrieves the CIS settings for the Xero organistaion.
      tags:
        - Accounting
  /Overpayments:
    get:
      operationId: getOverpayments
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves overpayments
      tags:
        - Accounting
  "/Overpayments/{OverpaymentID}":
    get:
      operationId: getOverpayment
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves a specific overpayment using a unique overpayment Id
      tags:
        - Accounting
  "/Overpayments/{OverpaymentID}/Allocations":
    put:
      operationId: createOverpaymentAllocations
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates a single allocation for a specific overpayment
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ allocations: [{ invoice: { invoiceID: "00000000-0000-0000-0000-000000000000", lineItems: [], contact: {}, type: Invoice.TypeEnum.ACCPAY }, amount: 10.0, date: "2019-03-12" }]}'
      x-ruby-requestBody: 'allocations = { allocations: [{ invoice: { invoice_id: "00000000-0000-0000-0000-000000000000", line_items: [], contact: {}, type: XeroRuby::Accounting::Invoice::ACCPAY }, amount: 10.0, date: "2019-03-12" }]}'
  "/Overpayments/{OverpaymentID}/History":
    get:
      operationId: getOverpaymentHistory
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves history records of a specific overpayment
      tags:
        - Accounting
    put:
      operationId: createOverpaymentHistory
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates a history record for a specific overpayment
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  /PaymentServices:
    get:
      operationId: getPaymentServices
      security:
        - OAuth2:
            - paymentservices
      summary: Retrieves payment services
      tags:
        - Accounting
    put:
      operationId: createPaymentService
      security:
        - OAuth2:
            - paymentservices
      summary: Creates a payment service
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ paymentServices: [{ paymentServiceName: "PayUpNow", paymentServiceUrl: "https://www.payupnow.com/", payNowText: "Time To Pay" }]}'
      x-ruby-requestBody: 'payment_services = { payment_services: [{ payment_service_name: "PayUpNow", payment_service_url: "https://www.payupnow.com/", pay_now_text: "Time To Pay" }]}'
  /Payments:
    get:
      operationId: getPayments
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves payments for invoices and credit notes
      tags:
        - Accounting
    post:
      operationId: createPayment
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates a single payment for invoice or credit notes
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ invoice: { invoiceID: "00000000-0000-0000-0000-000000000000", lineItems: [], contact: {}, type: Invoice.TypeEnum.ACCPAY }, account: { code: "970" }, date: "2019-03-12", amount: 1.0 }'
      x-ruby-requestBody: 'invoice = { invoice: { invoice_id: "00000000-0000-0000-0000-000000000000", line_items: [], contact: {}, type: XeroRuby::Accounting::Invoice::ACCPAY }, account: { code: "970" }, date: "2019-03-12", amount: 1.0 }'
    put:
      operationId: createPayments
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates multiple payments for invoices or credit notes
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ payments: [{ invoice: { invoiceID: "00000000-0000-0000-0000-000000000000", lineItems: [], contact: {}, type: Invoice.TypeEnum.ACCPAY }, account: { code: "970" }, date: "2019-03-12", amount: 1.0 }]}'
      x-ruby-requestBody: 'payments = { payments: [{ invoice: { invoice_id: "00000000-0000-0000-0000-000000000000", line_items: [], contact: {}, type: XeroRuby::Accounting::Invoice::ACCPAY }, account: { code: "970" }, date: "2019-03-12", amount: 1.0 }]}'
  "/Payments/{PaymentID}":
    get:
      operationId: getPayment
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves a specific payment for invoices and credit notes using a unique payment Id
      tags:
        - Accounting
    post:
      operationId: deletePayment
      security:
        - OAuth2:
            - accounting.transactions
      summary: Updates a specific payment for invoices and credit notes
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ status: "DELETED" }'
      x-ruby-requestBody: 'payments = { status: "DELETED" }'
  "/Payments/{PaymentID}/History":
    get:
      operationId: getPaymentHistory
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves history records of a specific payment
      tags:
        - Accounting
    put:
      operationId: createPaymentHistory
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates a history record for a specific payment
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  /Prepayments:
    get:
      operationId: getPrepayments
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves prepayments
      tags:
        - Accounting
  "/Prepayments/{PrepaymentID}":
    get:
      operationId: getPrepayment
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Allows you to retrieve a specified prepayments
      tags:
        - Accounting
  "/Prepayments/{PrepaymentID}/Allocations":
    put:
      operationId: createPrepaymentAllocations
      security:
        - OAuth2:
            - accounting.transactions
      summary: Allows you to create an Allocation for prepayments
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ allocations: [{ invoice: { invoiceID: "00000000-0000-0000-0000-000000000000", lineItems: [], contact: {}, type: null }, amount: 1.0, date: "2019-03-13" }]}'
      x-ruby-requestBody: 'allocations = { allocations: [{ invoice: { invoice_id: "00000000-0000-0000-0000-000000000000", line_items: [], contact: {}, type: null }, amount: 1.0, date: "2019-03-13" }]}'
  "/Prepayments/{PrepaymentID}/History":
    get:
      operationId: getPrepaymentHistory
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves history record for a specific prepayment
      tags:
        - Accounting
    put:
      operationId: createPrepaymentHistory
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates a history record for a specific prepayment
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  /PurchaseOrders:
    get:
      operationId: getPurchaseOrders
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves purchase orders
      tags:
        - Accounting
    post:
      operationId: updateOrCreatePurchaseOrders
      security:
        - OAuth2:
            - accounting.transactions
      summary: Updates or creates one or more purchase orders
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ purchaseOrders: [ { contact: { contactID: "00000000-0000-0000-0000-000000000000" }, lineItems: [{ description: "Foobar", quantity: 1.0, unitAmount: 20.0, accountCode: "710" }], date: "2019-03-13" }]}'
      x-ruby-requestBody: 'purchase_orders = { purchase_orders: [{ contact: { contact_id: "00000000-0000-0000-0000-000000000000" }, line_items: [{ description: "Foobar", quantity: 1.0, unitAmount: 20.0, accountCode: "710" }], date: "2019-03-13" }]}'
    put:
      operationId: createPurchaseOrders
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates one or more purchase orders
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ purchaseOrders: [{ contact: { contactID: "00000000-0000-0000-0000-000000000000" }, lineItems: [{ description: "Foobar", quantity: 1.0, unitAmount: 20.0, accountCode: "710" }], date: "2019-03-13" }]}'
      x-ruby-requestBody: 'purchase_orders = { purchase_orders: [{ contact: { contact_id: "00000000-0000-0000-0000-000000000000" }, line_items: [{ description: "Foobar", quantity: 1.0, unitAmount: 20.0, account_code: "710" }], date: "2019-03-13" }]}'
  "/PurchaseOrders/{PurchaseOrderID}":
    get:
      operationId: getPurchaseOrder
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves a specific purchase order using a unique purchase order Id
      tags:
        - Accounting
    post:
      operationId: updatePurchaseOrder
      security:
        - OAuth2:
            - accounting.transactions
      summary: Updates a specific purchase order
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ purchaseOrders:[ { attentionTo: "Peter Parker", lineItems: [], contact: {} }]}'
      x-ruby-requestBody: 'purchase_orders = { purchase_orders: [ { attention_to: "Peter Parker", line_items: [], contact: {} }]}'
  "/PurchaseOrders/{PurchaseOrderID}/Attachments":
    get:
      operationId: getPurchaseOrderAttachments
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves attachments for a specific purchase order
      tags:
        - Accounting
  "/PurchaseOrders/{PurchaseOrderID}/Attachments/{AttachmentID}":
    get:
      operationId: getPurchaseOrderAttachmentById
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves specific attachment for a specific purchase order using a unique attachment Id
      tags:
        - Accounting
  "/PurchaseOrders/{PurchaseOrderID}/Attachments/{FileName}":
    get:
      operationId: getPurchaseOrder≠AttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves a specific attachment for a specific purchase order by filename
      tags:
        - Accounting
    post:
      operationId: updatePurchaseOrderAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments
      summary: Updates a specific attachment for a specific purchase order by filename
      tags:
        - Accounting
      x-hasAccountingValidationError: true
    put:
      operationId: createPurchaseOrderAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments
      summary: Creates attachment for a specific purchase order
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  "/PurchaseOrders/{PurchaseOrderID}/History":
    get:
      operationId: getPurchaseOrderHistory
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves history for a specific purchase order
      tags:
        - Accounting
    put:
      operationId: createPurchaseOrderHistory
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates a history record for a specific purchase orders
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  "/PurchaseOrders/{PurchaseOrderID}/pdf":
    get:
      operationId: getPurchaseOrderAsPdf
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves specific purchase order as PDF files using a unique purchase order Id
      tags:
        - Accounting
      x-path: /PurchaseOrders/{PurchaseOrderID}
  "/PurchaseOrders/{PurchaseOrderNumber}":
    get:
      operationId: getPurchaseOrderByNumber
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves a specific purchase order using purchase order number
      tags:
        - Accounting
  /Quotes:
    get:
      operationId: getQuotes
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves sales quotes
      tags:
        - Accounting
    post:
      operationId: updateOrCreateQuotes
      security:
        - OAuth2:
            - accounting.transactions
      summary: Updates or creates one or more quotes
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ quotes: [{ contact: { contactID: "00000000-0000-0000-0000-000000000000" }, lineItems: [{ description: "Foobar", quantity: 1.0, unitAmount: 20.0, accountCode: "12775" }], date: "2020-02-01" }]}'
      x-ruby-requestBody: 'quotes = { quotes: [{ contact: { contact_id: "00000000-0000-0000-0000-000000000000" }, line_items: [{ description: "Foobar", quantity: 1.0, unit_amount: 20.0, account_code: "12775" }], date: "2020-02-01" }]}'
    put:
      operationId: createQuotes
      security:
        - OAuth2:
            - accounting.transactions
      summary: Create one or more quotes
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ quotes: [{ contact: { contactID: "00000000-0000-0000-0000-000000000000" }, lineItems: [{ description: "Foobar", quantity: 1.0, unitAmount: 20.0, accountCode: "12775" }], date: "2020-02-01" }]}'
      x-ruby-requestBody: 'quotes = { quotes: [{ contact: { contact_id: "00000000-0000-0000-0000-000000000000" }, line_items: [{ description: "Foobar", quantity: 1.0, unit_amount: 20.0, account_code: "12775" }], date: "2020-02-01" }]}'
  "/Quotes/{QuoteID}":
    get:
      operationId: getQuote
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves a specific quote using a unique quote Id
      tags:
        - Accounting
    post:
      operationId: updateQuote
      security:
        - OAuth2:
            - accounting.transactions
      summary: Updates a specific quote
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ quotes: [{ reference: "I am an update", contact: { contactID: "00000000-0000-0000-0000-000000000000" }, date: "2020-02-01" }]}'
      x-ruby-requestBody: 'quotes = { quotes: [{ reference: "I am an update", contact: { contact_id: "00000000-0000-0000-0000-000000000000" }, date: "2020-02-01" }]}'
  "/Quotes/{QuoteID}/Attachments":
    get:
      operationId: getQuoteAttachments
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves attachments for a specific quote
      tags:
        - Accounting
  "/Quotes/{QuoteID}/Attachments/{AttachmentID}":
    get:
      operationId: getQuoteAttachmentById
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves a specific attachment from a specific quote using a unique attachment Id
      tags:
        - Accounting
  "/Quotes/{QuoteID}/Attachments/{FileName}":
    get:
      operationId: getQuoteAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves a specific attachment from a specific quote by filename
      tags:
        - Accounting
    post:
      operationId: updateQuoteAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments
      summary: Updates a specific attachment from a specific quote by filename
      tags:
        - Accounting
      x-hasAccountingValidationError: true
    put:
      operationId: createQuoteAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments
      summary: Creates attachment for a specific quote
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  "/Quotes/{QuoteID}/History":
    get:
      operationId: getQuoteHistory
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves history records of a specific quote
      tags:
        - Accounting
    put:
      operationId: createQuoteHistory
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates a history record for a specific quote
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  "/Quotes/{QuoteID}/pdf":
    get:
      operationId: getQuoteAsPdf
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves a specific quote as a PDF file using a unique quote Id
      tags:
        - Accounting
      x-path: /Quotes/{QuoteID}
  /Receipts:
    get:
      operationId: getReceipts
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves draft expense claim receipts for any user
      tags:
        - Accounting
    put:
      operationId: createReceipt
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates draft expense claim receipts for any user
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ receipts: [{ contact: { contactID: "00000000-0000-0000-0000-000000000000" }, lineItems: [{ description: "Foobar", quantity: 2.0, unitAmount: 20.0, accountCode: "400", taxType: TaxType.NONE, lineAmount: 40.0 }], user: { userID: "00000000-0000-0000-0000-000000000000" }, lineAmountTypes: LineAmountTypes.Inclusive, status: Receipt.StatusEnum.DRAFT, date: null} ] }'
      x-ruby-requestBody: 'receipts = { receipts: [ { contact: { contact_id: "00000000-0000-0000-0000-000000000000" }, line_items: [{ description: "Foobar", quantity: 2.0, unit_amount: 20.0, account_code: "400", tax_type: XeroRuby::Accounting::TaxType::NONE, line_amount: 40.0 }], user: { user_id: "00000000-0000-0000-0000-000000000000" }, line_amount_types: XeroRuby::Accounting::INCLUSIVE, status: XeroRuby::Accounting::Receipt::DRAFT, date: nil }]}'
  "/Receipts/{ReceiptID}":
    get:
      operationId: getReceipt
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves a specific draft expense claim receipt by using a unique receipt Id
      tags:
        - Accounting
    post:
      operationId: updateReceipt
      security:
        - OAuth2:
            - accounting.transactions
      summary: Updates a specific draft expense claim receipts
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ receipts: [{ user: { userID: "00000000-0000-0000-0000-000000000000" }, reference: "Foobar", date: "2020-01-01", contact: {}, lineItems: [] }]}'
      x-ruby-requestBody: 'receipts = { receipts: [{ user: { user_id: "00000000-0000-0000-0000-000000000000" }, reference: "Foobar", date: "2020-01-01", contact: {}, line_items: [] }]}'
  "/Receipts/{ReceiptID}/Attachments":
    get:
      operationId: getReceiptAttachments
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves attachments for a specific expense claim receipt
      tags:
        - Accounting
  "/Receipts/{ReceiptID}/Attachments/{AttachmentID}":
    get:
      operationId: getReceiptAttachmentById
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves a specific attachments from a specific expense claim receipts by using a unique attachment Id
      tags:
        - Accounting
  "/Receipts/{ReceiptID}/Attachments/{FileName}":
    get:
      operationId: getReceiptAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves a specific attachment from a specific expense claim receipts by file name
      tags:
        - Accounting
    post:
      operationId: updateReceiptAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments
      summary: Updates a specific attachment on a specific expense claim receipts by file name
      tags:
        - Accounting
      x-hasAccountingValidationError: true
    put:
      operationId: createReceiptAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments
      summary: Creates an attachment on a specific expense claim receipts by file name
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  "/Receipts/{ReceiptID}/History":
    get:
      operationId: getReceiptHistory
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves a history record for a specific receipt
      tags:
        - Accounting
    put:
      operationId: createReceiptHistory
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates a history record for a specific receipt
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  /RepeatingInvoices:
    get:
      operationId: getRepeatingInvoices
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves repeating invoices
      tags:
        - Accounting
  "/RepeatingInvoices/{RepeatingInvoiceID}":
    get:
      operationId: getRepeatingInvoice
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves a specific repeating invoice by using a unique repeating invoice Id
      tags:
        - Accounting
  "/RepeatingInvoices/{RepeatingInvoiceID}/Attachments":
    get:
      operationId: getRepeatingInvoiceAttachments
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves attachments from a specific repeating invoice
      tags:
        - Accounting
  "/RepeatingInvoices/{RepeatingInvoiceID}/Attachments/{AttachmentID}":
    get:
      operationId: getRepeatingInvoiceAttachmentById
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves a specific attachment from a specific repeating invoice
      tags:
        - Accounting
  "/RepeatingInvoices/{RepeatingInvoiceID}/Attachments/{FileName}":
    get:
      operationId: getRepeatingInvoiceAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments.read
      summary: Retrieves a specific attachment from a specific repeating invoices by file name
      tags:
        - Accounting
    post:
      operationId: updateRepeatingInvoiceAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments
      summary: Updates a specific attachment from a specific repeating invoices by file name
      tags:
        - Accounting
      x-hasAccountingValidationError: true
    put:
      operationId: createRepeatingInvoiceAttachmentByFileName
      security:
        - OAuth2:
            - accounting.attachments
      summary: Creates an attachment from a specific repeating invoices by file name
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  "/RepeatingInvoices/{RepeatingInvoiceID}/History":
    get:
      operationId: getRepeatingInvoiceHistory
      security:
        - OAuth2:
            - accounting.transactions.read
      summary: Retrieves history record for a specific repeating invoice
      tags:
        - Accounting
    put:
      operationId: createRepeatingInvoiceHistory
      security:
        - OAuth2:
            - accounting.transactions
      summary: Creates a  history record for a specific repeating invoice
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  /Reports:
    get:
      operationId: getReportBASorGSTList
      security:
        - OAuth2:
            - accounting.reports.read
      summary: Retrieves report for BAS (only valid for AU orgs)
      tags:
        - Accounting
  /Reports/AgedPayablesByContact:
    get:
      operationId: getReportAgedPayablesByContact
      security:
        - OAuth2:
            - accounting.reports.read
      summary: Retrieves report for aged payables by contact
      tags:
        - Accounting
  /Reports/AgedReceivablesByContact:
    get:
      operationId: getReportAgedReceivablesByContact
      security:
        - OAuth2:
            - accounting.reports.read
      summary: Retrieves report for aged receivables by contact
      tags:
        - Accounting
  /Reports/BalanceSheet:
    get:
      operationId: getReportBalanceSheet
      security:
        - OAuth2:
            - accounting.reports.read
      summary: Retrieves report for balancesheet
      tags:
        - Accounting
  /Reports/BankSummary:
    get:
      operationId: getReportBankSummary
      security:
        - OAuth2:
            - accounting.reports.read
      summary: Retrieves report for bank summary
      tags:
        - Accounting
  /Reports/BudgetSummary:
    get:
      operationId: getReportBudgetSummary
      security:
        - OAuth2:
            - accounting.reports.read
      summary: Retrieves report for budget summary
      tags:
        - Accounting
  /Reports/ExecutiveSummary:
    get:
      operationId: getReportExecutiveSummary
      security:
        - OAuth2:
            - accounting.reports.read
      summary: Retrieves report for executive summary
      tags:
        - Accounting
  /Reports/ProfitAndLoss:
    get:
      operationId: getReportProfitAndLoss
      security:
        - OAuth2:
            - accounting.reports.read
      summary: Retrieves report for profit and loss
      tags:
        - Accounting
  /Reports/TenNinetyNine:
    get:
      operationId: getReportTenNinetyNine
      security:
        - OAuth2:
            - accounting.reports.tenninetynine.read
      summary: Retrieve reports for 1099
      tags:
        - Accounting
  /Reports/TrialBalance:
    get:
      operationId: getReportTrialBalance
      security:
        - OAuth2:
            - accounting.reports.read
      summary: Retrieves report for trial balance
      tags:
        - Accounting
  "/Reports/{ReportID}":
    get:
      operationId: getReportBASorGST
      security:
        - OAuth2:
            - accounting.reports.read
      summary: Retrieves a specific report for BAS using a unique report Id (only valid for AU orgs)
      tags:
        - Accounting
  /Setup:
    post:
      operationId: postSetup
      security:
        - OAuth2:
            - accounting.settings
      summary: Sets the chart of accounts, the conversion date and conversion balances
      tags:
        - Accounting
  /TaxRates:
    get:
      operationId: getTaxRates
      security:
        - OAuth2:
            - accounting.settings.read
      summary: Retrieves tax rates
      tags:
        - Accounting
    post:
      operationId: updateTaxRate
      security:
        - OAuth2:
            - accounting.settings
      summary: Updates tax rates
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ taxRates: [{ name: "State Tax NY", taxComponents: [{ name: "State Tax", rate: 2.25 }], status: TaxRate.StatusEnum.DELETED, reportTaxType: TaxRate.ReportTaxTypeEnum.INPUT }]}'
      x-ruby-requestBody: 'tax_rates = { tax_rates: [{ name: "State Tax NY", tax_components: [{ name: "State Tax", rate: 2.25 }], status: XeroRuby::Accounting::TaxRate::Deleted, report_tax_type: XeroRuby::Accounting::TaxRate::INPUT }]}'
    put:
      operationId: createTaxRates
      security:
        - OAuth2:
            - accounting.settings
      summary: Creates one or more tax rates
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ taxRates: [{ name: "CA State Tax", taxComponents: [{ name: "State Tax", rate: 2.25 }]}]}'
      x-ruby-requestBody: 'tax_rates = { tax_rates: [{ name: "CA State Tax", tax_components: [{ name: "State Tax", rate: 2.25 }]}]}'
  /TrackingCategories:
    get:
      operationId: getTrackingCategories
      security:
        - OAuth2:
            - accounting.settings.read
      summary: Retrieves tracking categories and options
      tags:
        - Accounting
    put:
      operationId: createTrackingCategory
      security:
        - OAuth2:
            - accounting.settings
      summary: Create tracking categories
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  "/TrackingCategories/{TrackingCategoryID}":
    delete:
      operationId: deleteTrackingCategory
      security:
        - OAuth2:
            - accounting.settings
      summary: Deletes a specific tracking category
      tags:
        - Accounting
    get:
      operationId: getTrackingCategory
      security:
        - OAuth2:
            - accounting.settings.read
      summary: Retrieves specific tracking categories and options using a unique tracking category Id
      tags:
        - Accounting
    post:
      operationId: updateTrackingCategory
      security:
        - OAuth2:
            - accounting.settings
      summary: Updates a specific tracking category
      tags:
        - Accounting
      x-hasAccountingValidationError: true
      x-node-requestBody: '{ name: "Avengers" }'
      x-ruby-requestBody: 'tracking_categories = { name: "Avengers" }'
  "/TrackingCategories/{TrackingCategoryID}/Options":
    put:
      operationId: createTrackingOptions
      security:
        - OAuth2:
            - accounting.settings
      summary: Creates options for a specific tracking category
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  "/TrackingCategories/{TrackingCategoryID}/Options/{TrackingOptionID}":
    delete:
      operationId: deleteTrackingOptions
      security:
        - OAuth2:
            - accounting.settings
      summary: Deletes a specific option for a specific tracking category
      tags:
        - Accounting
    post:
      operationId: updateTrackingOptions
      security:
        - OAuth2:
            - accounting.settings
      summary: Updates a specific option for a specific tracking category
      tags:
        - Accounting
      x-hasAccountingValidationError: true
  /Users:
    get:
      operationId: getUsers
      security:
        - OAuth2:
            - accounting.settings.read
      summary: Retrieves users
      tags:
        - Accounting
  "/Users/{UserID}":
    get:
      operationId: getUser
      security:
        - OAuth2:
            - accounting.settings.read
      summary: Retrieves a specific user
      tags:
        - Accounting
components:
  securitySchemes:
    OAuth2:
      description: For more information
      flows:
        authorizationCode:
          authorizationUrl: https://login.xero.com/identity/connect/authorize
          scopes:
            accounting.attachments: Grant read-write access to attachments
            accounting.attachments.read: Grant read-only access to attachments
            accounting.contacts: Grant read-write access to contacts and contact groups
            accounting.contacts.read: Grant read-only access to contacts and contact groups
            accounting.journals.read: Grant read-only access to journals
            accounting.reports.read: Grant read-only access to accounting reports
            accounting.reports.tenninetynine.read: Grant read-only access to 1099 reports
            accounting.settings: Grant read-write access to organisation and account settings
            accounting.settings.read: Grant read-only access to organisation and account settings
            accounting.transactions: Grant read-write access to bank transactions, credit notes, invoices, repeating invoices
            accounting.transactions.read: Grant read-only access to invoices
            assets: Grant read-write access to assets
            assets.read: Grant read-only access to fixed assets
            bankfeeds: Grant read-write access to bankfeeds
            email: Grant read-only access to your email
            files: Grant read-write access to files and folders
            files.read: Grant read-only access to files and folders
            openid: Grant read-only access to your open id
            paymentservices: Grant read-write access to payment services
            payroll: Grant read-write access to payroll
            payroll.employees: Grant read-write access to payroll employees
            payroll.employees.read: Grant read-only access to payroll employees
            payroll.leaveapplications: Grant read-write access to payroll leaveapplications
            payroll.leaveapplications.read: Grant read-only access to payroll leaveapplications
            payroll.payitems: Grant read-write access to payroll payitems
            payroll.payitems.read: Grant read-only access to payroll payitems
            payroll.payrollcalendars: Grant read-write access to payroll calendars
            payroll.payrollcalendars.read: Grant read-only access to payroll calendars
            payroll.payruns: Grant read-write access to payroll payruns
            payroll.payruns.read: Grant read-only access to payroll payruns
            payroll.payslip: Grant read-write access to payroll payslips
            payroll.payslip.read: Grant read-only access to payroll payslips
            payroll.read: Grant read-only access to payroll
            payroll.settings.read: Grant read-only access to payroll settings
            payroll.superfundproducts.read: Grant read-only access to payroll superfundproducts
            payroll.superfunds: Grant read-write access to payroll superfunds
            payroll.superfunds.read: Grant read-only access to payroll superfunds
            payroll.timesheets: Grant read-write access to payroll timesheets
            payroll.timesheets.read: Grant read-only access to payroll timesheets
            profile: your profile information
            projects: Grant read-write access to projects
            projects.read: Grant read-only access to projects
          tokenUrl: https://identity.xero.com/connect/token
      type: oauth2
