{
  "openapi": "3.0.0",
  "servers": [
    {
      "url": "https://api.bitbucket.org/2.0"
    }
  ],
  "info": {
    "contact": {
      "email": "support@bitbucket.org",
      "name": "Bitbucket Support",
      "url": "https://support.atlassian.com/bitbucket-cloud/"
    },
    "description": "Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.",
    "termsOfService": "https://www.atlassian.com/legal/customer-agreement",
    "title": "Bitbucket API",
    "version": "2.0",
    "x-apisguru-categories": [
      "developer_tools",
      "collaboration"
    ],
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_d301sr5gafysq2.cloudfront.net_0c55837759e5_img_homepage_bitbucket-logo-blue.svg"
    },
    "x-origin": [
      {
        "format": "openapi",
        "url": "https://bitbucket.org/api/swagger.json",
        "version": "3.0"
      }
    ],
    "x-providerName": "bitbucket.org",
    "x-tags": [
      "code repository",
      "code collaboration",
      "git"
    ]
  },
  "tags": [
    {
      "description": "The addon resource is intended to use used by Bitbucket Cloud Connect\nApps, and only supports JWT authentication.\n",
      "name": "Addon"
    },
    {
      "description": "Repository owners and administrators can set branch management\nrules on a repository that control what can be pushed by whom.\nThrough these rules, you can enforce a project or team\nworkflow. For example, owners or administrators can:\n\n* Limit push powers\n* Prevent branch deletion\n* Prevent history re-writes (Git only)\n",
      "name": "Branch restrictions"
    },
    {
      "description": "The branching model resource is used to modify the branching model\nfor a repository.\n\nYou can use the branching model to define a branch based workflow\nfor your repositories. When you map your workflow to branch types,\nyou can ensure that branches are named consistently by configuring\nwhich branch types to make available.\n",
      "name": "Branching model"
    },
    {
      "description": "Commit statuses provide a way to tag commits with meta data,\nlike automated build results.\n",
      "name": "Commit statuses"
    },
    {
      "description": "These are the repository's commits. They are paginated and returned in\nreverse chronological order, similar to the output of git log.\n",
      "name": "Commits"
    },
    {
      "description": "Teams are deploying code faster than ever, thanks to continuous\ndelivery practices and tools like Bitbucket Pipelines. Bitbucket\nDeployments gives teams visibility into their deployment\nenvironments and helps teams to track how far changes have\nprogressed in their deployment pipeline.\n",
      "name": "Deployments"
    },
    {
      "description": "Access the list of download links associated with the repository.",
      "name": "Downloads"
    },
    {
      "description": "The issue resources provide functionality for getting information on\nissues in an issue tracker, creating new issues, updating them and deleting\nthem.\n\nYou can access public issues without authentication, but you can't gain access\nto private repositories' issues. By authenticating, you will get the ability\nto create issues, as well as access to updating data or deleting issues you\nhave access to.\n",
      "name": "Issue tracker"
    },
    {
      "description": "Bitbucket Pipelines brings continuous delivery to Bitbucket\nCloud, empowering teams with full branching to deployment\nvisibility and faster feedback loops.\n",
      "name": "Pipelines"
    },
    {
      "description": "Bitbucket Cloud projects make it easier for teams to focus on\na goal, product, or process by organizing their repositories.\n",
      "name": "Projects"
    },
    {
      "description": "Pull requests are a feature that makes it easier for developers\nto collaborate using Bitbucket. They provide a user-friendly web\ninterface for discussing proposed changes before integrating them\ninto the official project.\n",
      "name": "Pullrequests"
    },
    {
      "description": "The refs resource allows you access branches and tags in a repository.\nBy default, results will be in the order the underlying source control\nsystem returns them and identical to the ordering one sees when running\n\"$ git show-ref\". Note that this follows simple lexical ordering of the\n ref names.\n",
      "name": "Refs"
    },
    {
      "description": "Code insights provides reports, annotations, and metrics to help you\nand your team improve code quality in pull requests throughout the code\nreview process. Some of the available code insights are static analysis\nreports, security scan results, artifact links, unit tests, and build\nstatus.\n",
      "name": "Reports"
    },
    {
      "description": "A Git repository is a virtual storage of your project. It\nallows you to save versions of your code, which you can access\nwhen needed. The repo resource allows you to access public repos,\nor repos that belong to a specific workspace.\n",
      "name": "Repositories"
    },
    {
      "description": "Snippets allow you share code segments or files with yourself, members of\nyour workspace, or the world.\n\nLike pull requests, repositories and workspaces, the full set of snippets\nis defined by what the current user has access to. This includes all\nsnippets owned by any of the workspaces the user is a member of, or\nsnippets by other users that the current user is either watching or has\n collaborated on (for instance by commenting on it).\n",
      "name": "Snippets"
    },
    {
      "description": "Browse the source code in the repository and\n                              create new commits by uploading.",
      "name": "Source"
    },
    {
      "description": "The SSH resource allows you to manage SSH keys.\n",
      "name": "Ssh"
    },
    {
      "description": "The teams resource has been deprecated, and the workspaces\nendpoint should be used instead.\n\nThe teams resource returns all the teams that the authenticated\nuser is associated with.\n",
      "name": "Teams"
    },
    {
      "description": "The users resource allows you to access public information\nassociated with a user account. Most resources in the users\nendpoint have been deprecated in favor of workspaces.\n",
      "name": "Users"
    },
    {
      "description": "Webhooks provide a way to configure Bitbucket Cloud to make requests to\nyour server (or another external service) whenever certain events occur in\nBitbucket Cloud.\n\nA webhook consists of:\n\n* A subject -- The resource that generates the events. Currently, this resource\nis the repository, user account, or team where you create the webhook.\n* One or more event -- The default event is a repository push, but you can\nselect multiple events that can trigger the webhook.\n[...]",
      "name": "Webhooks"
    },
    {
      "description": "The wiki is a simple place to keep documents. Some people use it\nas their project home page. The wiki is a Git repository, so you\ncan clone it and edit it like any other source files.\n",
      "name": "Wiki"
    },
    {
      "description": "A workspace is where you create repositories, collaborate on\nyour code, and organize different streams of work in your Bitbucket\nCloud account. Workspaces replace the use of teams and users in API\ncalls.\n",
      "name": "Workspaces"
    }
  ],
  "paths": {
    "/addon": {
      "delete": {
        "description": "Deletes the application for the user.\n\nThis endpoint is intended to be used by Bitbucket Connect apps\nand only supports JWT authentication -- that is how Bitbucket\nidentifies the particular installation of the app. Developers\nwith applications registered in the \"Develop Apps\" section\nof Bitbucket Marketplace need not use this endpoint as\nupdates for those applications can be sent out via the\nUI of that section.\n\n```\n$ curl -X DELETE https://api.bitbucket.org/[...]",
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Addon"
        ]
      },
      "put": {
        "description": "Updates the application installation for the user.\n\nThis endpoint is intended to be used by Bitbucket Connect apps\nand only supports JWT authentication -- that is how Bitbucket\nidentifies the particular installation of the app. Developers\nwith applications registered in the \"Develop Apps\" section\nof Bitbucket Marketplace need not use this endpoint as\nupdates for those applications can be sent out via the\nUI of that section.\n\nA new, valid descriptor must be pro[...]",
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Addon"
        ]
      }
    },
    "/addon/linkers": {
      "get": {
        "description": "Gets a list of all [linkers](/cloud/bitbucket/modules/linker/)\nfor the authenticated application.",
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Addon"
        ]
      }
    },
    "/addon/linkers/{linker_key}": {
      "get": {
        "description": "Gets a [linker](/cloud/bitbucket/modules/linker/) specified by `linker_key`\nfor the authenticated application.",
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Addon"
        ]
      }
    },
    "/addon/linkers/{linker_key}/values": {
      "delete": {
        "description": "Delete all [linker](/cloud/bitbucket/modules/linker/) values for the\nspecified linker of the authenticated application.",
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Addon"
        ]
      },
      "get": {
        "description": "Gets a list of all [linker](/cloud/bitbucket/modules/linker/) values for the\nspecified linker of the authenticated application.\n\nA linker value lets applications supply values to modify its regular expression.\n\nThe base regular expression must use a Bitbucket-specific match group `(?K)`\nwhich will be translated to `([\\w\\-]+)`. A value must match this pattern.\n\n[Read more about linker values](/cloud/bitbucket/modules/linker/#usingthebitbucketapitosupplyvalues)",
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Addon"
        ]
      },
      "post": {
        "description": "Creates a [linker](/cloud/bitbucket/modules/linker/) value for the specified\nlinker of authenticated application.\n\nA linker value lets applications supply values to modify its regular expression.\n\nThe base regular expression must use a Bitbucket-specific match group `(?K)`\nwhich will be translated to `([\\w\\-]+)`. A value must match this pattern.\n\n[Read more about linker values](/cloud/bitbucket/modules/linker/#usingthebitbucketapitosupplyvalues)",
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Addon"
        ]
      },
      "put": {
        "description": "Bulk update [linker](/cloud/bitbucket/modules/linker/) values for the specified\nlinker of the authenticated application.\n\nA linker value lets applications supply values to modify its regular expression.\n\nThe base regular expression must use a Bitbucket-specific match group `(?K)`\nwhich will be translated to `([\\w\\-]+)`. A value must match this pattern.\n\n[Read more about linker values](/cloud/bitbucket/modules/linker/#usingthebitbucketapitosupplyvalues)",
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Addon"
        ]
      }
    },
    "/addon/linkers/{linker_key}/values/{value_id}": {
      "delete": {
        "description": "Delete a single [linker](/cloud/bitbucket/modules/linker/) value\nof the authenticated application.",
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Addon"
        ]
      },
      "get": {
        "description": "Get a single [linker](/cloud/bitbucket/modules/linker/) value\nof the authenticated application.",
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Addon"
        ]
      }
    },
    "/hook_events": {
      "get": {
        "description": "Returns the webhook resource or subject types on which webhooks can\nbe registered.\n\nEach resource/subject type contains an `events` link that returns the\npaginated list of specific events each individual subject type can\nemit.\n\nThis endpoint is publicly accessible and does not require\nauthentication or scopes.\n\nExample:\n\n```\n$ curl https://api.bitbucket.org/2.0/hook_events\n\n{\n    \"repository\": {\n        \"links\": {\n            \"events\": {\n         [...]",
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Webhooks"
        ]
      }
    },
    "/hook_events/{subject_type}": {
      "get": {
        "description": "Returns a paginated list of all valid webhook events for the\nspecified entity.\n**The team and user webhooks are deprecated, and you should use workspace instead.\nFor more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**\n\nThis is public data that does not require any scopes or authentication.\n\nExample:\n\nNOTE: The following example is a truncated response object for the `workspace` `subject_typ[...]",
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Webhooks"
        ]
      }
    },
    "/pullrequests/{selected_user}": {
      "get": {
        "description": "Returns all pull requests authored by the specified user.\n\nBy default only open pull requests are returned. This can be controlled\nusing the `state` query parameter. To retrieve pull requests that are\nin one of multiple states, repeat the `state` parameter for each\nindividual state.\n\nThis endpoint also supports filtering and sorting of the results. See\n[filtering and sorting](../../../../meta/filtering) for more details.",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      }
    },
    "/repositories": {
      "get": {
        "description": "Returns a paginated list of all public repositories.\n\nThis endpoint also supports filtering and sorting of the results. See\n[filtering and sorting](../meta/filtering) for more details.",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Repositories"
        ]
      }
    },
    "/repositories/{workspace}": {
      "get": {
        "description": "Returns a paginated list of all repositories owned by the specified\naccount or UUID.\n\nThe result can be narrowed down based on the authenticated user's role.\n\nE.g. with `?role=contributor`, only those repositories that the\nauthenticated user has write access to are returned (this includes any\nrepo the user is an admin on, as that implies write access).\n\nThis endpoint also supports filtering and sorting of the results. See\n[filtering and sorting](../../meta/filte[...]",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Repositories"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}": {
      "delete": {
        "description": "Deletes the repository. This is an irreversible operation.\n\nThis does not affect its forks.",
        "security": [
          {
            "oauth2": [
              "repository:delete"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Repositories"
        ]
      },
      "get": {
        "description": "Returns the object describing this repository.",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Repositories"
        ]
      },
      "post": {
        "description": "Creates a new repository.\n\nNote: In order to set the project for the newly created repository,\npass in either the project key or the project UUID as part of the\nrequest body as shown in the examples below:\n\n```\n$ curl -X POST -H \"Content-Type: application/json\" -d '{\n    \"scm\": \"git\",\n    \"project\": {\n        \"key\": \"MARS\"\n    }\n}' https://api.bitbucket.org/2.0/repositories/teamsinspace/hablanding\n```\n\nor\n\n```\n$ curl -X POST -H \"Content-Type[...]",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Repositories"
        ]
      },
      "put": {
        "description": "Since this endpoint can be used to both update and to create a\nrepository, the request body depends on the intent.\n\n### Creation\n\nSee the POST documentation for the repository endpoint for an example\nof the request body.\n\n### Update\n\nNote: Changing the `name` of the repository will cause the location to\nbe changed. This is because the URL of the repo is derived from the\nname (a process called slugification). In such a scenario, it is\npossible for the request [...]",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Repositories"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/branch-restrictions": {
      "get": {
        "description": "Returns a paginated list of all branch restrictions on the\nrepository.",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Branch restrictions"
        ]
      },
      "post": {
        "description": "Creates a new branch restriction rule for a repository.\n\n`kind` describes what will be restricted. Allowed values include:\n`push`, `force`, `delete` and `restrict_merges`.\n\nDifferent kinds of branch restrictions have different requirements:\n\n* `push` and `restrict_merges` require `users` and `groups` to be\n  specified. Empty lists are allowed, in which case permission is\n  denied for everybody.\n\nThe restriction applies to all branches that match. There are\ntwo[...]",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Branch restrictions"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/branch-restrictions/{id}": {
      "delete": {
        "description": "Deletes an existing branch restriction rule.",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Branch restrictions"
        ]
      },
      "get": {
        "description": "Returns a specific branch restriction rule.",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Branch restrictions"
        ]
      },
      "put": {
        "description": "Updates an existing branch restriction rule.\n\nFields not present in the request body are ignored.\n\nSee [`POST`](../branch-restrictions#post) for details.",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Branch restrictions"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/branching-model": {
      "get": {
        "description": "Return the branching model as applied to the repository. This view is\nread-only. The branching model settings can be changed using the\n[settings](branching-model/settings#get) API.\n\nThe returned object:\n\n1. Always has a `development` property. `development.branch` contains\n   the actual repository branch object that is considered to be the\n   `development` branch. `development.branch` will not be present\n   if it does not exist.\n2. Might have a `production` prop[...]",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Branching model"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/branching-model/settings": {
      "get": {
        "description": "Return the branching model configuration for a repository. The returned\nobject:\n\n1. Always has a `development` property for the development branch.\n2. Always a `production` property for the production branch. The\n   production branch can be disabled.\n3. The `branch_types` contains all the branch types.\n\nThis is the raw configuration for the branching model. A client\nwishing to see the branching model with its actual current branches may\nfind the [active model AP[...]",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Branching model"
        ]
      },
      "put": {
        "description": "Update the branching model configuration for a repository.\n\nThe `development` branch can be configured to a specific branch or to\ntrack the main branch. When set to a specific branch it must\ncurrently exist. Only the passed properties will be updated. The\nproperties not passed will be left unchanged. A request without a\n`development` property will leave the development branch unchanged.\n\nIt is possible for the `development` branch to be invalid. This\nhappens when[...]",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Branching model"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}": {
      "get": {
        "description": "Returns the specified commit.\n\nExample:\n\n```\n$ curl https://api.bitbucket.org/2.0/repositories/bitbucket/geordi/commit/f7591a1\n{\n    \"rendered\": {\n        \"message\": {\n        \"raw\": \"Add a GEORDI_OUTPUT_DIR setting\",\n        \"markup\": \"markdown\",\n        \"html\": \"<p>Add a GEORDI_OUTPUT_DIR setting</p>\",\n        \"type\": \"rendered\"\n        }\n    },\n    \"hash\": \"f7591a13eda445d9a9167f98eb870319f4b6c2d8\",\n    \"repository\": {\n       [...]",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Commits"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/approve": {
      "delete": {
        "description": "Redact the authenticated user's approval of the specified commit.\n\nThis operation is only available to users that have explicit access to\nthe repository. In contrast, just the fact that a repository is\npublicly accessible to users does not give them the ability to approve\ncommits.",
        "security": [
          {
            "oauth2": [
              "repository:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Commits"
        ]
      },
      "post": {
        "description": "Approve the specified commit as the authenticated user.\n\nThis operation is only available to users that have explicit access to\nthe repository. In contrast, just the fact that a repository is\npublicly accessible to users does not give them the ability to approve\ncommits.",
        "security": [
          {
            "oauth2": [
              "repository:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Commits"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/comments": {
      "get": {
        "description": "Returns the commit's comments.\n\nThis includes both global and inline comments.\n\nThe default sorting is oldest to newest and can be overridden with\nthe `sort` query parameter.",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Commits"
        ]
      },
      "post": {
        "description": "Creates new comment on the specified commit.\n\nTo post a reply to an existing comment, include the `parent.id` field:\n\n```\n$ curl https://api.bitbucket.org/2.0/repositories/atlassian/prlinks/commit/db9ba1e031d07a02603eae0e559a7adc010257fc/comments/ \\\n  -X POST -u evzijst \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"content\": {\"raw\": \"One more thing!\"},\n       \"parent\": {\"id\": 5728901}}'\n```",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Commits"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/comments/{comment_id}": {
      "get": {
        "description": "Returns the specified commit comment.",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Commits"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/properties/{app_key}/{property_name}": {
      "delete": {
        "description": "Delete an [application property](/cloud/bitbucket/application-properties/) value stored against a commit.",
        "operationId": "deleteCommitHostedPropertyValue",
        "tags": [
          "properties"
        ]
      },
      "get": {
        "description": "Retrieve an [application property](/cloud/bitbucket/application-properties/) value stored against a commit.",
        "operationId": "getCommitHostedPropertyValue",
        "tags": [
          "properties"
        ]
      },
      "put": {
        "description": "Update an [application property](/cloud/bitbucket/application-properties/) value stored against a commit.",
        "operationId": "updateCommitHostedPropertyValue",
        "tags": [
          "properties"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/pullrequests": {
      "get": {
        "operationId": "getPullrequestsForCommit",
        "summary": "Returns a paginated list of all pull requests as part of which this commit was reviewed. Pull Request Commit Links app must be installed first before using this API; installation automatically occurs when 'Go to pull request' is clicked from the web interface for a commit's details.",
        "tags": [
          "Pullrequests"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/reports": {
      "get": {
        "description": "Returns a paginated list of Reports linked to this commit.",
        "operationId": "getReportsForCommit",
        "tags": [
          "Reports",
          "Commits"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/reports/{reportId}": {
      "delete": {
        "description": "Deletes a single Report matching the provided ID.",
        "operationId": "deleteReport",
        "tags": [
          "Reports",
          "Commits"
        ]
      },
      "get": {
        "description": "Returns a single Report matching the provided ID.",
        "operationId": "getReport",
        "tags": [
          "Reports",
          "Commits"
        ]
      },
      "put": {
        "description": "Creates or updates a report for the specified commit.\nTo upload a report, make sure to generate an ID that is unique across all reports for that commit. If you want to use an existing id from your own system, we recommend prefixing it with your system's name to avoid collisions, for example, mySystem-001.\n\n### Sample cURL request:\n```\ncurl --request PUT 'https://api.bitbucket.org/2.0/repositories/<username>/<reposity-name>/commit/<commit-hash>/reports/mysystem-001' \[...]",
        "operationId": "createOrUpdateReport",
        "tags": [
          "Reports",
          "Commits"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/reports/{reportId}/annotations": {
      "get": {
        "description": "Returns a paginated list of Annotations for a specified report.",
        "operationId": "getAnnotationsForReport",
        "tags": [
          "Reports",
          "Commits"
        ]
      },
      "post": {
        "description": "Bulk upload of annotations.\nAnnotations are individual findings that have been identified as part of a report, for example, a line of code that represents a vulnerability. These annotations can be attached to a specific file and even a specific line in that file, however, that is optional. Annotations are not mandatory and a report can contain up to 1000 annotations.\n\nAdd the annotations you want to upload as objects in a JSON array and make sure each annotation has th[...]",
        "operationId": "bulkCreateOrUpdateAnnotations",
        "tags": [
          "Reports",
          "Commits"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/reports/{reportId}/annotations/{annotationId}": {
      "delete": {
        "description": "Deletes a single Annotation matching the provided ID.",
        "operationId": "deleteAnnotation",
        "tags": [
          "Reports",
          "Commits"
        ]
      },
      "get": {
        "description": "Returns a single Annotation matching the provided ID.",
        "operationId": "getAnnotation",
        "tags": [
          "Reports",
          "Commits"
        ]
      },
      "put": {
        "description": "Creates or updates an individual annotation for the specified report.\nAnnotations are individual findings that have been identified as part of a report, for example, a line of code that represents a vulnerability. These annotations can be attached to a specific file and even a specific line in that file, however, that is optional. Annotations are not mandatory and a report can contain up to 1000 annotations.\n\nJust as reports, annotation needs to be uploaded with a uniq[...]",
        "operationId": "createOrUpdateAnnotation",
        "tags": [
          "Reports",
          "Commits"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/statuses": {
      "get": {
        "description": "Returns all statuses (e.g. build results) for a specific commit.",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Repositories",
          "Commit statuses"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/statuses/build": {
      "post": {
        "description": "Creates a new build status against the specified commit.\n\nIf the specified key already exists, the existing status object will\nbe overwritten.\n\nExample:\n\n```\ncurl https://api.bitbucket.org/2.0/repositories/my-workspace/my-repo/commit/e10dae226959c2194f2b07b077c07762d93821cf/statuses/build/           -X POST -u jdoe -H 'Content-Type: application/json'           -d '{\n    \"key\": \"MY-BUILD\",\n    \"state\": \"SUCCESSFUL\",\n    \"description\": \"42 tests passed[...]",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Repositories",
          "Commit statuses"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/statuses/build/{key}": {
      "get": {
        "description": "Returns the specified build status for a commit.",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Repositories",
          "Commit statuses"
        ]
      },
      "put": {
        "description": "Used to update the current status of a build status object on the\nspecific commit.\n\nThis operation can also be used to change other properties of the\nbuild status:\n\n* `state`\n* `name`\n* `description`\n* `url`\n* `refname`\n\nThe `key` cannot be changed.",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Repositories",
          "Commit statuses"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/commits": {
      "get": {
        "description": "These are the repository's commits. They are paginated and returned\nin reverse chronological order, similar to the output of `git log`.\nLike these tools, the DAG can be filtered.\n\n## GET /repositories/{workspace}/{repo_slug}/commits/\n\nReturns all commits in the repo in topological order (newest commit\nfirst). All branches and tags are included (similar to\n`git log --all`).\n\n## GET /repositories/{workspace}/{repo_slug}/commits/?exclude=master\n\nReturns all commi[...]",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Commits"
        ]
      },
      "post": {
        "description": "Identical to `GET /repositories/{workspace}/{repo_slug}/commits`,\nexcept that POST allows clients to place the include and exclude\nparameters in the request body to avoid URL length issues.\n\n**Note that this resource does NOT support new commit creation.**",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Commits"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/commits/{revision}": {
      "get": {
        "description": "These are the repository's commits. They are paginated and returned\nin reverse chronological order, similar to the output of `git log`.\nLike these tools, the DAG can be filtered.\n\n## GET /repositories/{workspace}/{repo_slug}/commits/master\n\nReturns all commits on rev `master` (similar to `git log master`).\n\n## GET /repositories/{workspace}/{repo_slug}/commits/dev?include=foo&exclude=master\n\nReturns all commits on ref `dev` or `foo`, except those that are reachab[...]",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Commits"
        ]
      },
      "post": {
        "description": "Identical to `GET /repositories/{workspace}/{repo_slug}/commits/{revision}`,\nexcept that POST allows clients to place the include and exclude\nparameters in the request body to avoid URL length issues.\n\n**Note that this resource does NOT support new commit creation.**",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Commits"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/components": {
      "get": {
        "description": "Returns the components that have been defined in the issue tracker.\n\nThis resource is only available on repositories that have the issue\ntracker enabled.",
        "security": [
          {
            "oauth2": [
              "issue"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/components/{component_id}": {
      "get": {
        "description": "Returns the specified issue tracker component object.",
        "security": [
          {
            "oauth2": [
              "issue"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/default-reviewers": {
      "get": {
        "description": "Returns the repository's default reviewers.\n\nThese are the users that are automatically added as reviewers on every\nnew pull request that is created.",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/default-reviewers/{target_username}": {
      "delete": {
        "description": "Removes a default reviewer from the repository.",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      },
      "get": {
        "description": "Returns the specified reviewer.\n\nThis can be used to test whether a user is among the repository's\ndefault reviewers list. A 404 indicates that that specified user is not\na default reviewer.",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      },
      "put": {
        "description": "Adds the specified user to the repository's list of default\nreviewers.\n\nThis method is idempotent. Adding a user a second time has no effect.",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/deploy-keys": {
      "get": {
        "description": "Returns all deploy-keys belonging to a repository.\n\nExample:\n```\n$ curl -H \"Authorization <auth header>\" \\\nhttps://api.bitbucket.org/2.0/repositories/mleu/test/deploy-keys\n\nOutput:\n{\n    \"pagelen\": 10,\n    \"values\": [\n        {\n            \"id\": 123,\n            \"key\": \"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAK/b1cHHDr/TEV1JGQl+WjCwStKG6Bhrv0rFpEsYlyTBm1fzN0VOJJYn4ZOPCPJwqse6fGbXntEs+BbXiptR+++HycVgl65TMR0b5ul5AgwrVdZdT7qjCOCgaSV74/9xlHDK8oqgGnfA7[...]",
        "security": [
          {
            "oauth2": [
              "repository",
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Deployments"
        ]
      },
      "post": {
        "description": "Create a new deploy key in a repository. Note: If authenticating a deploy key\nwith an OAuth consumer, any changes to the OAuth consumer will subsequently\ninvalidate the deploy key.\n\n\nExample:\n```\n$ curl -XPOST \\\n-H \"Authorization <auth header>\" \\\n-H \"Content-type: application/json\" \\\nhttps://api.bitbucket.org/2.0/repositories/mleu/test/deploy-keys -d \\\n'{\n    \"key\": \"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAK/b1cHHDr/TEV1JGQl+WjCwStKG6Bhrv0rFpEsYlyTB[...]",
        "security": [
          {
            "oauth2": [
              "repository",
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Deployments"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/deploy-keys/{key_id}": {
      "delete": {
        "description": "This deletes a deploy key from a repository.\n\nExample:\n```\n$ curl -XDELETE \\\n-H \"Authorization <auth header>\" \\\nhttps://api.bitbucket.org/2.0/repositories/mleu/test/deploy-keys/1234\n```",
        "security": [
          {
            "oauth2": [
              "repository",
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Deployments"
        ]
      },
      "get": {
        "description": "Returns the deploy key belonging to a specific key.\n\nExample:\n```\n$ curl -H \"Authorization <auth header>\" \\\nhttps://api.bitbucket.org/2.0/repositories/mleu/test/deploy-key/1234\n\nOutput:\n{\n    \"comment\": \"mleu@C02W454JHTD8\",\n    \"last_used\": null,\n    \"links\": {\n        \"self\": {\n            \"href\": https://api.bitbucket.org/2.0/repositories/mleu/test/deploy-key/1234\"\n        }\n    },\n    \"repository\": {\n        \"full_name\": \"mleu/test[...]",
        "security": [
          {
            "oauth2": [
              "repository",
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Deployments"
        ]
      },
      "put": {
        "description": "Create a new deploy key in a repository.\n\nThe same key needs to be passed in but the comment and label can change.\n\nExample:\n```\n$ curl -XPUT \\\n-H \"Authorization <auth header>\" \\\n-H \"Content-type: application/json\" \\\nhttps://api.bitbucket.org/2.0/repositories/mleu/test/deploy-keys/1234 -d \\\n'{\n    \"label\": \"newlabel\",\n    \"key\": \"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAK/b1cHHDr/TEV1JGQl+WjCwStKG6Bhrv0rFpEsYlyTBm1fzN0VOJJYn4ZOPCPJwqse6fGbXntEs+B[...]",
        "security": [
          {
            "oauth2": [
              "repository",
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Deployments"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/deployments/": {
      "get": {
        "description": "Find deployments",
        "operationId": "getDeploymentsForRepository",
        "tags": [
          "Deployments"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/deployments/{deployment_uuid}": {
      "get": {
        "description": "Retrieve a deployment",
        "operationId": "getDeploymentForRepository",
        "tags": [
          "Deployments"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/deployments_config/environments/{environment_uuid}/variables": {
      "get": {
        "description": "Find deployment environment level variables.",
        "operationId": "getDeploymentVariables",
        "tags": [
          "Pipelines"
        ]
      },
      "post": {
        "description": "Create a deployment environment level variable.",
        "operationId": "createDeploymentVariable",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/deployments_config/environments/{environment_uuid}/variables/{variable_uuid}": {
      "delete": {
        "description": "Delete a deployment environment level variable.",
        "operationId": "deleteDeploymentVariable",
        "tags": [
          "Pipelines"
        ]
      },
      "put": {
        "description": "Update a deployment environment level variable.",
        "operationId": "updateDeploymentVariable",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/diff/{spec}": {
      "get": {
        "description": "Produces a raw git-style diff.\n\n#### Single commit spec\n\nIf the `spec` argument to this API is a single commit, the diff is\nproduced against the first parent of the specified commit.\n\n#### Two commit spec\n\nTwo commits separated by `..` may be provided as the `spec`, e.g.,\n`3a8b42..9ff173`. When two commits are provided and the `merge` query\nparameter is true or absent, this API produces a 3-way diff, also\nreferred to as a merge diff. This is equivalent to merg[...]",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Commits"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/diffstat/{spec}": {
      "get": {
        "description": "Produces a response in JSON format with a record for every path\nmodified, including information on the type of the change and the\nnumber of lines added and removed.\n\n#### Single commit spec\n\nIf the `spec` argument to this API is a single commit, the diff is\nproduced against the first parent of the specified commit.\n\n#### Two commit spec\n\nTwo commits separated by `..` may be provided as the `spec`, e.g.,\n`3a8b42..9ff173`. When two commits are provided and the `[...]",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Commits"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/downloads": {
      "get": {
        "description": "Returns a list of download links associated with the repository.",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Downloads"
        ]
      },
      "post": {
        "description": "Upload new download artifacts.\n\nTo upload files, perform a `multipart/form-data` POST containing one\nor more `files` fields:\n\n    $ echo Hello World > hello.txt\n    $ curl -s -u evzijst -X POST https://api.bitbucket.org/2.0/repositories/evzijst/git-tests/downloads -F files=@hello.txt\n\nWhen a file is uploaded with the same name as an existing artifact,\nthen the existing file will be replaced.",
        "security": [
          {
            "oauth2": [
              "repository:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Downloads"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/downloads/{filename}": {
      "delete": {
        "description": "Deletes the specified download artifact from the repository.",
        "security": [
          {
            "oauth2": [
              "repository:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Downloads"
        ]
      },
      "get": {
        "description": "Return a redirect to the contents of a download artifact.\n\nThis endpoint returns the actual file contents and not the artifact's\nmetadata.\n\n    $ curl -s -L https://api.bitbucket.org/2.0/repositories/evzijst/git-tests/downloads/hello.txt\n    Hello World",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Downloads"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/environments/": {
      "get": {
        "description": "Find environments",
        "operationId": "getEnvironmentsForRepository",
        "tags": [
          "Deployments"
        ]
      },
      "post": {
        "description": "Create an environment.",
        "operationId": "createEnvironment",
        "tags": [
          "Deployments"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/environments/{environment_uuid}": {
      "delete": {
        "description": "Delete an environment",
        "operationId": "deleteEnvironmentForRepository",
        "tags": [
          "Deployments"
        ]
      },
      "get": {
        "description": "Retrieve an environment",
        "operationId": "getEnvironmentForRepository",
        "tags": [
          "Deployments"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/environments/{environment_uuid}/changes/": {
      "post": {
        "description": "Update an environment",
        "operationId": "updateEnvironmentForRepository",
        "tags": [
          "Deployments"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/filehistory/{commit}/{path}": {
      "get": {
        "description": "Returns a paginated list of commits that modified the specified file.\n\nCommits are returned in reverse chronological order. This is roughly\nequivalent to the following commands:\n\n    $ git log --follow --date-order <sha> <path>\n\n    $ hg log --follow <path>\n\nBy default, Bitbucket will follow renames and the path name in the\nreturned entries reflects that. This can be turned off using the\n`?renames=false` query parameter.\n\nResults are returned in descending ch[...]",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Source",
          "Repositories"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/forks": {
      "get": {
        "description": "Returns a paginated list of all the forks of the specified\nrepository.",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Repositories"
        ]
      },
      "post": {
        "description": "Creates a new fork of the specified repository.\n\n## Forking a repository\n\nTo create a fork, specify the workspace explicitly as part of the\nrequest body:\n\n```\n$ curl -X POST -u jdoe https://api.bitbucket.org/2.0/repositories/atlassian/bbql/forks \\\n  -H 'Content-Type: application/json' -d '{\n    \"name\": \"bbql_fork\",\n    \"workspace\": {\n      \"slug\": \"atlassian\"\n    }\n}'\n```\n\nTo fork a repository into the same workspace, also specify a new `name`.[...]",
        "security": [
          {
            "oauth2": [
              "repository:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Repositories"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/hooks": {
      "get": {
        "description": "Returns a paginated list of webhooks installed on this repository.",
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Repositories",
          "Webhooks"
        ]
      },
      "post": {
        "description": "Creates a new webhook on the specified repository.\n\nExample:\n\n```\n$ curl -X POST -u credentials -H 'Content-Type: application/json'\n  https://api.bitbucket.org/2.0/repositories/my-workspace/my-repo-slug/hooks\n  -d '\n    {\n      \"description\": \"Webhook Description\",\n      \"url\": \"https://example.com/\",\n      \"active\": true,\n      \"events\": [\n        \"repo:push\",\n        \"issue:created\",\n        \"issue:updated\"\n      ]\n    }'\n```\n\nNote [...]",
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Repositories",
          "Webhooks"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/hooks/{uid}": {
      "delete": {
        "description": "Deletes the specified webhook subscription from the given\nrepository.",
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Repositories",
          "Webhooks"
        ]
      },
      "get": {
        "description": "Returns the webhook with the specified id installed on the specified\nrepository.",
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Repositories",
          "Webhooks"
        ]
      },
      "put": {
        "description": "Updates the specified webhook subscription.\n\nThe following properties can be mutated:\n\n* `description`\n* `url`\n* `active`\n* `events`",
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Repositories",
          "Webhooks"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/issues": {
      "get": {
        "description": "Returns the issues in the issue tracker.",
        "security": [
          {
            "oauth2": [
              "issue"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      },
      "post": {
        "description": "Creates a new issue.\n\nThis call requires authentication. Private repositories or private\nissue trackers require the caller to authenticate with an account that\nhas appropriate authorization.\n\nThe authenticated user is used for the issue's `reporter` field.",
        "security": [
          {
            "oauth2": [
              "issue:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/issues/export": {
      "post": {
        "description": "A POST request to this endpoint initiates a new background celery task that archives the repo's issues.\n\nFor example, you can run:\n\ncurl -u <username> -X POST http://api.bitbucket.org/2.0/repositories/<owner_username>/<repo_slug>/\nissues/export\n\nWhen the job has been accepted, it will return a 202 (Accepted) along with a unique url to this job in the\n'Location' response header. This url is the endpoint for where the user can obtain their zip files.\"",
        "security": [
          {
            "oauth2": [
              "issue",
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/issues/export/{repo_name}-issues-{task_id}.zip": {
      "get": {
        "description": "This endpoint is used to poll for the progress of an issue export\njob and return the zip file after the job is complete.\nAs long as the job is running, this will return a 200 response\nwith in the response body a description of the current status.\n\nAfter the job has been scheduled, but before it starts executing, this\nendpoint's response is:\n\n{\n \"type\": \"issue_job_status\",\n \"status\": \"ACCEPTED\",\n \"phase\": \"Initializing\",\n \"total\": 0,\n \"count\": [...]",
        "security": [
          {
            "oauth2": [
              "issue",
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/issues/import": {
      "get": {
        "description": "When using GET, this endpoint reports the status of the current import task. Request example:\n\n```\n$ curl -u <username> -X GET https://api.bitbucket.org/2.0/repositories/<owner_username>/<repo_slug>/issues/import\n```\n\nAfter the job has been scheduled, but before it starts executing, this endpoint's response is:\n\n```\n< HTTP/1.1 202 Accepted\n{\n    \"type\": \"issue_job_status\",\n    \"status\": \"PENDING\",\n    \"phase\": \"Attachments\",\n    \"total\": 15,\n [...]",
        "security": [
          {
            "oauth2": [
              "issue:write",
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      },
      "post": {
        "description": "A POST request to this endpoint will import the zip file given by the archive parameter into the repository. All\nexisting issues will be deleted and replaced by the contents of the imported zip file.\n\nImports are done through a multipart/form-data POST. There is one valid and required form field, with the name\n\"archive,\" which needs to be a file field:\n\n```\n$ curl -u <username> -X POST -F archive=@/path/to/file.zip https://api.bitbucket.org/2.0/repositories/<owne[...]",
        "security": [
          {
            "oauth2": [
              "issue:write",
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/issues/{issue_id}": {
      "delete": {
        "description": "Deletes the specified issue. This requires write access to the\nrepository.",
        "security": [
          {
            "oauth2": [
              "issue:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      },
      "get": {
        "description": "Returns the specified issue.",
        "security": [
          {
            "oauth2": [
              "issue"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      },
      "put": {
        "description": "Modifies the issue.\n\n```\n$ curl https://api.bitbucket.org/2.0/repostories/evzijst/dogslow/issues/123 \\\n  -u evzijst -s -X PUT -H 'Content-Type: application/json' \\\n  -d '{\n  \"title\": \"Updated title\",\n  \"assignee\": {\n    \"username\": \"evzijst\"\n  },\n  \"priority\": \"minor\",\n  \"version\": {\n    \"name\": \"1.0\"\n  },\n  \"component\": null\n}'\n```\n\nThis example changes the `title`, `assignee`, `priority` and the\n`version`. It also removes the v[...]",
        "security": [
          {
            "oauth2": [
              "issue:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/issues/{issue_id}/attachments": {
      "get": {
        "description": "Returns all attachments for this issue.\n\nThis returns the files' meta data. This does not return the files'\nactual contents.\n\nThe files are always ordered by their upload date.",
        "security": [
          {
            "oauth2": [
              "issue"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      },
      "post": {
        "description": "Upload new issue attachments.\n\nTo upload files, perform a `multipart/form-data` POST containing one\nor more file fields.\n\nWhen a file is uploaded with the same name as an existing attachment,\nthen the existing file will be replaced.",
        "security": [
          {
            "oauth2": [
              "issue:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/issues/{issue_id}/attachments/{path}": {
      "delete": {
        "description": "Deletes an attachment.",
        "security": [
          {
            "oauth2": [
              "issue:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      },
      "get": {
        "description": "Returns the contents of the specified file attachment.\n\nNote that this endpoint does not return a JSON response, but instead\nreturns a redirect pointing to the actual file that in turn will return\nthe raw contents.\n\nThe redirect URL contains a one-time token that has a limited lifetime.\nAs a result, the link should not be persisted, stored, or shared.",
        "security": [
          {
            "oauth2": [
              "issue"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/issues/{issue_id}/changes": {
      "get": {
        "description": "Returns the list of all changes that have been made to the specified\nissue. Changes are returned in chronological order with the oldest\nchange first.\n\nEach time an issue is edited in the UI or through the API, an immutable\nchange record is created under the `/issues/123/changes` endpoint. It\nalso has a comment associated with the change.\n\nNote that this operation is changing significantly, due to privacy changes.\nSee the [announcement](https://developer.atlassian[...]",
        "security": [
          {
            "oauth2": [
              "issue"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      },
      "post": {
        "description": "Makes a change to the specified issue.\n\nFor example, to change an issue's state and assignee, create a new\nchange object that modifies these fields:\n\n```\ncurl https://api.bitbucket.org/2.0/site/master/issues/1234/changes \\\n  -s -u evzijst -X POST -H \"Content-Type: application/json\" \\\n  -d '{\n    \"changes\": {\n      \"assignee_account_id\": {\n        \"new\": \"557058:c0b72ad0-1cb5-4018-9cdc-0cde8492c443\"\n      },\n      \"state\": {\n        \"new\": 're[...]",
        "security": [
          {
            "oauth2": [
              "issue:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/issues/{issue_id}/changes/{change_id}": {
      "get": {
        "description": "Returns the specified issue change object.\n\nThis resource is only available on repositories that have the issue\ntracker enabled.",
        "security": [
          {
            "oauth2": [
              "issue"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/issues/{issue_id}/comments": {
      "get": {
        "description": "Returns a paginated list of all comments that were made on the\nspecified issue.\n\nThe default sorting is oldest to newest and can be overridden with\nthe `sort` query parameter.\n\nThis endpoint also supports filtering and sorting of the results. See\n[filtering and sorting](../../../../../../meta/filtering) for more details.",
        "security": [
          {
            "oauth2": [
              "issue"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      },
      "post": {
        "description": "Creates a new issue comment.\n\n```\n$ curl https://api.bitbucket.org/2.0/repositories/atlassian/prlinks/issues/42/comments/ \\\n  -X POST -u evzijst \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"content\": {\"raw\": \"Lorem ipsum.\"}}'\n```",
        "security": [
          {
            "oauth2": [
              "issue:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/issues/{issue_id}/comments/{comment_id}": {
      "delete": {
        "description": "Deletes the specified comment.",
        "security": [
          {
            "oauth2": [
              "issue:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      },
      "get": {
        "description": "Returns the specified issue comment object.",
        "security": [
          {
            "oauth2": [
              "issue"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      },
      "put": {
        "description": "Updates the content of the specified issue comment. Note that only\nthe `content.raw` field can be modified.\n\n```\n$ curl https://api.bitbucket.org/2.0/repositories/atlassian/prlinks/issues/42/comments/5728901 \\\n  -X PUT -u evzijst \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"content\": {\"raw\": \"Lorem ipsum.\"}'\n```",
        "security": [
          {
            "oauth2": [
              "issue:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/issues/{issue_id}/vote": {
      "delete": {
        "description": "Retract your vote.",
        "security": [
          {
            "oauth2": [
              "account:write",
              "issue:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      },
      "get": {
        "description": "Check whether the authenticated user has voted for this issue.\nA 204 status code indicates that the user has voted, while a 404\nimplies they haven't.",
        "security": [
          {
            "oauth2": [
              "account",
              "issue"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      },
      "put": {
        "description": "Vote for this issue.\n\nTo cast your vote, do an empty PUT. The 204 status code indicates that\nthe operation was successful.",
        "security": [
          {
            "oauth2": [
              "account:write",
              "issue"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/issues/{issue_id}/watch": {
      "delete": {
        "description": "Stop watching this issue.",
        "security": [
          {
            "oauth2": [
              "account:write",
              "issue:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      },
      "get": {
        "description": "Indicated whether or not the authenticated user is watching this\nissue.",
        "security": [
          {
            "oauth2": [
              "account",
              "issue"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      },
      "put": {
        "description": "Start watching this issue.\n\nTo start watching this issue, do an empty PUT. The 204 status code\nindicates that the operation was successful.",
        "security": [
          {
            "oauth2": [
              "account:write",
              "issue"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/merge-base/{revspec}": {
      "get": {
        "description": "Returns the best common ancestor between two commits, specified in a revspec\nof 2 commits (e.g. 3a8b42..9ff173).\n\nIf more than one best common ancestor exists, only one will be returned. It is\nunspecified which will be returned.",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Commits"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/milestones": {
      "get": {
        "description": "Returns the milestones that have been defined in the issue tracker.\n\nThis resource is only available on repositories that have the issue\ntracker enabled.",
        "security": [
          {
            "oauth2": [
              "issue"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/milestones/{milestone_id}": {
      "get": {
        "description": "Returns the specified issue tracker milestone object.",
        "security": [
          {
            "oauth2": [
              "issue"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/patch/{spec}": {
      "get": {
        "description": "Produces a raw patch for a single commit (diffed against its first\nparent), or a patch-series for a revspec of 2 commits (e.g.\n`3a8b42..9ff173` where the first commit represents the source and the\nsecond commit the destination).\n\nIn case of the latter (diffing a revspec), a patch series is returned\nfor the commits on the source branch (`3a8b42` and its ancestors in\nour example). For Mercurial, a single patch is returned that combines\nthe changes of all commits on [...]",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Commits"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines-config/caches/": {
      "get": {
        "description": "Retrieve the repository pipelines caches.",
        "operationId": "getRepositoryPipelineCaches",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines-config/caches/{cache_uuid}": {
      "delete": {
        "description": "Delete a repository cache.",
        "operationId": "deleteRepositoryPipelineCache",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines-config/caches/{cache_uuid}/content-uri": {
      "get": {
        "description": "Retrieve the URI of the content of the specified cache.",
        "operationId": "getRepositoryPipelineCacheContentURI",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines/": {
      "get": {
        "description": "Find pipelines",
        "operationId": "getPipelinesForRepository",
        "tags": [
          "Pipelines"
        ]
      },
      "post": {
        "description": "Endpoint to create and initiate a pipeline.\nThere are a couple of different options to initiate a pipeline, where the payload of the request will determine which type of pipeline will be instantiated.\n# Trigger a Pipeline for a branch\nOne way to trigger pipelines is by specifying the branch for which you want to trigger a pipeline.\nThe specified branch will be used to determine which pipeline definition from the `bitbucket-pipelines.yml` file will be applied to initia[...]",
        "operationId": "createPipelineForRepository",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}": {
      "get": {
        "description": "Retrieve a specified pipeline",
        "operationId": "getPipelineForRepository",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/": {
      "get": {
        "description": "Find steps for the given pipeline.",
        "operationId": "getPipelineStepsForRepository",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}": {
      "get": {
        "description": "Retrieve a given step of a pipeline.",
        "operationId": "getPipelineStepForRepository",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}/log": {
      "get": {
        "description": "Retrieve the log file for a given step of a pipeline.\n\nThis endpoint supports (and encourages!) the use of [HTTP Range requests](https://tools.ietf.org/html/rfc7233) to deal with potentially very large log files.",
        "operationId": "getPipelineStepLogForRepository",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}/logs/{log_uuid}": {
      "get": {
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}/test_reports": {
      "get": {
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}/test_reports/test_cases": {
      "get": {
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}/test_reports/test_cases/{test_case_uuid}/test_case_reasons": {
      "get": {
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/stopPipeline": {
      "post": {
        "description": "Signal the stop of a pipeline and all of its steps that not have completed yet.",
        "operationId": "stopPipeline",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines_config": {
      "get": {
        "description": "Retrieve the repository pipelines configuration.",
        "operationId": "getRepositoryPipelineConfig",
        "tags": [
          "Pipelines"
        ]
      },
      "put": {
        "description": "Update the pipelines configuration for a repository.",
        "operationId": "updateRepositoryPipelineConfig",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines_config/build_number": {
      "put": {
        "description": "Update the next build number that should be assigned to a pipeline. The next build number that will be configured has to be strictly higher than the current latest build number for this repository.",
        "operationId": "updateRepositoryBuildNumber",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines_config/schedules/": {
      "get": {
        "description": "Retrieve the configured schedules for the given repository.",
        "operationId": "getRepositoryPipelineSchedules",
        "tags": [
          "Pipelines"
        ]
      },
      "post": {
        "description": "Create a schedule for the given repository.",
        "operationId": "createRepositoryPipelineSchedule",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines_config/schedules/{schedule_uuid}": {
      "delete": {
        "description": "Delete a schedule.",
        "operationId": "deleteRepositoryPipelineSchedule",
        "tags": [
          "Pipelines"
        ]
      },
      "get": {
        "description": "Retrieve a schedule by its UUID.",
        "operationId": "getRepositoryPipelineSchedule",
        "tags": [
          "Pipelines"
        ]
      },
      "put": {
        "description": "Update a schedule.",
        "operationId": "updateRepositoryPipelineSchedule",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines_config/schedules/{schedule_uuid}/executions/": {
      "get": {
        "description": "Retrieve the executions of a given schedule.",
        "operationId": "getRepositoryPipelineScheduleExecutions",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines_config/ssh/key_pair": {
      "delete": {
        "description": "Delete the repository SSH key pair.",
        "operationId": "deleteRepositoryPipelineKeyPair",
        "tags": [
          "Pipelines"
        ]
      },
      "get": {
        "description": "Retrieve the repository SSH key pair excluding the SSH private key. The private key is a write only field and will never be exposed in the logs or the REST API.",
        "operationId": "getRepositoryPipelineSshKeyPair",
        "tags": [
          "Pipelines"
        ]
      },
      "put": {
        "description": "Create or update the repository SSH key pair. The private key will be set as a default SSH identity in your build container.",
        "operationId": "updateRepositoryPipelineKeyPair",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines_config/ssh/known_hosts/": {
      "get": {
        "description": "Find repository level known hosts.",
        "operationId": "getRepositoryPipelineKnownHosts",
        "tags": [
          "Pipelines"
        ]
      },
      "post": {
        "description": "Create a repository level known host.",
        "operationId": "createRepositoryPipelineKnownHost",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines_config/ssh/known_hosts/{known_host_uuid}": {
      "delete": {
        "description": "Delete a repository level known host.",
        "operationId": "deleteRepositoryPipelineKnownHost",
        "tags": [
          "Pipelines"
        ]
      },
      "get": {
        "description": "Retrieve a repository level known host.",
        "operationId": "getRepositoryPipelineKnownHost",
        "tags": [
          "Pipelines"
        ]
      },
      "put": {
        "description": "Update a repository level known host.",
        "operationId": "updateRepositoryPipelineKnownHost",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines_config/variables/": {
      "get": {
        "description": "Find repository level variables.",
        "operationId": "getRepositoryPipelineVariables",
        "tags": [
          "Pipelines"
        ]
      },
      "post": {
        "description": "Create a repository level variable.",
        "operationId": "createRepositoryPipelineVariable",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines_config/variables/{variable_uuid}": {
      "delete": {
        "description": "Delete a repository level variable.",
        "operationId": "deleteRepositoryPipelineVariable",
        "tags": [
          "Pipelines"
        ]
      },
      "get": {
        "description": "Retrieve a repository level variable.",
        "operationId": "getRepositoryPipelineVariable",
        "tags": [
          "Pipelines"
        ]
      },
      "put": {
        "description": "Update a repository level variable.",
        "operationId": "updateRepositoryPipelineVariable",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/properties/{app_key}/{property_name}": {
      "delete": {
        "description": "Delete an [application property](/cloud/bitbucket/application-properties/) value stored against a repository.",
        "operationId": "deleteRepositoryHostedPropertyValue",
        "tags": [
          "properties"
        ]
      },
      "get": {
        "description": "Retrieve an [application property](/cloud/bitbucket/application-properties/) value stored against a repository.",
        "operationId": "getRepositoryHostedPropertyValue",
        "tags": [
          "properties"
        ]
      },
      "put": {
        "description": "Update an [application property](/cloud/bitbucket/application-properties/) value stored against a repository.",
        "operationId": "updateRepositoryHostedPropertyValue",
        "tags": [
          "properties"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests": {
      "get": {
        "description": "Returns all pull requests on the specified repository.\n\nBy default only open pull requests are returned. This can be controlled\nusing the `state` query parameter. To retrieve pull requests that are\nin one of multiple states, repeat the `state` parameter for each\nindividual state.\n\nThis endpoint also supports filtering and sorting of the results. See\n[filtering and sorting](../../../../meta/filtering) for more details.",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      },
      "post": {
        "description": "Creates a new pull request where the destination repository is\nthis repository and the author is the authenticated user.\n\nThe minimum required fields to create a pull request are `title` and\n`source`, specified by a branch name.\n\n```\ncurl https://api.bitbucket.org/2.0/repositories/my-username/my-repository/pullrequests \\\n    -u my-username:my-password \\\n    --request POST \\\n    --header 'Content-Type: application/json' \\\n    --data '{\n        \"title\": \"[...]",
        "security": [
          {
            "oauth2": [
              "pullrequest:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/activity": {
      "get": {
        "description": "Returns a paginated list of the pull request's activity log.\n\nThis handler serves both a v20 and internal endpoint. The v20 endpoint\nreturns reviewer comments, updates, approvals and request changes. The internal\nendpoint includes those plus tasks and attachments.\n\nComments created on a file or a line of code have an inline property.\n\nComment example:\n```\n{\n    \"pagelen\": 20,\n    \"values\": [\n        {\n            \"comment\": {\n                \"links\"[...]",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}": {
      "get": {
        "description": "Returns the specified pull request.",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      },
      "put": {
        "description": "Mutates the specified pull request.\n\nThis can be used to change the pull request's branches or description.\n\nOnly open pull requests can be mutated.",
        "security": [
          {
            "oauth2": [
              "pullrequest:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/activity": {
      "get": {
        "description": "Returns a paginated list of the pull request's activity log.\n\nThis handler serves both a v20 and internal endpoint. The v20 endpoint\nreturns reviewer comments, updates, approvals and request changes. The internal\nendpoint includes those plus tasks and attachments.\n\nComments created on a file or a line of code have an inline property.\n\nComment example:\n```\n{\n    \"pagelen\": 20,\n    \"values\": [\n        {\n            \"comment\": {\n                \"links\"[...]",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/approve": {
      "delete": {
        "description": "Redact the authenticated user's approval of the specified pull\nrequest.",
        "security": [
          {
            "oauth2": [
              "pullrequest:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      },
      "post": {
        "description": "Approve the specified pull request as the authenticated user.",
        "security": [
          {
            "oauth2": [
              "pullrequest:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/comments": {
      "get": {
        "description": "Returns a paginated list of the pull request's comments.\n\nThis includes both global, inline comments and replies.\n\nThe default sorting is oldest to newest and can be overridden with\nthe `sort` query parameter.\n\nThis endpoint also supports filtering and sorting of the results. See\n[filtering and sorting](../../../../../../meta/filtering) for more\ndetails.",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      },
      "post": {
        "description": "Creates a new pull request comment.\n\nReturns the newly created pull request comment.",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/comments/{comment_id}": {
      "delete": {
        "description": "Deletes a specific pull request comment.",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      },
      "get": {
        "description": "Returns a specific pull request comment.",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      },
      "put": {
        "description": "Updates a specific pull request comment.",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/commits": {
      "get": {
        "description": "Returns a paginated list of the pull request's commits.\n\nThese are the commits that are being merged into the destination\nbranch when the pull requests gets accepted.",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/decline": {
      "post": {
        "description": "Declines the pull request.",
        "security": [
          {
            "oauth2": [
              "pullrequest:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/diff": {
      "get": {
        "description": "Redirects to the [repository diff](../../diff/%7Bspec%7D)\nwith the revspec that corresponds to the pull request.",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/diffstat": {
      "get": {
        "description": "Redirects to the [repository diffstat](../../diffstat/%7Bspec%7D)\nwith the revspec that corresponds to the pull request.",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/merge": {
      "post": {
        "description": "Merges the pull request.",
        "security": [
          {
            "oauth2": [
              "pullrequest:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/merge/task-status/{task_id}": {
      "get": {
        "description": "When merging a pull request takes too long, the client receives a\ntask ID along with a 202 status code. The task ID can be used in a call\nto this endpoint to check the status of a merge task.\n\n```\ncurl -X GET https://api.bitbucket.org/2.0/repositories/atlassian/bitbucket/pullrequests/2286/merge/task-status/<task_id>\n```\n\nIf the merge task is not yet finished, a PENDING status will be returned.\n\n```\nHTTP/2 200\n{\n    \"task_status\": \"PENDING\",\n    \"links\"[...]",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/patch": {
      "get": {
        "description": "Redirects to the [repository patch](../../patch/%7Bspec%7D)\nwith the revspec that corresponds to pull request.",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/request-changes": {
      "delete": {
        "description": "",
        "security": [
          {
            "oauth2": [
              "pullrequest:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      },
      "post": {
        "description": "",
        "security": [
          {
            "oauth2": [
              "pullrequest:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Pullrequests"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/statuses": {
      "get": {
        "description": "Returns all statuses (e.g. build results) for the given pull\nrequest.",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Repositories",
          "Pullrequests",
          "Commit statuses"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pullrequest_id}/properties/{app_key}/{property_name}": {
      "delete": {
        "description": "Delete an [application property](/cloud/bitbucket/application-properties/) value stored against a pull request.",
        "operationId": "deletePullRequestHostedPropertyValue",
        "tags": [
          "properties"
        ]
      },
      "get": {
        "description": "Retrieve an [application property](/cloud/bitbucket/application-properties/) value stored against a pull request.",
        "operationId": "getPullRequestHostedPropertyValue",
        "tags": [
          "properties"
        ]
      },
      "put": {
        "description": "Update an [application property](/cloud/bitbucket/application-properties/) value stored against a pull request.",
        "operationId": "updatePullRequestHostedPropertyValue",
        "tags": [
          "properties"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/refs": {
      "get": {
        "description": "Returns the branches and tags in the repository.\n\nBy default, results will be in the order the underlying source control system returns them and identical to\nthe ordering one sees when running \"$ git show-ref\". Note that this follows simple\nlexical ordering of the ref names.\n\nThis can be undesirable as it does apply any natural sorting semantics, meaning for instance that refs are\nsorted [\"branch1\", \"branch10\", \"branch2\", \"v10\", \"v11\", \"v9\"] instead o[...]",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Refs"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/refs/branches": {
      "get": {
        "description": "Returns a list of all open branches within the specified repository.\n        Results will be in the order the source control manager returns them.\n\n        ```\n        $ curl -s https://api.bitbucket.org/2.0/repositories/atlassian/aui/refs/branches?pagelen=1 | jq .\n        {\n          \"pagelen\": 1,\n          \"size\": 187,\n          \"values\": [\n            {\n              \"name\": \"issue-9.3/AUI-5343-assistive-class\",\n              \"links\": {\n        [...]",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Refs"
        ]
      },
      "post": {
        "description": "Creates a new branch in the specified repository.\n\nThe payload of the POST should consist of a JSON document that\ncontains the name of the tag and the target hash.\n\n```\ncurl https://api.bitbucket.org/2.0/repositories/seanfarley/hg/refs/branches \\\n-s -u seanfarley -X POST -H \"Content-Type: application/json\" \\\n-d '{\n    \"name\" : \"smf/create-feature\",\n    \"target\" : {\n        \"hash\" : \"default\",\n    }\n}'\n```\n\nThis call requires authentication. P[...]",
        "security": [
          {
            "oauth2": [
              "repository:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Refs"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/refs/branches/{name}": {
      "delete": {
        "description": "Delete a branch in the specified repository.\n\nThe main branch is not allowed to be deleted and will return a 400\nresponse.\n\nThe branch name should not include any prefixes (e.g.\nrefs/heads).",
        "security": [
          {
            "oauth2": [
              "repository:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Refs"
        ]
      },
      "get": {
        "description": "Returns a branch object within the specified repository.\n\n        ```\n        $ curl -s https://api.bitbucket.org/2.0/repositories/atlassian/aui/refs/branches/master | jq .\n        {\n          \"name\": \"master\",\n          \"links\": {\n            \"commits\": {\n              \"href\": \"https://api.bitbucket.org/2.0/repositories/atlassian/aui/commits/master\"\n            },\n            \"self\": {\n              \"href\": \"https://api.bitbucket.org/2.0/repos[...]",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Refs"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/refs/tags": {
      "get": {
        "description": "Returns the tags in the repository.\n\nBy default, results will be in the order the underlying source control system returns them and identical to\nthe ordering one sees when running \"$ hg tags\" or \"$ git tag --list\". Note that this follows simple\nlexical ordering of the ref names.\n\nThis can be undesirable as it does apply any natural sorting semantics, meaning for instance that tags are\nsorted [\"v10\", \"v11\", \"v9\"] instead of [\"v9\", \"v10\", \"v11\"].\n\nS[...]",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Refs"
        ]
      },
      "post": {
        "description": "Creates a new tag in the specified repository.\n\nThe payload of the POST should consist of a JSON document that\ncontains the name of the tag and the target hash.\n\n```\ncurl https://api.bitbucket.org/2.0/repositories/jdoe/myrepo/refs/tags \\\n-s -u jdoe -X POST -H \"Content-Type: application/json\" \\\n-d '{\n    \"name\" : \"new-tag-name\",\n    \"target\" : {\n        \"hash\" : \"a1b2c3d4e5f6\",\n    }\n}'\n```\n\nThis endpoint does support using short hash prefixes[...]",
        "security": [
          {
            "oauth2": [
              "repository:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Refs"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/refs/tags/{name}": {
      "delete": {
        "description": "Delete a tag in the specified repository.\n\nFor Git, the tag name should not include any prefixes (e.g. refs/tags).\nFor Mercurial, this adds a commit to the main branch that removes the\nspecified tag.",
        "security": [
          {
            "oauth2": [
              "repository:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Refs"
        ]
      },
      "get": {
        "description": "Returns the specified tag.\n\n```\n$ curl -s https://api.bitbucket.org/2.0/repositories/seanfarley/hg/refs/tags/3.8 -G | jq .\n{\n  \"name\": \"3.8\",\n  \"links\": {\n    \"commits\": {\n      \"href\": \"https://api.bitbucket.org/2.0/repositories/seanfarley/hg/commits/3.8\"\n    },\n    \"self\": {\n      \"href\": \"https://api.bitbucket.org/2.0/repositories/seanfarley/hg/refs/tags/3.8\"\n    },\n    \"html\": {\n      \"href\": \"https://bitbucket.org/seanfarley/hg/co[...]",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Refs"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/src": {
      "get": {
        "description": "This endpoint redirects the client to the directory listing of the\nroot directory on the main branch.\n\nThis is equivalent to directly hitting\n[/2.0/repositories/{username}/{repo_slug}/src/{commit}/{path}](src/%7Bcommit%7D/%7Bpath%7D)\nwithout having to know the name or SHA1 of the repo's main branch.\n\nTo create new commits, [POST to this endpoint](#post)",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Source",
          "Repositories"
        ]
      },
      "post": {
        "description": "This endpoint is used to create new commits in the repository by\nuploading files.\n\nTo add a new file to a repository:\n\n```\n$ curl https://api.bitbucket.org/2.0/repositories/username/slug/src \\\n  -F /repo/path/to/image.png=@image.png\n```\n\nThis will create a new commit on top of the main branch, inheriting the\ncontents of the main branch, but adding (or overwriting) the\n`image.png` file to the repository in the `/repo/path/to` directory.\n\nTo create a commit t[...]",
        "security": [
          {
            "oauth2": [
              "repository:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Source",
          "Repositories"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/src/{commit}/{path}": {
      "get": {
        "description": "This endpoints is used to retrieve the contents of a single file,\nor the contents of a directory at a specified revision.\n\n## Raw file contents\n\nWhen `path` points to a file, this endpoint returns the raw contents.\nThe response's Content-Type is derived from the filename\nextension (not from the contents). The file contents are not processed\nand no character encoding/recoding is performed and as a result no\ncharacter encoding is included as part of the Content-Typ[...]",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Source",
          "Repositories"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/versions": {
      "get": {
        "description": "Returns the versions that have been defined in the issue tracker.\n\nThis resource is only available on repositories that have the issue\ntracker enabled.",
        "security": [
          {
            "oauth2": [
              "issue"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/versions/{version_id}": {
      "get": {
        "description": "Returns the specified issue tracker version object.",
        "security": [
          {
            "oauth2": [
              "issue"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Issue tracker"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/watchers": {
      "get": {
        "description": "Returns a paginated list of all the watchers on the specified\nrepository.",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Repositories"
        ]
      }
    },
    "/snippets": {
      "get": {
        "description": "Returns all snippets. Like pull requests, repositories and workspaces, the\nfull set of snippets is defined by what the current user has access to.\n\nThis includes all snippets owned by any of the workspaces the user is a member of,\nor snippets by other users that the current user is either watching or has collaborated\non (for instance by commenting on it).\n\nTo limit the set of returned snippets, apply the\n`?role=[owner|contributor|member]` query parameter where the[...]",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      },
      "post": {
        "description": "Creates a new snippet under the authenticated user's account.\n\nSnippets can contain multiple files. Both text and binary files are\nsupported.\n\nThe simplest way to create a new snippet from a local file:\n\n    $ curl -u username:password -X POST https://api.bitbucket.org/2.0/snippets               -F file=@image.png\n\nCreating snippets through curl has a few limitations and so let's look\nat a more complicated scenario.\n\nSnippets are created with a multipart POST.[...]",
        "security": [
          {
            "oauth2": [
              "snippet:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      }
    },
    "/snippets/{workspace}": {
      "get": {
        "description": "Identical to [`/snippets`](../snippets), except that the result is further filtered\nby the snippet owner and only those that are owned by `{workspace}` are\nreturned.",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      },
      "post": {
        "description": "Identical to [`/snippets`](../snippets#post), except that the new snippet will be\ncreated under the workspace specified in the path parameter\n`{workspace}`.",
        "security": [
          {
            "oauth2": [
              "snippet:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      }
    },
    "/snippets/{workspace}/{encoded_id}": {
      "delete": {
        "description": "Deletes a snippet and returns an empty response.",
        "security": [
          {
            "oauth2": [
              "snippet:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      },
      "get": {
        "description": "Retrieves a single snippet.\n\nSnippets support multiple content types:\n\n* application/json\n* multipart/related\n* multipart/form-data\n\n\napplication/json\n----------------\n\nThe default content type of the response is `application/json`.\nSince JSON is always `utf-8`, it cannot reliably contain file contents\nfor files that are not text. Therefore, JSON snippet documents only\ncontain the filename and links to the file contents.\n\nThis means that in order to retri[...]",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      },
      "put": {
        "description": "Used to update a snippet. Use this to add and delete files and to\nchange a snippet's title.\n\nTo update a snippet, one can either PUT a full snapshot, or only the\nparts that need to be changed.\n\nThe contract for PUT on this API is that properties missing from the\nrequest remain untouched so that snippets can be efficiently\nmanipulated with differential payloads.\n\nTo delete a property (e.g. the title, or a file), include its name in\nthe request, but omit its valu[...]",
        "security": [
          {
            "oauth2": [
              "snippet:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      }
    },
    "/snippets/{workspace}/{encoded_id}/comments": {
      "get": {
        "description": "Used to retrieve a paginated list of all comments for a specific\nsnippet.\n\nThis resource works identical to commit and pull request comments.\n\nThe default sorting is oldest to newest and can be overridden with\nthe `sort` query parameter.",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      },
      "post": {
        "description": "Creates a new comment.\n\nThe only required field in the body is `content.raw`.\n\nTo create a threaded reply to an existing comment, include `parent.id`.",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      }
    },
    "/snippets/{workspace}/{encoded_id}/comments/{comment_id}": {
      "delete": {
        "description": "Deletes a snippet comment.\n\nComments can only be removed by their author.",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      },
      "get": {
        "description": "Returns the specific snippet comment.",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      },
      "put": {
        "description": "Updates a comment.\n\nComments can only be updated by their author.",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      }
    },
    "/snippets/{workspace}/{encoded_id}/commits": {
      "get": {
        "description": "Returns the changes (commits) made on this snippet.",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      }
    },
    "/snippets/{workspace}/{encoded_id}/commits/{revision}": {
      "get": {
        "description": "Returns the changes made on this snippet in this commit.",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      }
    },
    "/snippets/{workspace}/{encoded_id}/files/{path}": {
      "get": {
        "description": "Convenience resource for getting to a snippet's raw files without the\nneed for first having to retrieve the snippet itself and having to pull\nout the versioned file links.",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      }
    },
    "/snippets/{workspace}/{encoded_id}/watch": {
      "delete": {
        "description": "Used to stop watching a specific snippet. Returns 204 (No Content)\nto indicate success.",
        "security": [
          {
            "oauth2": [
              "snippet:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      },
      "get": {
        "description": "Used to check if the current user is watching a specific snippet.\n\nReturns 204 (No Content) if the user is watching the snippet and 404 if\nnot.\n\nHitting this endpoint anonymously always returns a 404.",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      },
      "put": {
        "description": "Used to start watching a specific snippet. Returns 204 (No Content).",
        "security": [
          {
            "oauth2": [
              "snippet:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      }
    },
    "/snippets/{workspace}/{encoded_id}/watchers": {
      "get": {
        "deprecated": true,
        "description": "Returns a paginated list of all users watching a specific snippet.",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      }
    },
    "/snippets/{workspace}/{encoded_id}/{node_id}": {
      "delete": {
        "description": "Deletes the snippet.\n\nNote that this only works for versioned URLs that point to the latest\ncommit of the snippet. Pointing to an older commit results in a 405\nstatus code.\n\nTo delete a snippet, regardless of whether or not concurrent changes\nare being made to it, use `DELETE /snippets/{encoded_id}` instead.",
        "security": [
          {
            "oauth2": [
              "snippet:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      },
      "get": {
        "description": "Identical to `GET /snippets/encoded_id`, except that this endpoint\ncan be used to retrieve the contents of the snippet as it was at an\nolder revision, while `/snippets/encoded_id` always returns the\nsnippet's current revision.\n\nNote that only the snippet's file contents are versioned, not its\nmeta data properties like the title.\n\nOther than that, the two endpoints are identical in behavior.",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      },
      "put": {
        "description": "Identical to `UPDATE /snippets/encoded_id`, except that this endpoint\ntakes an explicit commit revision. Only the snippet's \"HEAD\"/\"tip\"\n(most recent) version can be updated and requests on all other,\nolder revisions fail by returning a 405 status.\n\nUsage of this endpoint over the unrestricted `/snippets/encoded_id`\ncould be desired if the caller wants to be sure no concurrent\nmodifications have taken place between the moment of the UPDATE\nrequest and the orig[...]",
        "security": [
          {
            "oauth2": [
              "snippet:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      }
    },
    "/snippets/{workspace}/{encoded_id}/{node_id}/files/{path}": {
      "get": {
        "description": "Retrieves the raw contents of a specific file in the snippet. The\n`Content-Disposition` header will be \"attachment\" to avoid issues with\nmalevolent executable files.\n\nThe file's mime type is derived from its filename and returned in the\n`Content-Type` header.\n\nNote that for text files, no character encoding is included as part of\nthe content type.",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      }
    },
    "/snippets/{workspace}/{encoded_id}/{revision}/diff": {
      "get": {
        "description": "Returns the diff of the specified commit against its first parent.\n\nNote that this resource is different in functionality from the `patch`\nresource.\n\nThe differences between a diff and a patch are:\n\n* patches have a commit header with the username, message, etc\n* diffs support the optional `path=foo/bar.py` query param to filter the\n  diff to just that one file diff (not supported for patches)\n* for a merge, the diff will show the diff between the merge commit a[...]",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      }
    },
    "/snippets/{workspace}/{encoded_id}/{revision}/patch": {
      "get": {
        "description": "Returns the patch of the specified commit against its first\nparent.\n\nNote that this resource is different in functionality from the `diff`\nresource.\n\nThe differences between a diff and a patch are:\n\n* patches have a commit header with the username, message, etc\n* diffs support the optional `path=foo/bar.py` query param to filter the\n  diff to just that one file diff (not supported for patches)\n* for a merge, the diff will show the diff between the merge commit [...]",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Snippets"
        ]
      }
    },
    "/teams": {
      "get": {
        "deprecated": true,
        "description": "Returns all the teams that the authenticated user is associated\nwith.\n\n**This endpoint has been deprecated,\nand you should use the [workspaces](./workspaces) endpoint.\nFor more information, see [this post](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**",
        "security": [
          {
            "oauth2": [
              "team"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Teams"
        ]
      }
    },
    "/teams/{username}": {
      "get": {
        "deprecated": true,
        "description": "Gets the public information associated with a team.\n\nIf the team's profile is private, `location`, `website` and\n`created_on` elements are omitted.\n\n**This endpoint has been deprecated,\nand you should use the [workspace](../workspaces/%7Bworkspace%7D) endpoint.\nFor more information, see [this post](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**",
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Teams"
        ]
      }
    },
    "/teams/{username}/followers": {
      "get": {
        "deprecated": true,
        "description": "Returns the list of accounts that are following this team.\n\n**This endpoint has been deprecated. There is no workspaces replacement.\nFor more information, see [this post](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**",
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Teams"
        ]
      }
    },
    "/teams/{username}/following": {
      "get": {
        "deprecated": true,
        "description": "Returns the list of accounts this team is following.\n\n**This endpoint has been deprecated. There is no workspaces replacement.\nFor more information, see [this post](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**",
        "security": [
          {
            "oauth2": [
              "account"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Teams"
        ]
      }
    },
    "/teams/{username}/hooks": {
      "get": {
        "deprecated": true,
        "description": "Returns a paginated list of webhooks installed on this team.\n\n**This endpoint has been deprecated, and you should\nuse the new [workspace hooks](../../workspaces/%7Bworkspace%7D/hooks#get) endpoint.\nFor more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**",
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Teams",
          "Webhooks"
        ]
      },
      "post": {
        "deprecated": true,
        "description": "Creates a new webhook on the specified team.\n\nTeam webhooks are fired for events from all repositories belonging to\nthat team account.\n\nNote that only admins can install webhooks on teams.\n\n**This endpoint has been deprecated, and you should\nuse the new [workspace hooks](../../workspaces/%7Bworkspace%7D/hooks#post) endpoint.\nFor more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**",
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Teams",
          "Webhooks"
        ]
      }
    },
    "/teams/{username}/hooks/{uid}": {
      "delete": {
        "deprecated": true,
        "description": "Deletes the specified webhook subscription from the given team\naccount.\n\n**This endpoint has been deprecated, and you should\nuse the new [workspace hooks](../../../workspaces/%7Bworkspace%7D/hooks/%7Buid%7D#delete) endpoint.\nFor more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**",
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Teams",
          "Webhooks"
        ]
      },
      "get": {
        "deprecated": true,
        "description": "Returns the webhook with the specified id installed on the given\nteam account.\n\n**This endpoint has been deprecated, and you should\nuse the new [workspace hooks](../../../workspaces/%7Bworkspace%7D/hooks/%7Buid%7D#get) endpoint.\nFor more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**",
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Teams",
          "Webhooks"
        ]
      },
      "put": {
        "deprecated": true,
        "description": "Updates the specified webhook subscription.\n\nThe following properties can be mutated:\n\n* `description`\n* `url`\n* `active`\n* `events`\n\n**This endpoint has been deprecated, and you should\nuse the new [workspace hooks](../../../workspaces/%7Bworkspace%7D/hooks/%7Buid%7D#put) endpoint.\nFor more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**",
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Teams",
          "Webhooks"
        ]
      }
    },
    "/teams/{username}/members": {
      "get": {
        "deprecated": true,
        "description": "Returns all members of the specified team. Any member of any of the\nteam's groups is considered a member of the team. This includes users\nin groups that may not actually have access to any of the team's\nrepositories.\n\n**This operation has been deprecated due to privacy changes.\nSee the [announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/)\nfor details.\nYou should this [workspaces](../../workspaces/%7Bworkspace%7D/members) endpo[...]",
        "security": [
          {
            "oauth2": [
              "account"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Teams"
        ]
      }
    },
    "/teams/{username}/permissions": {
      "get": {
        "deprecated": true,
        "description": "Returns an object for each team permission a user on the team has.\n\n**This endpoint has been deprecated,\nand you should use the [workspace permissions](../../workspaces/%7Bworkspace%7D/permissions) endpoint.\nFor more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**\n\nPermissions returned are effective permissions — if a user is a member of\nmultiple groups with distinct roles, only the highest le[...]",
        "security": [
          {
            "oauth2": [
              "team"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Teams"
        ]
      }
    },
    "/teams/{username}/permissions/repositories": {
      "get": {
        "deprecated": true,
        "description": "Returns an object for each repository permission for all of a\nteam’s repositories.\n\n**This endpoint has been deprecated,\nand you should use the [workspace repository permissions](../../../workspaces/%7Bworkspace%7D/permissions/repositories) endpoint.\nFor more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**\n\nIf the username URL parameter refers to a user account instead of\na team account, an o[...]",
        "security": [
          {
            "oauth2": [
              "repository",
              "team"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Teams"
        ]
      }
    },
    "/teams/{username}/permissions/repositories/{repo_slug}": {
      "get": {
        "deprecated": true,
        "description": "Returns an object for each repository permission of a given repository.\n\n**This endpoint has been deprecated,\nand you should use the [workspace repository permissions](../../../../workspaces/%7Bworkspace%7D/permissions/repositories/%7Brepo_slug%7D) endpoint.\nFor more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**\n\nIf the username URL parameter refers to a user account instead of\na team accoun[...]",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Teams"
        ]
      }
    },
    "/teams/{username}/pipelines_config/variables/": {
      "get": {
        "deprecated": true,
        "description": "Find account level variables.\nThis endpoint has been deprecated, and you should use the new workspaces endpoint. For more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).",
        "operationId": "getPipelineVariablesForTeam",
        "tags": [
          "Pipelines"
        ]
      },
      "post": {
        "deprecated": true,
        "description": "Create an account level variable.\nThis endpoint has been deprecated, and you should use the new workspaces endpoint. For more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).",
        "operationId": "createPipelineVariableForTeam",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/teams/{username}/pipelines_config/variables/{variable_uuid}": {
      "delete": {
        "deprecated": true,
        "description": "Delete a team level variable.\nThis endpoint has been deprecated, and you should use the new workspaces endpoint. For more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).",
        "operationId": "deletePipelineVariableForTeam",
        "tags": [
          "Pipelines"
        ]
      },
      "get": {
        "deprecated": true,
        "description": "Retrieve a team level variable.\nThis endpoint has been deprecated, and you should use the new workspaces endpoint. For more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).",
        "operationId": "getPipelineVariableForTeam",
        "tags": [
          "Pipelines"
        ]
      },
      "put": {
        "deprecated": true,
        "description": "Update a team level variable.\nThis endpoint has been deprecated, and you should use the new workspaces endpoint. For more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).",
        "operationId": "updatePipelineVariableForTeam",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/teams/{username}/projects/": {
      "get": {
        "deprecated": true,
        "description": "**This endpoint has been deprecated,\nand you should use the [workspace projects](../../../workspaces/%7Bworkspace%7D/projects#get) endpoint.\nFor more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**",
        "security": [
          {
            "oauth2": [
              "project"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Projects"
        ]
      },
      "post": {
        "deprecated": true,
        "description": "Creates a new project.\n\n**This endpoint has been deprecated,\nand you should use the [workspace projects](../../../workspaces/%7Bworkspace%7D/projects#post) endpoint.\nFor more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**\n\nNote that the avatar has to be embedded as either a data-url\nor a URL to an external image as shown in the examples below:\n\n```\n$ body=$(cat << EOF\n{\n    \"name\": \"M[...]",
        "security": [
          {
            "oauth2": [
              "project:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Projects"
        ]
      }
    },
    "/teams/{username}/projects/{project_key}": {
      "delete": {
        "deprecated": true,
        "description": "**This endpoint has been deprecated,\nand you should use the [workspace project](../../../workspaces/%7Bworkspace%7D/projects/%7Bproject_key%7D#delete) endpoint.\nFor more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**",
        "security": [
          {
            "oauth2": [
              "project:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Projects"
        ]
      },
      "get": {
        "deprecated": true,
        "description": "**This endpoint has been deprecated,\nand you should use the [workspace project](../../../workspaces/%7Bworkspace%7D/projects/%7Bproject_key%7D#get) endpoint.\nFor more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**",
        "security": [
          {
            "oauth2": [
              "project"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Projects"
        ]
      },
      "put": {
        "deprecated": true,
        "description": "Since this endpoint can be used to both update and to create a\nproject, the request body depends on the intent.\n\n**This endpoint has been deprecated,\nand you should use the [workspace project](../../../workspaces/%7Bworkspace%7D/projects/%7Bproject_key%7D#put) endpoint.\nFor more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**\n\n### Creation\n\nSee the POST documentation for the project collecti[...]",
        "security": [
          {
            "oauth2": [
              "project:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Projects"
        ]
      }
    },
    "/teams/{username}/search/code": {
      "get": {
        "operationId": "searchAccount",
        "summary": "Search for code in the repositories of the specified team.\n\nSearching across all repositories:\n\n```\ncurl 'https://api.bitbucket.org/2.0/teams/team_name/search/code?search_query=foo'\n{\n  \"size\": 1,\n  \"page\": 1,\n  \"pagelen\": 10,\n  \"query_substituted\": false,\n  \"values\": [\n    {\n      \"type\": \"code_search_result\",\n      \"content_match_count\": 2,\n      \"content_matches\": [\n        {\n          \"lines\": [\n            {\n              \"line\": [...]",
        "tags": [
          "Search"
        ]
      }
    },
    "/teams/{workspace}/repositories": {
      "get": {
        "deprecated": true,
        "description": "All repositories in the given workspace. This includes any private\nrepositories the calling user has access to.\n\n**This endpoint has been deprecated,\nand you should use the [repository list](../../repositories/%7Bworkspace%7D) endpoint.\nFor more information, see the [deprecation announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Users",
          "Teams"
        ]
      }
    },
    "/user": {
      "get": {
        "description": "Returns the currently logged in user.",
        "security": [
          {
            "oauth2": [
              "account"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Users"
        ]
      }
    },
    "/user/emails": {
      "get": {
        "description": "Returns all the authenticated user's email addresses. Both\nconfirmed and unconfirmed.",
        "security": [
          {
            "oauth2": [
              "email"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Users"
        ]
      }
    },
    "/user/emails/{email}": {
      "get": {
        "description": "Returns details about a specific one of the authenticated user's\nemail addresses.\n\nDetails describe whether the address has been confirmed by the user and\nwhether it is the user's primary address or not.",
        "security": [
          {
            "oauth2": [
              "email"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Users"
        ]
      }
    },
    "/user/permissions/repositories": {
      "get": {
        "description": "Returns an object for each repository the caller has explicit access\nto and their effective permission — the highest level of permission the\ncaller has. This does not return public repositories that the user was\nnot granted any specific permission in, and does not distinguish between\ndirect and indirect privileges.\n\nPermissions can be:\n\n* `admin`\n* `write`\n* `read`\n\nExample:\n\n```\n$ curl https://api.bitbucket.org/2.0/user/permissions/repositories\n\n{\n  \"p[...]",
        "security": [
          {
            "oauth2": [
              "account",
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Repositories"
        ]
      }
    },
    "/user/permissions/teams": {
      "get": {
        "deprecated": true,
        "description": "Returns an object for each team the caller is a member of, and their\neffective role — the highest level of privilege the caller has. If a\nuser is a member of multiple groups with distinct roles, only the\nhighest level is returned.\n\n**This endpoint has been deprecated,\nand you should use the [workspace permissions](./workspaces) endpoint.\nFor more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**[...]",
        "security": [
          {
            "oauth2": [
              "account"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Teams"
        ]
      }
    },
    "/user/permissions/workspaces": {
      "get": {
        "description": "Returns an object for each workspace the caller is a member of, and\ntheir effective role - the highest level of privilege the caller has.\nIf a user is a member of multiple groups with distinct roles, only the\nhighest level is returned.\n\nPermissions can be:\n\n* `owner`\n* `collaborator`\n* `member`\n\nExample:\n\n```\n$ curl https://api.bitbucket.org/2.0/user/permissions/workspaces\n\n{\n  \"pagelen\": 10,\n  \"page\": 1,\n  \"size\": 1,\n  \"values\": [\n    {\n    [...]",
        "security": [
          {
            "oauth2": [
              "account"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Workspaces"
        ]
      }
    },
    "/users/{selected_user}": {
      "get": {
        "description": "Gets the public information associated with a user account.\n\nIf the user's profile is private, `location`, `website` and\n`created_on` elements are omitted.\n\nNote that the user object returned by this operation is changing significantly, due to privacy changes.\nSee the [announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/#changes-to-bitbucket-user-objects) for details.",
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Users"
        ]
      }
    },
    "/users/{selected_user}/hooks": {
      "get": {
        "deprecated": true,
        "description": "Returns a paginated list of webhooks installed on this user account.\n\nNote that the username path parameter has been deprecated due to\n[privacy changes](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/#removal-of-usernames-from-user-referencing-apis).\nUse the account's UUID or account_id instead.\n\n**This endpoint has been deprecated, and you should\nuse the new [workspace hooks](../../workspaces/%7Bworkspace%7D/hooks#get) endpoint.\nFor mo[...]",
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Users",
          "Webhooks"
        ]
      },
      "post": {
        "deprecated": true,
        "description": "Creates a new webhook on the specified user account.\n\nAccount-level webhooks are fired for events from all repositories\nbelonging to that account.\n\nNote that one can only register webhooks on one's own account, not that\nof others.\n\nAlso, note that the username path parameter has been deprecated due to\n[privacy changes](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/#removal-of-usernames-from-user-referencing-apis).\nUse the account's U[...]",
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Users",
          "Webhooks"
        ]
      }
    },
    "/users/{selected_user}/hooks/{uid}": {
      "delete": {
        "deprecated": true,
        "description": "Deletes the specified webhook subscription from the given user\naccount.\n\nNote that the username path parameter has been deprecated due to\n[privacy changes](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/#removal-of-usernames-from-user-referencing-apis).\nUse the account's UUID or account_id instead.\n\n**This endpoint has been deprecated, and you should\nuse the new [workspace hooks](../../../workspaces/%7Bworkspace%7D/hooks/%7Buid%7D#delet[...]",
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Users",
          "Webhooks"
        ]
      },
      "get": {
        "deprecated": true,
        "description": "Returns the webhook with the specified id installed on the given\nuser account.\n\nNote that the username path parameter has been deprecated due to\n[privacy changes](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/#removal-of-usernames-from-user-referencing-apis).\nUse the account's UUID or account_id instead.\n\n**This endpoint has been deprecated, and you should\nuse the new [workspace hook details](../../../workspaces/%7Bworkspace%7D/hooks/%[...]",
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Users",
          "Webhooks"
        ]
      },
      "put": {
        "deprecated": true,
        "description": "Updates the specified webhook subscription.\n\nThe following properties can be mutated:\n\n* `description`\n* `url`\n* `active`\n* `events`\n\nNote that the username path parameter has been deprecated due to\n[privacy changes](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/#removal-of-usernames-from-user-referencing-apis).\nUse the account's UUID or account_id instead.\n\n**This endpoint has been deprecated, and you should\nuse the new [workspa[...]",
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Users",
          "Webhooks"
        ]
      }
    },
    "/users/{selected_user}/pipelines_config/variables/": {
      "get": {
        "deprecated": true,
        "description": "Find user level variables.\nThis endpoint has been deprecated, and you should use the new workspaces endpoint. For more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).",
        "operationId": "getPipelineVariablesForUser",
        "tags": [
          "Pipelines"
        ]
      },
      "post": {
        "deprecated": true,
        "description": "Create a user level variable.\nThis endpoint has been deprecated, and you should use the new workspaces endpoint. For more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).",
        "operationId": "createPipelineVariableForUser",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/users/{selected_user}/pipelines_config/variables/{variable_uuid}": {
      "delete": {
        "deprecated": true,
        "description": "Delete an account level variable.\nThis endpoint has been deprecated, and you should use the new workspaces endpoint. For more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).",
        "operationId": "deletePipelineVariableForUser",
        "tags": [
          "Pipelines"
        ]
      },
      "get": {
        "deprecated": true,
        "description": "Retrieve a user level variable.\nThis endpoint has been deprecated, and you should use the new workspaces endpoint. For more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).",
        "operationId": "getPipelineVariableForUser",
        "tags": [
          "Pipelines"
        ]
      },
      "put": {
        "deprecated": true,
        "description": "Update a user level variable.\nThis endpoint has been deprecated, and you should use the new workspaces endpoint. For more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).",
        "operationId": "updatePipelineVariableForUser",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/users/{selected_user}/properties/{app_key}/{property_name}": {
      "delete": {
        "description": "Delete an [application property](/cloud/bitbucket/application-properties/) value stored against a user.",
        "operationId": "deleteUserHostedPropertyValue",
        "tags": [
          "properties"
        ]
      },
      "get": {
        "description": "Retrieve an [application property](/cloud/bitbucket/application-properties/) value stored against a user.",
        "operationId": "retrieveUserHostedPropertyValue",
        "tags": [
          "properties"
        ]
      },
      "put": {
        "description": "Update an [application property](/cloud/bitbucket/application-properties/) value stored against a user.",
        "operationId": "updateUserHostedPropertyValue",
        "tags": [
          "properties"
        ]
      }
    },
    "/users/{selected_user}/search/code": {
      "get": {
        "summary": "Search for code in the repositories of the specified user.\n\nSearching across all repositories:\n\n```\ncurl 'https://api.bitbucket.org/2.0/users/{ed08f5e1-605b-4f4a-aee4-6c97628a673e}/search/code?search_query=foo'\n{\n  \"size\": 1,\n  \"page\": 1,\n  \"pagelen\": 10,\n  \"query_substituted\": false,\n  \"values\": [\n    {\n      \"type\": \"code_search_result\",\n      \"content_match_count\": 2,\n      \"content_matches\": [\n        {\n          \"lines\": [\n          [...]",
        "tags": [
          "Search"
        ]
      }
    },
    "/users/{selected_user}/ssh-keys": {
      "get": {
        "description": "Returns a paginated list of the user's SSH public keys.\n\nExample:\n\n```\n$ curl https://api.bitbucket.org/2.0/users/{ed08f5e1-605b-4f4a-aee4-6c97628a673e}/ssh-keys\n{\n    \"page\": 1,\n    \"pagelen\": 10,\n    \"size\": 1,\n    \"values\": [\n        {\n            \"comment\": \"user@myhost\",\n            \"created_on\": \"2018-03-14T13:17:05.196003+00:00\",\n            \"key\": \"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKqP3Cr632C2dNhhgKVcon4ldUSAeKiku2yP9O9/bDtY\",\[...]",
        "security": [
          {
            "oauth2": [
              "account"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Ssh"
        ]
      },
      "post": {
        "description": "Adds a new SSH public key to the specified user account and returns the resulting key.\n\nExample:\n```\n$ curl -X POST -H \"Content-Type: application/json\" -d '{\"key\": \"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKqP3Cr632C2dNhhgKVcon4ldUSAeKiku2yP9O9/bDtY user@myhost\"}' https://api.bitbucket.org/2.0/users/{ed08f5e1-605b-4f4a-aee4-6c97628a673e}/ssh-keys\n\n{\n    \"comment\": \"user@myhost\",\n    \"created_on\": \"2018-03-14T13:17:05.196003+00:00\",\n    \"key\": \"ssh-ed[...]",
        "security": [
          {
            "oauth2": [
              "account:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Ssh"
        ]
      }
    },
    "/users/{selected_user}/ssh-keys/{key_id}": {
      "delete": {
        "description": "Deletes a specific SSH public key from a user's account\n\nExample:\n```\n$ curl -X DELETE https://api.bitbucket.org/2.0/users/{ed08f5e1-605b-4f4a-aee4-6c97628a673e}/ssh-keys/{b15b6026-9c02-4626-b4ad-b905f99f763a}\n```",
        "security": [
          {
            "oauth2": [
              "account:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Ssh"
        ]
      },
      "get": {
        "description": "Returns a specific SSH public key belonging to a user.\n\nExample:\n```\n$ curl https://api.bitbucket.org/2.0/users/{ed08f5e1-605b-4f4a-aee4-6c97628a673e}/ssh-keys/{fbe4bbab-f6f7-4dde-956b-5c58323c54b3}\n\n{\n    \"comment\": \"user@myhost\",\n    \"created_on\": \"2018-03-14T13:17:05.196003+00:00\",\n    \"key\": \"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKqP3Cr632C2dNhhgKVcon4ldUSAeKiku2yP9O9/bDtY\",\n    \"label\": \"\",\n    \"last_used\": \"2018-03-20T13:18:05.196003+00:[...]",
        "security": [
          {
            "oauth2": [
              "account"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Ssh"
        ]
      },
      "put": {
        "description": "Updates a specific SSH public key on a user's account\n\nNote: Only the 'comment' field can be updated using this API. To modify the key or comment values, you must delete and add the key again.\n\nExample:\n```\n$ curl -X PUT -H \"Content-Type: application/json\" -d '{\"label\": \"Work key\"}' https://api.bitbucket.org/2.0/users/{ed08f5e1-605b-4f4a-aee4-6c97628a673e}/ssh-keys/{b15b6026-9c02-4626-b4ad-b905f99f763a}\n\n{\n    \"comment\": \"\",\n    \"created_on\": \"2018-[...]",
        "security": [
          {
            "oauth2": [
              "account:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Ssh"
        ]
      }
    },
    "/users/{username}/members": {
      "get": {
        "deprecated": true,
        "description": "**This endpoint has been deprecated,\nand you should use the [workspaces](../../workspaces/%7Bworkspace%7D/members) endpoint.\nFor more information, see [this post](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**",
        "security": [
          {
            "oauth2": [
              "account"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Users"
        ]
      }
    },
    "/users/{workspace}/repositories": {
      "get": {
        "deprecated": true,
        "description": "All repositories in the given workspace. This includes any private\nrepositories the calling user has access to.\n\n**This endpoint has been deprecated,\nand you should use the [repository list](../../repositories/%7Bworkspace%7D) endpoint.\nFor more information, see the [deprecation announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Users",
          "Teams"
        ]
      }
    },
    "/workspaces": {
      "get": {
        "description": "Returns a list of workspaces accessible by the authenticated user.\n\nExample:\n\n```\n$ curl https://api.bitbucket.org/2.0/workspaces\n\n{\n  \"pagelen\": 10,\n  \"page\": 1,\n  \"size\": 1,\n  \"values\": [\n    {\n        \"uuid\": \"{a15fb181-db1f-48f7-b41f-e1eff06929d6}\",\n        \"links\": {\n            \"owners\": {\n                \"href\": \"https://api.bitbucket.org/2.0/workspaces/bbworkspace1/members?q=permission%3D%22owner%22\"\n            },\n           [...]",
        "security": [
          {
            "oauth2": [
              "account"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Workspaces"
        ]
      }
    },
    "/workspaces/{workspace}": {
      "get": {
        "description": "Returns the requested workspace.",
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Workspaces"
        ]
      }
    },
    "/workspaces/{workspace}/hooks": {
      "get": {
        "description": "Returns a paginated list of webhooks installed on this workspace.",
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Workspaces",
          "Webhooks"
        ]
      },
      "post": {
        "description": "Creates a new webhook on the specified workspace.\n\nWorkspace webhooks are fired for events from all repositories contained\nby that workspace.\n\nNote that only owners can install webhooks on workspaces.",
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Workspaces",
          "Webhooks"
        ]
      }
    },
    "/workspaces/{workspace}/hooks/{uid}": {
      "delete": {
        "description": "Deletes the specified webhook subscription from the given workspace.",
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Workspaces",
          "Webhooks"
        ]
      },
      "get": {
        "description": "Returns the webhook with the specified id installed on the given\nworkspace.",
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Workspaces",
          "Webhooks"
        ]
      },
      "put": {
        "description": "Updates the specified webhook subscription.\n\nThe following properties can be mutated:\n\n* `description`\n* `url`\n* `active`\n* `events`",
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Workspaces",
          "Webhooks"
        ]
      }
    },
    "/workspaces/{workspace}/members": {
      "get": {
        "description": "Returns all members of the requested workspace.",
        "security": [
          {
            "oauth2": [
              "account"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Workspaces"
        ]
      }
    },
    "/workspaces/{workspace}/members/{member}": {
      "get": {
        "description": "Returns the workspace membership, which includes\na `User` object for the member and a `Workspace` object\nfor the requested workspace.",
        "security": [
          {
            "oauth2": [
              "account"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Workspaces"
        ]
      }
    },
    "/workspaces/{workspace}/permissions": {
      "get": {
        "description": "Returns the list of members in a workspace\nand their permission levels.\nPermission can be:\n* `owner`\n* `collaborator`\n* `member`\n\nExample:\n\n```\n$ curl -X https://api.bitbucket.org/2.0/workspaces/bbworkspace1/permissions\n\n{\n    \"pagelen\": 10,\n    \"values\": [\n        {\n            \"permission\": \"owner\",\n            \"type\": \"workspace_membership\",\n            \"user\": {\n                \"type\": \"user\",\n                \"uuid\": \"{470c176d[...]",
        "security": [
          {
            "oauth2": [
              "account"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Workspaces"
        ]
      }
    },
    "/workspaces/{workspace}/permissions/repositories": {
      "get": {
        "description": "Returns an object for each repository permission for all of a\nworkspace's repositories.\n\nPermissions returned are effective permissions: the highest level of\npermission the user has. This does not distinguish between direct and\nindirect (group) privileges.\n\nOnly users with admin permission for the team may access this resource.\n\nPermissions can be:\n\n* `admin`\n* `write`\n* `read`\n\nExample:\n\n```\n$ curl https://api.bitbucket.org/2.0/workspaces/atlassian_tuto[...]",
        "security": [
          {
            "oauth2": [
              "account"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Workspaces"
        ]
      }
    },
    "/workspaces/{workspace}/permissions/repositories/{repo_slug}": {
      "get": {
        "description": "Returns an object for the repository permission of each user in the\nrequested repository.\n\nPermissions returned are effective permissions: the highest level of\npermission the user has. This does not distinguish between direct and\nindirect (group) privileges.\n\nOnly users with admin permission for the repository may access this resource.\n\nPermissions can be:\n\n* `admin`\n* `write`\n* `read`\n\nExample:\n\n```\n$ curl https://api.bitbucket.org/2.0/workspaces/atlass[...]",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Workspaces"
        ]
      }
    },
    "/workspaces/{workspace}/pipelines-config/identity/oidc/.well-known/openid-configuration": {
      "get": {
      }
    },
    "/workspaces/{workspace}/pipelines-config/identity/oidc/keys.json": {
      "get": {
      }
    },
    "/workspaces/{workspace}/pipelines-config/variables": {
      "get": {
        "description": "Find workspace level variables.",
        "operationId": "getPipelineVariablesForWorkspace",
        "tags": [
          "Pipelines"
        ]
      },
      "post": {
        "description": "Create a workspace level variable.",
        "operationId": "createPipelineVariableForWorkspace",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/workspaces/{workspace}/pipelines-config/variables/{variable_uuid}": {
      "delete": {
        "description": "Delete a workspace level variable.",
        "operationId": "deletePipelineVariableForWorkspace",
        "tags": [
          "Pipelines"
        ]
      },
      "get": {
        "description": "Retrieve a workspace level variable.",
        "operationId": "getPipelineVariableForWorkspace",
        "tags": [
          "Pipelines"
        ]
      },
      "put": {
        "description": "Update a workspace level variable.",
        "operationId": "updatePipelineVariableForWorkspace",
        "tags": [
          "Pipelines"
        ]
      }
    },
    "/workspaces/{workspace}/projects": {
      "get": {
        "description": "Returns the list of projects in this workspace.",
        "security": [
          {
            "oauth2": [
              "project"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Workspaces"
        ]
      },
      "post": {
        "description": "Creates a new project.\n\nNote that the avatar has to be embedded as either a data-url\nor a URL to an external image as shown in the examples below:\n\n```\n$ body=$(cat << EOF\n{\n    \"name\": \"Mars Project\",\n    \"key\": \"MARS\",\n    \"description\": \"Software for colonizing mars.\",\n    \"links\": {\n        \"avatar\": {\n            \"href\": \"data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/...\"\n        }\n    },\n    \"is_[...]",
        "security": [
          {
            "oauth2": [
              "project:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Projects"
        ]
      }
    },
    "/workspaces/{workspace}/projects/{project_key}": {
      "delete": {
        "description": "Deletes this project. This is an irreversible operation.\n\nYou cannot delete a project that still contains repositories.\nTo delete the project, [delete](../../../repositories/%7Bworkspace%7D/%7Brepo_slug%7D#delete)\nor transfer the repositories first.\n\nExample:\n```\n$ curl -X DELETE https://api.bitbucket.org/2.0/bbworkspace1/PROJ\n```",
        "security": [
          {
            "oauth2": [
              "project:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Projects"
        ]
      },
      "get": {
        "description": "Returns the requested project.",
        "security": [
          {
            "oauth2": [
              "project"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Projects",
          "Workspaces"
        ]
      },
      "put": {
        "description": "Since this endpoint can be used to both update and to create a\nproject, the request body depends on the intent.\n\n### Creation\n\nSee the POST documentation for the project collection for an\nexample of the request body.\n\nNote: The `key` should not be specified in the body of request\n(since it is already present in the URL). The `name` is required,\neverything else is optional.\n\n### Update\n\nSee the POST documentation for the project collection for an\nexample of [...]",
        "security": [
          {
            "oauth2": [
              "project:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "tags": [
          "Projects"
        ]
      }
    },
    "/workspaces/{workspace}/search/code": {
      "get": {
        "summary": "Search for code in the repositories of the specified workspace.\n\nSearching across all repositories:\n\n```\ncurl 'https://api.bitbucket.org/2.0/workspaces/workspace_slug_or_uuid/search/code?search_query=foo'\n{\n  \"size\": 1,\n  \"page\": 1,\n  \"pagelen\": 10,\n  \"query_substituted\": false,\n  \"values\": [\n    {\n      \"type\": \"code_search_result\",\n      \"content_match_count\": 2,\n      \"content_matches\": [\n        {\n          \"lines\": [\n            {\n [...]",
        "tags": [
          "Search"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "api_key": {
        "description": "API Keys can be used as Basic HTTP Authentication credentials and provide a substitute for the account's actual username and password. API Keys are only available to team accounts and there is only 1 key per account. API Keys do not support scopes and have therefore access to all contents of the account.",
        "in": "header",
        "name": "Authorization",
        "type": "apiKey"
      },
      "basic": {
        "description": "Basic HTTP Authentication as per [RFC-2617](https://tools.ietf.org/html/rfc2617) (Digest not supported). Note that Basic Auth with username and password as credentials is only available on accounts that have 2-factor-auth / 2-step-verification disabled. If you use 2fa, you should authenticate using OAuth2 instead.",
        "scheme": "basic",
        "type": "http"
      },
      "oauth2": {
        "description": "OAuth 2 as per [RFC-6749](https://tools.ietf.org/html/rfc6749).",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://bitbucket.org/site/oauth2/authorize",
            "scopes": {
              "account": "Read your account information",
              "account:write": "Read and modify your account information",
              "email": "Read your account's primary email address",
              "issue": "Read your repositories' issues",
              "issue:write": "Read and modify your repositories' issues",
              "pipeline": "Access your repositories' build pipelines",
              "pipeline:variable": "Access your repositories' build pipelines and configure their variables",
              "pipeline:write": "Access and rerun your repositories' build pipelines",
              "project": "Read your workspace's project settings and read repositories contained within your workspace's projects",
              "project:write": "Read and modify your workspace's project settings, and read and transfer repositories within your workspace's projects",
              "pullrequest": "Read your repositories and their pull requests",
              "pullrequest:write": "Read and modify your repositories and their pull requests",
              "repository": "Read your repositories",
              "repository:admin": "Administer your repositories",
              "repository:delete": "Delete your repositories",
              "repository:write": "Read and modify your repositories",
              "runner": "Access your workspaces/repositories' runners",
              "runner:write": "Access and edit your workspaces/repositories' runners",
              "snippet": "Read your snippets",
              "snippet:write": "Read and modify your snippets",
              "team": "Read your team membership information",
              "team:write": "Read and modify your team membership information",
              "webhook": "Read and modify your repositories' webhooks",
              "wiki": "Read and modify your repositories' wikis"
            },
            "tokenUrl": "https://bitbucket.org/site/oauth2/access_token"
          }
        },
        "type": "oauth2"
      }
    }
  },
  "x-atlassian-narrative": {
    "documents": [
      {
        "anchor": "authentication",
        "body": "\nThe purpose of this section is to describe how to authenticate when making API calls using the Bitbucket REST API.\n\n-----\n\n* [Oauth 2](#oauth-2)\n  * [Making requests](#making-requests)\n  * [Repository cloning](#repository-cloning)\n  * [Refresh tokens](#refresh-tokens)\n* [Scopes](#scopes)\n* [App passwords](#app-passwords)\n* [Basic auth](#basic-auth)\n\n---\n\n### OAuth 2.0\n\nOur OAuth 2 implementation is merged in with our existing OAuth 1 in\nsuch a way that existin[...]",
        "description": "How to authenticate API actions",
        "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTcuNjQ3MyAxODYuODEzOCI+CiAgPGRlZnM+CiAgICA8c3R5bGU+CiAgICAgIC5jbHMtMSB7CiAgICAgICAgaXNvbGF0aW9uOiBpc29sYXRlOwogICAgICB9CgogICAgICAuY2xzLTIgewogICAgICAgIGZpbGw6ICNkZTM1MGI7CiAgICAgIH0KCiAgICAgIC5jbHMtMyB7CiAgICAgICAgZmlsbDogI2ZmNTYzMDsKICAgICAgfQoKICAgICAgLmNscy00IHsKICAgICAgICBmaWxsOiAjZGZlMWU1OwogICAgICAgIG1peC1ibGVuZC1tb2RlOiBtdWx0aXBseTsKICAgICAgfQoKICAgICAgLmNscy01IHsKICAgICAgI[...]",
        "title": "Authentication methods"
      },
      {
        "anchor": "filtering",
        "body": "\nYou can query the 2.0 API for specific objects using a simple language which resembles SQL.\n\nNote that filtering and querying by username has been deprecated, due to privacy changes. \nSee the [announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/#changes-to-querying) \nfor details.\n\n---\n\n* [Supported endpoints](#supported-endpoints)\n* [Operators](#operators)\n* [Data types](#data-types)\n* [Querying](#querying)\n* [Sorting query resu[...]",
        "description": "Query the 2.0 API for specific objects",
        "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgMTk0LjE5MTkgMTQ3LjYwOTIiPgogIDxkZWZzPgogICAgPHN0eWxlPgogICAgICAuY2xzLTEgewogICAgICAgIGlzb2xhdGlvbjogaXNvbGF0ZTsKICAgICAgfQoKICAgICAgLmNscy0yIHsKICAgICAgICBmaWxsOiAjY2ZkNGRiOwogICAgICB9CgogICAgICAuY2xzLTMsIC5jbHMtNCB7CiAgICAgICAgZmlsbDogIzg3NzdkOTsKICAgICAgfQoKICAgICAgLmNscy00IHsKICAgICAgICBtaXgtYmxlbmQtbW9kZTogbXVsdGlwbHk7CiAgI[...]",
        "title": "Filter and sort API objects"
      },
      {
        "anchor": "pagination",
        "body": "\nEndpoints that return collections of objects should always apply pagination.\nPaginated collections are always wrapped in the following wrapper object:\n\n```json\n{\n  \"size\": 5421,\n  \"page\": 2,\n  \"pagelen\": 10,\n  \"next\": \"https://api.bitbucket.org/2.0/repositories/pypy/pypy/commits?page=3\",\n  \"previous\": \"https://api.bitbucket.org/2.0/repositories/pypy/pypy/commits?page=1\",\n  \"values\": [\n    ...\n  ]\n}\n```\n\nPagination is often page-bound, with a que[...]",
        "description": "Learn more about pagination",
        "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgMjM4LjgyIDE1MS42Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2IyZDRmZjt9LmNscy0ye2ZpbGw6IzRjOWFmZjt9LmNscy0ze2ZpbGw6IzAwNTJjYzt9LmNscy00e29wYWNpdHk6MC42O30uY2xzLTV7ZmlsbDp1cmwoI2xpbmVhci1ncmFkaWVudCk7fS5jbHMtNntmaWxsOnVybCgjbGluZWFyLWdyYWRpZW50LTIpO30uY2xzLTd7ZmlsbDp1cmwoI2xpbmVhci1ncmFkaWVudC0zKTt9LmNscy04e2ZpbGw6dXJsKCNsaW5lYXItZ3JhZ[...]",
        "title": "Pagination"
      },
      {
        "anchor": "partial-response",
        "body": "\nBy default, each endpoint returns the full representation of a resource and in\nsome cases that can be a lot of data. For example, retrieving a list of pull\nrequests can amount to quite a large document.\n\nFor better performance, you can ask the server to only return the fields you\nreally need and to omit unwanted data. To request a partial response and to\nadd or remove specific fields from a response, use the `fields` query\nparameter.\n\n\n### Example\n\nMost API resourc[...]",
        "description": "Tweak which fields are returned",
        "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgMTYyLjQ0ODcgMjEwLjExMTUiPgogIDxkZWZzPgogICAgPHN0eWxlPgogICAgICAuY2xzLTEgewogICAgICAgIGlzb2xhdGlvbjogaXNvbGF0ZTsKICAgICAgfQoKICAgICAgLmNscy0yLCAuY2xzLTYsIC5jbHMtOCB7CiAgICAgICAgZmlsbDogbm9uZTsKICAgICAgfQoKICAgICAgLmNscy0yLCAuY2xzLTggewogICAgICAgIHN0cm9rZTogIzAwNjVmZjsKICAgICAgICBzdHJva2Utd2lkdGg6IDJweDsKICAgICAgfQoKICAgICAgLmNsc[...]",
        "title": "Partial responses"
      },
      {
        "anchor": "serialization",
        "body": "\n----\n\n* [Open API Specification](#open-api-specification)\n* [JSON Schema](#json-schema)\n* [Condensed Versus Full Objects](#condensed-versus-full-objects)\n\n____\n\n\n### Open API Specification\n\nBitbucket uses the [Open API Specification](https://openapis.org) (OAI,\nformerly known as Swagger) to describe its APIs. Our OAI specification schema\nis hosted at [https://api.bitbucket.org/swagger.json](https://api.bitbucket.org/swagger.json)\nand serves as the canonical defin[...]",
        "description": "Learn more about object representations",
        "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMjAuNzYyNCAyMDUuNTg2Ij4KICA8ZGVmcz4KICAgIDxzdHlsZT4KICAgICAgLmNscy0xIHsKICAgICAgICBpc29sYXRpb246IGlzb2xhdGU7CiAgICAgIH0KCiAgICAgIC5jbHMtMiwgLmNscy02IHsKICAgICAgICBtaXgtYmxlbmQtbW9kZTogbXVsdGlwbHk7CiAgICAgIH0KCiAgICAgIC5jbHMtMTMsIC5jbHMtMywgLmNscy00LCAuY2xzLTYgewogICAgICAgIGZpbGw6IG5vbmU7CiAgICAgICAgc3Ryb2tlOiAjYzFjN2QwOwogICAgICAgIHN0cm9rZS1saW5lY2FwOiByb3VuZDsKICAgICAgICBzdHJva2Utb[...]",
        "title": "Schemas and Serialization"
      },
      {
        "anchor": "uri-uuid",
        "body": "\nYou should be familiar with REST architecture before writing an integration. Read this overview page to gain a good understanding of Bitbucket's REST implementation.\n\n----\n\n* [URI structure](#uri-structure)\n* [HTTP methods](#http-methods)\n* [UUID](#universally-unique-identifier)\n    * [User object and UUID](#user-object-and-uuid)\n    * [Repository object and UUID](#repository-object-and-uuid)\n    * [Team object and UUID](#team-object-and-uuid)\n* [Standard error respo[...]",
        "description": "URL's, UUID's, errors, and timestamps",
        "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgMTc5LjI2IDE3Ny42NSI+PGRlZnM+PHN0eWxlPi5jbHMtMXtmaWxsOnVybCgjbGluZWFyLWdyYWRpZW50KTt9LmNscy0ye2ZpbGw6IzA5MWU0Mjt9LmNscy0xMCwuY2xzLTExLC5jbHMtMywuY2xzLTQsLmNscy05e2ZpbGw6bm9uZTt9LmNscy0ze3N0cm9rZTojOTljMWZmO30uY2xzLTMsLmNscy00e3N0cm9rZS1saW5lY2FwOnJvdW5kO3N0cm9rZS1saW5lam9pbjpyb3VuZDtzdHJva2Utd2lkdGg6MDt9LmNscy0xMiwuY2xzLTQsLmNsc[...]",
        "title": "URI, UUID, and structures"
      },
      {
        "anchor": "cors-hypermedia",
        "body": "\nThis section describes [Cross-origin resource sharing](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) (CORS), what content types we support in requests and responses, and hyperlinking resources in each json responses.\n\n\n----\n\n* [CORS](#cors)\n* [Supported content types](#supported-content-types)\n* [Resource links](#resource-links)\n\n----\n\n### Cors\n\nThe Bitbucket API supports Cross-origin resource sharing to allow requests for restricted resources acros[...]",
        "description": "Learn about resources and linking",
        "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgMjM2LjYgMjE4LjQzIj48ZGVmcz48c3R5bGU+LmNscy0xe2lzb2xhdGlvbjppc29sYXRlO30uY2xzLTIsLmNscy0zLC5jbHMtNHtmaWxsOm5vbmU7c3Ryb2tlLWxpbmVjYXA6cm91bmQ7c3Ryb2tlLW1pdGVybGltaXQ6MTA7c3Ryb2tlLXdpZHRoOjExcHg7fS5jbHMtMntzdHJva2U6dXJsKCNsaW5lYXItZ3JhZGllbnQpO30uY2xzLTN7c3Ryb2tlOnVybCgjTmV3X0dyYWRpZW50X1N3YXRjaF8xNCk7fS5jbHMtNHtzdHJva2U6dXJsKCNOZ[...]",
        "title": "Cors and hypermedia"
      },
      {
        "anchor": "bb-connect",
        "body": "\nYou can use the Atlassian Connect for Bitbucket Cloud to build add-ons which\ncan connect with the Bitbucket UI and your own application set. An add-on could\nbe an integration with another existing service, new features for the Atlassian\napplication, or even a new product that runs within the Atlassian application.\n\nFor complete information see:\n[Atlassian Connect for Bitbucket Cloud](https://developer.atlassian.com/bitbucket/index.html)\n",
        "description": "Build Bitbucket add-ons with Connect",
        "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgMjU3LjMxNjMgMTYyLjU5OTQiPgogIDxkZWZzPgogICAgPHN0eWxlPgogICAgICAuY2xzLTEgewogICAgICAgIGlzb2xhdGlvbjogaXNvbGF0ZTsKICAgICAgfQoKICAgICAgLmNscy0yIHsKICAgICAgICBmaWxsOiAjMzQ0NTYzOwogICAgICB9CgogICAgICAuY2xzLTMgewogICAgICAgIGZpbGw6ICMxZGI5ZDQ7CiAgICAgIH0KCiAgICAgIC5jbHMtNCB7CiAgICAgICAgZmlsbDogIzAwNTdkODsKICAgICAgfQoKICAgICAgLmNscy01L[...]",
        "title": "Atlassian Connect"
      }
    ]
  },
  "x-radar-pages": [
    {
      "content": "\n# Authentication methods\n\nThe purpose of this section is to describe how to authenticate when making API calls using the Bitbucket REST API.\n\n-----\n\n*On this page*\n\n* [Oauth 2](#oauth-2)\n  * [Making requests](#make-requests)\n  * [Repository cloning](#repo-clone)\n  * [Refresh tokens](#refresh-tokens)\n* [Scopes](#scopes-bbc)\n* [App passwords](#app-pw)\n* [Basic auth](#basic-auth)\n\n---\n\n# Bitbucket Cloud OAuth 2.0 <a name=\"oauth-2\"></a>\n\nOur OAuth 2 implemen[...]",
      "description": "How to authenticate API actions",
      "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTcuNjQ3MyAxODYuODEzOCI+CiAgPGRlZnM+CiAgICA8c3R5bGU+CiAgICAgIC5jbHMtMSB7CiAgICAgICAgaXNvbGF0aW9uOiBpc29sYXRlOwogICAgICB9CgogICAgICAuY2xzLTIgewogICAgICAgIGZpbGw6ICNkZTM1MGI7CiAgICAgIH0KCiAgICAgIC5jbHMtMyB7CiAgICAgICAgZmlsbDogI2ZmNTYzMDsKICAgICAgfQoKICAgICAgLmNscy00IHsKICAgICAgICBmaWxsOiAjZGZlMWU1OwogICAgICAgIG1peC1ibGVuZC1tb2RlOiBtdWx0aXBseTsKICAgICAgfQoKICAgICAgLmNscy01IHsKICAgICAgICB[...]",
      "key": "authentication",
      "title": "Authentication methods"
    },
    {
      "content": "\n# Filter and sort API objects\n\nYou can query the 2.0 API for specific objects using a simple language which resembles SQL.\n\nNote that filtering and querying by username has been deprecated, due to privacy changes.\nSee the [announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/#changes-to-querying)\nfor details.\n\n---\n**On this page**\n\n* [Supported endpoints](#supp-endpoints)\n* [Operators](#operators)\n* [Data types](#data-types)\n*[...]",
      "description": "Query the 2.0 API for specific objects",
      "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgMTk0LjE5MTkgMTQ3LjYwOTIiPgogIDxkZWZzPgogICAgPHN0eWxlPgogICAgICAuY2xzLTEgewogICAgICAgIGlzb2xhdGlvbjogaXNvbGF0ZTsKICAgICAgfQoKICAgICAgLmNscy0yIHsKICAgICAgICBmaWxsOiAjY2ZkNGRiOwogICAgICB9CgogICAgICAuY2xzLTMsIC5jbHMtNCB7CiAgICAgICAgZmlsbDogIzg3NzdkOTsKICAgICAgfQoKICAgICAgLmNscy00IHsKICAgICAgICBtaXgtYmxlbmQtbW9kZTogbXVsdGlwbHk7CiAgICA[...]",
      "key": "filtering",
      "title": "Filter and sort API objects"
    },
    {
      "content": "\n# Pagination\n\nEndpoints that return collections of objects should always apply pagination.\nPaginated collections are always wrapped in the following wrapper object:\n\n```json\n{\n  \"size\": 5421,\n  \"page\": 2,\n  \"pagelen: 10,\n  \"next\": \"https://api.bitbucket.org/2.0/repositories/pypy/pypy/commits?page=3\",\n  \"previous\": \"https://api.bitbucket.org/2.0/repositories/pypy/pypy/commits?page=1\",\n  \"values\": [\n    ...\n  ]\n}\n```\n\nPagination is often page-bo[...]",
      "description": "Learn more about pagination",
      "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgMjM4LjgyIDE1MS42Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2IyZDRmZjt9LmNscy0ye2ZpbGw6IzRjOWFmZjt9LmNscy0ze2ZpbGw6IzAwNTJjYzt9LmNscy00e29wYWNpdHk6MC42O30uY2xzLTV7ZmlsbDp1cmwoI2xpbmVhci1ncmFkaWVudCk7fS5jbHMtNntmaWxsOnVybCgjbGluZWFyLWdyYWRpZW50LTIpO30uY2xzLTd7ZmlsbDp1cmwoI2xpbmVhci1ncmFkaWVudC0zKTt9LmNscy04e2ZpbGw6dXJsKCNsaW5lYXItZ3JhZGl[...]",
      "key": "pagination",
      "title": "Pagination"
    },
    {
      "content": "\n# Partial responses\n\nBy default, each endpoint returns the full representation of a resource and in\nsome cases that can be a lot of data. For example, retrieving a list of pull\nrequests can amount to quite a large document.\n\nFor better performance, you can ask the server to only return the fields you\nreally need and to omit unwanted data. To request a partial response and to\nadd or remove specific fields from a response, use the `fields` query\nparameter.\n\n\n## Exam[...]",
      "description": "Tweak which fields are returned",
      "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgMTYyLjQ0ODcgMjEwLjExMTUiPgogIDxkZWZzPgogICAgPHN0eWxlPgogICAgICAuY2xzLTEgewogICAgICAgIGlzb2xhdGlvbjogaXNvbGF0ZTsKICAgICAgfQoKICAgICAgLmNscy0yLCAuY2xzLTYsIC5jbHMtOCB7CiAgICAgICAgZmlsbDogbm9uZTsKICAgICAgfQoKICAgICAgLmNscy0yLCAuY2xzLTggewogICAgICAgIHN0cm9rZTogIzAwNjVmZjsKICAgICAgICBzdHJva2Utd2lkdGg6IDJweDsKICAgICAgfQoKICAgICAgLmNscy0[...]",
      "key": "partial-response",
      "title": "Partial responses"
    },
    {
      "content": "\n# Open API Specification and Object Representations\n\n----\n\n*On this page*\n\n* [Open API Specification](#oai)\n* [JSON Schema](#jsonschema)\n* [Condensed Versus Full Objects](#representations)\n\n____\n\n\n## Open API Specification <a name=\"aoi\"></a>\n\nBitbucket uses the [Open API Specification](https://openapis.org) (OAI,\nformerly known as Swagger) to describe its APIs. Our OAI specification schema\nis hosted at [https://api.bitbucket.org/swagger.json](https://api.bi[...]",
      "description": "Learn more about object representations",
      "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMjAuNzYyNCAyMDUuNTg2Ij4KICA8ZGVmcz4KICAgIDxzdHlsZT4KICAgICAgLmNscy0xIHsKICAgICAgICBpc29sYXRpb246IGlzb2xhdGU7CiAgICAgIH0KCiAgICAgIC5jbHMtMiwgLmNscy02IHsKICAgICAgICBtaXgtYmxlbmQtbW9kZTogbXVsdGlwbHk7CiAgICAgIH0KCiAgICAgIC5jbHMtMTMsIC5jbHMtMywgLmNscy00LCAuY2xzLTYgewogICAgICAgIGZpbGw6IG5vbmU7CiAgICAgICAgc3Ryb2tlOiAjYzFjN2QwOwogICAgICAgIHN0cm9rZS1saW5lY2FwOiByb3VuZDsKICAgICAgICBzdHJva2UtbWl[...]",
      "key": "serialization",
      "title": "Schemas and Serialization"
    },
    {
      "content": "\n# URI, UUID, and structures\n\nYou should be familiar with REST architecture before writing an integration. Read this overview page to gain a good understanding of Bitbucket's REST implementation.\n\n----\n**On this page**\n\n* [URI structure](#uri-structure)\n* [HTTP methods](#http-methods)\n* [UUID](#uuid)\n    * [User object and UUID](#userobj)\n    * [Repository object and UUID](#repo-obj)\n    * [Team object and UUID](#teamobj)\n* [Standard error responses](#stand-error)[...]",
      "description": "URL's, UUID's, errors, and timestamps",
      "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgMTc5LjI2IDE3Ny42NSI+PGRlZnM+PHN0eWxlPi5jbHMtMXtmaWxsOnVybCgjbGluZWFyLWdyYWRpZW50KTt9LmNscy0ye2ZpbGw6IzA5MWU0Mjt9LmNscy0xMCwuY2xzLTExLC5jbHMtMywuY2xzLTQsLmNscy05e2ZpbGw6bm9uZTt9LmNscy0ze3N0cm9rZTojOTljMWZmO30uY2xzLTMsLmNscy00e3N0cm9rZS1saW5lY2FwOnJvdW5kO3N0cm9rZS1saW5lam9pbjpyb3VuZDtzdHJva2Utd2lkdGg6MDt9LmNscy0xMiwuY2xzLTQsLmNscy0[...]",
      "key": "uri-uuid",
      "title": "URI, UUID, and structures"
    },
    {
      "content": "\n# Cors and hypermedia\n\nThis section describes [Cross-origin resource sharing](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) (CORS), what content types we support in requests and responses, and hyperlinking resources in each json responses.\n\n\n----\n**On this page**\n\n* [CORS](#cors)\n* [Supported content types](#supported-content)\n* [Resource links](#resource-links)\n\n----\n\n## Cors <a name=\"cors\"></a>\n\nThe Bitbucket API supports Cross-origin resour[...]",
      "description": "Learn about resources and linking",
      "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgMjM2LjYgMjE4LjQzIj48ZGVmcz48c3R5bGU+LmNscy0xe2lzb2xhdGlvbjppc29sYXRlO30uY2xzLTIsLmNscy0zLC5jbHMtNHtmaWxsOm5vbmU7c3Ryb2tlLWxpbmVjYXA6cm91bmQ7c3Ryb2tlLW1pdGVybGltaXQ6MTA7c3Ryb2tlLXdpZHRoOjExcHg7fS5jbHMtMntzdHJva2U6dXJsKCNsaW5lYXItZ3JhZGllbnQpO30uY2xzLTN7c3Ryb2tlOnVybCgjTmV3X0dyYWRpZW50X1N3YXRjaF8xNCk7fS5jbHMtNHtzdHJva2U6dXJsKCNOZXd[...]",
      "key": "cors-hypermedia",
      "title": "Cors and hypermedia"
    },
    {
      "content": "\n# Atlassian Connect for Bitbucket\n\nYou can use the Atlassian Connect for Bitbucket Cloud to build add-ons which\ncan connect with the Bitbucket UI and your own application set. An add-on could\nbe an integration with another existing service, new features for the Atlassian\napplication, or even a new product that runs within the Atlassian application.\n\nFor complete information see:\n[Atlassian Connect for Bitbucket Cloud](https://developer.atlassian.com/bitbucket/index.ht[...]",
      "description": "Build Bitbucket add-ons with Connect",
      "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgMjU3LjMxNjMgMTYyLjU5OTQiPgogIDxkZWZzPgogICAgPHN0eWxlPgogICAgICAuY2xzLTEgewogICAgICAgIGlzb2xhdGlvbjogaXNvbGF0ZTsKICAgICAgfQoKICAgICAgLmNscy0yIHsKICAgICAgICBmaWxsOiAjMzQ0NTYzOwogICAgICB9CgogICAgICAuY2xzLTMgewogICAgICAgIGZpbGw6ICMxZGI5ZDQ7CiAgICAgIH0KCiAgICAgIC5jbHMtNCB7CiAgICAgICAgZmlsbDogIzAwNTdkODsKICAgICAgfQoKICAgICAgLmNscy01LCA[...]",
      "key": "bb-connect",
      "title": "Atlassian Connect"
    }
  ],
  "x-revision": "6f572d69e972"
}