openapi: 3.0.0
servers:
  - description: Xero Identity service API
    url: https://api.xero.com
info:
  contact:
    email: api@xero.com
    name: Xero Platform Team
    url: https://developer.xero.com
    x-twitter: XeroAPI
  description: These endpoints are related to managing authentication tokens and identity for Xero API
  license:
    name: MIT
    url: https://github.com/XeroAPI/Xero-OpenAPI/blob/master/LICENSE
  termsOfService: https://developer.xero.com/xero-developer-platform-terms-conditions/
  title: Xero OAuth 2 Identity Service API
  version: 2.9.4
  x-apisguru-categories:
    - financial
  x-origin:
    - format: openapi
      url: https://raw.githubusercontent.com/XeroAPI/Xero-OpenAPI/master/xero-identity.yaml
      version: "3.0"
  x-providerName: xero.com
  x-serviceName: xero-identity
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_apis.guru_assets_images_no-logo.svg
paths:
  /Connections:
    get:
      description: Override the base server url that include version
      operationId: getConnections
      security:
        - OAuth2: []
      summary: Retrieves the connections for this user
      tags:
        - identity
      x-basepath: https://api.xero.com
  "/Connections/{id}":
    delete:
      description: Override the base server url that include version
      operationId: deleteConnection
      security:
        - OAuth2: []
      summary: Deletes a connection for this user (i.e. disconnect a tenant)
      tags:
        - identity
      x-basepath: https://api.xero.com
components:
  securitySchemes:
    BasicAuth:
      scheme: basic
      type: http
    OAuth2:
      description: For more information
      flows:
        authorizationCode:
          authorizationUrl: https://login.xero.com/identity/connect/authorize
          scopes:
            accounting.attachments: Grant read-write access to
            accounting.attachments.read: Grant read-only access to
            accounting.contacts: Grant read-write access to
            accounting.contacts.read: Grant read-only access to
            accounting.journals.read: Grant read-only access to journals
            accounting.reports.read: Grant read-only access to accounting reports
            accounting.settings: Grant read-write access to organisation and account settings
            accounting.settings.read: Grant read-only access to organisation and account settings
            accounting.transactions: Grant read-write access to bank transactions, credit notes, invoices, repeating invoices
            accounting.transactions.read: Grant read-only access to invoices
            assets assets.read: Grant read-only access to
            email: Grant read-only access to your email
            files: Grant read-write access to
            files.read: Grant read-only access to
            openid: Grant read-only access to your open id
            payroll: Grant read-write access to
            payroll.employees: Grant read-write access to
            payroll.employees.read: Grant read-only access to
            payroll.leaveapplications: Grant read-write access to
            payroll.leaveapplications.read: Grant read-only access to
            payroll.payitems: Grant read-write access to
            payroll.payitems.read: Grant read-only access to
            payroll.payrollcalendars: Grant read-write access to
            payroll.payrollcalendars.read: Grant read-only access to
            payroll.payruns: Grant read-write access to
            payroll.payruns.read: Grant read-only access to
            payroll.payslip: Grant read-write access to
            payroll.payslip.read: Grant read-only access to
            payroll.read: Grant read-only access to
            payroll.settings.read: Grant read-only access to
            payroll.superfundproducts.read: Grant read-only access to
            payroll.superfunds: Grant read-write access to
            payroll.superfunds.read: Grant read-only access to
            payroll.timesheets: Grant read-write access to
            payroll.timesheets.read: Grant read-only access to
            profile: your profile information
            projects: Grant read-write access to projects
            projects.read: Grant read-only access to projects
          tokenUrl: https://identity.xero.com/connect/token
      type: oauth2
