{
  "openapi": "3.0.1",
  "servers": [
    {
      "description": "Sandbox Server",
      "url": "https://apis.nbg.gr/sandbox/uk.openbanking.accountinfo/oauth2/v3.1.5"
    },
    {
      "description": "Production Server",
      "url": "https://services.nbg.gr/apis/open-banking/v3.1.5/aisp"
    }
  ],
  "info": {
    "contact": {
      "email": "developer@nbg.gr",
      "name": "NBG",
      "url": "https://developer.nbg.gr/"
    },
    "description": "## Functionality at a glance\r\n\r\nThe NBG \"UK OPB - Account and Transaction v3.1.5\" API follows the [UK Open Banking Specification\r\n    v3.1.5](https://openbankinguk.github.io/read-write-api-site3/v3.1.5/profiles/account-and-transaction-api-profile.html)\r\n\r\nThis Account and Transaction API Specification describes the flows and payloads for retrieving a list of accounts and their transactions.\r\n\r\nThe API endpoints described here allow a AISP to:  \r\n\r\n* Create[...]",
    "title": "Account and Transaction API Specification - UK",
    "version": "v3.1.5",
    "x-apisguru-categories": [
      "financial"
    ],
    "x-origin": [
      {
        "format": "openapi",
        "url": "https://developer.nbg.gr/api.gateway/publicportal/sites/default/files/2020-09/NBGSwagger-account-and_transaction_api_specification_uk-v3.1.5-swagger%20%284%29.yaml",
        "version": "3.0"
      }
    ],
    "x-providerName": "nbg.gr",
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_apis.guru_assets_images_no-logo.svg"
    }
  },
  "paths": {
    "/account-access-consents": {
      "post": {
        "description": "Create Account Access Consents",
        "security": [
          {
            "Client-Credentials-Token": [
              "sandbox-uk-account-info-api-v1",
              "accounts"
            ],
            "Client-Id": []
          }
        ],
        "summary": "Create Account Access Consents",
        "tags": [
          "AccountAccess"
        ]
      }
    },
    "/account-access-consents/{consentId}": {
      "delete": {
        "description": "Delete Account Access Consents by Consent ID",
        "security": [
          {
            "Client-Credentials-Token": [
              "sandbox-uk-account-info-api-v1",
              "accounts"
            ],
            "Client-Id": []
          }
        ],
        "summary": "Delete Account Access Consents",
        "tags": [
          "AccountAccess"
        ]
      },
      "get": {
        "description": "Get Account Access Consents by Consent ID",
        "security": [
          {
            "Client-Credentials-Token": [
              "sandbox-uk-account-info-api-v1",
              "accounts"
            ],
            "Client-Id": []
          }
        ],
        "summary": "Get Account Access Consents",
        "tags": [
          "AccountAccess"
        ]
      }
    },
    "/accounts": {
      "get": {
        "description": "Get Accounts",
        "security": [
          {
            "Authorization-Code-Token": [
              "sandbox-uk-account-info-api-v1 offline_access",
              "accounts offline_access"
            ],
            "Client-Id": []
          }
        ],
        "summary": "Get Accounts",
        "tags": [
          "Accounts"
        ]
      }
    },
    "/accounts/{accountId}": {
      "get": {
        "description": "Get Accounts by Account ID",
        "security": [
          {
            "Authorization-Code-Token": [
              "sandbox-uk-account-info-api-v1 offline_access",
              "accounts offline_access"
            ],
            "Client-Id": []
          }
        ],
        "summary": "Get Accounts",
        "tags": [
          "Accounts"
        ]
      }
    },
    "/accounts/{accountId}/balances": {
      "get": {
        "description": "Get Balances by Account ID",
        "security": [
          {
            "Authorization-Code-Token": [
              "sandbox-uk-account-info-api-v1 offline_access",
              "accounts offline_access"
            ],
            "Client-Id": []
          }
        ],
        "summary": "Get Balances",
        "tags": [
          "Balances"
        ]
      }
    },
    "/accounts/{accountId}/beneficiaries": {
      "get": {
        "description": "Get Beneficiaries by Account ID",
        "security": [
          {
            "Authorization-Code-Token": [
              "sandbox-uk-account-info-api-v1 offline_access",
              "accounts offline_access"
            ],
            "Client-Id": []
          }
        ],
        "summary": "Get Beneficiaries",
        "tags": [
          "Beneficiaries"
        ]
      }
    },
    "/accounts/{accountId}/parties": {
      "get": {
        "description": "Get Parties by Account ID",
        "security": [
          {
            "Authorization-Code-Token": [
              "sandbox-uk-account-info-api-v1 offline_access",
              "accounts offline_access"
            ],
            "Client-Id": []
          }
        ],
        "summary": "Get Parties",
        "tags": [
          "Parties"
        ]
      }
    },
    "/accounts/{accountId}/party": {
      "get": {
        "description": "Get Party by Account ID",
        "security": [
          {
            "Authorization-Code-Token": [
              "sandbox-uk-account-info-api-v1 offline_access",
              "accounts offline_access"
            ],
            "Client-Id": []
          }
        ],
        "summary": "Get Party",
        "tags": [
          "Parties"
        ]
      }
    },
    "/accounts/{accountId}/scheduled-payments": {
      "get": {
        "description": "Get Scheduled Payments by Account ID",
        "security": [
          {
            "Authorization-Code-Token": [
              "sandbox-uk-account-info-api-v1 offline_access",
              "accounts offline_access"
            ],
            "Client-Id": []
          }
        ],
        "summary": "Get Scheduled Payments",
        "tags": [
          "ScheduledPayments"
        ]
      }
    },
    "/accounts/{accountId}/standing-orders": {
      "get": {
        "description": "Get Standing Orders by Account ID",
        "security": [
          {
            "Authorization-Code-Token": [
              "sandbox-uk-account-info-api-v1 offline_access",
              "accounts offline_access"
            ],
            "Client-Id": []
          }
        ],
        "summary": "Get Standing Orders",
        "tags": [
          "StandingOrders"
        ]
      }
    },
    "/accounts/{accountId}/statements": {
      "get": {
        "description": "Get Statements by Account ID",
        "security": [
          {
            "Authorization-Code-Token": [
              "sandbox-uk-account-info-api-v1 offline_access",
              "accounts offline_access"
            ],
            "Client-Id": []
          }
        ],
        "summary": "Get Statements",
        "tags": [
          "Statements"
        ]
      }
    },
    "/accounts/{accountId}/statements/{statementId}": {
      "get": {
        "description": "Get Statements by Account ID and Statement ID",
        "security": [
          {
            "Authorization-Code-Token": [
              "sandbox-uk-account-info-api-v1 offline_access",
              "accounts offline_access"
            ],
            "Client-Id": []
          }
        ],
        "summary": "Get Statements",
        "tags": [
          "Statements"
        ]
      }
    },
    "/accounts/{accountId}/statements/{statementId}/file": {
      "get": {
        "description": "Get Statement PDF File by Account ID and Statement ID",
        "security": [
          {
            "Authorization-Code-Token": [
              "sandbox-uk-account-info-api-v1 offline_access",
              "accounts offline_access"
            ],
            "Client-Id": []
          }
        ],
        "summary": "Get Statements",
        "tags": [
          "Statements"
        ]
      }
    },
    "/accounts/{accountId}/statements/{statementId}/transactions": {
      "get": {
        "description": "Get Transactions by Account ID and Statement ID",
        "security": [
          {
            "Authorization-Code-Token": [
              "sandbox-uk-account-info-api-v1 offline_access",
              "accounts offline_access"
            ],
            "Client-Id": []
          }
        ],
        "summary": "Get Transactions",
        "tags": [
          "Transactions"
        ]
      }
    },
    "/accounts/{accountId}/transactions": {
      "get": {
        "description": "Get Transactions by Account ID",
        "security": [
          {
            "Authorization-Code-Token": [
              "sandbox-uk-account-info-api-v1 offline_access",
              "accounts offline_access"
            ],
            "Client-Id": []
          }
        ],
        "summary": "Get Transactions",
        "tags": [
          "Transactions"
        ]
      }
    },
    "/party": {
      "get": {
        "description": "Get Party",
        "security": [
          {
            "Authorization-Code-Token": [
              "sandbox-uk-account-info-api-v1 offline_access",
              "accounts offline_access"
            ],
            "Client-Id": []
          }
        ],
        "summary": "Get Party",
        "tags": [
          "Parties"
        ]
      }
    },
    "/sandbox": {
      "post": {
        "description": "Create Sandbox",
        "security": [
          {
            "Authorization-Code-Token": [
              "sandbox-uk-account-info-api-v1 offline_access",
              "accounts offline_access"
            ],
            "Client-Id": []
          }
        ],
        "summary": "Create Sandbox",
        "tags": [
          "Sandbox"
        ]
      },
      "put": {
        "description": "Import Sandbox",
        "security": [
          {
            "Authorization-Code-Token": [
              "sandbox-uk-account-info-api-v1 offline_access",
              "accounts offline_access"
            ],
            "Client-Id": []
          }
        ],
        "summary": "Import Sandbox",
        "tags": [
          "Sandbox"
        ]
      }
    },
    "/sandbox/{sandboxId}": {
      "delete": {
        "description": "Delete Sandbox",
        "security": [
          {
            "Authorization-Code-Token": [
              "sandbox-uk-account-info-api-v1 offline_access",
              "accounts offline_access"
            ],
            "Client-Id": []
          }
        ],
        "summary": "Delete Sandbox",
        "tags": [
          "Sandbox"
        ]
      },
      "get": {
        "description": "Export Sandbox",
        "security": [
          {
            "Authorization-Code-Token": [
              "sandbox-uk-account-info-api-v1 offline_access",
              "accounts offline_access"
            ],
            "Client-Id": []
          }
        ],
        "summary": "Export Sandbox",
        "tags": [
          "Sandbox"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Authorization-Code-Token": {
        "description": "OAuth2 Authorization Code Flow",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://my.nbg.gr/identity/connect/authorize",
            "scopes": {
              "accounts offline_access": "Production Scope",
              "sandbox-uk-account-info-api-v1 offline_access": "Sandbox Scope"
            },
            "tokenUrl": "https://my.nbg.gr/identity/connect/token"
          }
        },
        "type": "oauth2"
      },
      "Client-Credentials-Token": {
        "description": "OAuth2 Client Credentials Flow",
        "flows": {
          "clientCredentials": {
            "scopes": {
              "accounts": "Production Scope",
              "sandbox-uk-account-info-api-v1": "Sandbox Scope"
            },
            "tokenUrl": "https://my.nbg.gr/identity/connect/token"
          }
        },
        "type": "oauth2"
      },
      "Client-Id": {
        "description": "Application's Id",
        "in": "header",
        "name": "Client-Id",
        "type": "apiKey"
      }
    }
  }
}