openapi: 3.0.0
servers:
  - description: Xero Bank Feeds API base url
    url: https://api.xero.com/bankfeeds.xro/1.0
info:
  contact:
    email: api@xero.com
    name: Xero Platform Team
    url: https://developer.xero.com
    x-twitter: XeroAPI
  description: The Bank Feeds API is a closed API that is only available to financial institutions that have an established financial services partnership with Xero. If you're an existing financial services partner that wants access, contact your local Partner Manager. If you're a financial institution who wants to provide bank feeds to your business customers, contact us to become a financial services partner.
  license:
    name: MIT
    url: https://github.com/XeroAPI/Xero-OpenAPI/blob/master/LICENSE
  termsOfService: https://developer.xero.com/xero-developer-platform-terms-conditions/
  title: Xero Bank Feeds API
  version: 2.9.4
  x-apisguru-categories:
    - financial
  x-origin:
    - format: openapi
      url: https://raw.githubusercontent.com/XeroAPI/Xero-OpenAPI/master/xero_bankfeeds.yaml
      version: "3.0"
  x-providerName: xero.com
  x-serviceName: xero_bankfeeds
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_apis.guru_assets_images_no-logo.svg
paths:
  /FeedConnections:
    get:
      description: By passing in the appropriate options, you can search for available feed connections in the system.
      operationId: getFeedConnections
      security:
        - OAuth2:
            - bankfeeds
      summary: Searches for feed connections
      tags:
        - BankFeeds
    post:
      description: By passing in the FeedConnections array object in the body, you can create one or more new feed connections
      operationId: createFeedConnections
      security:
        - OAuth2:
            - bankfeeds
      summary: Create one or more new feed connection
      tags:
        - BankFeeds
      x-hasBankFeedsValidationError: true
  /FeedConnections/DeleteRequests:
    post:
      description: By passing in FeedConnections array object in the body, you can delete a feed connection.
      operationId: deleteFeedConnections
      security:
        - OAuth2:
            - bankfeeds
      summary: Delete an existing feed connection
      tags:
        - BankFeeds
  "/FeedConnections/{id}":
    get:
      description: By passing in a FeedConnection Id options, you can search for matching feed connections
      operationId: getFeedConnection
      security:
        - OAuth2:
            - bankfeeds
      summary: Retrieve single feed connection based on a unique id provided
      tags:
        - BankFeeds
  /Statements:
    get:
      description: By passing in parameters, you can search for matching statements
      operationId: getStatements
      security:
        - OAuth2:
            - bankfeeds
      summary: Retrieve all statements
      tags:
        - BankFeeds
    post:
      operationId: createStatements
      security:
        - OAuth2:
            - bankfeeds
      summary: Creates one or more new statements
      tags:
        - BankFeeds
      x-hasBankFeedsValidationError: true
  "/Statements/{statementID}":
    get:
      description: By passing in a statement id, you can search for matching statements
      operationId: getStatement
      security:
        - OAuth2:
            - bankfeeds
      summary: Retrieve single statement based on unique id provided
      tags:
        - BankFeeds
components:
  securitySchemes:
    OAuth2:
      description: For more information visit https://developer.xero.com/documentation/oauth2/overview
      flows:
        authorizationCode:
          authorizationUrl: https://login.xero.com/identity/connect/authorize
          scopes:
            accounting.attachments: Grant read-write access to attachments
            accounting.attachments.read: Grant read-only access to attachments
            accounting.contacts: Grant read-write access to contacts and contact groups
            accounting.contacts.read: Grant read-only access to contacts and contact groups
            accounting.journals.read: Grant read-only access to journals
            accounting.reports.read: Grant read-only access to accounting reports
            accounting.settings: Grant read-write access to organisation and account settings
            accounting.settings.read: Grant read-only access to organisation and account settings
            accounting.transactions: Grant read-write access to bank transactions, credit notes, invoices, repeating invoices
            accounting.transactions.read: Grant read-only access to invoices
            assets assets.read: Grant read-only access to fixed assets
            bankfeeds: Grant read-write access to bankfeeds
            email: Grant read-only access to your email
            files: Grant read-write access to files and folders
            files.read: Grant read-only access to files and folders
            openid: Grant read-only access to your open id
            paymentservices: Grant read-write access to payment services
            payroll: Grant read-write access to payroll
            payroll.employees: Grant read-write access to payroll employees
            payroll.employees.read: Grant read-only access to payroll employees
            payroll.leaveapplications: Grant read-write access to payroll leaveapplications
            payroll.leaveapplications.read: Grant read-only access to payroll leaveapplications
            payroll.payitems: Grant read-write access to payroll payitems
            payroll.payitems.read: Grant read-only access to payroll payitems
            payroll.payrollcalendars: Grant read-write access to payroll calendars
            payroll.payrollcalendars.read: Grant read-only access to payroll calendars
            payroll.payruns: Grant read-write access to payroll payruns
            payroll.payruns.read: Grant read-only access to payroll payruns
            payroll.payslip: Grant read-write access to payroll payslips
            payroll.payslip.read: Grant read-only access to payroll payslips
            payroll.read: Grant read-only access to payroll
            payroll.settings.read: Grant read-only access to payroll settings
            payroll.superfundproducts.read: Grant read-only access to payroll superfundproducts
            payroll.superfunds: Grant read-write access to payroll superfunds
            payroll.superfunds.read: Grant read-only access to payroll superfunds
            payroll.timesheets: Grant read-write access to payroll timesheets
            payroll.timesheets.read: Grant read-only access to payroll timesheets
            profile: your profile information
            projects: Grant read-write access to projects
            projects.read: Grant read-only access to projects
          tokenUrl: https://identity.xero.com/connect/token
      type: oauth2
