openapi: 3.0.0
servers:
  - url: 'https://cloudbilling.googleapis.com/'
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: |-
    Allows developers to manage billing for their Google Cloud Platform projects
        programmatically.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Google Cloud Billing
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://cloudbilling.googleapis.com/$discovery/rest?version=v1'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: cloudbilling
externalDocs:
  url: 'https://cloud.google.com/billing/'
tags:
  - name: billingAccounts
  - name: projects
paths:
  /v1/billingAccounts:
    get:
      description: |-
        Lists the billing accounts that the current authenticated user
        [owns](https://support.google.com/cloud/answer/4430947).
      operationId: cloudbilling.billingAccounts.list
      parameters:
        - description: |-
            Requested page size. The maximum page size is 100; this is also the
            default.
          in: query
          name: pageSize
          schema:
            type: integer
        - description: |-
            A token identifying a page of results to return. This should be a
            `next_page_token` value returned from a previous `ListBillingAccounts`
            call. If unspecified, the first page of results is returned.
          in: query
          name: pageToken
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ListBillingAccountsResponse'
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      tags:
        - billingAccounts
    parameters:
      - $ref: '#/components/parameters/access_token'
      - $ref: '#/components/parameters/prettyPrint'
      - $ref: '#/components/parameters/key'
      - $ref: '#/components/parameters/quotaUser'
      - $ref: '#/components/parameters/pp'
      - $ref: '#/components/parameters/fields'
      - $ref: '#/components/parameters/alt'
      - $ref: '#/components/parameters/_.xgafv'
      - $ref: '#/components/parameters/callback'
      - $ref: '#/components/parameters/oauth_token'
      - $ref: '#/components/parameters/uploadType'
      - $ref: '#/components/parameters/bearer_token'
      - $ref: '#/components/parameters/upload_protocol'
  '/v1/{name}':
    get:
      description: |-
        Gets information about a billing account. The current authenticated user
        must be an [owner of the billing
        account](https://support.google.com/cloud/answer/4430947).
      operationId: cloudbilling.billingAccounts.get
      parameters:
        - description: |-
            The resource name of the billing account to retrieve. For example,
            `billingAccounts/012345-567890-ABCDEF`.
          in: path
          name: name
          required: true
          x-reservedExpansion: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BillingAccount'
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      tags:
        - billingAccounts
    parameters:
      - $ref: '#/components/parameters/access_token'
      - $ref: '#/components/parameters/prettyPrint'
      - $ref: '#/components/parameters/key'
      - $ref: '#/components/parameters/quotaUser'
      - $ref: '#/components/parameters/pp'
      - $ref: '#/components/parameters/fields'
      - $ref: '#/components/parameters/alt'
      - $ref: '#/components/parameters/_.xgafv'
      - $ref: '#/components/parameters/callback'
      - $ref: '#/components/parameters/oauth_token'
      - $ref: '#/components/parameters/uploadType'
      - $ref: '#/components/parameters/bearer_token'
      - $ref: '#/components/parameters/upload_protocol'
  '/v1/{name}/billingInfo':
    get:
      description: |-
        Gets the billing information for a project. The current authenticated user
        must have [permission to view the
        project](https://cloud.google.com/docs/permissions-overview#h.bgs0oxofvnoo
        ).
      operationId: cloudbilling.projects.getBillingInfo
      parameters:
        - description: |-
            The resource name of the project for which billing information is
            retrieved. For example, `projects/tokyo-rain-123`.
          in: path
          name: name
          required: true
          x-reservedExpansion: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProjectBillingInfo'
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      tags:
        - projects
    parameters:
      - $ref: '#/components/parameters/access_token'
      - $ref: '#/components/parameters/prettyPrint'
      - $ref: '#/components/parameters/key'
      - $ref: '#/components/parameters/quotaUser'
      - $ref: '#/components/parameters/pp'
      - $ref: '#/components/parameters/fields'
      - $ref: '#/components/parameters/alt'
      - $ref: '#/components/parameters/_.xgafv'
      - $ref: '#/components/parameters/callback'
      - $ref: '#/components/parameters/oauth_token'
      - $ref: '#/components/parameters/uploadType'
      - $ref: '#/components/parameters/bearer_token'
      - $ref: '#/components/parameters/upload_protocol'
    put:
      description: |-
        Sets or updates the billing account associated with a project. You specify
        the new billing account by setting the `billing_account_name` in the
        `ProjectBillingInfo` resource to the resource name of a billing account.
        Associating a project with an open billing account enables billing on the
        project and allows charges for resource usage. If the project already had a
        billing account, this method changes the billing account used for resource
        usage charges.

        *Note:* Incurred charges that have not yet been reported in the transaction
        history of the Google Cloud Console may be billed to the new billing
        account, even if the charge occurred before the new billing account was
        assigned to the project.

        The current authenticated user must have ownership privileges for both the
        [project](https://cloud.google.com/docs/permissions-overview#h.bgs0oxofvnoo
        ) and the [billing
        account](https://support.google.com/cloud/answer/4430947).

        You can disable billing on the project by setting the
        `billing_account_name` field to empty. This action disassociates the
        current billing account from the project. Any billable activity of your
        in-use services will stop, and your application could stop functioning as
        expected. Any unbilled charges to date will be billed to the previously
        associated account. The current authenticated user must be either an owner
        of the project or an owner of the billing account for the project.

        Note that associating a project with a *closed* billing account will have
        much the same effect as disabling billing on the project: any paid
        resources used by the project will be shut down. Thus, unless you wish to
        disable billing, you should always call this method with the name of an
        *open* billing account.
      operationId: cloudbilling.projects.updateBillingInfo
      parameters:
        - description: |-
            The resource name of the project associated with the billing information
            that you want to update. For example, `projects/tokyo-rain-123`.
          in: path
          name: name
          required: true
          x-reservedExpansion: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProjectBillingInfo'
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      tags:
        - projects
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectBillingInfo'
  '/v1/{name}/projects':
    get:
      description: |-
        Lists the projects associated with a billing account. The current
        authenticated user must be an [owner of the billing
        account](https://support.google.com/cloud/answer/4430947).
      operationId: cloudbilling.billingAccounts.projects.list
      parameters:
        - description: |-
            The resource name of the billing account associated with the projects that
            you want to list. For example, `billingAccounts/012345-567890-ABCDEF`.
          in: path
          name: name
          required: true
          x-reservedExpansion: true
          schema:
            type: string
        - description: |-
            Requested page size. The maximum page size is 100; this is also the
            default.
          in: query
          name: pageSize
          schema:
            type: integer
        - description: |-
            A token identifying a page of results to be returned. This should be a
            `next_page_token` value returned from a previous `ListProjectBillingInfo`
            call. If unspecified, the first page of results is returned.
          in: query
          name: pageToken
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ListProjectBillingInfoResponse'
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      tags:
        - billingAccounts
    parameters:
      - $ref: '#/components/parameters/access_token'
      - $ref: '#/components/parameters/prettyPrint'
      - $ref: '#/components/parameters/key'
      - $ref: '#/components/parameters/quotaUser'
      - $ref: '#/components/parameters/pp'
      - $ref: '#/components/parameters/fields'
      - $ref: '#/components/parameters/alt'
      - $ref: '#/components/parameters/_.xgafv'
      - $ref: '#/components/parameters/callback'
      - $ref: '#/components/parameters/oauth_token'
      - $ref: '#/components/parameters/uploadType'
      - $ref: '#/components/parameters/bearer_token'
      - $ref: '#/components/parameters/upload_protocol'
components:
  schemas:
    BillingAccount:
      description: |-
        A billing account in [Google Cloud
        Console](https://console.cloud.google.com/). You can assign a billing account
        to one or more projects.
      properties:
        displayName:
          description: |-
            The display name given to the billing account, such as `My Billing
            Account`. This name is displayed in the Google Cloud Console.
          type: string
        name:
          description: |-
            The resource name of the billing account. The resource name has the form
            `billingAccounts/{billing_account_id}`. For example,
            `billingAccounts/012345-567890-ABCDEF` would be the resource name for
            billing account `012345-567890-ABCDEF`.
          type: string
        open:
          description: |-
            True if the billing account is open, and will therefore be charged for any
            usage on associated projects. False if the billing account is closed, and
            therefore projects associated with it will be unable to use paid services.
          type: boolean
      type: object
    ListBillingAccountsResponse:
      description: Response message for `ListBillingAccounts`.
      properties:
        billingAccounts:
          description: A list of billing accounts.
          items:
            $ref: '#/components/schemas/BillingAccount'
          type: array
        nextPageToken:
          description: |-
            A token to retrieve the next page of results. To retrieve the next page,
            call `ListBillingAccounts` again with the `page_token` field set to this
            value. This field is empty if there are no more results to retrieve.
          type: string
      type: object
    ListProjectBillingInfoResponse:
      description: Request message for `ListProjectBillingInfoResponse`.
      properties:
        nextPageToken:
          description: |-
            A token to retrieve the next page of results. To retrieve the next page,
            call `ListProjectBillingInfo` again with the `page_token` field set to this
            value. This field is empty if there are no more results to retrieve.
          type: string
        projectBillingInfo:
          description: |-
            A list of `ProjectBillingInfo` resources representing the projects
            associated with the billing account.
          items:
            $ref: '#/components/schemas/ProjectBillingInfo'
          type: array
      type: object
    ProjectBillingInfo:
      description: |-
        Encapsulation of billing information for a Cloud Console project. A project
        has at most one associated billing account at a time (but a billing account
        can be assigned to multiple projects).
      properties:
        billingAccountName:
          description: |-
            The resource name of the billing account associated with the project, if
            any. For example, `billingAccounts/012345-567890-ABCDEF`.
          type: string
        billingEnabled:
          description: |-
            True if the project is associated with an open billing account, to which
            usage on the project is charged. False if the project is associated with a
            closed billing account, or no billing account at all, and therefore cannot
            use paid services. This field is read-only.
          type: boolean
        name:
          description: |-
            The resource name for the `ProjectBillingInfo`; has the form
            `projects/{project_id}/billingInfo`. For example, the resource name for the
            billing information for project `tokyo-rain-123` would be
            `projects/tokyo-rain-123/billingInfo`. This field is read-only.
          type: string
        projectId:
          description: |-
            The ID of the project that this `ProjectBillingInfo` represents, such as
            `tokyo-rain-123`. This is a convenience field so that you don't need to
            parse the `name` field to obtain a project ID. This field is read-only.
          type: string
      type: object
  parameters:
    access_token:
      description: OAuth access token.
      in: query
      name: access_token
      schema:
        type: string
    alt:
      description: Data format for response.
      in: query
      name: alt
      schema:
        type: string
        enum:
          - json
          - media
          - proto
        default: json
    bearer_token:
      description: OAuth bearer token.
      in: query
      name: bearer_token
      schema:
        type: string
    callback:
      description: JSONP
      in: query
      name: callback
      schema:
        type: string
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      schema:
        type: string
    key:
      description: 'API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.'
      in: query
      name: key
      schema:
        type: string
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      schema:
        type: string
    pp:
      description: Pretty-print response.
      in: query
      name: pp
      schema:
        type: boolean
        default: true
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      schema:
        type: boolean
        default: true
    quotaUser:
      description: 'Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.'
      in: query
      name: quotaUser
      schema:
        type: string
    uploadType:
      description: 'Legacy upload protocol for media (e.g. "media", "multipart").'
      in: query
      name: uploadType
      schema:
        type: string
    upload_protocol:
      description: 'Upload protocol for media (e.g. "raw", "multipart").'
      in: query
      name: upload_protocol
      schema:
        type: string
    _.xgafv:
      description: V1 error format.
      in: query
      name: $.xgafv
      schema:
        type: string
        enum:
          - '1'
          - '2'
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
          scopes:
            'https://www.googleapis.com/auth/cloud-platform': View and manage your data across Google Cloud Platform services
    Oauth2c:
      description: Oauth 2.0 accessCode authentication
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
          tokenUrl: 'https://accounts.google.com/o/oauth2/token'
          scopes:
            'https://www.googleapis.com/auth/cloud-platform': View and manage your data across Google Cloud Platform services
