openapi: 3.0.0
servers:
  - url: 'https://script.googleapis.com/'
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Executes Google Apps Script projects.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Google Apps Script Execution
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.gstatic.com/images/icons/material/product/2x/apps_script_64dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://script.googleapis.com/$discovery/rest?version=v1'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: script
externalDocs:
  url: 'https://developers.google.com/apps-script/execution/rest/v1/scripts/run'
tags:
  - name: scripts
paths:
  '/v1/scripts/{scriptId}:run':
    parameters:
      - $ref: '#/components/parameters/quotaUser'
      - $ref: '#/components/parameters/pp'
      - $ref: '#/components/parameters/oauth_token'
      - $ref: '#/components/parameters/bearer_token'
      - $ref: '#/components/parameters/upload_protocol'
      - $ref: '#/components/parameters/prettyPrint'
      - $ref: '#/components/parameters/uploadType'
      - $ref: '#/components/parameters/fields'
      - $ref: '#/components/parameters/callback'
      - $ref: '#/components/parameters/_.xgafv'
      - $ref: '#/components/parameters/alt'
      - $ref: '#/components/parameters/key'
      - $ref: '#/components/parameters/access_token'
    post:
      description: |-
        Runs a function in an Apps Script project. The project must be deployed
        for use with the Apps Script Execution API.

        This method requires authorization with an OAuth 2.0 token that includes at
        least one of the scopes listed in the [Authorization](#authorization)
        section; script projects that do not require authorization cannot be
        executed through this API. To find the correct scopes to include in the
        authentication token, open the project in the script editor, then select
        **File > Project properties** and click the **Scopes** tab.
      operationId: script.scripts.run
      parameters:
        - description: |-
            The project key of the script to be executed. To find the project key, open
            the project in the script editor and select **File > Project properties**.
          in: path
          name: scriptId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Operation'
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.google.com/calendar/feeds'
          Oauth2c:
            - 'https://www.google.com/calendar/feeds'
        - Oauth2:
            - 'https://www.google.com/m8/feeds'
          Oauth2c:
            - 'https://www.google.com/m8/feeds'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group'
          Oauth2c:
            - 'https://www.googleapis.com/auth/admin.directory.group'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user'
          Oauth2c:
            - 'https://www.googleapis.com/auth/admin.directory.user'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/forms'
          Oauth2c:
            - 'https://www.googleapis.com/auth/forms'
        - Oauth2:
            - 'https://www.googleapis.com/auth/forms.currentonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/forms.currentonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/groups'
          Oauth2c:
            - 'https://www.googleapis.com/auth/groups'
        - Oauth2:
            - 'https://www.googleapis.com/auth/spreadsheets'
          Oauth2c:
            - 'https://www.googleapis.com/auth/spreadsheets'
        - Oauth2:
            - 'https://www.googleapis.com/auth/userinfo.email'
          Oauth2c:
            - 'https://www.googleapis.com/auth/userinfo.email'
      tags:
        - scripts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExecutionRequest'
components:
  schemas:
    ExecutionError:
      description: |-
        An object that provides information about the nature of an error in the Apps
        Script Execution API. If an
        `run` call succeeds but the
        script function (or Apps Script itself) throws an exception, the response
        body's `error` field contains a
        `Status` object. The `Status` object's `details` field
        contains an array with a single one of these `ExecutionError` objects.
      properties:
        errorMessage:
          description: |-
            The error message thrown by Apps Script, usually localized into the user's
            language.
          type: string
        errorType:
          description: |-
            The error type, for example `TypeError` or `ReferenceError`. If the error
            type is unavailable, this field is not included.
          type: string
        scriptStackTraceElements:
          description: |-
            An array of objects that provide a stack trace through the script to show
            where the execution failed, with the deepest call first.
          items:
            $ref: '#/components/schemas/ScriptStackTraceElement'
          type: array
      type: object
    ExecutionRequest:
      description: |-
        A request to run the function in a script. The script is identified by the
        specified `script_id`. Executing a function on a script returns results
        based on the implementation of the script.
      properties:
        devMode:
          description: |-
            If `true` and the user is an owner of the script, the script runs at the
            most recently saved version rather than the version deployed for use with
            the Execution API. Optional; default is `false`.
          type: boolean
        function:
          description: |-
            The name of the function to execute in the given script. The name does not
            include parentheses or parameters.
          type: string
        parameters:
          description: |-
            The parameters to be passed to the function being executed. The object type
            for each parameter should match the expected type in Apps Script.
            Parameters cannot be Apps Script-specific object types (such as a
            `Document` or a `Calendar`); they can only be primitive types such as
            `string`, `number`, `array`, `object`, or `boolean`. Optional.
          items: {}
          type: array
        sessionState:
          description: |-
            For Android add-ons only. An ID that represents the user's current session
            in the Android app for Google Docs or Sheets, included as extra data in the
            [`Intent`](https://developer.android.com/guide/components/intents-filters.html)
            that launches the add-on. When an Android add-on is run with a session
            state, it gains the privileges of a
            [bound](https://developers.google.com/apps-script/guides/bound) script &mdash;
            that is, it can access information like the user's current cursor position
            (in Docs) or selected cell (in Sheets). To retrieve the state, call
            `Intent.getStringExtra("com.google.android.apps.docs.addons.SessionState")`.
            Optional.
          type: string
      type: object
    ExecutionResponse:
      description: |-
        An object that provides the return value of a function executed through the
        Apps Script Execution API. If a
        `run` call succeeds and the
        script function returns successfully, the response body's
        `response` field contains this
        `ExecutionResponse` object.
      properties:
        result:
          description: |-
            The return value of the script function. The type matches the object type
            returned in Apps Script. Functions called through the Execution API cannot
            return Apps Script-specific objects (such as a `Document` or a `Calendar`);
            they can only return primitive types such as a `string`, `number`, `array`,
            `object`, or `boolean`.
      type: object
    JoinAsyncRequest:
      description: |-
        A request to retrieve the results from a collection of requests,
        specified by the operation resource names.
      properties:
        names:
          description: |-
            List of operation resource names that we want to join,
            as returned from a call to RunAsync.
          items:
            type: string
          type: array
        scriptId:
          description: |-
            The script id which specifies the script which all processes in the names
            field must be from.
          type: string
        timeout:
          description: Timeout for information retrieval in milliseconds.
          format: google-duration
          type: string
      type: object
    JoinAsyncResponse:
      description: An object that provides the return value for the JoinAsync method.
      properties:
        results:
          additionalProperties:
            $ref: '#/components/schemas/Operation'
          description: |-
            The return values for each script function, in a map of operation resource
            names to the Operation containing the result of the process. The response
            will contain either an error or the result of the script function.
          type: object
      type: object
    Operation:
      description: |-
        The response will not arrive until the function finishes executing. The maximum runtime is listed in the guide to [limitations in Apps Script](https://developers.google.com/apps-script/guides/services/quotas#current_limitations).
        <p>If the script function returns successfully, the `response` field will contain an `ExecutionResponse` object with the function's return value in the object's `result` field.</p>
        <p>If the script function (or Apps Script itself) throws an exception, the `error` field will contain a `Status` object. The `Status` object's `details` field will contain an array with a single `ExecutionError` object that provides information about the nature of the error.</p>
        <p>If the `run` call itself fails (for example, because of a malformed request or an authorization error), the method will return an HTTP response code in the 4XX range with a different format for the response body. Client libraries will automatically convert a 4XX response into an exception class.</p>
      properties:
        done:
          description: This field is not used.
          type: boolean
        error:
          $ref: '#/components/schemas/Status'
        metadata:
          additionalProperties:
            description: Properties of the object. Contains field @type with type URL.
          description: This field is not used.
          type: object
        name:
          description: This field is not used.
          type: string
        response:
          additionalProperties:
            description: Properties of the object. Contains field @type with type URL.
          description: 'If the script function returns successfully, this field will contain an `ExecutionResponse` object with the function''s return value as the object''s `result` field.'
          type: object
      type: object
    ScriptStackTraceElement:
      description: A stack trace through the script that shows where the execution failed.
      properties:
        function:
          description: The name of the function that failed.
          type: string
        lineNumber:
          description: The line number where the script failed.
          format: int32
          type: integer
      type: object
    Status:
      description: 'If a `run` call succeeds but the script function (or Apps Script itself) throws an exception, the response body''s `error` field will contain this `Status` object.'
      properties:
        code:
          description: 'The status code. For this API, this value will always be 3, corresponding to an INVALID_ARGUMENT error.'
          format: int32
          type: integer
        details:
          description: An array that contains a single `ExecutionError` object that provides information about the nature of the error.
          items:
            additionalProperties:
              description: Properties of the object. Contains field @type with type URL.
            type: object
          type: array
        message:
          description: 'A developer-facing error message, which is in English. Any user-facing error message is localized and sent in the [`google.rpc.Status.details`](google.rpc.Status.details) field, or localized by the client.'
          type: string
      type: object
  parameters:
    access_token:
      description: OAuth access token.
      in: query
      name: access_token
      schema:
        type: string
    alt:
      description: Data format for response.
      in: query
      name: alt
      schema:
        type: string
        enum:
          - json
          - media
          - proto
        default: json
    bearer_token:
      description: OAuth bearer token.
      in: query
      name: bearer_token
      schema:
        type: string
    callback:
      description: JSONP
      in: query
      name: callback
      schema:
        type: string
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      schema:
        type: string
    key:
      description: 'API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.'
      in: query
      name: key
      schema:
        type: string
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      schema:
        type: string
    pp:
      description: Pretty-print response.
      in: query
      name: pp
      schema:
        type: boolean
        default: true
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      schema:
        type: boolean
        default: true
    quotaUser:
      description: 'Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.'
      in: query
      name: quotaUser
      schema:
        type: string
    uploadType:
      description: 'Legacy upload protocol for media (e.g. "media", "multipart").'
      in: query
      name: uploadType
      schema:
        type: string
    upload_protocol:
      description: 'Upload protocol for media (e.g. "raw", "multipart").'
      in: query
      name: upload_protocol
      schema:
        type: string
    _.xgafv:
      description: V1 error format.
      in: query
      name: $.xgafv
      schema:
        type: string
        enum:
          - '1'
          - '2'
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
          scopes:
            'https://mail.google.com/': 'Read, send, delete, and manage your email'
            'https://www.google.com/calendar/feeds': Manage your calendars
            'https://www.google.com/m8/feeds': Manage your contacts
            'https://www.googleapis.com/auth/admin.directory.group': View and manage the provisioning of groups on your domain
            'https://www.googleapis.com/auth/admin.directory.user': View and manage the provisioning of users on your domain
            'https://www.googleapis.com/auth/drive': View and manage the files in your Google Drive
            'https://www.googleapis.com/auth/forms': View and manage your forms in Google Drive
            'https://www.googleapis.com/auth/forms.currentonly': View and manage forms that this application has been installed in
            'https://www.googleapis.com/auth/groups': View and manage your Google Groups
            'https://www.googleapis.com/auth/spreadsheets': View and manage your spreadsheets in Google Drive
            'https://www.googleapis.com/auth/userinfo.email': View your email address
    Oauth2c:
      description: Oauth 2.0 accessCode authentication
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
          tokenUrl: 'https://accounts.google.com/o/oauth2/token'
          scopes:
            'https://mail.google.com/': 'Read, send, delete, and manage your email'
            'https://www.google.com/calendar/feeds': Manage your calendars
            'https://www.google.com/m8/feeds': Manage your contacts
            'https://www.googleapis.com/auth/admin.directory.group': View and manage the provisioning of groups on your domain
            'https://www.googleapis.com/auth/admin.directory.user': View and manage the provisioning of users on your domain
            'https://www.googleapis.com/auth/drive': View and manage the files in your Google Drive
            'https://www.googleapis.com/auth/forms': View and manage your forms in Google Drive
            'https://www.googleapis.com/auth/forms.currentonly': View and manage forms that this application has been installed in
            'https://www.googleapis.com/auth/groups': View and manage your Google Groups
            'https://www.googleapis.com/auth/spreadsheets': View and manage your spreadsheets in Google Drive
            'https://www.googleapis.com/auth/userinfo.email': View your email address
