swagger: "2.0"
schemes:
  - https
host: api.ebay.com
basePath: /buy/browse/v1
info:
  contact:
    name: eBay Inc,
    x-twitter: ebay
  description: "The Browse API has the following resources: item_summary: Lets shoppers search for specific items by keyword, GTIN, category, charity, product, or item aspects and refine the results by using filters, such as aspects, compatibility, and fields values. &nbsp;(Experimental) search_by_image: Lets shoppers search for specific items by image. You can refine the results by using URI parameters and filters. item: Lets you retrieve the details of a specific item or all the items in an it[...]"
  license:
    name: eBay API License Agreement
    url: https://go.developer.ebay.com/api-license-agreement
  title: Browse API
  version: v1.1.0
  x-apisguru-categories:
    - ecommerce
  x-logo:
    backgroundColor: "#FFFFFF"
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_ebay_profile_image.jpeg
  x-origin:
    - format: swagger
      url: https://developer.ebay.com/api-docs/master/buy/browse/openapi/2/buy_browse_v1_beta_oas2.json
      version: "2.0"
  x-providerName: ebay.com
  x-serviceName: buy-browse
securityDefinitions:
  Authorization Code:
    authorizationUrl: https://auth.ebay.com/oauth2/authorize
    description: The security definitions for this API. Please check individual operations for applicable scopes.
    flow: accessCode
    scopes:
      https://api.ebay.com/oauth/api_scope/buy.shopping.cart: " This scope would allow signed in user to access shopping carts"
    tokenUrl: https://api.ebay.com/identity/v1/oauth2/token
    type: oauth2
  Client Credentials:
    description: The security definitions for this API. Please check individual operations for applicable scopes.
    flow: application
    scopes:
      https://api.ebay.com/oauth/api_scope: View public data from eBay
      https://api.ebay.com/oauth/api_scope/buy.item.bulk: Retrieve eBay items in bulk.
      https://api.ebay.com/oauth/scope/base@application: " This scope would allow applications to access any API associated with a base intent. Tokens with this scope should be restricted to use from server environments."
    tokenUrl: https://api.ebay.com/identity/v1/oauth2/token
    type: oauth2
paths:
  /item/:
    get:
      description: "This method retrieves the details of specific items that the buyer needs to make a purchasing decision. Note: This is a (Limited Release) available only to select Partners. For this method, only the following fields are returned: eligibleForInlineCheckout, estimatedAvailabilities, itemAffiliateWebURL, itemID, ItemWebURL, legacyItemID, price, sellerItemRevision, and topRatedBuyingExperience. URLs for this method Production URL: https://api.ebay.com/buy/browse/v1/item/ Sandbox [...]"
      operationId: getItems
      security:
        - Client Credentials:
            - https://api.ebay.com/oauth/api_scope/buy.item.bulk
      tags:
        - item
  /item/get_item_by_legacy_id:
    get:
      description: "This method is a bridge between the eBay legacy APIs, such as Shopping, and Finding and the eBay Buy APIs. There are differences between how legacy APIs and RESTful APIs return the identifier of an &quot;item&quot; and what the item ID represents. This method lets you use the legacy item ids retrieve the details of a specific item, such as description, price, and other information the buyer needs to make a purchasing decision. It also returns the RESTful item ID, which you ca[...]"
      operationId: getItemByLegacyId
      security:
        - Client Credentials:
            - https://api.ebay.com/oauth/api_scope
      tags:
        - item
  /item/get_items_by_item_group:
    get:
      description: "This method retrieves the details of the individual items in an item group. An item group is an item that has various aspect differences, such as color, size, storage capacity, etc. You pass in the item group ID as a URI parameter. You use this method to show the item details of items with multiple aspects, such as color, size, storage capacity, etc. This method returns two main containers; items and commonDescriptions. The items container has an array of containers with the [...]"
      operationId: getItemsByItemGroup
      tags:
        - item
  "/item/{item_id}":
    get:
      description: "This method retrieves the details of a specific item, such as description, price, category, all item aspects, condition, return policies, seller feedback and score, shipping options, shipping costs, estimated delivery, and other information the buyer needs to make a purchasing decision. The Buy APIs are designed to let you create an eBay shopping experience in your app or website. This means you will need to know when something, such as the availability, quantity, etc., has c[...]"
      operationId: getItem
      security:
        - Client Credentials:
            - https://api.ebay.com/oauth/api_scope
      tags:
        - item
  "/item/{item_id}/check_compatibility":
    post:
      description: "This method checks if a product is compatible with the specified item. You can use this method to check the compatibility of cars, trucks, and motorcycles with a specific part listed on eBay. For example, to check the compatibility of a part, you pass in the item ID of the part as a URI parameter and specify all the attributes used to define a specific car in the compatibilityProperties container. If the call is successful, the response will be COMPATIBLE, NOT_COMPATIBLE, or [...]"
      operationId: checkCompatibility
      security:
        - Client Credentials:
            - https://api.ebay.com/oauth/api_scope
      tags:
        - item
  /item_summary/search:
    get:
      description: "This method searches for eBay items by various query parameters and retrieves summaries of the items. You can search by keyword, category, eBay product ID (ePID), or GTIN, charity ID, or a combination of these. Note: Only FIXED_PRICE (Buy It Now) items are returned by default. However, this method does return items where both FIXED_PRICE and AUCTION are available as a buying option. After a bid has been placed, items become active auction items and are no longer returned by d[...]"
      operationId: search
      security:
        - Client Credentials:
            - https://api.ebay.com/oauth/api_scope
      tags:
        - item_summary
  /item_summary/search_by_image:
    post:
      description: "This is an Experimental method. This method searches for eBay items based on a image and retrieves summaries of the items. You pass in a Base64 image in the request payload and can refine the search by category, or eBay product ID (ePID), or a combination of these using URI parameters. To get the Base64 image string, you can use sites such as https://codebeautify.org/image-to-base64-converter. This method also supports the following: Filtering by the value of one or multiple [...]"
      operationId: searchByImage
      security:
        - Client Credentials:
            - https://api.ebay.com/oauth/api_scope
      tags:
        - search_by_image
  /shopping_cart/:
    get:
      description: "This is an experimental method. This method retrieves all the items in the eBay member's cart; items added to the cart while on ebay.com as well as items added to the cart using the Browse API. There are no URI parameters or request payload. The response returns the summary details of all the items in the eBay member's cart; items added to the cart while on ebay.com as well as items added to the cart using the Browse API. If the cart is empty, the response is HTTP 204. The qu[...]"
      operationId: getShoppingCart
      security:
        - Authorization Code:
            - https://api.ebay.com/oauth/api_scope/buy.shopping.cart
      tags:
        - shopping_cart
  /shopping_cart/add_item:
    post:
      description: "This is an Experimental method. This method creates an eBay cart for the eBay member, if one does not exist, and adds items to that cart. Because a cart never expires, any item added to the cart will remain in the cart until it is removed. To use this method, you must submit a RESTful item ID and the quantity of the item. If the quantity value is greater than the number of available, the quantity value is changed to the number available and a warning is returned. For example,[...]"
      operationId: addItem
      security:
        - Authorization Code:
            - https://api.ebay.com/oauth/api_scope/buy.shopping.cart
      tags:
        - shopping_cart
  /shopping_cart/remove_item:
    post:
      description: "This is an experimental method. This method removes a specific item from the eBay member's cart. You specify the ID of the item in the cart (cartItemId) that you want to remove. The response returns all the items in the eBay member's cart; items added to the cart while on ebay.com as well as items added to the cart using the Browse API. If you remove the last item in the cart, the response is HTTP 204. The quantity and state of an item changes often. If the item becomes &quot[...]"
      operationId: removeItem
      security:
        - Authorization Code:
            - https://api.ebay.com/oauth/api_scope/buy.shopping.cart
      tags:
        - shopping_cart
  /shopping_cart/update_quantity:
    post:
      description: "This is an experimental method. This method updates the quantity value of a specific item in the eBay member's cart. You specify the ID of the item in the cart (cartItemId) and the new value for the quantity. If the quantity value is greater than the number of available, the quantity value is changed to the number available and a warning is returned. For example, if there are 15 baseballs available and you set the quantity value to 50, the service automatically changes the va[...]"
      operationId: updateQuantity
      security:
        - Authorization Code:
            - https://api.ebay.com/oauth/api_scope/buy.shopping.cart
      tags:
        - shopping_cart