openapi: 3.0.0
servers:
  - url: 'https://openapi-converter.herokuapp.com/api/v1'
  - url: 'http://openapi-converter.herokuapp.com/api/v1'
info:
  contact:
    email: mike.ralphson@gmail.com
    name: Mike Ralphson
    url: 'https://github.com/mermade/swagger2openapi/issues'
  description: Converter and validator for Swagger 2.0 to OpenAPI 3.0.x definitions
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  termsOfService: 'https://opensource.org/licenses/MIT'
  title: Swagger2OpenAPI Converter
  version: 1.0.0
  x-apisguru-categories:
    - developer_tools
  x-logo:
    backgroundColor: '#FFFFFF'
    url: 'https://avatars1.githubusercontent.com/u/15950345?v=3&s=200'
  x-origin:
    - format: swagger
      url: 'https://raw.githubusercontent.com/Mermade/openapi-webconverter/master/contract/swagger.json'
      version: '2.0'
  x-providerName: openapi-converter.herokuapp.com
externalDocs:
  url: 'https://github.com/mermade/openapi-webconverter'
security: []
tags:
  - description: Metadata functions
    name: metadata
  - description: Conversion functions
    name: conversion
  - description: Validation functions
    name: validation
paths:
  /badge:
    get:
      description: ''
      operationId: getBadge
      parameters:
        - description: The URL to retrieve the OpenAPI 3.0.x definition from
          in: query
          name: url
          required: true
          schema:
            type: string
            format: uri
      responses:
        '301':
          description: Moved
      summary: Return a redirect to a badge svg file depending on a source definition's validity
      tags:
        - validation
  /convert:
    get:
      description: ''
      operationId: convertUrl
      responses:
        '200':
          description: default
      summary: Convert a Swagger 2.0 definition to OpenAPI 3.0.x from a URL
      tags:
        - conversion
    post:
      description: ''
      operationId: convert
      responses:
        '200':
          description: default
      summary: 'Convert a Swagger 2.0 definition passed in the body to OpenAPI 3.0.x '
      tags:
        - conversion
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                filename:
                  description: The file to upload and convert
                  type: string
                source:
                  description: The text of a Swagger 2.0 definition to convert
                  type: string
                validate:
                  type: string
                  enum:
                    - 'on'
  /status:
    get:
      description: ''
      operationId: getStatus
      responses:
        '200':
          description: default
      summary: Get the status of the API
      tags:
        - metadata
  /validate:
    get:
      description: ''
      operationId: validateUrl
      parameters:
        - description: The URL to retrieve the OpenAPI 3.0.x definition from
          in: query
          name: url
          required: true
          schema:
            type: string
            format: uri
      responses:
        '200':
          description: default
      summary: Validate an OpenAPI 3.0.x definition
      tags:
        - validation
    post:
      description: ''
      operationId: validate
      responses:
        '200':
          description: default
      summary: Validate an OpenAPI 3.0.x definition supplied in the body of the request
      tags:
        - validation
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                filename:
                  description: The file to upload and validate
                  type: string
                source:
                  description: The text of an OpenAPI 3.0.x definition to validate
                  type: string
components:
  schemas: {}
